apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

group = 'com.aks.realtimeaudio'
version = '1.0.0'

android {
  namespace 'com.aks.realtimeaudio'
  compileSdkVersion 35

  defaultConfig {
    minSdkVersion 24
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }

  kotlinOptions {
    jvmTarget = '17'
  }

  publishing {
    singleVariant('release')
  }
}

dependencies {
  implementation project(':expo-modules-core')
}
