/**
 * Centralized user-visible copy — English source of truth.
 *
 * Every static string the user can read (screen text, buttons, placeholders,
 * accessibility labels, dialogs, notices, and error lines shown in the UI)
 * lives here. Screens and components must reference `copy` instead of
 * hardcoding literals, so nothing user-facing is scattered across the app.
 *
 * Rules:
 * - English is the canonical structure; translations live in
 *   `src/localization/<code>.ts` and must satisfy `Translation`.
 * - Dynamic values use functions, e.g. `connectedSources(3)`.
 * - URLs, email addresses, asset paths, and formatting helpers
 *   (Intl formatters, `replaceAll("_", " ")`) stay at the call site —
 *   they are data/formatting, not translatable copy.
 * - Logic-coupled identifiers (route names, filter keys shared with
 *   grouping logic, status codes) stay where they are.
 *
 * Runtime: `copy` is mutable through `applyLanguage` (used by
 * `LanguageProvider`), so the 90+ `copy.*` call sites keep working unchanged
 * while the active language switches. Language registration lives in
 * `src/localization/languages.ts`.
 */

import type { DayPart } from "@/lib/dayPart";

export const en = {
    common: {
        back: "Back",
        cancel: "Cancel",
        save: "Save",
        dismiss: "Dismiss",
        clear: "Clear",
        loading: "Loading...",
        tryAgain: "Try again",
        loadMore: "Load more",
        pleaseTryAgain: "Please try again.",
        checkConnection: "Check your connection and try again.",
        emailPlaceholder: "you@example.com",
        justNow: "just now",
        dateUnavailable: "Date unavailable",
        version: (value: string) => `Version ${value}`,
    },
    brand: {
        name: "Aks.ai",
        tagline: "Understand yourself, differently.",
    },
    splash: {
        appName: "Aks.ai",
        subtitle: "Understand yourself, differently.",
    },
    onboarding: {
        skip: "Skip",
        moveForward: "Move forward",
        getStarted: "Get started",
        notices: {
            unableToContinue: "Unable to continue",
        },
        slides: [
            {
                eyebrow: "YOUR LIFE LEAVES CLUES",
                title: "You already leave\nclues about yourself.",
                description:
                    "The things you repeat. The moments you avoid. The days that feel different. Aks brings those signals together.",
            },
            {
                eyebrow: "DON'T JUST REFLECT",
                title: "Don’t guess.\nTest it.",
                description:
                    "Turn a hunch into a small experiment. Change one thing, measure what happens, and discover what actually works for you.",
            },
            {
                eyebrow: "A CLEARER YOU",
                title: "Become less of\na mystery to yourself.",
                description:
                    "Over time, Aks builds a living picture of your patterns, your responses, and the changes that make a difference.",
            },
        ],
    },
    legal: {
        termsTitle: "Terms of Service",
        privacyTitle: "Privacy Policy",
        acceptance: {
            title: "Before we begin.",
            description:
                "Aks works with personal information to help you understand your patterns. Here's what you should know before continuing.",
            cardTitle: "Your data, your control.",
            cardBody:
                "Aks uses the information you choose to share to identify patterns and help you run personal experiments.",
            bullets: [
                "You decide what information to provide.",
                "You can manage your data and permissions.",
                "Aks does not replace professional medical or mental-health advice.",
            ],
            agreePrefix: "I agree to Aks.ai's",
            terms: "Terms of Service",
            andWord: "and",
            privacy: "Privacy Policy",
            continue: "Continue to Aks",
            retryAction: "Retry",
            retry: "Retry",
            footnote: "You can review these documents again later from Settings.",
            consentA11y: "Accept Terms of Service and Privacy Policy",
            notices: {
                unableToSave: "Unable to save acceptance",
            },
        },
        links: {
            prefix: "By continuing, you agree to Aks.ai's",
            terms: "Terms of Service",
            andWord: "and",
            privacy: "Privacy Policy",
        },
    },
    login: {
        title: "Welcome back.",
        description: "Sign in to continue discovering what Aks notices about you.",
        emailLabel: "Email address",
        sendLink: "Sign in",
        sendLinkA11y: "Send sign-in link",
        secureLinkNote: "We'll email you a secure sign-in link. No password needed.",
        divider: "OR CONTINUE WITH",
        google: "Google",
        googleA11y: "Continue with Google",
        facebook: "Facebook",
        facebookA11y: "Continue with Facebook",
        github: "Continue with GitHub",
        githubA11y: "Continue with GitHub",
        noAccount: "Don't have an account?",
        createOne: "Create one",
        dismissError: "Tap to dismiss.",
        notices: {
            unableToSendLink: "Unable to send sign-in link",
            unableToSignIn: "Unable to sign in",
        },
    },
    register: {
        title: "Create your account.",
        description: "Start building a clearer picture of yourself with Aks.",
        nameLabel: "Full name",
        namePlaceholder: "Your full name",
        nameA11y: "Full name",
        emailLabel: "Email address",
        createAccount: "Create account",
        createAccountA11y: "Create account with email",
        secureLinkNote: "We'll send you a secure sign-in link. No password needed.",
        divider: "OR SIGN UP WITH",
        google: "Google",
        googleA11y: "Continue with Google",
        facebook: "Facebook",
        facebookA11y: "Continue with Facebook",
        github: "Continue with GitHub",
        githubA11y: "Continue with GitHub",
        hasAccount: "Already have an account?",
        signIn: "Sign in",
        dismissError: "Tap to dismiss.",
        notices: {
            unableToCreate: "Unable to create account",
            unableToSignIn: "Unable to sign in",
        },
    },
    emailConfirmation: {
        title: "Check your email.",
        body: (email: string) =>
            `We sent a secure sign-in link to ${email}. Open it on this device to continue.`,
        resendNote: "If you resend, only the newest link will work.",
        resend: "Resend link",
        resendA11y: "Resend sign-in link",
        editEmail: "Edit email",
        editEmailA11y: "Edit email address",
    },
    mirror: {
        eyebrow: "MIRROR",
        greeting: (firstName: string | null, part: DayPart = "morning") => {
            const base =
                part === "afternoon"
                    ? "Good afternoon"
                    : part === "evening"
                        ? "Good evening"
                        : part === "night"
                            ? "Good night"
                            : "Good morning";
            return `${base}${firstName ? `, ${firstName}` : ""}.`;
        },
        intro: "I’m Aks. Let’s start with something small.",
        understandTitle: "What would you like to understand?",
        differentHint: "Or tell Aks something completely different.",
        checkInEyebrow: "QUICK CHECK-IN",
        checkInTitle: "How’s today feeling?",
        topics: ["Focus", "Energy", "Sleep", "Emotions", "Routines", "Relationships", "Productivity"],
        topicDraft: (topic: string) => `I’d like to understand my ${topic.toLowerCase()}.`,
        checks: ["Good", "Okay", "Chaos"],
        aksLabel: "AKS",
        errorTitle: "Something went wrong.",
        retryResponse: "Retry response",
        listening: "Listening…",
        listeningMeta: (duration: string) => `${duration} · stays on this device`,
        stopRecordingA11y: "Stop recording",
        voiceReady: "Voice reflection ready",
        voiceReadyHint: "Aks will transcribe it into a reflection.",
        discardRecordingA11y: "Discard recording",
        sendRecordingA11y: "Send recording",
        composerPlaceholder: "Tell Aks what’s on your mind…",
        sendMessageA11y: "Send message",
        recordVoiceA11y: "Record voice reflection",
        notices: {
            micUnavailable: "Microphone unavailable",
            micUnavailableBody:
                "Microphone access is needed to record a voice reflection. You can still type instead.",
            cantListen: "Couldn’t start listening",
            cantListenBody: "Please try again, or share what’s on your mind in text.",
            stopRecording: "Couldn't stop recording",
            recordingFailed: "Couldn't save that recording",
            transcriptionNotConfigured:
                "Voice reflections aren't available on this build yet. You can still type a reflection.",
            audioTooLong: "That recording is too long. Try a shorter one.",
            subscriptionRequired:
                "Voice reflections need Aks Premium, so this recording wasn't used. You can still type instead.",
            emptyTranscription:
                "Aks couldn't hear anything in that recording. Check your microphone is working and try again.",
            unsupportedAudio: "That recording format isn't supported. Try recording again.",
            transcriptionUnavailable:
                "Aks couldn't listen to that recording right now. You can try again or type instead.",
            unauthorized: "Please sign in and try again.",
            recordingFailedFallback:
                "Aks couldn't save that recording just now. You can try again or type instead.",
        },
    },
    mirrorBar: {
        newConversation: "New conversation",
        composerPlaceholder: "Tell Aks what’s on your mind…",
        sendMessageA11y: "Send message",
        closeComposerA11y: "Close composer",
        openKeyboardA11y: "Open keyboard",
        stopVoiceA11y: "Stop voice conversation",
        startVoiceA11y: "Start voice conversation",
        voiceOffA11y: "Turn spoken replies off",
        voiceOnA11y: "Turn spoken replies on",
        moreOptionsA11y: "More conversation options",
        hint: "You don’t need to organize your thoughts first. Just start talking.",
    },
    aiConversation: {
        greeting: (firstName: string | null) => `Hey, ${firstName ?? "there"} 👋`,
        openingPrompts: [
            "What’s been on your mind?",
            "How are you feeling today?",
            "Is there something you’ve been carrying lately?",
            "What’s been taking up space in your head?",
            "Want to talk about what’s bothering you?",
            "Anything you feel like getting off your chest?",
            "What’s been weighing on you lately?",
            "Is there something you wish you could say?",
        ],
        copyAction: "Copy",
        copiedAction: "Copied",
        copyA11y: "Copy message",
        shareAction: "Share",
        shareA11y: "Share message",
        tryAgainAction: "Try again",
        tryAgainA11y: "Try this response again",
        motionReadyA11y: "Aks is ready",
        thinking: "Thinking…",
        thinkingDefault: "Aks is thinking…",
        aksTag: "aks",
        youTag: "you",
        listening: "Listening…",
        speaking: "Speaking…",
        loadingConversation: "Loading conversation…",
        youPrefix: "You: ",
        errorTitle: "Something went wrong.",
        retryResponse: "Retry response",
        voicePaused: "Voice paused.",
        editPlaceholder: "Rewrite your message…",
        saveAndSend: "Save and send",
        saveAndSendA11y: "Save and send edited message",
        cancelEditingA11y: "Cancel editing",
        cancel: "Cancel",
        editMessage: "Edit message",
        editMessageA11y: "Edit your message",
    },
    timeline: {
        header: "Timeline",
        headerCaption: "Your journey with Aks, over time.",
        eyebrow: "YOUR JOURNEY",
        title: "Your story, as it unfolds.",
        description:
            "See the moments, patterns, experiments, and learnings that shaped your journey with Aks.",
        errorTitle: "Couldn't load your timeline.",
        errorBody: "Your story is still here. Try again in a moment.",
        loadMoreError: "Couldn't load more of your story.",
        empty: {
            allTitle: "Your story is still unfolding.",
            allBody:
                "As you talk with Aks, meaningful moments, patterns, experiments, and learnings will appear here.",
            insightsTitle: "No insights yet.",
            insightsBody: "Meaningful insights will appear here as Aks sees enough evidence over time.",
            experimentsTitle: "No experiments yet.",
            experimentsBody: "Experiments you set up will appear here as you run them.",
            checkInsTitle: "No check-ins yet.",
            checkInsBody: "Your meaningful check-ins will appear here.",
            decisionsTitle: "No decisions yet.",
            decisionsBody: "Decisions and patterns Aks notices will appear here as they take shape.",
            learningsTitle: "No learnings yet.",
            learningsBody: "New learnings will appear here as your story becomes clearer.",
        },
    },
    you: {
        title: "You",
        fallbackName: "Aks member",
        subtitle: "Your personal space",
        knowsTitle: "What Aks knows",
        knowsEmpty: "Still getting to know you",
        memoriesCount: (count: number) => `${count} ${count === 1 ? "memory" : "memories"}`,
        exploringTitle: "What you're exploring",
        exploringEmpty: "Choose your focus",
        unnoticedTitle: "Things you haven't noticed",
        insightsCount: (count: number) => `${count} ${count === 1 ? "insight" : "insights"} worth a look`,
        insightsEmpty: "Nothing settled yet",
        journeySection: "YOUR JOURNEY",
        patternsTitle: "Patterns",
        patternsDescription: "Things Aks has noticed",
        experimentsTitle: "Experiments",
        experimentsDescription: "What you're currently testing",
        yourDataTitle: "Your data",
        yourDataDescription: "Review and manage your information",
        preferencesSection: "PREFERENCES",
        notificationsTitle: "Notifications",
        notificationsDescription: "When Aks should reach out",
        appearanceTitle: "Appearance",
        appearanceDescription: "System · Light · Dark",
        privacyTitle: "Privacy",
        privacyDescription: "Permissions and privacy controls",
        supportSection: "SUPPORT",
        helpTitle: "Help & feedback",
    },
    settings: {
        header: "Settings",
        eyebrow: "SETTINGS",
        title: "Your Aks, your way.",
        description: "Manage your account, plan, and information about Aks.",
        accountSection: "ACCOUNT",
        profileTitle: "Profile",
        profileDescription: "Manage your personal information",
        accountTitle: "Account",
        accountDescription: "Sign out or delete your account",
        subscriptionTitle: "Subscription",
        subscriptionDescription: "Manage your Aks plan and billing",
        preferencesSection: "PREFERENCES",
        languageTitle: "Language",
        aboutSection: "ABOUT",
        aboutTitle: "About Aks",
        aboutDescription: "Learn more about Aks",
        termsTitle: "Terms of Service",
        privacyTitle: "Privacy Policy",
    },
    profile: {
        header: "Profile",
        fallbackName: "Aks member",
        fallbackEmail: "Email unavailable",
        editName: "Edit name",
        editNameA11y: "Edit name",
        changePhotoA11y: "Change profile photo",
        photoA11y: "Profile photo",
        photoSheetTitle: "Profile photo",
        chooseImage: "Choose image",
        removePhoto: "Remove photo",
        aksSection: "AKS",
        exploringTitle: "What you're exploring",
        exploringEmpty: "Not set",
        noticeTitle: "What Aks should notice",
        noticeEmpty: "Not set",
        preferencesSection: "PREFERENCES",
        timezoneTitle: "Timezone",
        languageTitle: "Language",
        accountSection: "ACCOUNT",
        emailTitle: "Email",
        emailUnavailable: "Unavailable",
        memberSince: "Member since",
        memberSinceUnavailable: "Unavailable",
        signInMethod: "Sign-in method",
        signInMethodFallback: "Email",
        editNameTitle: "Edit your name",
        editNameMessage: "This is how Aks addresses you.",
        nameA11y: "Full name",
        namePlaceholder: "Your name",
        saving: "Saving…",
        saveChanges: "Save changes",
        fullName: "Full name",
        notices: {
            unableToSaveName: "Unable to save profile",
            unableToUpdatePhoto: "Unable to update photo",
            unableToRemovePhoto: "Unable to remove photo",
            checkConnection: "Check your connection and try again.",
            tryAgain: "Please try again.",
        },
    },
    exploring: {
        header: "What you're exploring",
        eyebrow: "PERSONAL",
        title: "Choose your focus.",
        description: "Select the areas you want to understand more clearly.",
        options: ["Focus", "Energy", "Sleep", "Mood", "Habits", "Stress"],
    },
    noticeAreas: {
        header: "What Aks should notice",
        eyebrow: "PERSONAL",
        title: "Guide what Aks notices.",
        description: "Choose the areas Aks should prioritize when organizing possible patterns.",
        options: ["Daily routines", "Energy changes", "Focus patterns", "Sleep quality", "Mood shifts", "Experiment outcomes"],
    },
    timezone: {
        header: "Timezone",
        eyebrow: "PREFERENCES",
        title: "Your local time.",
        description: "Choose the timezone Aks uses for scheduling.",
    },
    language: {
        header: "Language",
        eyebrow: "PREFERENCES",
        title: "Choose your language.",
        description: "Select the language used throughout Aks.",
        notAvailableYet: (name: string) => `${name} isn't available yet. English is used until its translation ships.`,
        comingSoon: "Coming soon",
    },
    appearance: {
        header: "Appearance",
        eyebrow: "YOUR EXPERIENCE",
        title: "Make it feel like yours.",
        description: "Choose how Aks looks throughout the app.",
        themeSection: "THEME",
        themes: {
            systemTitle: "System",
            systemDescription: "Follow your device appearance.",
            lightTitle: "Light",
            lightDescription: "Keep Aks bright and clear.",
            darkTitle: "Dark",
            darkDescription: "A softer experience in low light.",
        },
        noteCaption: "A NOTE FROM AKS",
        noteBody: "Appearance only changes how Aks looks.",
        notices: {
            unableToSave: "Unable to save appearance",
        },
    },
    account: {
        header: "Account",
        signedInAs: "SIGNED IN AS",
        emailUnavailable: "Email unavailable",
        signOut: "Sign out",
        deleteAccount: "Delete account",
        confirmSignOutTitle: "Sign out?",
        confirmSignOutMessage: "You'll need to sign in again to continue using Aks.",
        confirmDeleteTitle: "Delete account?",
        confirmDeleteMessage:
            "This permanently removes your account and associated data. This cannot be undone.",
        notices: {
            unableToSignOut: "Unable to sign out",
            unableToDelete: "Unable to delete account",
            deleteUnavailable:
                "Account deletion is not available right now. Please try again later.",
        },
    },
    about: {
        header: "About Aks",
        eyebrow: "ABOUT",
        title: "Understand yourself, differently.",
        description:
            "Aks helps you reflect on your activity, notice possible patterns, and run personal experiments with more intention.",
        productLabel: "Product",
        productValue: "Aks.ai",
        versionLabel: "Version",
        versionValue: "1.0.0",
        note: "Aks supports personal reflection and does not replace professional medical or mental-health advice.",
    },
    subscription: {
        header: "Subscription",
        eyebrow: "YOUR PLAN",
        title: "Aks plan and billing.",
        description:
            "Review your current plan and billing status. Subscription management can be connected when billing is available.",
        checkingPlan: "Checking your plan…",
        fallbackError: "We couldn't check your plan. Please try again.",
        currentPlan: "CURRENT PLAN",
        activeBadge: "Active",
        planActive: "Your plan is active.",
        renewsOn: (date: string) => `Renews on ${date}`,
        accessUntil: (date: string) => `Access until ${date}`,
        autoRenewOff: "Auto-renewal is off.",
        billing: "BILLING",
        manage: "Manage subscription",
        restore: "Restore purchases",
        choosePlan: "CHOOSE YOUR PLAN",
        chooseTitle: "Spend more time with Aks.",
        chooseDescription:
            "Choose the rhythm that works for you. You can manage or restore your subscription at any time.",
        expiredWithDate: (date: string) => `Your Premium access ended on ${date}.`,
        expiredFallback: "Your Premium access has ended.",
        plansEmpty: "Plans aren't listed right now. Please check back in a moment.",
        premiumEyebrow: "AKS PREMIUM",
        bestValue: "BEST VALUE",
        premiumAccess: "Full access to Aks Premium",
        continueWith: (title: string) => `Continue with ${title}`,
        unavailableTitle: "Subscriptions aren't connected on this device yet.",
        unavailableBody:
            "Once billing is available on this device, plans will appear here and you can review or manage them from this screen.",
        noteCaption: "A NOTE FROM AKS",
        noteBody: "Payments are handled by your device's store.",
    },
    notifications: {
        header: "Notifications",
        eyebrow: "STAY IN THE LOOP",
        title: "Only when it matters.",
        description: "Choose when Aks can reach out. You can change these preferences at any time.",
        sectionMain: "NOTIFICATIONS",
        allowTitle: "Allow notifications",
        allowDescription: "Pause or resume all Aks notifications.",
        categoriesSection: "WHAT AKS CAN SEND",
        categories: {
            insightsTitle: "New insights",
            insightsDescription: "When Aks notices a meaningful pattern.",
            experimentsTitle: "Experiment updates",
            experimentsDescription: "Reminders and outcomes from active experiments.",
            checkInsTitle: "Check-in reminders",
            checkInsDescription: "A gentle prompt to reflect on your day.",
            weeklyTitle: "Weekly reflection",
            weeklyDescription: "A summary of what changed during the week.",
        },
        quietSection: "QUIET HOURS",
        quietTitle: "Quiet hours",
        quietDescription: "Silence notifications from 10:00 PM to 8:00 AM.",
        deviceSection: "DEVICE SETTINGS",
        deviceTitle: "Manage device notifications",
        deviceDescription: "Open your device settings to manage Aks permissions.",
        noteCaption: "A NOTE FROM AKS",
        noteBody: "Aks only reaches out when it matters.",
    },
    yourData: {
        header: "Your data",
        eyebrow: "YOUR DATA",
        title: "What Aks remembers.",
        description:
            "See the information Aks has gathered from your activity and the things you've chosen to share.",
        glanceSection: "AT A GLANCE",
        remembersSection: "WHAT AKS REMEMBERS",
        sourcesSection: "DATA SOURCES",
        sourcesTitle: "Connected sources",
        sourcesUnknown: "Check which sources are connected.",
        sourcesNone: "No connected sources. Available when supported.",
        sourcesCount: (count: number) => `${count} connected · manage or disconnect any time.`,
        choiceSection: "YOUR CHOICE",
        choiceTitle: "You decide what stays.",
        choiceBody: "Review, export, or delete your information any time.",
        exportAction: "Export data",
        deleteAction: "Delete data",
        noteCaption: "A NOTE FROM AKS",
        noteBody: "Your data stays understandable and under your control.",
        loadingData: "Loading data summary",
        retry: "Try again",
    },
    reflections: {
        header: "Reflections",
        eyebrow: "YOUR REFLECTIONS",
        title: "Things you've shared.",
        description: "Review the reflections that give Aks context about your experiences.",
        itemTitle: "Reflection",
        emptyTitle: "No reflections yet.",
        emptyBody: "Your reflections will appear here when you begin sharing them with Aks.",
    },
    checkIns: {
        header: "Check-ins",
        eyebrow: "YOUR CHECK-INS",
        title: "Small moments, remembered.",
        description: "Review the check-ins you've used to capture how things felt over time.",
        itemFallback: "Check-in",
        itemTitle: (mood: string) => `${mood} check-in`,
        energy: (value: number) => `Energy ${value}`,
        focus: (value: number) => `Focus ${value}`,
        stress: (value: number) => `Stress ${value}`,
        noDetails: "No additional details",
        emptyTitle: "No check-ins yet.",
        emptyBody: "Your check-ins will appear here once you begin recording them.",
    },
    conversations: {
        header: "Conversations",
        eyebrow: "YOUR CONVERSATIONS",
        title: "Your conversations with Aks.",
        description:
            "Revisit what you shared, without mixing it with future interpretations. Search covers titles and what was said.",
        searchA11y: "Search conversations",
        searchPlaceholder: "Search your conversations",
        clearSearch: "Clear",
        loadingA11y: "Loading conversations",
        loadErrorTitle: "Unable to load conversations.",
        emptyQueryTitle: "No matching conversations.",
        emptyQueryBody: "Try a different word — Aks searches what you said, not just titles.",
        emptyTitle: "No conversations yet.",
        emptyBody: "Conversations you start with Aks will appear here.",
        archiveHint: "Long press to archive",
        loadMore: "Load more",
        archiveTitle: "Archive conversation?",
        archiveMessage: "It will be hidden from your active conversation history.",
        archiveConfirm: "Archive",
        notices: {
            unableToArchive: "Unable to archive",
        },
    },
    conversationDetail: {
        fallbackTitle: "Conversation",
        renameA11y: "Rename conversation",
        loadingA11y: "Loading conversation",
        unavailableTitle: "Conversation unavailable.",
        archivedBody: "It may have been archived or removed.",
        renameSection: "RENAME CONVERSATION",
        titleA11y: "Conversation title",
        titlePlaceholder: "Conversation title",
        saveRename: "Save",
        cancelRename: "Cancel",
        cancelRenameA11y: "Cancel renaming",
        historySection: "CONVERSATION HISTORY",
        startedAt: (date: string) => `Started ${date}`,
        continueMirror: "Continue in Mirror",
        loadEarlier: "Load earlier messages",
        youLabel: "You",
        aksLabel: "Aks",
        systemLabel: "System",
        emptyTitle: "No messages yet.",
    },
    memories: {
        header: "What Aks remembers",
        eyebrow: "WHAT AKS REMEMBERS",
        title: "Useful context, carefully kept.",
        description:
            "Things Aks has picked up from repeated, evidence-backed information you've shared.",
        observationsCount: (count: number) => `${count} ${count === 1 ? "observation" : "observations"}`,
        lastNoticed: (date: string) => `Last noticed ${date}`,
        emptyTitle: "Aks is still getting to know your patterns.",
        emptyBody:
            "Repeated, useful context will appear here when there is enough evidence to remember it.",
    },
    memoryDetail: {
        header: "Memory",
        loadingA11y: "Loading memory",
        unavailableTitle: "Memory unavailable.",
        archivedFallback: "It may have been archived or removed.",
        eyebrow: "WHAT AKS REMEMBERS",
        reasonTitle: "Why Aks remembers this",
        reasonFallback: (count: number) => `This has appeared in ${count} ${count === 1 ? "thing" : "things"} you've shared.`,
        lastNoticed: (date: string) => `Last noticed ${date}`,
        evidenceSection: "EVIDENCE",
        viewConversation: " · View conversation",
        archiveAction: "Archive memory",
        removeAction: "Remove memory",
        archiveTitle: "Archive this memory?",
        archiveMessage:
            "Aks will stop using this memory now. Future things you share may support it again. Your original conversations, reflections, and check-ins will remain.",
        archiveConfirm: "Archive",
        removeTitle: "Remove this memory?",
        removeMessage:
            "This removes Aks's stored memory only. The original information you shared will not be deleted.",
        removeConfirm: "Remove",
        notices: {
            unableToArchive: "Unable to archive",
            unableToRemove: "Unable to remove",
        },
    },
    patterns: {
        header: "Patterns",
        eyebrow: "YOUR PATTERNS",
        title: "Connections worth noticing.",
        description: "Possible relationships grounded in repeated signals from what you've shared.",
        observationsCount: (count: number) => `${count} observations`,
        emptyTitle: "No patterns yet.",
        emptyBody: "Aks needs a little more time and evidence before it can spot useful connections.",
        status: {
            possible: "Possible pattern",
            notSupported: "Not supported",
            supported: "Supported",
            testing: "Being tested",
            fallback: "Candidate",
        },
    },
    patternDetail: {
        header: "Pattern",
        loadingA11y: "Loading pattern",
        unavailableTitle: "Pattern unavailable.",
        archivedFallback: "It may have been archived or removed.",
        reasonTitle: "Why Aks noticed this",
        evidenceLine: (supporting: number, contradicting: number) =>
            `This relationship is linked to ${supporting} supporting ${supporting === 1 ? "observation" : "observations"}` +
            (contradicting ? ` and ${contradicting} contradicting ${contradicting === 1 ? "observation" : "observations"}` : "") +
            ".",
        confidencePending: "Confidence still being assessed",
        confidenceValue: (percent: number) => `Evidence confidence ${percent}%`,
        firstNoticed: (date: string) => `First noticed ${date}`,
        lastObserved: (date: string) => `Last observed ${date}`,
        alternativeTitle: "Another possibility",
        evidenceSection: "EVIDENCE",
        supporting: "Supporting",
        contradicting: "Contradicting",
        viewConversation: " · View conversation",
        notReadyA11y: "This pattern is not ready to test",
        testA11y: "Test this pattern",
        notReady: "Not ready to test",
        testAction: "Test this pattern",
        archiveAction: "Archive pattern",
        removeAction: "Remove pattern",
        statusLabels: {
            candidate: "Candidate",
            possible: "Possible pattern",
            testing: "Being tested",
            supported: "Supported",
            notSupported: "Not supported",
            archived: "Archived",
        },
        archiveTitle: "Archive this pattern?",
        archiveMessage:
            "Aks will stop showing this pattern. Future observations may support a new review.",
        archiveConfirm: "Archive",
        removeTitle: "Remove this pattern?",
        removeMessage:
            "This removes only the derived pattern and its evidence links. Your signals and original information will remain.",
        removeConfirm: "Remove",
        notices: {
            unableToArchive: "Unable to archive",
            unableToRemove: "Unable to remove",
        },
    },
    experiments: {
        header: "Experiments",
        eyebrow: "YOUR EXPERIMENTS",
        title: "Small tests, useful evidence.",
        description: "Experiments help you test a possible pattern without treating it as fact.",
        observationsCount: (count: number) => `${count} observations`,
        emptyTitle: "No experiments yet.",
        emptyBody: "When a pattern is worth testing, you can run a small experiment around it.",
        status: {
            active: "Active",
            completed: "Completed",
            cancelled: "Cancelled",
            fallback: "Draft",
        },
    },
    experimentSetup: {
        header: "Set up experiment",
        patternSection: "PATTERN BEING TESTED",
        titleLabel: "TITLE",
        titlePlaceholder: "Short experiment title",
        hypothesisLabel: "HYPOTHESIS",
        hypothesisPlaceholder: "A small change may...",
        hypothesisDefault: "A small change may affect what you observe in this pattern.",
        descriptionLabel: "WHAT TO TRY AND OBSERVE",
        descriptionPlaceholder: "Describe one small change and what you will record.",
        descriptionDefault:
            "Choose one small, reversible change. Record whether the result felt easier, the same, or harder each time.",
        durationLabel: "DURATION",
        durationA11y: (days: number) => `${days} day duration`,
        durationDays: (days: number) => `${days}d`,
        defaultTitle: (patternTitle: string) => `Test: ${patternTitle}`.slice(0, 120),
        createAction: "Create draft",
        createA11y: "Create experiment draft",
        createError: "We couldn't create this experiment. Check the details and try again.",
        patternUnavailable: "This pattern is unavailable.",
    },
    experimentDetail: {
        header: "Experiment",
        unavailableTitle: "Experiment unavailable.",
        hypothesisTitle: "Hypothesis",
        whatToTryTitle: "What to try",
        startAction: "Start experiment",
        startA11y: "Start experiment",
        removeAction: "Remove experiment",
        removeA11y: "Remove experiment",
        removeTitle: "Remove experiment?",
        removeMessage:
            "This deletes the experiment, observations, and any learning supported only by this experiment. The original pattern and signals remain.",
        removeConfirm: "Remove",
        recordedFallback: "Recorded",
        observationsSection: "OBSERVATIONS",
        emptyObservations: "No observations recorded yet.",
        resultSection: "RESULT",
        analysisPending: "Analysis pending",
        confidenceValue: (percent: number) => `Evidence confidence ${percent}%`,
        promptTitle: "How did it feel this time?",
        resultEasier: "Easier",
        resultSame: "Same",
        resultHarder: "Harder",
        recordA11y: (result: string) => `Record ${result}`,
        observationPlaceholder: "Optional note",
        observationA11y: "Optional observation note",
        observationsMeta: (count: number) => `${count} recorded observations`,
        observationsDay: (current: number, total: number | null) =>
            total ? ` · Day ${current} of ${total}` : "",
        observationsThrough: (date: string) => ` · Through ${date}`,
        completeAction: "Complete experiment",
        completeA11y: "Complete experiment",
        cancelAction: "Cancel experiment",
        cancelA11y: "Cancel experiment",
        resultPendingBody: "Your observations are saved while the outcome is prepared.",
        retryAnalysis: "Retry interpretation",
        retryAnalysisA11y: "Retry experiment analysis",
        retryLearning: "Retry learning synthesis",
        retryLearningA11y: "Retry learning synthesis",
        retryInsight: "Retry insight generation",
        retryInsightA11y: "Retry insight generation",
        resultLabels: {
            easier: "Easier",
            same: "Same",
            harder: "Harder",
        },
        outcomeLabels: {
            supports: "Supports the hypothesis",
            mixed: "Mixed result",
            doesNotSupport: "Didn't support the hypothesis",
            insufficientData: "Not enough data",
        },
        confirmCompleteTitle: "Complete this experiment?",
        confirmCompleteMessage: "Aks will summarize what your observations suggest.",
        confirmCompleteLabel: "Complete",
        confirmCancelTitle: "Cancel this experiment?",
        confirmCancelMessage: "Your recorded observations will stay available.",
        confirmCancelLabel: "Cancel experiment",
        keepGoing: "Keep going",
        notices: {
            unableToUpdate: "Unable to update",
            unableToRecord: "Unable to record",
            recordRetry: "Your previous attempt can be retried safely.",
        },
    },
    learnings: {
        header: "Learnings",
        eyebrow: "YOUR LEARNINGS",
        title: "What the evidence suggests.",
        description:
            "Careful takeaways from experiments you've completed and observations you recorded.",
        statusRevised: "Revised",
        statusActive: "Active",
        observationsCount: (count: number) => `${count} observations`,
        emptyTitle: "No learnings yet.",
        emptyBody:
            "Once you've tested something and gathered enough evidence, Aks can help make sense of what changed.",
    },
    learningDetail: {
        header: "Learning",
        unavailableTitle: "Learning unavailable.",
        evidenceTitle: "What led to this?",
        evidenceLine: (experiments: number, observations: number) =>
            `Based on ${experiments} completed ${experiments === 1 ? "experiment" : "experiments"} and ${observations} recorded ${observations === 1 ? "observation" : "observations"}.`,
        confidenceValue: (percent: number) => `Evidence confidence ${percent}%`,
        updatedAt: (date: string) => `Updated ${date}`,
        sourceSection: "SOURCE EXPERIMENTS",
        openExperimentA11y: (title: string) => `Open experiment ${title}`,
        observationsCount: (count: number) => `${count} observations`,
        archiveAction: "Archive learning",
        archiveA11y: "Archive learning",
        removeAction: "Remove learning",
        removeA11y: "Remove learning",
        resultLabels: {
            supports: "Supported the hypothesis",
            mixed: "Mixed result",
            doesNotSupport: "Did not support the hypothesis",
            insufficientData: "Not enough data",
        },
        archiveTitle: "Archive this learning?",
        archiveMessage: "The source experiments and observations will remain available.",
        archiveConfirm: "Archive",
        removeTitle: "Remove this learning?",
        removeMessage:
            "This removes only the derived learning. Experiments, observations, patterns, and signals will remain.",
        removeConfirm: "Remove",
        notices: {
            unableToArchive: "Unable to archive",
            unableToRemove: "Unable to remove",
        },
    },
    insights: {
        header: "Insights",
        eyebrow: "INSIGHTS",
        title: "Something worth noticing.",
        description: "A small set of timely observations grounded in what you've tested and learned.",
        statusNew: "New",
        statusSeen: "Seen",
        emptyTitle: "No insights yet.",
        emptyBody: "As Aks sees enough evidence over time, useful things will start to stand out.",
    },
    insightDetail: {
        header: "Insight",
        eyebrow: "INSIGHT",
        unavailableTitle: "Insight unavailable.",
        reasonTitle: "Why Aks noticed this",
        openExperimentA11y: (title: string) => `Open source experiment ${title}`,
        openLearningA11y: (title: string) => `Open source learning ${title}`,
        observationsCount: (count: number) => `${count} recorded observations · View experiment`,
        viewLearning: "View source learning",
        confidenceValue: (percent: number) => `Evidence confidence ${percent}%`,
        createdAt: (date: string) => `Created ${date}`,
        dismissAction: "Dismiss insight",
        dismissA11y: "Dismiss insight",
        removeAction: "Remove insight",
        removeA11y: "Remove insight",
        dismissTitle: "Dismiss this insight?",
        dismissMessage: "The learning, experiment, pattern, and evidence will remain.",
        dismissConfirm: "Dismiss",
        removeTitle: "Remove this insight?",
        removeMessage: "This removes only the insight. All source information will remain.",
        removeConfirm: "Remove",
        notices: {
            unableToDismiss: "Unable to dismiss",
            unableToRemove: "Unable to remove",
        },
    },
    privacyHome: {
        header: "Privacy",
        eyebrow: "YOUR PRIVACY",
        title: "Your life is yours.",
        description:
            "Aks helps you understand yourself while keeping you in control of the information behind your experience.",
        dataSection: "YOUR DATA",
        knowsTitle: "What Aks knows",
        knowsDescription: "Understand the information used to create your experience.",
        accessTitle: "What Aks can access",
        accessDescription: "Review what you provide or choose to connect.",
        controlsSection: "DATA CONTROLS",
        usageTitle: "How your data is used",
        usageDescription: "See how information supports insights and experiments.",
        exportTitle: "Export your data",
        exportDescription: "Request a copy of your Aks information.",
        deleteTitle: "Delete your data",
        deleteDescription: "Start a careful account data deletion request.",
        legalSection: "LEGAL",
        privacyPolicyTitle: "Privacy Policy",
        privacyPolicyDescription: "Read the full Aks Privacy Policy.",
    },
    dataAccess: {
        header: "What Aks can access",
        title: "Clear by design.",
        description:
            "Aks works with information you provide and data sources you deliberately choose to connect.",
        sourcesSection: "CONNECTED SOURCES",
        loadingSources: "Loading your connected sources…",
        loadError: "We couldn't load your connected sources right now.",
        emptyTitle: "No connected sources yet",
        emptyBody:
            "Aks reads from external services only after you explicitly connect them. You can manage any connection from your account settings.",
        connectedNeedsPermission: "Connected · permission needed",
        connectedSynced: (relative: string) => `Connected and reading data · synced ${relative}`,
        connectedNotSynced: "Connected and reading data · not synced yet",
        holdsSection: "WHAT AKS HOLDS",
        items: [
            {
                title: "Information you provide",
                body: "Details you enter directly into Aks, such as profile information and preferences.",
            },
            {
                title: "Reflections and check-ins",
                body: "Entries you create to describe your experiences, mood, focus, energy, or routines.",
            },
            {
                title: "Experiment data",
                body: "Experiments you create and the outcomes or notes you record.",
            },
            {
                title: "Account information",
                body: "Basic information needed to identify and manage your Aks account.",
            },
            {
                title: "Connected data sources",
                body: "Only information from services you explicitly choose to connect, where those connections are available.",
            },
        ],
        controlTitle: "You're in control",
        controlBody: "Aks only uses what you enter or explicitly connect.",
    },
    dataUsage: {
        header: "How your data is used",
        title: "Your data has a purpose.",
        description:
            "Aks uses information within the product to make your experience more relevant and understandable.",
        sections: [
            {
                title: "Why Aks uses your data",
                body: "Information you choose to share helps Aks personalize reflections, identify useful themes, and support your goals.",
            },
            {
                title: "Reflections and check-ins",
                body: "Your entries can provide context for changes in mood, energy, focus, and routines over time.",
            },
            {
                title: "Pattern detection",
                body: "Aks can compare information you provide to surface possible patterns for you to review. These are prompts for reflection, not medical conclusions.",
            },
            {
                title: "Memory",
                body: "Aks may retain a small amount of repeated, useful context. Every memory stays linked to the information that supports it and can be removed without deleting the original source.",
            },
            {
                title: "Experiments and outcomes",
                body: "Experiment entries can help you compare what you tried with the outcomes you recorded.",
            },
            {
                title: "AI-assisted understanding",
                body: "AI may help organize and summarize the information you provide. Review important insights and use your own judgment.",
            },
        ],
        privacyPolicyAction: "Read full Privacy Policy",
    },
    exportData: {
        header: "Export your data",
        preparingTitle: "Preparing your export",
        preparingBody:
            "Gathering your conversations, reflections, memories, patterns, experiments, and insights. This usually takes a few seconds.",
        errorTitle: "Take your data with you.",
        errorBody: "A downloadable copy of your Aks information is available on request.",
        failedTitle: "Couldn't create your export.",
        failedFallback: "Something went wrong while preparing your export. Please try again.",
        retryA11y: "Try to create the export again",
        cancelAction: "Cancel",
        cancelA11y: "Go back to the export introduction",
        readyTitle: "Your export is ready.",
        readyBody:
            "A snapshot of your Aks information was prepared just now. It covers the same sections listed when you requested it.",
        expiresIn: (countdown: string) => `Link expires in ${countdown}`,
        expiresSoon: "a moment",
        saveAction: "Save export",
        saveA11y: "Save the export",
        requestAnother: "Request another export",
        requestAnotherA11y: "Request another export",
        idleTitle: "Take your data with you.",
        idleBody:
            "A downloadable copy of your Aks information is available on request. Each export is a single file that reflects your account at the moment you request it.",
        includedSection: "WHAT IS INCLUDED",
        included: [
            "Profile and preferences",
            "Conversations and messages",
            "Reflections",
            "Check-ins",
            "Signals",
            "Memories and evidence links",
            "Patterns and evidence links",
            "Experiments and observations",
            "Learnings and source links",
            "Insights and source references",
        ],
        requestAction: "Request data export",
        requestA11y: "Request the export",
    },
    deleteData: {
        header: "Delete your data",
        title: "Leave nothing behind.",
        description:
            "Deleting your account permanently removes the data you created in Aks. It also signs you out of this device.",
        warningTitle: "This cannot be undone.",
        warningBody:
            "Once your account is deleted, your Aks data is gone and cannot be recovered. Consider exporting your data first if you would like a copy.",
        removedSection: "WHAT WILL BE REMOVED",
        removed: [
            "Conversations and messages",
            "Reflections",
            "Check-ins",
            "Derived signals",
            "Memories and evidence links",
            "Patterns and evidence links",
            "Experiments and observations",
            "Learnings and source links",
            "Insights and source references",
        ],
        confirmA11y: "Confirm that you understand this is permanent",
        confirmLabel: "I understand that this action is permanent and that all of my Aks data will be removed.",
        deleteAction: "Delete my account and data",
        deleteActionA11y: "Delete my account and data",
        deletingAction: "Deleting your account…",
        deletedTitle: "Your account is being deleted.",
        deletedBody: "You'll be signed out as the deletion completes.",
        backToSettings: "Back to Settings",
        backToSettingsA11y: "Return to Settings",
        keepAccount: "Keep my account",
        keepAccountA11y: "Keep my account",
        keepNote: "Deleting your account also removes any export files created for this account.",
    },
    helpHome: {
        header: "Help & feedback",
        title: "We're listening.",
        description: "Something not working, something confusing, or something you wish Aks could do?",
        supportTitle: "Need a hand?",
        supportBody: "Our support team is here to help.",
        supportAction: "Contact support",
        getHelpSection: "GET HELP",
        faqTitle: "Frequently asked questions",
        faqDescription: "Find quick answers to common questions",
        reportTitle: "Report a problem",
        reportDescription: "Tell us when something isn't working",
        improveSection: "MAKE AKS BETTER",
        suggestTitle: "Suggest an idea",
        suggestDescription: "Tell us what you'd like Aks to learn or do",
        shareTitle: "Share your experience",
        shareDescription: "Tell us what feels great or could be better",
        contactSection: "CONTACT",
        supportEmail: "support@aks.ai",
        supportResponse: "Usually replies within 1–2 business days",
        footerVersion: "1.0.0",
    },
    faq: {
        header: "Help & feedback",
        title: "Frequently asked questions",
        description: "Find quick answers about how Aks works and how your data is handled.",
        searchPlaceholder: "Search questions",
        clearSearch: "Clear",
        resultsCount: (count: number) => `${count} RESULTS`,
        popularSection: "POPULAR QUESTIONS",
        questionsCount: (count: number) => `${count} questions`,
        items: [
            {
                question: "How does Aks discover patterns?",
                answer: "Aks looks for useful connections in the information and reflections you choose to share.",
            },
            {
                question: "Can I control what data Aks uses?",
                answer: "Yes. You can review your information and manage available permissions from Your data and Privacy.",
            },
            {
                question: "How do experiments work?",
                answer: "Experiments help you test small changes and reflect on what affects your focus, energy, sleep, and routines.",
            },
            {
                question: "Can I change notification settings?",
                answer: "Yes. Open Notifications from the You page to choose when Aks should reach out.",
            },
            {
                question: "Is Aks medical advice?",
                answer: "No. Aks supports personal reflection and does not replace professional medical or mental-health advice.",
            },
        ],
        emptyTitle: "Nothing matched",
        emptyBody: "Try another search term or browse the questions above.",
        clearAction: "Clear search",
        helpTitle: "Still need help?",
        helpBody: "Tell us what's going on and we'll help you figure it out.",
        contactAction: "Get in touch",
    },
    sendFeedback: {
        header: "Send feedback",
        title: "Help shape Aks.",
        description: "Share an idea, request a feature, or tell us what is already working well.",
        optionLabel: "FEEDBACK TYPE",
        optionHint: "Choose one",
        options: ["Idea", "Feature request", "General feedback", "Something I liked"],
        initialOption: "General feedback",
        messageLabel: "YOUR FEEDBACK",
        messagePlaceholder: "What would make Aks more useful to you?",
        messageHint: "Ideas, suggestions, or things you enjoyed are all welcome.",
        emailHint: "Leave your email only if you'd like a response.",
        noteTitle: "Your feedback matters.",
        noteBody: "What you share helps us decide what Aks should become next.",
        submit: "Send feedback",
        leaveMessage: "You can leave this page without sending anything.",
    },
    reportProblem: {
        header: "Report a problem",
        title: "What went wrong?",
        description:
            "Tell us what happened. The more context you share, the easier it is for us to understand and fix it.",
        optionLabel: "PROBLEM CATEGORY",
        optionHint: "Choose one",
        options: [
            "Something isn't working",
            "App crashed",
            "Incorrect insight",
            "Data issue",
            "Notification issue",
            "Other",
        ],
        messageLabel: "WHAT HAPPENED?",
        messagePlaceholder: "Describe what you expected and what happened instead...",
        messageHint: "Please include any steps that caused the problem.",
        emailHint: "Add an email only if you'd like us to follow up.",
        noteTitle: "Thank you for helping improve Aks.",
        noteBody: "Your report helps us make Aks more reliable for everyone.",
        submit: "Submit report",
        leaveMessage: "You can leave this page without submitting.",
    },
    feedbackForm: {
        selectedState: "Selected",
        contactEmail: "CONTACT EMAIL",
        optionalMark: " OPTIONAL",
        emailPlaceholder: "you@example.com",
        charLimit: 1000,
    },
    profilePreference: {
        saveAction: "Save preferences",
        saveA11y: (title: string) => `Save ${title}`,
        noteCaption: "SAVED TO YOUR PROFILE",
        noteBody: "Your choices are saved to your profile.",
        notices: {
            unableToSave: "Unable to save preferences",
        },
    },
    dataCategory: {
        recentSection: "RECENT",
        loadingA11y: (title: string) => `Loading ${title}`,
        loadErrorTitle: "Unable to load this data.",
        tryAgain: "Try again",
        loadMore: "Load more",
        noteCaption: "A NOTE FROM AKS",
        noteBody: "Your entries appear here as they're created.",
    },
    bottomSheet: {
        dismissA11y: "Dismiss",
        defaultConfirm: "Got it",
        cancel: "Cancel",
    },
    connectedSources: {
        header: "Connected sources",
        eyebrow: "CONTEXT & PERMISSIONS",
        title: "You decide what Aks knows.",
        description:
            "Aks works fully without any connected source. Each source is optional, independent, and explains exactly what it shares. You can disconnect anything at any time.",
        loadingA11y: "Loading sources",
        loadError: "We couldn't load your connected sources.",
        status: {
            connected: "Connected",
            permissionRequired: "Permission needed",
            notConnected: "Not connected",
            notAvailable: "Unavailable on this device",
            revoked: "Disconnected",
            temporarilyUnavailable: "Temporarily unavailable",
            error: "Unavailable right now",
        },
        syncedAgo: (relative: string) => `synced ${relative}`,
        notSynced: "not synced yet",
        whyHelps: "WHY IT HELPS",
        whatReceives: "WHAT AKS RECEIVES",
        whatStored: "WHAT IS STORED",
        howToStop: "HOW TO STOP",
        goodToKnow: "GOOD TO KNOW",
        disconnect: "Disconnect",
        deleteData: "Delete imported data",
        allow: "Allow",
        connect: "Connect",
        reconnect: "Reconnect",
        choiceSection: "YOUR CHOICE",
        choiceBody: "Only sources you connect are used. Stop any time in one tap.",
        confirmations: {
            cancelAction: "Cancel",
        },
        notices: {
            providerNotConfigured: "That provider isn't configured yet on this build.",
            unableToConnect: "We couldn't connect that source right now.",
        },
        groups: {
            productivity: "PRODUCTIVITY",
            work: "WORK",
            device: "DEVICE / BEHAVIOR",
        },
    },
    sources: {
        location: {
            name: "Location",
            purpose:
                "Let Aks understand where your day happens. This can help distinguish a difficult day from a day disrupted by travel or unexpected changes.",
            receives:
                "Coarse place context (home area, work area, travel, unfamiliar place) and movement windows — never continuous tracking.",
            stored: "Observation windows like 'travel, 45 minutes around 6:30 PM'. Precise coordinates are not stored.",
            stop: "Disconnect Location any time. Future collection stops immediately; already-stored observations can be deleted separately.",
            batteryNote:
                "Uses occasional location checks while connected. Enabling may increase battery usage slightly.",
        },
        calendar: {
            name: "Calendar",
            purpose:
                "Planned events help Aks understand the difference between a plan that changed and motivation that dipped.",
            receives:
                "Event times and a broad category. Titles only when they define the plan; never attendee lists, notes, or meeting links.",
            stored: "Minimal event records: time, duration, category, confirmed/cancelled.",
            stop: "Disconnect Calendar any time. Future collection stops immediately.",
        },
        reminders: {
            name: "Tasks & reminders",
            purpose:
                "Planned actions vs. what actually happened — without Aks ever claiming you 'skipped' something.",
            receives: "Due times and completion state of reminders you choose to sync.",
            stored: "Due time and completed/not-recorded status.",
            stop: "Disconnect Tasks & reminders any time.",
        },
        screenTime: {
            name: "Screen time",
            purpose:
                "Aggregated device-usage context may explain focus changes — it is never treated as proof of distraction.",
            receives: "Aggregated usage durations by broad category per time window.",
            stored: "Aggregated windows like 'social apps, 60 minutes, 9–10 PM'. No per-tap data.",
            stop: "Disconnect Screen time any time.",
        },
        googleCalendar: {
            name: "Google Calendar",
            purpose:
                "Your Google events give Aks the same planning context as your device calendar, for accounts you explicitly connect.",
            receives:
                "Event times and a broad category from the calendars you select. Never attendee lists, notes, or meeting links.",
            stored: "Minimal event records: time, duration, category, confirmed/cancelled.",
            stop: "Disconnect Google Calendar any time — and revoke access in your Google account settings.",
        },
        appleCalendar: {
            name: "Apple Calendar",
            purpose: "On iPhone and iPad, the same device calendar context through Apple's calendar store.",
            receives: "Event times and a broad category. Never attendee lists, notes, or meeting links.",
            stored: "Minimal event records: time, duration, category, confirmed/cancelled.",
            stop: "Disconnect Apple Calendar any time.",
        },
        googleTasks: {
            name: "Google Tasks",
            purpose:
                "Planned tasks from a Google account you connect, so Aks sees what you intended — never concluding you failed.",
            receives: "Task due times and completion state.",
            stored: "Due time and completed/not-recorded status.",
            stop: "Disconnect Google Tasks any time — and revoke access in your Google account settings.",
        },
        appleReminders: {
            name: "Apple Reminders",
            purpose:
                "On iPhone and iPad, planned actions from Apple Reminders feed the same planned-vs-happened context.",
            receives: "Due times and completion state of reminders.",
            stored: "Due time and completed/not-recorded status.",
            stop: "Disconnect Apple Reminders any time.",
        },
        notion: {
            name: "Notion",
            purpose:
                "Pages and databases you explicitly share with the Aks integration, so work context can inform conversations.",
            receives:
                "Titles, times, and a broad category for content you shared with the Aks Notion integration. Never page bodies.",
            stored: "Minimal item records: title-category, time, status.",
            stop: "Disconnect Notion any time — and remove the Aks integration from your Notion workspace.",
        },
        todoist: {
            name: "Todoist",
            purpose: "A connected task provider (Todoist or similar) so plans outside Aks count too.",
            receives: "Task due times and completion state.",
            stored: "Due time and completed/not-recorded status.",
            stop: "Disconnect Todoist any time — and revoke access in the provider's account settings.",
        },
        github: {
            name: "GitHub",
            purpose: "Your own commit and PR activity as objective work context — never other people's data.",
            receives: "Your commit and pull-request activity counts and times from repos you select.",
            stored: "Aggregated activity windows like '2 commits, 10–11 PM'. No code content.",
            stop: "Disconnect GitHub any time — and revoke the Aks OAuth app in your GitHub settings.",
        },
        slack: {
            name: "Slack",
            purpose: "Focus-block and availability signals from workspaces you explicitly connect.",
            receives: "Your own activity windows and Do-Not-Disturb state. Never message content.",
            stored: "Aggregated activity windows. No messages, no channels, no colleagues' data.",
            stop: "Disconnect Slack any time — and remove the Aks app from your workspace.",
        },
        email: {
            name: "Email",
            purpose: "Lightweight email-load context (counts only) from providers you connect — Gmail or others.",
            receives: "Counts and timing of received email. Never subject lines, bodies, or senders.",
            stored: "Aggregated counts per window. No content, no addresses.",
            stop: "Disconnect Email any time — and revoke access in the provider's security settings.",
        },
        voiceSession: {
            name: "Microphone",
            purpose:
                "Voice conversations are an explicit action you start. The microphone is used only during an active voice session.",
            receives: "Audio only while a voice conversation is running.",
            stored: "Transcripts you keep; audio is not stored.",
            stop: "End the voice session — the microphone turns off. Aks never listens in the background.",
        },
    },
    transparency: {
        connectedWith: (sources: string) =>
            `You've connected your ${sources}, so Aks can see that context alongside what you share here.`,
        names: {
            location: "location",
            calendar: "calendar",
            googleCalendar: "Google Calendar",
            appleCalendar: "Apple Calendar",
            reminders: "tasks",
            googleTasks: "Google Tasks",
            appleReminders: "Apple Reminders",
            todoist: "Todoist",
            notion: "Notion",
            github: "GitHub",
            slack: "Slack",
            email: "email",
            screenTime: "screen time",
            voiceSession: "voice",
        },
    },
    oauth: {
        googleCalendar: "Google Calendar",
        googleTasks: "Google Tasks",
        notion: "Notion",
        todoist: "Todoist",
        github: "GitHub",
        slack: "Slack",
        email: "Email",
    },
    errors: {
        pagedData: "We couldn't load this data. Please try again.",
        pagedDataMore: "We couldn't load more data. Please try again.",
        dataSummary: "We couldn't load your data summary. Please try again.",
        dataAccess: "Couldn't load your connected sources. Please try again.",
        memory: "We couldn't load this memory.",
        pattern: "We couldn't load this pattern.",
        experiment: "We couldn't load this experiment.",
        learning: "We couldn't load this learning.",
        insight: "We couldn't load this insight.",
        conversation: "We couldn't load this conversation. Please try again.",
        conversationEarlier: "We couldn't load earlier messages. Please try again.",
        conversationPlain: "We couldn't load this conversation.",
        conversationEarlierPlain: "We couldn't load earlier messages.",
        messageEmptySave: "Write something before saving.",
        exportLinkExpired: "The export link has expired. Please request a new export.",
        renameConversation: "We couldn't rename that conversation. Please try again.",
        exportExpired: "The export link has expired. Please request a new export.",
        exportCreate: "The export could not be created. Please try again.",
        exportDownload: "The export could not be downloaded. Please try again.",
        deleteAccount: "Account deletion is not available right now. Please try again later.",
        preferences: "We couldn't load your preferences.",
        appSetup: "We couldn't finish setting up your account. Please try again.",
        exportSaveTitle: "Save your Aks export",
        exportClearDevice: "Your account data is being deleted, but clearing this device needs another attempt.",
        shareUnavailable: "Sharing isn't available on this device. Please try again.",
        exportIncomplete: "The export response was incomplete. Please try again.",
        exportInterrupted: "The download was interrupted. Please try again.",
        exportGeneric: "Something went wrong. Please try again.",
        connectedSources: "We couldn't load your connected sources.",
        sourceUnavailable: "This source isn't available on your device.",
        sourcePermission: "Aks needs that permission to connect this source. You can try again later.",
        sourceConnect: "We couldn't connect that source.",
        sourceDisconnect: "We couldn't disconnect that source.",
        sourceDelete: "We couldn't delete that source's data.",
        oauthRecord: "We couldn't record that connection.",
        oauthDisconnect: "We couldn't disconnect that account.",
        webPage: "Unable to load this page.",
        webPageBody: "Please check your internet connection and try again.",
        generic: "Something went wrong. Please try again.",
        signInUnavailable: "Sign in is not available right now. Please try again later.",
        signInStart: "We couldn't start sign in.",
        authRequest: "We couldn't complete that request. Please try again.",
        storeUnreachable: "We couldn't reach the store. Check your connection and try again.",
        plansUnavailable: "Plans aren't available right now. Please try again in a moment.",
        planUnavailable: "That plan isn't available right now. Please try again in a moment.",
        storeFailed: "The store couldn't complete your request. Please try again.",
        subscriptionGeneric: "Something went wrong while handling your subscription. Please try again.",
        purchaseCancelled: "Checkout was cancelled. Nothing was charged.",
        purchasePending:
            "Your purchase is waiting for confirmation from the store. It will appear here once it's complete.",
        alreadySubscribed: "You're already subscribed to this plan.",
        checkoutPendingPremium:
            "Checkout finished, but Premium isn't active on your account yet. Emulator Test Store purchases don't activate Premium — use a device with the Play Store. Otherwise wait a moment, then try Restore purchases.",
        restoreEmpty: "No previous purchases were found to restore.",
        emptyMessage: "Write something before sending.",
        mirror: {
            noReply: "Aks hasn't responded to your last message yet.",
            unsavedRetry: "Your last message may not have finished saving. You can retry it safely.",
            resolvePending: "Retry or resolve your previous message before sending another one.",
            refreshFailed: "Aks couldn't refresh that response. The previous one is still here.",
            refreshFailedConversation:
                "Aks couldn't complete this response after several attempts. Your message is still saved.",
            refreshFailedUnsafe: "Aks couldn't understand the response safely. Your message is saved.",
            refreshFallback: "Aks couldn't process that right now. Your message is saved.",
            updateMessage: "We couldn't update that message. It may already have a reply from Aks.",
            checkInFailed: "We couldn't save your check-in. Please try again.",
            saveFailed: "We couldn't save your message. Check your connection and try again.",
            outboxQueued: "Saved on this device. Aks will send it when you're back online.",
            signInForVoice: "Voice conversations are available after you sign in.",
            voiceStartFailed: "We couldn’t start a voice conversation.",
        },
        voice: {
            realtimeNotConfigured: "Voice conversations aren’t configured for this build yet.",
            sessionUnavailable: "We couldn’t start a voice session. Please try again.",
            transportUnavailable: "This conversation option needs a development build of Aks.",
            audioUnavailable: "Live voice needs a development build with the Aks audio engine.",
            micDenied: "Microphone access is needed for a voice conversation.",
            transcriptionFailed: "Aks couldn’t make out what you said. Please try again.",
            providerError: "Aks couldn’t start the voice conversation right now.",
            sessionExpired: "The voice conversation expired. Reconnect to continue.",
            voiceFailed: "The voice conversation failed.",
            saveVoiceMessage: "We couldn’t save your voice message. It stays only in this session.",
            saveVoiceReply: "We couldn’t save Aks’s reply. It stays only in this session.",
            audioCaptureFailed: "Audio capture failed.",
            audioFailed: "Audio failed.",
        },
        writes: {
            signInRequired: "Please sign in to continue.",
            experimentInvalid: "The experiment response was invalid.",
            observation: "We couldn't save that observation.",
            reflection: "We couldn't save that reflection.",
            message: "We couldn't save that message.",
            checkIn: "We couldn't save that check-in.",
            insightUpdate: "We couldn't update this insight.",
            experimentUpdate: "We couldn't update this experiment.",
            startConversation: "We couldn't start that conversation.",
            sendMessage: "We couldn't save your message.",
            confirmMessage: "We couldn't confirm your saved message.",
            searchConversations: "We couldn't search your conversations.",
            updateConversation: "We couldn't update that conversation.",
            updateMessage: "We couldn't update that message.",
            confirmUpdatedMessage: "We couldn't confirm your updated message.",
            archiveConversation: "We couldn't archive that conversation.",
            archivePattern: "We couldn't archive this pattern.",
            removePattern: "We couldn't remove this pattern.",
            archiveMemory: "We couldn't archive this memory.",
            removeMemory: "We couldn't remove this memory.",
            archiveLearning: "We couldn't archive this learning.",
            removeLearning: "We couldn't remove this learning.",
        },
    },
    timelineEntries: {
        patternForming: "PATTERN FORMING",
        insight: "INSIGHT",
        newLearning: "NEW LEARNING",
        outcomeRecorded: "OUTCOME RECORDED",
        experimentStarted: "EXPERIMENT STARTED",
        experimentActive: "EXPERIMENT ACTIVE",
        reflection: "REFLECTION",
        checkIn: "CHECK-IN",
        experimentOutcomeTitle: "Experiment outcome recorded",
        reflectionTitle: "You captured a reflection",
    },
} as const;

export type AppCopy = typeof en;

/**
 * Structural translation shape: identical keys to English, but with every
 * literal widened to `string`. Every language table in `src/localization/`
 * must satisfy this type, so the compiler rejects missing or extra keys while
 * leaving wording free. Arrays keep their exact length, so lists like the
 * onboarding slides stay structurally parallel across languages.
 */
type WidenTree<T> =
    T extends (...args: infer A) => infer R
        ? (...args: A) => WidenTree<R>
        : T extends string
            ? string
            : T extends number
                ? number
                : T extends object
                    ? { [K in keyof T]: WidenTree<T[K]> }
                    : T;

export type Translation = WidenTree<typeof en>;

/**
 * Languages the app knows. Each new code needs a registry entry in
 * `src/localization/languages.ts`; a table under `src/localization/<code>.ts`
 * is what makes it selectable instead of falling back to English.
 */
export type Language = "en" | "hi" | "fr" | "es" | "zh" | "ja" | "ko" | "ar" | "ur";

/**
 * Swap the active copy table at runtime. `copy` is a deliberate module-level
 * singleton: every one of the 90+ `copy.*` call sites keeps working unchanged
 * while the active language switches. UI re-renders through
 * `LanguageProvider`, which re-renders its subtree when the language changes.
 */
export function applyLanguage(table: Translation): void {
    Object.assign(copy, table);
}

/**
 * Deep copy that keeps interpolation functions by reference. `copy` must be
 * independent of `en`: applying a language writes into `copy`'s own tree, and
 * if `copy` aliased `en`, the English source of truth would be corrupted by
 * the first switch and could never be restored.
 */
function cloneTable<T>(value: T): T {
    if (typeof value === "function") return value;
    if (Array.isArray(value)) return value.map(cloneTable) as unknown as T;
    if (value && typeof value === "object") {
        const out: Record<string, unknown> = {};
        for (const [key, item] of Object.entries(value)) out[key] = cloneTable(item);
        return out as T;
    }
    return value;
}

export const copy: AppCopy = cloneTable(en);
