import type { Translation } from "@/constants/copy";
import type { DayPart } from "@/lib/dayPart";

/**
 * Arabic translation.
 *
 * Every key of the English source of truth is required; the compiler rejects
 * missing or extra keys. Uses clear Modern Standard Arabic with a direct
 * singular أنت address — the right tone for a reflective personal app, and
 * readable across regions. Proper nouns keep their official Arabic or Latin
 * forms (Aks, Mirror, Premium, Notion, GitHub, Slack, Todoist) and Apple's and
 * Google's apps use their official Arabic product names.
 *
 * Typography: Arabic punctuation (، ؛ ؟), Arabic quotation marks («»), a space
 * between Arabic and Latin words or numerals for readability, and 24-hour
 * times. Counts use Arabic counters rather than plurals (3 ملاحظات). Mirror's
 * deliberately hedged language survives translation — possible patterns are
 * أنماط محتملة and observations stay دعوات للتأمل، لا استنتاجات طبية.
 *
 * NOTE ON LAYOUT: Arabic script itself is shaped and ordered right-to-left by
 * the platform text engine, so these strings read correctly. The surrounding
 * layout, however, is still left-to-right — mirroring the chrome (padding,
 * icons, back arrows, row order) requires I18nManager.forceRTL plus an app
 * reload and is a separate piece of work.
 */
const ar: Translation = {
    common: {
        back: "رجوع",
        cancel: "إلغاء",
        save: "حفظ",
        dismiss: "إغلاق",
        clear: "مسح",
        loading: "جارٍ التحميل…",
        tryAgain: "إعادة المحاولة",
        loadMore: "تحميل المزيد",
        pleaseTryAgain: "يرجى المحاولة مرة أخرى.",
        checkConnection: "تحقق من اتصالك وحاول مرة أخرى.",
        emailPlaceholder: "you@example.com",
        justNow: "الآن",
        dateUnavailable: "التاريخ غير متاح",
        version: (value: string) => `الإصدار ${value}`,
    },
    brand: {
        name: "Aks.ai",
        tagline: "افهم نفسك من زاوية أخرى.",
    },
    splash: {
        appName: "Aks.ai",
        subtitle: "افهم نفسك من زاوية أخرى.",
    },
    onboarding: {
        skip: "تخطي",
        moveForward: "التالي",
        getStarted: "هيا نبدأ",
        notices: {
            unableToContinue: "تعذّر المتابعة",
        },
        slides: [
            {
                eyebrow: "يومك يترك خيوطاً",
                title: "أنت تترك بالفعل\nخيوطاً تدلّ عليك.",
                description:
                    "ما تكرره. اللحظات التي تتجنبها. الأيام التي تشعر فيها أن شيئاً ما مختلف. Aks يجمع هذه الإشارات.",
            },
            {
                eyebrow: "أبعد من التأمل فقط",
                title: "لا نخمّن.\nبل نجرّب.",
                description:
                    "حوّل حدسك إلى تجربة صغيرة. غيّر شيئاً واحداً، وراقب ما يحدث، واكتشف ما يناسبك فعلاً.",
            },
            {
                eyebrow: "نسخة أوضح منك",
                title: "لكي لا تبقى\nلغزاً على نفسك.",
                description:
                    "مع الوقت، يبني Aks صورة حيّة لأنماطك واستجاباتك وما يصنع الفرق في يومك.",
            },
        ],
    },
    legal: {
        termsTitle: "شروط الاستخدام",
        privacyTitle: "سياسة الخصوصية",
        acceptance: {
            title: "قبل أن نبدأ.",
            description:
                "يتعامل Aks مع معلومات شخصية أثناء مساعدتك على ملاحظة أنماطك. هناك أمور تستحق أن تعرفها قبل المتابعة.",
            cardTitle: "بياناتك ملكك.",
            cardBody: "يستخدم Aks المعلومات التي تختار مشاركتها لإيجاد الأنماط ودعم تجاربك الشخصية.",
            bullets: [
                "أنت تقرر ما تشاركه.",
                "يمكنك إدارة بياناتك وأذوناتك في أي وقت.",
                "Aks ليس بديلاً عن الاستشارة الطبية أو النفسية المتخصصة.",
            ],
            agreePrefix: "أوافق على",
            terms: "شروط الاستخدام",
            andWord: "و",
            privacy: "سياسة الخصوصية",
            continue: "بدء استخدام Aks",
            retryAction: "إعادة المحاولة",
            retry: "إعادة المحاولة",
            footnote: "يمكنك مراجعة هذه المستندات في أي وقت من الإعدادات.",
            consentA11y: "أوافق على شروط الاستخدام وسياسة الخصوصية",
            notices: {
                unableToSave: "تعذّر حفظ الموافقة",
            },
        },
        links: {
            prefix: "بالمتابعة، أنت توافق على",
            terms: "شروط الاستخدام",
            andWord: "و",
            privacy: "سياسة الخصوصية الخاصة بـ Aks.ai.",
        },
    },
    login: {
        title: "مرحباً بعودتك.",
        description: "سجّل الدخول لمتابعة ما لاحظه Aks عنك.",
        emailLabel: "البريد الإلكتروني",
        sendLink: "تسجيل الدخول",
        sendLinkA11y: "إرسال رابط تسجيل الدخول",
        secureLinkNote: "سنرسل رابط دخول آمناً إلى بريدك الإلكتروني. لا حاجة لكلمة مرور.",
        divider: "أو تابع باستخدام",
        google: "Google",
        googleA11y: "المتابعة باستخدام Google",
        facebook: "Facebook",
        facebookA11y: "المتابعة باستخدام Facebook",
        github: "GitHub",
        githubA11y: "المتابعة باستخدام GitHub",
        noAccount: "ليس لديك حساب؟",
        createOne: "أنشئ حساباً",
        dismissError: "اضغط للإغلاق.",
        notices: {
            unableToSendLink: "تعذّر إرسال رابط تسجيل الدخول",
            unableToSignIn: "تعذّر تسجيل الدخول",
        },
    },
    register: {
        title: "لننشئ حسابك.",
        description: "لنبدأ رؤية نفسك بوضوح أكبر، مع Aks.",
        nameLabel: "الاسم",
        namePlaceholder: "اسمك",
        nameA11y: "الاسم",
        emailLabel: "البريد الإلكتروني",
        createAccount: "إنشاء حساب",
        createAccountA11y: "إنشاء حساب بالبريد الإلكتروني",
        secureLinkNote: "سنرسل رابط دخول آمناً إلى بريدك الإلكتروني. لا حاجة لكلمة مرور.",
        divider: "أو سجّل باستخدام",
        google: "Google",
        googleA11y: "المتابعة باستخدام Google",
        facebook: "Facebook",
        facebookA11y: "المتابعة باستخدام Facebook",
        github: "GitHub",
        githubA11y: "المتابعة باستخدام GitHub",
        hasAccount: "لديك حساب بالفعل؟",
        signIn: "تسجيل الدخول",
        dismissError: "اضغط للإغلاق.",
        notices: {
            unableToCreate: "تعذّر إنشاء الحساب",
            unableToSignIn: "تعذّر تسجيل الدخول",
        },
    },
    emailConfirmation: {
        title: "تحقّق من بريدك الإلكتروني.",
        body: (email: string) => `أرسلنا رابط دخول آمناً إلى ${email}. افتح الرابط على هذا الجهاز للمتابعة.`,
        resendNote: "عند إعادة الإرسال، يعمل أحدث رابط فقط.",
        resend: "إعادة إرسال الرابط",
        resendA11y: "إعادة إرسال رابط تسجيل الدخول",
        editEmail: "تغيير البريد الإلكتروني",
        editEmailA11y: "تغيير البريد الإلكتروني",
    },
    mirror: {
        eyebrow: "MIRROR",
        greeting: (firstName: string | null, part: DayPart = "morning") => {
            const base =
                part === "afternoon"
                    ? "طاب يومك"
                    : part === "evening"
                        ? "مساء الخير"
                        : part === "night"
                            ? "ليلة سعيدة"
                            : "صباح الخير";
            return `${base}${firstName ? `، ${firstName}` : ""}.`;
        },
        intro: "أنا Aks. لنبدأ بشيء صغير.",
        understandTitle: "ما الذي تريد أن تفهمه؟",
        differentHint: "يمكنك أيضاً أن تحدّث Aks عن شيء مختلف تماماً.",
        checkInEyebrow: "تحقّق سريع",
        checkInTitle: "كيف حالك اليوم؟",
        topics: ["التركيز", "الطاقة", "النوم", "المشاعر", "الروتين اليومي", "العلاقات", "الإنتاجية"],
        topicDraft: (topic: string) => `أريد أن أفهم ${topic} عندي.`,
        checks: ["جيد", "عادي", "مضطرب"],
        aksLabel: "AKS",
        errorTitle: "حدث خطأ ما.",
        retryResponse: "إعادة محاولة الرد",
        listening: "جارٍ الاستماع…",
        listeningMeta: (duration: string) => `${duration} · يُحفظ على هذا الجهاز فقط`,
        stopRecordingA11y: "إيقاف التسجيل",
        voiceReady: "تأمّلك الصوتي جاهز",
        voiceReadyHint: "سيحوّله Aks إلى نص للتأمل.",
        discardRecordingA11y: "تجاهل التسجيل",
        sendRecordingA11y: "إرسال التسجيل",
        composerPlaceholder: "أخبر Aks بما يدور في ذهنك الآن…",
        sendMessageA11y: "إرسال الرسالة",
        recordVoiceA11y: "تسجيل تأمّل صوتي",
        notices: {
            micUnavailable: "الميكروفون غير متاح",
            micUnavailableBody: "نحتاج إذن الميكروفون لتسجيل تأمّل صوتي. يمكنك الكتابة بدلاً من ذلك.",
            cantListen: "تعذّر بدء الاستماع",
            cantListenBody: "جرّب مرة أخرى، أو اكتب ما يدور في ذهنك.",
            stopRecording: "تعذّر إيقاف التسجيل",
            recordingFailed: "تعذّر حفظ هذا التسجيل",
            transcriptionNotConfigured:
                "تحويل الكلام إلى نص غير مهيّأ في هذا الإصدار بعد. يمكنك كتابة تأمّلك بدلاً من ذلك.",
            audioTooLong: "التسجيل طويل جداً. جرّب مقطعاً أقصر.",
            subscriptionRequired:
                "التأمّل الصوتي يتطلب Aks Premium، لذلك لم يُستخدم هذا التسجيل. يمكنك الكتابة بدلاً من ذلك.",
            emptyTranscription: "لم يسمع Aks شيئاً في هذا التسجيل. تحقق من الميكروفون وحاول مرة أخرى.",
            unsupportedAudio: "تنسيق التسجيل غير مدعوم. جرّب التسجيل مرة أخرى.",
            transcriptionUnavailable:
                "لم يتمكن Aks من سماع هذا التسجيل الآن. جرّب مرة أخرى أو اكتب بدلاً من ذلك.",
            unauthorized: "سجّل الدخول ثم حاول مرة أخرى.",
            recordingFailedFallback:
                "لم يتمكن Aks من حفظ هذا التسجيل الآن. جرّب مرة أخرى أو اكتب بدلاً من ذلك.",
        },
    },
    mirrorBar: {
        newConversation: "محادثة جديدة",
        composerPlaceholder: "أخبر Aks بما يدور في ذهنك الآن…",
        sendMessageA11y: "إرسال الرسالة",
        closeComposerA11y: "إغلاق حقل الكتابة",
        openKeyboardA11y: "فتح لوحة المفاتيح",
        stopVoiceA11y: "إنهاء المحادثة الصوتية",
        startVoiceA11y: "بدء المحادثة الصوتية",
        voiceOffA11y: "إيقاف الردود الصوتية",
        voiceOnA11y: "تشغيل الردود الصوتية",
        moreOptionsA11y: "خيارات إضافية للمحادثة",
        hint: "لا حاجة لترتيب أفكارك قبل الكلام. ابدأ فقط.",
    },
    aiConversation: {
        greeting: (firstName: string | null) => (firstName ? `مرحباً، ${firstName} 👋` : "مرحباً 👋"),
        openingPrompts: [
            "ما الذي يشغل بالك هذه الأيام؟",
            "كيف حالك اليوم؟",
            "هل هناك أمر يثقل عليك منذ فترة؟",
            "ما الذي يحتل مساحة في ذهنك؟",
            "هل نتحدث عمّا يدور في ذهنك؟",
            "هل هناك ما تريد أن تخرج به؟",
            "ما الذي يبدو ثقيلاً هذه الأيام؟",
            "هل هناك شيء تمنيت أن تقوله؟",
        ],
        copyAction: "نسخ",
        copiedAction: "تم النسخ",
        copyA11y: "نسخ الرسالة",
        shareAction: "مشاركة",
        shareA11y: "مشاركة الرسالة",
        tryAgainAction: "إعادة المحاولة",
        tryAgainA11y: "إعادة توليد هذا الرد",
        motionReadyA11y: "Aks جاهز",
        thinking: "جارٍ التفكير…",
        thinkingDefault: "Aks يفكّر…",
        aksTag: "aks",
        youTag: "أنت",
        listening: "جارٍ الاستماع…",
        speaking: "جارٍ التحدث…",
        loadingConversation: "جارٍ تحميل المحادثة…",
        youPrefix: "أنت: ",
        errorTitle: "حدث خطأ ما.",
        retryResponse: "إعادة محاولة الرد",
        voicePaused: "تم إيقاف الصوت مؤقتاً.",
        editPlaceholder: "أعد كتابة رسالتك…",
        saveAndSend: "حفظ وإرسال",
        saveAndSendA11y: "حفظ الرسالة المعدّلة وإرسالها",
        cancelEditingA11y: "إلغاء التعديل",
        cancel: "إلغاء",
        editMessage: "تعديل الرسالة",
        editMessageA11y: "تعديل رسالتك",
    },
    timeline: {
        header: "الخط الزمني",
        headerCaption: "مسارك مع Aks.",
        eyebrow: "رحلتك",
        title: "قصتك مستمرة.",
        description: "هنا ترى اللحظات والأنماط والتجارب والدروس التي صنعت وقتك مع Aks.",
        errorTitle: "تعذّر تحميل الخط الزمني.",
        errorBody: "قصتك محفوظة هنا. حاول مرة أخرى بعد قليل.",
        loadMoreError: "تعذّر تحميل المزيد.",
        empty: {
            allTitle: "قصتك ما زالت مستمرة.",
            allBody: "مع حديثك مع Aks، ستظهر هنا لحظات وأنماط وتجارب ودروس ذات معنى.",
            insightsTitle: "لا توجد رؤى بعد.",
            insightsBody: "عندما يجد Aks أدلة كافية مع الوقت، ستظهر هنا رؤى ذات معنى.",
            experimentsTitle: "لا توجد تجارب بعد.",
            experimentsBody: "التجارب التي تضعها بنفسك ستظهر هنا عند تنفيذها.",
            checkInsTitle: "لا توجد تحقّقات بعد.",
            checkInsBody: "ستظهر هنا التحقّقات ذات المعنى.",
            decisionsTitle: "لا توجد قرارات بعد.",
            decisionsBody: "القرارات والأنماط التي يلاحظها Aks ستظهر هنا عندما تتّضح.",
            learningsTitle: "لا توجد دروس بعد.",
            learningsBody: "كلما اتّضحت قصتك، ستظهر هنا دروس جديدة.",
        },
    },
    you: {
        title: "أنت",
        fallbackName: "عضو في Aks",
        subtitle: "مساحتك الشخصية",
        knowsTitle: "ما يعرفه Aks",
        knowsEmpty: "ما زال يتعرّف عليك",
        memoriesCount: (count: number) => `${count} ذكرى`,
        exploringTitle: "ما تستكشفه",
        exploringEmpty: "اختر اهتماماتك",
        unnoticedTitle: "ما لم تلاحظه بعد",
        insightsCount: (count: number) => `${count} رؤى تستحق النظر`,
        insightsEmpty: "لم يتحدد بعد",
        journeySection: "رحلتك",
        patternsTitle: "الأنماط",
        patternsDescription: "ما لاحظه Aks",
        experimentsTitle: "التجارب",
        experimentsDescription: "ما تجرّبه الآن",
        yourDataTitle: "بياناتك",
        yourDataDescription: "اطّلع على معلوماتك وأدرها",
        preferencesSection: "الإعدادات",
        notificationsTitle: "الإشعارات",
        notificationsDescription: "متى يتواصل Aks معك",
        appearanceTitle: "المظهر",
        appearanceDescription: "النظام · فاتح · داكن",
        privacyTitle: "الخصوصية",
        privacyDescription: "إدارة الأذونات والخصوصية",
        supportSection: "الدعم",
        helpTitle: "المساعدة والملاحظات",
    },
    settings: {
        header: "الإعدادات",
        eyebrow: "الإعدادات",
        title: "Aks على طريقتك.",
        description: "أدر حسابك واشتراكك وما يتعلق بـ Aks.",
        accountSection: "الحساب",
        profileTitle: "الملف الشخصي",
        profileDescription: "إدارة معلوماتك الشخصية",
        accountTitle: "الحساب",
        accountDescription: "تسجيل الخروج أو حذف الحساب",
        subscriptionTitle: "الاشتراك",
        subscriptionDescription: "إدارة خطط Aks والدفع",
        preferencesSection: "الإعدادات",
        languageTitle: "اللغة",
        aboutSection: "عن Aks",
        aboutTitle: "عن Aks",
        aboutDescription: "تعرّف على Aks أكثر",
        termsTitle: "شروط الاستخدام",
        privacyTitle: "سياسة الخصوصية",
    },
    profile: {
        header: "الملف الشخصي",
        fallbackName: "عضو في Aks",
        fallbackEmail: "البريد الإلكتروني غير متاح",
        editName: "تعديل الاسم",
        editNameA11y: "تعديل الاسم",
        changePhotoA11y: "تغيير صورة الملف الشخصي",
        photoA11y: "صورة الملف الشخصي",
        photoSheetTitle: "صورة الملف الشخصي",
        chooseImage: "اختيار صورة",
        removePhoto: "إزالة الصورة",
        aksSection: "Aks",
        exploringTitle: "ما تستكشفه",
        exploringEmpty: "غير محدد",
        noticeTitle: "ما ينبغي أن ينتبه إليه Aks",
        noticeEmpty: "غير محدد",
        preferencesSection: "الإعدادات",
        timezoneTitle: "المنطقة الزمنية",
        languageTitle: "اللغة",
        accountSection: "الحساب",
        emailTitle: "البريد الإلكتروني",
        emailUnavailable: "غير متاح",
        memberSince: "عضو منذ",
        memberSinceUnavailable: "غير متاح",
        signInMethod: "طريقة تسجيل الدخول",
        signInMethodFallback: "البريد الإلكتروني",
        editNameTitle: "تعديل الاسم",
        editNameMessage: "سيناديك Aks بهذا الاسم.",
        nameA11y: "الاسم",
        namePlaceholder: "اسمك",
        saving: "جارٍ الحفظ…",
        saveChanges: "حفظ التغييرات",
        fullName: "الاسم",
        notices: {
            unableToSaveName: "تعذّر حفظ الملف الشخصي",
            unableToUpdatePhoto: "تعذّر تحديث الصورة",
            unableToRemovePhoto: "تعذّر إزالة الصورة",
            checkConnection: "تحقق من اتصالك وحاول مرة أخرى.",
            tryAgain: "يرجى المحاولة مرة أخرى.",
        },
    },
    exploring: {
        header: "ما تستكشفه",
        eyebrow: "شخصي",
        title: "اختر اهتماماتك.",
        description: "اختر المجالات التي تريد فهمها بوضوح أكبر.",
        options: ["التركيز", "الطاقة", "النوم", "المزاج", "العادات", "التوتر"],
    },
    noticeAreas: {
        header: "ما ينبغي أن ينتبه إليه Aks",
        eyebrow: "شخصي",
        title: "حدّد ما ينتبه إليه Aks.",
        description: "اختر المجالات التي ينبغي أن يبدأ بها Aks عند ترتيب الأنماط المحتملة.",
        options: ["العادات اليومية", "تغيّرات الطاقة", "أنماط التركيز", "جودة النوم", "تغيّرات المزاج", "نتائج التجارب"],
    },
    timezone: {
        header: "المنطقة الزمنية",
        eyebrow: "الإعدادات",
        title: "وقتك المحلي.",
        description: "اختر المنطقة الزمنية التي يستخدمها Aks لترتيب الأمور في وقتها.",
    },
    language: {
        header: "اللغة",
        eyebrow: "الإعدادات",
        title: "اختر لغتك.",
        description: "اختر اللغة المستخدمة في كل أنحاء Aks.",
        notAvailableYet: (name: string) =>
            `${name} غير متاحة بعد. سنستخدم الإنجليزية حتى تتوفر الترجمة.`,
        comingSoon: "قريباً",
    },
    appearance: {
        header: "المظهر",
        eyebrow: "تجربتك",
        title: "بالشكل الذي يريحك.",
        description: "اختر كيف يبدو Aks في كل أنحاء التطبيق.",
        themeSection: "السمة",
        themes: {
            systemTitle: "النظام",
            systemDescription: "يتبع إعدادات جهازك.",
            lightTitle: "فاتح",
            lightDescription: "Aks بمظهر مضيء وواضح.",
            darkTitle: "داكن",
            darkDescription: "ألطف على العين في الأماكن المعتمة.",
        },
        noteCaption: "ملاحظة من AKS",
        noteBody: "المظهر يغيّر شكل Aks فقط.",
        notices: {
            unableToSave: "تعذّر حفظ المظهر",
        },
    },
    account: {
        header: "الحساب",
        signedInAs: "مسجّل الدخول باسم",
        emailUnavailable: "البريد الإلكتروني غير متاح",
        signOut: "تسجيل الخروج",
        deleteAccount: "حذف الحساب",
        confirmSignOutTitle: "تسجيل الخروج؟",
        confirmSignOutMessage: "ستحتاج إلى تسجيل الدخول مرة أخرى لمتابعة استخدام Aks.",
        confirmDeleteTitle: "حذف الحساب؟",
        confirmDeleteMessage: "سيُحذف حسابك والبيانات المرتبطة به نهائياً. لا يمكن التراجع عن هذا.",
        notices: {
            unableToSignOut: "تعذّر تسجيل الخروج",
            unableToDelete: "تعذّر حذف الحساب",
            deleteUnavailable: "حذف الحساب غير متاح حالياً. حاول مرة أخرى بعد قليل.",
        },
    },
    about: {
        header: "عن Aks",
        eyebrow: "نظرة عامة",
        title: "افهم نفسك من زاوية أخرى.",
        description:
            "يساعدك Aks على التأمل في نشاطك، وملاحظة الأنماط المحتملة، والقيام بتجارب شخصية أكثر وعياً.",
        productLabel: "المنتج",
        productValue: "Aks.ai",
        versionLabel: "الإصدار",
        versionValue: "1.0.0",
        note: "Aks أداة لدعم التأمل الشخصي، وليس بديلاً عن الاستشارة الطبية أو النفسية المتخصصة.",
    },
    subscription: {
        header: "الاشتراك",
        eyebrow: "خطتك",
        title: "خطط Aks والدفع.",
        description:
            "اطّلع على خطتك الحالية وحالة الدفع. وحين يتصل الدفع على هذا الجهاز، يمكنك إدارة اشتراكك من هنا.",
        checkingPlan: "جارٍ التحقق من خطتك…",
        fallbackError: "تعذّر التحقق من خطتك. حاول مرة أخرى.",
        currentPlan: "خطتك الحالية",
        activeBadge: "نشطة",
        planActive: "خطتك نشطة.",
        renewsOn: (date: string) => `تتجدد في ${date}`,
        accessUntil: (date: string) => `متاحة حتى ${date}`,
        autoRenewOff: "التجديد التلقائي متوقف.",
        billing: "الدفع",
        manage: "إدارة الاشتراك",
        restore: "استعادة المشتريات",
        choosePlan: "اختر خطة",
        chooseTitle: "وقت أطول مع Aks.",
        chooseDescription: "اختر الإيقاع الذي يناسبك. يمكنك إدارة اشتراكك واستعادته في أي وقت.",
        expiredWithDate: (date: string) => `انتهى وصولك إلى Premium في ${date}.`,
        expiredFallback: "انتهى وصولك إلى Premium.",
        plansEmpty: "لا توجد خطط لعرضها الآن. تحقق مرة أخرى بعد قليل.",
        premiumEyebrow: "AKS PREMIUM",
        bestValue: "الأفضل قيمة",
        premiumAccess: "الوصول الكامل إلى Aks Premium",
        continueWith: (title: string) => `المتابعة مع ${title}`,
        unavailableTitle: "لم يتصل الاشتراك على هذا الجهاز بعد.",
        unavailableBody:
            "حين يتوفر الدفع على هذا الجهاز، ستظهر الخطط هنا ويمكنك مراجعتها وإدارتها من هذه الشاشة.",
        noteCaption: "ملاحظة من AKS",
        noteBody: "تتم معالجة الدفع عبر متجر جهازك.",
    },
    notifications: {
        header: "الإشعارات",
        eyebrow: "عند الحاجة فقط",
        title: "في الأوقات المهمة فقط.",
        description: "اختر الوقت المناسب ليتواصل معك Aks. يمكنك تغيير هذه الإعدادات في أي وقت.",
        sectionMain: "الإشعارات",
        allowTitle: "السماح بالإشعارات",
        allowDescription: "إيقاف كل إشعارات Aks مؤقتاً أو استئنافها.",
        categoriesSection: "ما يمكن أن يرسله AKS",
        categories: {
            insightsTitle: "رؤى جديدة",
            insightsDescription: "عندما يلاحظ Aks نمطاً ذا معنى.",
            experimentsTitle: "تحديثات التجارب",
            experimentsDescription: "تنبيهات ونتائج التجارب الجارية.",
            checkInsTitle: "تنبيهات التحقّق",
            checkInsDescription: "دعوة لطيفة للتأمل في يومك.",
            weeklyTitle: "تأمّل أسبوعي",
            weeklyDescription: "ملخّص لما تغيّر خلال الأسبوع.",
        },
        quietSection: "ساعات الهدوء",
        quietTitle: "ساعات الهدوء",
        quietDescription: "لا نرسل إشعارات بين 22:00 و8:00.",
        deviceSection: "إعدادات الجهاز",
        deviceTitle: "إدارة إشعارات الجهاز",
        deviceDescription: "افتح إعدادات جهازك لإدارة أذونات Aks.",
        noteCaption: "ملاحظة من AKS",
        noteBody: "يتواصل Aks معك في الأوقات المهمة فقط.",
    },
    yourData: {
        header: "بياناتك",
        eyebrow: "بياناتك",
        title: "ما يتذكره Aks.",
        description: "اطّلع على ما جمعه Aks من نشاطك، وعلى ما اخترت مشاركته.",
        glanceSection: "نظرة سريعة",
        remembersSection: "ما يتذكره AKS",
        sourcesSection: "مصادر البيانات",
        sourcesTitle: "المصادر المتصلة",
        sourcesUnknown: "يمكنك معرفة أي المصادر متصلة.",
        sourcesNone: "لا توجد مصادر متصلة. ستكون متاحة عند دعمها.",
        sourcesCount: (count: number) => `${count} متصلة · يمكنك إدارتها أو فصلها في أي وقت.`,
        choiceSection: "خيارك",
        choiceTitle: "أنت تقرر ما يبقى.",
        choiceBody: "يمكنك مراجعة معلوماتك وتصديرها وحذفها في أي وقت.",
        exportAction: "تصدير بياناتك",
        deleteAction: "حذف البيانات",
        noteCaption: "ملاحظة من AKS",
        noteBody: "بياناتك واضحة وتحت سيطرتك.",
        loadingData: "جارٍ تحميل ملخّص البيانات",
        retry: "إعادة المحاولة",
    },
    reflections: {
        header: "التأملات",
        eyebrow: "تأملاتك",
        title: "ما شاركته.",
        description: "راجع التأملات التي منحت Aks سياقاً عن تجربتك.",
        itemTitle: "تأمل",
        emptyTitle: "لا توجد تأملات بعد.",
        emptyBody: "حين تبدأ المشاركة مع Aks، ستظهر تأملاتك هنا.",
    },
    checkIns: {
        header: "التحقّقات",
        eyebrow: "تحقّقاتك",
        title: "لحظات صغيرة تتذكرها.",
        description: "راجع التحقّقات التي استخدمتها لتسجيل شعورك في وقتها.",
        itemFallback: "تحقّق",
        itemTitle: (mood: string) => `تحقّق بمزاج ${mood}`,
        energy: (value: number) => `الطاقة ${value}`,
        focus: (value: number) => `التركيز ${value}`,
        stress: (value: number) => `التوتر ${value}`,
        noDetails: "لا تفاصيل إضافية",
        emptyTitle: "لا توجد تحقّقات بعد.",
        emptyBody: "حين تبدأ التسجيل، ستظهر تحقّقاتك هنا.",
    },
    conversations: {
        header: "المحادثات",
        eyebrow: "محادثاتك",
        title: "حديثك مع Aks.",
        description:
            "راجع ما شاركته كما كان، دون أن يمتزج بتفسيرات لاحقة. يشمل البحث العناوين وما دار في المحادثة.",
        searchA11y: "البحث في المحادثات",
        searchPlaceholder: "البحث في المحادثات",
        clearSearch: "مسح",
        loadingA11y: "جارٍ تحميل المحادثات",
        loadErrorTitle: "تعذّر تحميل محادثاتك.",
        emptyQueryTitle: "لا توجد محادثات مطابقة.",
        emptyQueryBody: "جرّب كلمة أخرى — يبحث Aks في ما قلته، وليس في العناوين فقط.",
        emptyTitle: "لا توجد محادثات بعد.",
        emptyBody: "ستظهر هنا المحادثات التي تبدأها مع Aks.",
        archiveHint: "اضغط مطولاً للأرشفة",
        loadMore: "تحميل المزيد",
        archiveTitle: "أرشفة هذه المحادثة؟",
        archiveMessage: "ستُخفى من قائمة المحادثات الجارية.",
        archiveConfirm: "أرشفة",
        notices: {
            unableToArchive: "تعذّرت الأرشفة",
        },
    },
    conversationDetail: {
        fallbackTitle: "محادثة",
        renameA11y: "إعادة تسمية المحادثة",
        loadingA11y: "جارٍ تحميل المحادثة",
        unavailableTitle: "المحادثة غير متاحة.",
        archivedBody: "قد تكون مؤرشفة أو محذوفة.",
        renameSection: "إعادة تسمية المحادثة",
        titleA11y: "عنوان المحادثة",
        titlePlaceholder: "عنوان المحادثة",
        saveRename: "حفظ",
        cancelRename: "إلغاء",
        cancelRenameA11y: "إلغاء إعادة التسمية",
        historySection: "سجل المحادثة",
        startedAt: (date: string) => `بدأت في ${date}`,
        continueMirror: "المتابعة في Mirror",
        loadEarlier: "تحميل الرسائل السابقة",
        youLabel: "أنت",
        aksLabel: "Aks",
        systemLabel: "النظام",
        emptyTitle: "لا توجد رسائل بعد.",
    },
    memories: {
        header: "ما يتذكره Aks",
        eyebrow: "ما يتذكره AKS",
        title: "سياق مفيد، وتقدير حذر.",
        description: "ما استخلصه Aks من المعلومات المدعومة التي شاركتها مراراً.",
        observationsCount: (count: number) => `${count} ملاحظات`,
        lastNoticed: (date: string) => `آخر ملاحظة ${date}`,
        emptyTitle: "ما زال Aks يتعرّف على أنماطك.",
        emptyBody: "حين تتجمع أدلة كافية للتذكّر، سيظهر هنا السياق المفيد الذي يتكرر.",
    },
    memoryDetail: {
        header: "ذكرى",
        loadingA11y: "جارٍ تحميل الذكرى",
        unavailableTitle: "الذكرى غير متاحة.",
        archivedFallback: "قد تكون مؤرشفة أو محذوفة.",
        eyebrow: "ما يتذكره AKS",
        reasonTitle: "لماذا يتذكر Aks هذا",
        reasonFallback: (count: number) => `يظهر في ${count} مما شاركته.`,
        lastNoticed: (date: string) => `آخر ملاحظة ${date}`,
        evidenceSection: "الأدلة",
        viewConversation: " · عرض المحادثة",
        archiveAction: "أرشفة الذكرى",
        removeAction: "حذف الذكرى",
        archiveTitle: "أرشفة هذه الذكرى؟",
        archiveMessage:
            "سيتوقف Aks عن استخدام هذه الذكرى. قد تعود مشاركاتك اللاحقة إلى دعمها. تبقى المحادثات والتأملات والتحقّقات الأصلية كما هي.",
        archiveConfirm: "أرشفة",
        removeTitle: "حذف هذه الذكرى؟",
        removeMessage:
            "يحذف هذا الذكرى التي يحتفظ بها Aks فقط. لا تُحذف المعلومات الأصلية التي شاركتها.",
        removeConfirm: "حذف",
        notices: {
            unableToArchive: "تعذّرت الأرشفة",
            unableToRemove: "تعذّر الحذف",
        },
    },
    patterns: {
        header: "الأنماط",
        eyebrow: "أنماطك",
        title: "روابط تستحق الملاحظة.",
        description: "علاقات محتملة مبنية على إشارات متكررة في ما شاركته.",
        observationsCount: (count: number) => `${count} ملاحظات`,
        emptyTitle: "لا توجد أنماط بعد.",
        emptyBody: "إيجاد روابط مفيدة يحتاج مزيداً من الوقت والأدلة.",
        status: {
            possible: "نمط محتمل",
            notSupported: "غير مدعوم",
            supported: "مدعوم",
            testing: "قيد الاختبار",
            fallback: "مرشّح",
        },
    },
    patternDetail: {
        header: "نمط",
        loadingA11y: "جارٍ تحميل النمط",
        unavailableTitle: "النمط غير متاح.",
        archivedFallback: "قد يكون مؤرشفاً أو محذوفاً.",
        reasonTitle: "لماذا لاحظ Aks هذا",
        evidenceLine: (supporting: number, contradicting: number) =>
            `يرتبط هذا النمط بـ ${supporting} ملاحظات داعمة` +
            (contradicting ? ` و${contradicting} ملاحظات مخالفة` : "") +
            ".",
        confidencePending: "جارٍ تقييم الثقة",
        confidenceValue: (percent: number) => `ثقة الأدلة ${percent}%`,
        firstNoticed: (date: string) => `أول ملاحظة ${date}`,
        lastObserved: (date: string) => `آخر ملاحظة ${date}`,
        alternativeTitle: "تفسير آخر",
        evidenceSection: "الأدلة",
        supporting: "داعمة",
        contradicting: "مخالفة",
        viewConversation: " · عرض المحادثة",
        notReadyA11y: "لا يمكن اختبار هذا النمط بعد",
        testA11y: "اختبار هذا النمط",
        notReady: "غير جاهز للاختبار",
        testAction: "اختبار هذا النمط",
        archiveAction: "أرشفة النمط",
        removeAction: "حذف النمط",
        statusLabels: {
            candidate: "مرشّح",
            possible: "نمط محتمل",
            testing: "قيد الاختبار",
            supported: "مدعوم",
            notSupported: "غير مدعوم",
            archived: "مؤرشف",
        },
        archiveTitle: "أرشفة هذا النمط؟",
        archiveMessage:
            "سيتوقف Aks عن عرض هذا النمط. قد تؤدي ملاحظاتك المستقبلية إلى إعادة تقييمه.",
        archiveConfirm: "أرشفة",
        removeTitle: "حذف هذا النمط؟",
        removeMessage:
            "يحذف هذا النمط المستخلص وروابط أدلته فقط. تبقى الإشارات والمعلومات الأصلية كما هي.",
        removeConfirm: "حذف",
        notices: {
            unableToArchive: "تعذّرت الأرشفة",
            unableToRemove: "تعذّر الحذف",
        },
    },
    experiments: {
        header: "التجارب",
        eyebrow: "تجاربك",
        title: "اختبارات صغيرة، وأدلة مفيدة.",
        description: "التجارب طريقة لاختبار نمط محتمل بدلاً من اعتباره حقيقة.",
        observationsCount: (count: number) => `${count} ملاحظات`,
        emptyTitle: "لا توجد تجارب بعد.",
        emptyBody: "عندما يكون هناك نمط يستحق الاختبار، يمكنك تجربته في تجربة صغيرة.",
        status: {
            active: "نشطة",
            completed: "مكتملة",
            cancelled: "ملغاة",
            fallback: "مسودة",
        },
    },
    experimentSetup: {
        header: "إعداد تجربة",
        patternSection: "النمط الذي تختبره",
        titleLabel: "العنوان",
        titlePlaceholder: "عنوان قصير للتجربة",
        hypothesisLabel: "الفرضية",
        hypothesisPlaceholder: "تغيير صغير قد يؤثر في…",
        hypothesisDefault: "قد يؤثر تغيير صغير في ما يُلاحظ في هذا النمط.",
        descriptionLabel: "ما ستجرّبه وما ستلاحظه",
        descriptionPlaceholder: "اكتب تغييراً صغيراً واحداً وما ستسجّله.",
        descriptionDefault:
            "اختر تغييراً صغيراً ويمكن التراجع عنه. سجّل في كل مرة إن كان الأمر أسهل أم مماثلاً أم أصعب.",
        durationLabel: "المدة",
        durationA11y: (days: number) => `${days} أيام`,
        durationDays: (days: number) => `${days} أيام`,
        defaultTitle: (patternTitle: string) => `اختبار: ${patternTitle}`.slice(0, 120),
        createAction: "إنشاء مسودة",
        createA11y: "إنشاء مسودة التجربة",
        createError: "تعذّر إنشاء هذه التجربة. راجع التفاصيل وحاول مرة أخرى.",
        patternUnavailable: "هذا النمط غير متاح.",
    },
    experimentDetail: {
        header: "تجربة",
        unavailableTitle: "التجربة غير متاحة.",
        hypothesisTitle: "الفرضية",
        whatToTryTitle: "ما ستجرّبه",
        startAction: "بدء التجربة",
        startA11y: "بدء التجربة",
        removeAction: "حذف التجربة",
        removeA11y: "حذف التجربة",
        removeTitle: "حذف هذه التجربة؟",
        removeMessage:
            "يحذف التجربة والملاحظات والدروس التي استندت إلى هذه التجربة فقط. يبقى النمط الأصلي وإشاراته.",
        removeConfirm: "حذف",
        recordedFallback: "مسجّل",
        observationsSection: "الملاحظات",
        emptyObservations: "لم تُسجّل ملاحظات بعد.",
        resultSection: "النتيجة",
        analysisPending: "في انتظار التحليل",
        confidenceValue: (percent: number) => `ثقة الأدلة ${percent}%`,
        promptTitle: "كيف بدا الأمر هذه المرة؟",
        resultEasier: "أسهل",
        resultSame: "مماثل",
        resultHarder: "أصعب",
        recordA11y: (result: string) => `التسجيل كـ ${result}`,
        observationPlaceholder: "ملاحظة اختيارية",
        observationA11y: "ملاحظة اختيارية",
        observationsMeta: (count: number) => `${count} ملاحظات مسجّلة`,
        observationsDay: (current: number, total: number | null) =>
            total ? ` · اليوم ${current} من ${total}` : "",
        observationsThrough: (date: string) => ` · حتى ${date}`,
        completeAction: "إكمال التجربة",
        completeA11y: "إكمال التجربة",
        cancelAction: "إلغاء التجربة",
        cancelA11y: "إلغاء التجربة",
        resultPendingBody: "تُحفظ ملاحظاتك بينما نرتّب النتيجة.",
        retryAnalysis: "إعادة محاولة التفسير",
        retryAnalysisA11y: "إعادة محاولة تحليل التجربة",
        retryLearning: "إعادة محاولة صياغة الدرس",
        retryLearningA11y: "إعادة محاولة صياغة الدرس",
        retryInsight: "إعادة محاولة إنشاء الرؤية",
        retryInsightA11y: "إعادة محاولة إنشاء الرؤية",
        resultLabels: {
            easier: "أسهل",
            same: "مماثل",
            harder: "أصعب",
        },
        outcomeLabels: {
            supports: "يدعم الفرضية",
            mixed: "نتائج مختلطة",
            doesNotSupport: "لا يدعم الفرضية",
            insufficientData: "بيانات غير كافية",
        },
        confirmCompleteTitle: "إكمال هذه التجربة؟",
        confirmCompleteMessage: "سيلخّص Aks ما يمكن قوله بناءً على ملاحظاتك.",
        confirmCompleteLabel: "إكمال",
        confirmCancelTitle: "إلغاء هذه التجربة؟",
        confirmCancelMessage: "تبقى الملاحظات التي سجّلتها كما هي.",
        confirmCancelLabel: "إلغاء التجربة",
        keepGoing: "المتابعة",
        notices: {
            unableToUpdate: "تعذّر التحديث",
            unableToRecord: "تعذّر التسجيل",
            recordRetry: "آخر تسجيل محفوظ ويمكن إعادة المحاولة بأمان.",
        },
    },
    learnings: {
        header: "الدروس",
        eyebrow: "دروسك",
        title: "ما تشير إليه الأدلة.",
        description: "استنتاجات حذرة من التجارب المكتملة والملاحظات المسجّلة.",
        statusRevised: "منقّح",
        statusActive: "سارٍ",
        observationsCount: (count: number) => `${count} ملاحظات`,
        emptyTitle: "لا توجد دروس بعد.",
        emptyBody: "عندما تجرّب شيئاً وتتجمع أدلة كافية، يساعدك Aks في ترتيب ما تغيّر.",
    },
    learningDetail: {
        header: "درس",
        unavailableTitle: "الدرس غير متاح.",
        evidenceTitle: "من أين جاء هذا؟",
        evidenceLine: (experiments: number, observations: number) =>
            `مبني على ${experiments} تجارب مكتملة و${observations} ملاحظات سجّلتها.`,
        confidenceValue: (percent: number) => `ثقة الأدلة ${percent}%`,
        updatedAt: (date: string) => `حُدّث في ${date}`,
        sourceSection: "التجربة المصدر",
        openExperimentA11y: (title: string) => `فتح تجربة ${title}`,
        observationsCount: (count: number) => `${count} ملاحظات`,
        archiveAction: "أرشفة الدرس",
        archiveA11y: "أرشفة الدرس",
        removeAction: "حذف الدرس",
        removeA11y: "حذف الدرس",
        resultLabels: {
            supports: "يدعم الفرضية",
            mixed: "نتائج مختلطة",
            doesNotSupport: "لا يدعم الفرضية",
            insufficientData: "بيانات غير كافية",
        },
        archiveTitle: "أرشفة هذا الدرس؟",
        archiveMessage: "تبقى التجربة والملاحظات المصدر متاحة.",
        archiveConfirm: "أرشفة",
        removeTitle: "حذف هذا الدرس؟",
        removeMessage:
            "يحذف الدرس المستخلص فقط. تبقى التجارب والملاحظات والأنماط والإشارات كما هي.",
        removeConfirm: "حذف",
        notices: {
            unableToArchive: "تعذّرت الأرشفة",
            unableToRemove: "تعذّر الحذف",
        },
    },
    insights: {
        header: "الرؤى",
        eyebrow: "الرؤى",
        title: "ما يستحق الملاحظة.",
        description: "عدد قليل من الملاحظات في وقتها، مبنية على ما جرّبته وتعلّمته.",
        statusNew: "جديدة",
        statusSeen: "مُطّلع عليها",
        emptyTitle: "لا توجد رؤى بعد.",
        emptyBody: "عندما يجد Aks أدلة كافية مع الوقت، سيبدأ ما يفيدك في الظهور.",
    },
    insightDetail: {
        header: "رؤية",
        eyebrow: "الرؤى",
        unavailableTitle: "الرؤية غير متاحة.",
        reasonTitle: "لماذا لاحظ Aks هذا",
        openExperimentA11y: (title: string) => `فتح تجربة ${title}`,
        openLearningA11y: (title: string) => `فتح درس ${title}`,
        observationsCount: (count: number) => `${count} ملاحظات مسجّلة · عرض التجربة`,
        viewLearning: "عرض الدرس المصدر",
        confidenceValue: (percent: number) => `ثقة الأدلة ${percent}%`,
        createdAt: (date: string) => `أُنشئت في ${date}`,
        dismissAction: "إغلاق الرؤية",
        dismissA11y: "إغلاق الرؤية",
        removeAction: "حذف الرؤية",
        removeA11y: "حذف الرؤية",
        dismissTitle: "إغلاق هذه الرؤية؟",
        dismissMessage: "تبقى الدروس والتجارب والأنماط والأدلة كما هي.",
        dismissConfirm: "إغلاق",
        removeTitle: "حذف هذه الرؤية؟",
        removeMessage: "يحذف هذه الرؤية فقط. تبقى كل المعلومات الأصلية كما هي.",
        removeConfirm: "حذف",
        notices: {
            unableToDismiss: "تعذّر الإغلاق",
            unableToRemove: "تعذّر الحذف",
        },
    },
    privacyHome: {
        header: "الخصوصية",
        eyebrow: "خصوصيتك",
        title: "حياتك ملكك.",
        description:
            "يساعدك Aks على فهم نفسك مع إبقاء المعلومات التي تدعم هذه التجربة تحت يدك.",
        dataSection: "بياناتك",
        knowsTitle: "ما يعرفه Aks",
        knowsDescription: "افهم المعلومات المستخدمة في بناء تجربتك.",
        accessTitle: "ما يمكن لـ Aks الوصول إليه",
        accessDescription: "راجع ما قدّمته أو ربطته.",
        controlsSection: "إدارة بياناتك",
        usageTitle: "كيف تُستخدم بياناتك",
        usageDescription: "اطّلع على كيفية دعم معلوماتك للرؤى والتجارب.",
        exportTitle: "تصدير بياناتك",
        exportDescription: "اطلب نسخة من معلوماتك في Aks.",
        deleteTitle: "حذف بياناتك",
        deleteDescription: "ابدأ إجراءً متأنياً لحذف بيانات الحساب.",
        legalSection: "معلومات قانونية",
        privacyPolicyTitle: "سياسة الخصوصية",
        privacyPolicyDescription: "اقرأ سياسة الخصوصية الكاملة لـ Aks.",
    },
    dataAccess: {
        header: "ما يمكن لـ Aks الوصول إليه",
        title: "واضح منذ التصميم.",
        description:
            "يتعامل Aks فقط مع المعلومات التي قدّمتها، ومصادر البيانات التي اخترت ربطها بوضوح.",
        sourcesSection: "المصادر المتصلة",
        loadingSources: "جارٍ تحميل المصادر المتصلة…",
        loadError: "تعذّر تحميل المصادر المتصلة الآن.",
        emptyTitle: "لا توجد مصادر متصلة بعد",
        emptyBody:
            "لا يقرأ Aks أي خدمة خارجية إلا بعد أن تربطها بوضوح. يمكنك إدارة الروابط في أي وقت من إعدادات حسابك.",
        connectedNeedsPermission: "متصل · يحتاج إذناً",
        connectedSynced: (relative: string) => `متصل ويقرأ بياناتك · آخر مزامنة ${relative}`,
        connectedNotSynced: "متصل ويقرأ بياناتك · لم تتم المزامنة بعد",
        holdsSection: "ما يحتفظ به AKS",
        items: [
            {
                title: "المعلومات التي قدّمتها",
                body: "مثل تفاصيل ملفك الشخصي وإعداداتك، وما أدخلته مباشرة في Aks.",
            },
            {
                title: "التأملات والتحقّقات",
                body: "السجلات التي أنشأتها للتعبير عن تجربتك ومزاجك وتركيزك وطاقتك وإيقاع يومك.",
            },
            {
                title: "بيانات التجارب",
                body: "التجارب التي أنشأتها والنتائج والملاحظات التي سجّلتها.",
            },
            {
                title: "معلومات الحساب",
                body: "الأساسيات اللازمة لتحديد حسابك في Aks وإدارته.",
            },
            {
                title: "مصادر البيانات المتصلة",
                body: "معلومات من الخدمات التي اخترت ربطها بوضوح فقط، وحين يكون ذلك الربط متاحاً.",
            },
        ],
        controlTitle: "أنت المتحكم",
        controlBody: "لا يستخدم Aks إلا ما أدخلته أو ربطته بوضوح.",
    },
    dataUsage: {
        header: "كيف تُستخدم بياناتك",
        title: "للبيانات هدف.",
        description: "يستخدم Aks معلوماتك داخل المنتج لجعل تجربتك أكثر صلة ووضوحاً.",
        sections: [
            {
                title: "لماذا يستخدم Aks بياناتك",
                body: "تساعد المعلومات التي اخترت مشاركتها Aks على تخصيص تأملاتك، وإيجاد موضوعات مفيدة، ودعم أهدافك.",
            },
            {
                title: "التأملات والتحقّقات",
                body: "تمنح سجلاتك سياقاً لتغيّرات مزاجك وطاقتك وتركيزك وإيقاع يومك.",
            },
            {
                title: "اكتشاف الأنماط",
                body: "قد يقارن Aks المعلومات التي تقدّمها ليقدّم أنماطاً محتملة قابلة للاختبار. هذه دعوات للتأمل، لا استنتاجات طبية.",
            },
            {
                title: "الذكريات",
                body: "قد يحتفظ Aks بقدر قليل من السياق المفيد الذي يتكرر. ترتبط الذكريات دائماً بالمعلومات التي تدعمها، ويمكن إزالتها دون حذف المعلومات الأصلية.",
            },
            {
                title: "التجارب والنتائج",
                body: "تمنحك سجلات التجارب طريقة لمقارنة ما جرّبته مع النتائج التي لاحظتها.",
            },
            {
                title: "دعم الفهم بالذكاء الاصطناعي",
                body: "قد يساعد الذكاء الاصطناعي في تنظيم أو تلخيص المعلومات التي قدمتها. تحقّق دائماً من الرؤى المهمة بنفسك واستقبلها بحكمك الخاص.",
            },
        ],
        privacyPolicyAction: "اقرأ سياسة الخصوصية الكاملة",
    },
    exportData: {
        header: "تصدير بياناتك",
        preparingTitle: "جارٍ تجهيز تصديرك",
        preparingBody:
            "نجمع محادثاتك وتأملاتك وذكرياتك وأنماطك وتجاربك ورؤاك. يستغرق هذا عادة ثوانٍ.",
        errorTitle: "خذ بياناتك معك.",
        errorBody: "بناءً على طلبك، نجهّز معلوماتك في Aks بصيغة قابلة للتنزيل.",
        failedTitle: "تعذّر إنشاء التصدير.",
        failedFallback: "حدثت مشكلة أثناء تجهيز تصديرك. حاول مرة أخرى.",
        retryA11y: "إعادة محاولة إنشاء التصدير",
        cancelAction: "إلغاء",
        cancelA11y: "العودة إلى شرح التصدير",
        readyTitle: "تصديرك جاهز.",
        readyBody: "أنشأنا للتو نسخة من معلوماتك في Aks. إنها الأقسام نفسها المعروضة عند الطلب.",
        expiresIn: (countdown: string) => `ينتهي الرابط خلال ${countdown}`,
        expiresSoon: "قريباً",
        saveAction: "حفظ التصدير",
        saveA11y: "حفظ التصدير",
        requestAnother: "طلب تصدير آخر",
        requestAnotherA11y: "طلب تصدير آخر",
        idleTitle: "خذ بياناتك معك.",
        idleBody:
            "بناءً على طلبك، نجهّز معلوماتك في Aks بصيغة قابلة للتنزيل. كل تصدير ملف واحد يعكس حالة حسابك لحظة الطلب.",
        includedSection: "ما يتضمنه",
        included: [
            "الملف الشخصي والإعدادات",
            "المحادثات والرسائل",
            "التأملات",
            "التحقّقات",
            "الإشارات",
            "الذكريات وأدلتها",
            "الأنماط وأدلتها",
            "التجارب والملاحظات",
            "الدروس ومراجعها",
            "الرؤى ومراجعها",
        ],
        requestAction: "طلب تصدير البيانات",
        requestA11y: "طلب تصدير",
    },
    deleteData: {
        header: "حذف البيانات",
        title: "من دون أن يبقى شيء.",
        description:
            "حذف حسابك يزيل نهائياً البيانات التي أنشأتها في Aks ويسجّل خروجك من هذا الجهاز.",
        warningTitle: "لا يمكن التراجع عن هذا.",
        warningBody:
            "حذف حسابك يعني أن بياناتك في Aks ستزول ولا يمكن استعادتها. إن كنت تريد نسخة، فكّر في تصدير بياناتك أولاً.",
        removedSection: "ما سيُحذف",
        removed: [
            "المحادثات والرسائل",
            "التأملات",
            "التحقّقات",
            "الإشارات المستخلصة",
            "الذكريات وأدلتها",
            "الأنماط وأدلتها",
            "التجارب والملاحظات",
            "الدروس ومراجعها",
            "الرؤى ومراجعها",
        ],
        confirmA11y: "أؤكد أن هذا الإجراء لا يمكن التراجع عنه",
        confirmLabel: "أفهم أن هذا الإجراء لا يمكن التراجع عنه وأن كل بياناتي في Aks ستُحذف.",
        deleteAction: "حذف الحساب والبيانات",
        deleteActionA11y: "حذف الحساب والبيانات",
        deletingAction: "جارٍ حذف حسابك…",
        deletedTitle: "جارٍ حذف حسابك.",
        deletedBody: "ستُسجَّل خروجك بمجرد اكتمال الحذف.",
        backToSettings: "العودة إلى الإعدادات",
        backToSettingsA11y: "العودة إلى الإعدادات",
        keepAccount: "الاحتفاظ بحسابي",
        keepAccountA11y: "الاحتفاظ بحسابي",
        keepNote: "حذف حسابك يحذف أيضاً ملفات التصدير التي أُنشئت لهذا الحساب.",
    },
    helpHome: {
        header: "المساعدة والملاحظات",
        title: "نحب أن نسمع منك.",
        description: "هل هناك شيء لا يعمل، أو غير واضح، أو تتمنى أن يفعله Aks؟",
        supportTitle: "تحتاج مساعدة؟",
        supportBody: "فريق الدعم جاهز لمساعدتك.",
        supportAction: "تواصل مع الدعم",
        getHelpSection: "الحصول على مساعدة",
        faqTitle: "الأسئلة الشائعة",
        faqDescription: "احصل على إجابات سريعة لأسئلة شائعة",
        reportTitle: "الإبلاغ عن مشكلة",
        reportDescription: "أخبرنا عندما لا يسير شيء كما ينبغي",
        improveSection: "لنجعل AKS أفضل",
        suggestTitle: "اقترح فكرة",
        suggestDescription: "أخبرنا بما تريد أن يتعلمه Aks أو يفعله",
        shareTitle: "شارك تجربتك",
        shareDescription: "أخبرنا بما أعجبك وما يمكن تحسينه",
        contactSection: "التواصل",
        supportEmail: "support@aks.ai",
        supportResponse: "نرد عادة خلال 1–2 يوم عمل",
        footerVersion: "1.0.0",
    },
    faq: {
        header: "المساعدة والملاحظات",
        title: "الأسئلة الشائعة",
        description: "احصل على إجابات سريعة عن طريقة عمل Aks وتعاملنا مع بياناتك.",
        searchPlaceholder: "ابحث في الأسئلة",
        clearSearch: "مسح",
        resultsCount: (count: number) => `${count} نتائج`,
        popularSection: "أسئلة يسألها الناس",
        questionsCount: (count: number) => `${count} أسئلة`,
        items: [
            {
                question: "كيف يجد Aks الأنماط؟",
                answer: "يبحث Aks عن روابط مفيدة في المعلومات والتأملات التي اخترت مشاركتها.",
            },
            {
                question: "هل يمكنني اختيار البيانات التي يستخدمها Aks؟",
                answer: "نعم. من «بياناتك» و«الخصوصية» يمكنك مراجعة معلوماتك وإدارة الأذونات المتاحة.",
            },
            {
                question: "كيف تعمل التجارب؟",
                answer: "تساعدك التجارب على تجربة تغيير صغير والتأمل في أثره على تركيزك وطاقتك ونومك وإيقاع يومك.",
            },
            {
                question: "هل يمكنني تغيير إعدادات الإشعارات؟",
                answer: "نعم. من صفحة «أنت» افتح «الإشعارات» واختر الأوقات المناسبة ليتواصل معك Aks.",
            },
            {
                question: "هل Aks استشارة طبية؟",
                answer: "لا. Aks أداة لدعم التأمل الشخصي، وليس بديلاً عن الاستشارة الطبية أو النفسية المتخصصة.",
            },
        ],
        emptyTitle: "لا توجد نتائج مطابقة",
        emptyBody: "جرّب كلمة بحث أخرى، أو تصفّح الأسئلة أعلاه.",
        clearAction: "مسح البحث",
        helpTitle: "ما زلت بحاجة إلى مساعدة؟",
        helpBody: "أخبرنا بما يحدث وسنساعدك على ترتيب الأمور.",
        contactAction: "تواصل معنا",
    },
    sendFeedback: {
        header: "إرسال ملاحظات",
        title: "لنبنِ Aks معاً.",
        description: "شاركنا أفكارك، أو طلبات الميزات، أو ما تشعر أنه يعمل جيداً بالفعل.",
        optionLabel: "نوع الملاحظة",
        optionHint: "اختر واحداً",
        options: ["فكرة", "طلب ميزة", "ملاحظة عامة", "ما أعجبني"],
        initialOption: "ملاحظة عامة",
        messageLabel: "ملاحظاتك",
        messagePlaceholder: "ما الذي سيجعل Aks أكثر فائدة؟",
        messageHint: "نرحّب بأي فكرة أو اقتراح أو إشادة.",
        emailHint: "أضف بريدك الإلكتروني فقط إذا كنت تريد رداً.",
        noteTitle: "رأيك مهم.",
        noteBody: "ما تشاركه يساعد في تحديد الخطوة التالية لـ Aks.",
        submit: "إرسال الملاحظات",
        leaveMessage: "يمكنك مغادرة هذه الصفحة دون إرسال شيء.",
    },
    reportProblem: {
        header: "الإبلاغ عن مشكلة",
        title: "ماذا حدث؟",
        description: "أخبرنا بما حدث. كل سياق إضافي يساعدنا على الفهم والإصلاح.",
        optionLabel: "نوع المشكلة",
        optionHint: "اختر واحداً",
        options: [
            "ميزة لا تعمل",
            "التطبيق توقف",
            "الرؤى غير صحيحة",
            "مشكلة في البيانات",
            "مشكلة في الإشعارات",
            "شيء آخر",
        ],
        messageLabel: "ماذا حدث؟",
        messagePlaceholder: "صف ما توقعته وما حدث فعلاً…",
        messageHint: "أضف أي خطوات تؤدي إلى المشكلة إن أمكن.",
        emailHint: "أضف بريدك الإلكتروني فقط إذا أردت أن نتواصل معك.",
        noteTitle: "شكراً لمساعدتك في تحسين Aks.",
        noteBody: "ملاحظاتك تساعدنا على جعل Aks أكثر موثوقية للجميع.",
        submit: "إرسال التقرير",
        leaveMessage: "يمكنك مغادرة هذه الصفحة دون إرسال شيء.",
    },
    feedbackForm: {
        selectedState: "محدّد",
        contactEmail: "بريد للتواصل",
        optionalMark: "(اختياري)",
        emailPlaceholder: "you@example.com",
        charLimit: 1000,
    },
    profilePreference: {
        saveAction: "حفظ الإعداد",
        saveA11y: (title: string) => `حفظ ${title}`,
        noteCaption: "محفوظ في ملفك الشخصي",
        noteBody: "يُحفظ اختيارك في ملفك الشخصي.",
        notices: {
            unableToSave: "تعذّر حفظ الإعداد",
        },
    },
    dataCategory: {
        recentSection: "الأحدث",
        loadingA11y: (title: string) => `جارٍ تحميل ${title}`,
        loadErrorTitle: "تعذّر تحميل هذه البيانات.",
        tryAgain: "إعادة المحاولة",
        loadMore: "تحميل المزيد",
        noteCaption: "ملاحظة من AKS",
        noteBody: "ستظهر السجلات التي أنشأتها هنا.",
    },
    bottomSheet: {
        dismissA11y: "إغلاق",
        defaultConfirm: "حسناً",
        cancel: "إلغاء",
    },
    connectedSources: {
        header: "المصادر المتصلة",
        eyebrow: "السياق والأذونات",
        title: "أنت من يقرر ما يعرفه Aks.",
        description:
            "يمكنك استخدام Aks دون ربط أي مصدر. كل مصدر اختياري ومستقل، ويوضّح ما يشارك. يمكنك الفصل في أي وقت.",
        loadingA11y: "جارٍ تحميل المصادر",
        loadError: "تعذّر تحميل المصادر المتصلة.",
        status: {
            connected: "متصل",
            permissionRequired: "يحتاج إذناً",
            notConnected: "غير متصل",
            notAvailable: "غير متاح على هذا الجهاز",
            revoked: "مفصول",
            temporarilyUnavailable: "غير متاح مؤقتاً",
            error: "غير متاح الآن",
        },
        syncedAgo: (relative: string) => `آخر مزامنة ${relative}`,
        notSynced: "لم تتم المزامنة بعد",
        whyHelps: "لماذا يفيد هذا",
        whatReceives: "ما يستقبله AKS",
        whatStored: "ما يُخزَّن",
        howToStop: "كيف توقفه",
        goodToKnow: "من الجيد أن تعرف",
        disconnect: "فصل الاتصال",
        deleteData: "حذف البيانات المستوردة",
        allow: "السماح",
        connect: "ربط",
        reconnect: "إعادة الربط",
        choiceSection: "خيارك",
        choiceBody: "تُستخدم المصادر المتصلة فقط. يمكنك الإيقاف بلمسة واحدة في أي وقت.",
        confirmations: {
            cancelAction: "إلغاء",
        },
        notices: {
            providerNotConfigured: "مزوّد الخدمة هذا غير مهيّأ في هذا الإصدار بعد.",
            unableToConnect: "تعذّر الاتصال بهذا المصدر الآن.",
        },
        groups: {
            productivity: "الإنتاجية",
            work: "العمل",
            device: "الجهاز / السلوك",
        },
    },
    sources: {
        location: {
            name: "الموقع",
            purpose:
                "يساعد Aks على فهم أين يحدث يومك. يساعد ذلك في التمييز بين يوم صعب ويوم أربكته التنقلات أو التغييرات غير المتوقعة.",
            receives:
                "سياق مكاني تقريبي (قريب من المنزل، قريب من العمل، في تنقّل، في مكان غير معتاد) والوقت — دون تتبّع مستمر.",
            stored: "نطاقات زمنية للملاحظة مثل «تنقّل، نحو 45 دقيقة عند 18:30». لا نحفظ إحداثيات دقيقة.",
            stop: "يمكنك فصل الموقع في أي وقت. يتوقف الجمع فوراً، ويمكن حذف الملاحظات المخزّنة على حدة.",
            batteryNote: "نتحقق من موقعك من وقت لآخر أثناء الربط. قد يزيد ذلك استهلاك البطارية قليلاً.",
        },
        calendar: {
            name: "التقويم",
            purpose:
                "عند معرفة الأحداث المقررة، يسهل على Aks التمييز بين «تغيّرت الخطة» و«انخفض الدافع».",
            receives:
                "أوقات الأحداث وتصنيفات تقريبية. تُستخدم العناوين لتعريف الحدث فقط؛ لا نقرأ قوائم المشاركين أو الملاحظات أو روابط الاجتماعات.",
            stored: "سجلات أحداث الحد الأدنى: الوقت والمدة والتصنيف ومؤكد/ملغي.",
            stop: "يمكنك فصل التقويم في أي وقت. يتوقف الجمع فوراً.",
        },
        reminders: {
            name: "المهام والتذكيرات",
            purpose:
                "الإجراءات التي كنت تنوي القيام بها وما حدث فعلاً — دون أن يفترض Aks أنك «لم تفعلها».",
            receives: "مواعيد وأحوال إنجاز التذكيرات التي اخترت مزامنتها.",
            stored: "المواعيد وحالة الإنجاز/عدم التسجيل.",
            stop: "يمكنك فصل المهام والتذكيرات في أي وقت.",
        },
        screenTime: {
            name: "وقت الشاشة",
            purpose:
                "قد يفسّر سياق استخدام الجهاز المجمّع تغيّرات التركيز لديك — دون التعامل معه كدليل على التشتت.",
            receives: "مدة استخدام مجمّعة بتصنيفات تقريبية خلال فترات زمنية.",
            stored: "نطاقات مجمّعة مثل «تطبيقات التواصل، 60 دقيقة، 21:00–22:00». لا بيانات على مستوى التفاعل الفردي.",
            stop: "يمكنك فصل وقت الشاشة في أي وقت.",
        },
        googleCalendar: {
            name: "تقويم Google",
            purpose:
                "يمنحك تقويم Google سياق التخطيط نفسه الذي يوفره تقويم جهازك للحسابات التي تربطها بوضوح.",
            receives:
                "أوقات وتصنيفات تقريبية لأحداث التقويمات المختارة. لا نقرأ قوائم المشاركين أو الملاحظات أو روابط الاجتماعات.",
            stored: "سجلات أحداث الحد الأدنى: الوقت والمدة والتصنيف ومؤكد/ملغي.",
            stop: "يمكنك فصل تقويم Google في أي وقت — وألغِ الوصول أيضاً من إعدادات حساب Google.",
        },
        appleCalendar: {
            name: "تقويم Apple",
            purpose:
                "على iPhone وiPad، نحصل على سياق تقويم الجهاز نفسه عبر مخزن تقويم Apple.",
            receives: "أوقات الأحداث وتصنيفات تقريبية. لا نقرأ قوائم المشاركين أو الملاحظات أو روابط الاجتماعات.",
            stored: "سجلات أحداث الحد الأدنى: الوقت والمدة والتصنيف ومؤكد/ملغي.",
            stop: "يمكنك فصل تقويم Apple في أي وقت.",
        },
        googleTasks: {
            name: "مهام Google",
            purpose:
                "المهام المقررة في حساب Google المرتبط تتيح لـ Aks رؤية نواياك — دون اعتبارها فشلاً.",
            receives: "مواعيد المهام وحالة إنجازها.",
            stored: "المواعيد وحالة الإنجاز/عدم التسجيل.",
            stop: "يمكنك فصل مهام Google في أي وقت — وألغِ الوصول أيضاً من إعدادات حساب Google.",
        },
        appleReminders: {
            name: "تذكيرات Apple",
            purpose:
                "على iPhone وiPad، تصبح الإجراءات المقررة في تذكيرات Apple سياق «المخطط مقابل الفعلي» نفسه.",
            receives: "مواعيد التذكيرات وحالة إنجازها.",
            stored: "المواعيد وحالة الإنجاز/عدم التسجيل.",
            stop: "يمكنك فصل تذكيرات Apple في أي وقت.",
        },
        notion: {
            name: "Notion",
            purpose:
                "الصفحات وقواعد البيانات التي تشاركها بوضوح مع تكامل Aks تُدخل سياق عملك في المحادثة.",
            receives:
                "عناوين وأوقات وتصنيفات تقريبية لما تشاركه مع تكامل Aks في Notion. لا نقرأ محتوى الصفحات.",
            stored: "سجلات عناصر الحد الأدنى: تصنيف العنوان والوقت والحالة.",
            stop: "يمكنك فصل Notion في أي وقت — وأزل تكامل Aks من مساحة عمل Notion أيضاً.",
        },
        todoist: {
            name: "Todoist",
            purpose:
                "خدمة مهام مرتبطة مثل Todoist تتيح لـ Aks أخذ الخطة خارج Aks نفسه في الحسبان.",
            receives: "مواعيد المهام وحالة إنجازها.",
            stored: "المواعيد وحالة الإنجاز/عدم التسجيل.",
            stop: "يمكنك فصل Todoist في أي وقت — وألغِ الوصول أيضاً من إعدادات حساب المزوّد.",
        },
        github: {
            name: "GitHub",
            purpose: "نشاطك في الالتزامات وطلبات السحب كسياق عمل موضوعي — دون بيانات الآخرين.",
            receives: "عدد وأوقات التزاماتك وطلبات السحب في المستودعات المختارة.",
            stored: "نطاقات نشاط مجمّعة مثل «التزامان، 22:00–23:00». لا محتوى للشيفرة.",
            stop: "يمكنك فصل GitHub في أي وقت — وألغِ تطبيق Aks على OAuth من إعدادات GitHub أيضاً.",
        },
        slack: {
            name: "Slack",
            purpose: "إشارات وقت التركيز والحالة من مساحة العمل التي تربطها بوضوح.",
            receives: "أوقات نشاطك وحالة عدم الإزعاج (DND). لا نقرأ محتوى الرسائل.",
            stored: "نطاقات نشاط مجمّعة. لا رسائل ولا قنوات ولا بيانات زملاء.",
            stop: "يمكنك فصل Slack في أي وقت — وأزل تطبيق Aks من مساحة العمل أيضاً.",
        },
        email: {
            name: "البريد الإلكتروني",
            purpose: "سياق خفيف لضغط البريد (عدد الرسائل فقط) من مزوّد تربطه مثل Gmail.",
            receives: "عدد الرسائل الواردة وأوقاتها. لا نقرأ العناوين أو النصوص أو المرسِلين.",
            stored: "أعداد مجمّعة لكل فترة زمنية. لا محتوى ولا عناوين بريد.",
            stop: "يمكنك فصل البريد في أي وقت — وألغِ الوصول أيضاً من إعدادات الأمان لدى المزوّد.",
        },
        voiceSession: {
            name: "الميكروفون",
            purpose:
                "المحادثات الصوتية إجراء تبدأه بنفسك بوضوح. يُستخدم الميكروفون أثناء الجلسات الصوتية فقط.",
            receives: "الصوت أثناء تشغيل محادثة صوتية فقط.",
            stored: "النصوص التي تحتفظ بها. لا يُخزَّن الصوت.",
            stop: "إنهاء الجلسة الصوتية يوقف الميكروفون. لا يستمع Aks في الخلفية أبداً.",
        },
    },
    transparency: {
        connectedWith: (sources: string) =>
            `بما أنك ربطت ${sources}، يمكن لـ Aks رؤية هذا السياق إلى جانب ما تشاركه هنا.`,
        names: {
            location: "الموقع",
            calendar: "التقويم",
            googleCalendar: "تقويم Google",
            appleCalendar: "تقويم Apple",
            reminders: "المهام",
            googleTasks: "مهام Google",
            appleReminders: "تذكيرات Apple",
            todoist: "Todoist",
            notion: "Notion",
            github: "GitHub",
            slack: "Slack",
            email: "البريد الإلكتروني",
            screenTime: "وقت الشاشة",
            voiceSession: "الصوت",
        },
    },
    oauth: {
        googleCalendar: "تقويم Google",
        googleTasks: "مهام Google",
        notion: "Notion",
        todoist: "Todoist",
        github: "GitHub",
        slack: "Slack",
        email: "البريد الإلكتروني",
    },
    errors: {
        pagedData: "تعذّر تحميل هذه البيانات. حاول مرة أخرى.",
        pagedDataMore: "تعذّر تحميل المزيد من البيانات. حاول مرة أخرى.",
        dataSummary: "تعذّر تحميل ملخّص بياناتك. حاول مرة أخرى.",
        dataAccess: "تعذّر تحميل المصادر المتصلة. حاول مرة أخرى.",
        memory: "تعذّر تحميل هذه الذكرى.",
        pattern: "تعذّر تحميل هذا النمط.",
        experiment: "تعذّر تحميل هذه التجربة.",
        learning: "تعذّر تحميل هذا الدرس.",
        insight: "تعذّر تحميل هذه الرؤية.",
        conversation: "تعذّر تحميل هذه المحادثة. حاول مرة أخرى.",
        conversationEarlier: "تعذّر تحميل الرسائل السابقة. حاول مرة أخرى.",
        conversationPlain: "تعذّر تحميل هذه المحادثة.",
        conversationEarlierPlain: "تعذّر تحميل الرسائل السابقة.",
        messageEmptySave: "اكتب شيئاً قبل الحفظ.",
        exportLinkExpired: "انتهت صلاحية رابط التصدير. اطلب تصديراً آخر.",
        renameConversation: "تعذّرت إعادة تسمية هذه المحادثة. حاول مرة أخرى.",
        exportExpired: "انتهت صلاحية رابط التصدير. اطلب تصديراً آخر.",
        exportCreate: "تعذّر إنشاء التصدير. حاول مرة أخرى.",
        exportDownload: "تعذّر تنزيل التصدير. حاول مرة أخرى.",
        deleteAccount: "حذف الحساب غير متاح حالياً. حاول مرة أخرى بعد قليل.",
        preferences: "تعذّر تحميل إعداداتك.",
        appSetup: "تعذّر إكمال إعداد حسابك. حاول مرة أخرى.",
        exportSaveTitle: "حفظ تصدير Aks",
        exportClearDevice: "نحذف بيانات حسابك، لكن تنظيف هذا الجهاز يحتاج محاولة أخرى.",
        shareUnavailable: "المشاركة غير متاحة على هذا الجهاز. حاول مرة أخرى.",
        exportIncomplete: "استجابة التصدير كانت ناقصة. حاول مرة أخرى.",
        exportInterrupted: "توقف التنزيل. حاول مرة أخرى.",
        exportGeneric: "حدث خطأ ما. حاول مرة أخرى.",
        connectedSources: "تعذّر تحميل المصادر المتصلة.",
        sourceUnavailable: "هذا المصدر غير متاح على جهازك.",
        sourcePermission: "يحتاج ربط هذا المصدر إلى إذن. حاول مرة أخرى لاحقاً.",
        sourceConnect: "تعذّر الاتصال بهذا المصدر.",
        sourceDisconnect: "تعذّر فصل هذا المصدر.",
        sourceDelete: "تعذّر حذف بيانات هذا المصدر.",
        oauthRecord: "تعذّر تسجيل هذا الربط.",
        oauthDisconnect: "تعذّر فصل هذا الحساب.",
        webPage: "تعذّر تحميل هذه الصفحة.",
        webPageBody: "تحقق من اتصالك بالإنترنت وحاول مرة أخرى.",
        generic: "حدث خطأ ما. حاول مرة أخرى.",
        signInUnavailable: "تسجيل الدخول غير متاح حالياً. حاول مرة أخرى بعد قليل.",
        signInStart: "تعذّر بدء تسجيل الدخول.",
        authRequest: "تعذّر إكمال هذا الطلب. حاول مرة أخرى.",
        storeUnreachable: "تعذّر الوصول إلى المتجر. تحقق من اتصالك وحاول مرة أخرى.",
        plansUnavailable: "لا توجد خطط متاحة الآن. حاول مرة أخرى بعد قليل.",
        planUnavailable: "هذه الخطة غير متاحة الآن. حاول مرة أخرى بعد قليل.",
        storeFailed: "لم يكمل المتجر طلبك. حاول مرة أخرى.",
        subscriptionGeneric: "حدثت مشكلة أثناء معالجة اشتراكك. حاول مرة أخرى.",
        purchaseCancelled: "أُلغي الشراء. لم يتم تحصيل أي مبلغ.",
        purchasePending: "الشراء في انتظار تأكيد المتجر. سيظهر هنا عند اكتماله.",
        alreadySubscribed: "هذه الخطة مفعّلة لديك بالفعل.",
        restoreEmpty: "لم نجد مشتريات سابقة لاستعادتها.",
        checkoutPendingPremium:
            "اكتملت عملية الدفع لكن Premium لم يُفعّل بعد في حسابك. الشراء من متجر Test Store في المحاكي لا يفعّل Premium — استخدم جهازاً فيه متجر Play. وإلا فانتظر قليلاً ثم جرّب «استعادة المشتريات».",
        emptyMessage: "اكتب شيئاً قبل الإرسال.",
        mirror: {
            noReply: "لم يردّ Aks على رسالتك الأخيرة بعد.",
            unsavedRetry: "قد لا يكتمل حفظ رسالتك الأخيرة. يمكنك إعادة المحاولة بأمان.",
            resolvePending: "أعد محاولة رسالتك السابقة أو أنهاها قبل إرسال رسالة جديدة.",
            refreshFailed: "لم يتمكن Aks من تحديث هذا الرد. ما كان قبله ما زال سليماً.",
            refreshFailedConversation:
                "حاول Aks عدة مرات ولم يتمكن من إكمال هذا الرد. رسالتك محفوظة.",
            refreshFailedUnsafe: "لم يتمكن Aks من تفسير هذا الرد بأمان. رسالتك محفوظة.",
            refreshFallback: "لم يتمكن Aks من معالجة ذلك الآن. رسالتك محفوظة.",
            updateMessage: "تعذّر تحديث هذه الرسالة. قد يكون لـ Aks رد عليها بالفعل.",
            checkInFailed: "تعذّر حفظ تحقّقك. حاول مرة أخرى.",
            saveFailed: "تعذّر حفظ رسالتك. تحقق من اتصالك وحاول مرة أخرى.",
            outboxQueued: "محفوظة على هذا الجهاز. سيرسلها Aks عند عودة الاتصال.",
            signInForVoice: "تتاح المحادثات الصوتية بعد تسجيل الدخول.",
            voiceStartFailed: "تعذّر بدء المحادثة الصوتية.",
        },
        voice: {
            realtimeNotConfigured: "المحادثات الصوتية غير مهيّأة في هذا الإصدار بعد.",
            sessionUnavailable: "تعذّر بدء الجلسة الصوتية. حاول مرة أخرى.",
            transportUnavailable: "هذا الخيار يحتاج إلى إصدار تطويري من Aks.",
            audioUnavailable: "الصوت المباشر يحتاج إلى إصدار تطويري يتضمن محرّك الصوت في Aks.",
            micDenied: "تحتاج المحادثات الصوتية إلى إذن الميكروفون.",
            transcriptionFailed: "لم يسمع Aks ما قلته. حاول مرة أخرى.",
            providerError: "لا يمكن لـ Aks بدء المحادثة الصوتية الآن.",
            sessionExpired: "انتهت الجلسة الصوتية. أعد الاتصال للمتابعة.",
            voiceFailed: "فشلت المحادثة الصوتية.",
            saveVoiceMessage: "تعذّر حفظ رسالتك الصوتية. ستبقى في هذه الجلسة فقط.",
            saveVoiceReply: "تعذّر حفظ رد Aks. سيبقى في هذه الجلسة فقط.",
            audioCaptureFailed: "فشل التقاط الصوت.",
            audioFailed: "حدثت مشكلة في الصوت.",
        },
        writes: {
            signInRequired: "سجّل الدخول للمتابعة.",
            experimentInvalid: "استجابة التجربة غير صالحة.",
            observation: "تعذّر حفظ هذه الملاحظة.",
            reflection: "تعذّر حفظ هذا التأمل.",
            message: "تعذّر حفظ هذه الرسالة.",
            checkIn: "تعذّر حفظ هذا التحقّق.",
            insightUpdate: "تعذّر تحديث هذه الرؤية.",
            experimentUpdate: "تعذّر تحديث هذه التجربة.",
            startConversation: "تعذّر بدء هذه المحادثة.",
            sendMessage: "تعذّر حفظ رسالتك.",
            confirmMessage: "تعذّر تأكيد رسالتك.",
            searchConversations: "تعذّر البحث في محادثاتك.",
            updateConversation: "تعذّر تحديث هذه المحادثة.",
            updateMessage: "تعذّر تحديث هذه الرسالة.",
            confirmUpdatedMessage: "تعذّر تأكيد رسالتك المحدّثة.",
            archiveConversation: "تعذّرت أرشفة هذه المحادثة.",
            archivePattern: "تعذّرت أرشفة هذا النمط.",
            removePattern: "تعذّر حذف هذا النمط.",
            archiveMemory: "تعذّرت أرشفة هذه الذكرى.",
            removeMemory: "تعذّر حذف هذه الذكرى.",
            archiveLearning: "تعذّرت أرشفة هذا الدرس.",
            removeLearning: "تعذّر حذف هذا الدرس.",
        },
    },
    timelineEntries: {
        patternForming: "نمط يتشكّل",
        insight: "رؤية",
        newLearning: "درس جديد",
        outcomeRecorded: "نتيجة مسجّلة",
        experimentStarted: "تجربة بدأت",
        experimentActive: "تجربة نشطة",
        reflection: "تأمل",
        checkIn: "تحقّق",
        experimentOutcomeTitle: "نتيجة تجربة مسجّلة",
        reflectionTitle: "تأمل مسجّل",
    },
};

export default ar;
