import type { Translation } from "@/constants/copy";
import type { DayPart } from "@/lib/dayPart";

/**
 * Spanish translation.
 *
 * Every key of the English source of truth is required; the compiler rejects
 * missing or extra keys. Uses the informal "tú" register throughout — the
 * dominant convention for consumer apps in Spanish and the right warmth for a
 * reflective personal companion. Proper nouns (Aks, Google, Notion, GitHub…)
 * stay as-is; "Google Calendar" keeps its official Spanish product name, while
 * Apple's app names use their Spanish localization (Calendario, Recordatorios).
 * Spanish typography: inverted ¿/¡ openers on every question/exclamation,
 * « » guillemets in stored-data examples, a space before " %".
 * Domain glossary: insight = hallazgo, pattern = patrón, learning = lección,
 * memory = recuerdo, signal = señal, Mirror = Espejo.
 */
const es: Translation = {
    common: {
        back: "Atrás",
        cancel: "Cancelar",
        save: "Guardar",
        dismiss: "Cerrar",
        clear: "Borrar",
        loading: "Cargando…",
        tryAgain: "Reintentar",
        loadMore: "Cargar más",
        pleaseTryAgain: "Inténtalo de nuevo.",
        checkConnection: "Comprueba tu conexión e inténtalo de nuevo.",
        emailPlaceholder: "tu@ejemplo.com",
        justNow: "justo ahora",
        dateUnavailable: "Fecha no disponible",
        version: (value: string) => `Versión ${value}`,
    },
    brand: {
        name: "Aks.ai",
        tagline: "Entenderse, de otra manera.",
    },
    splash: {
        appName: "Aks.ai",
        subtitle: "Entenderse, de otra manera.",
    },
    onboarding: {
        skip: "Saltar",
        moveForward: "Continuar",
        getStarted: "Empezar",
        notices: {
            unableToContinue: "No se puede continuar",
        },
        slides: [
            {
                eyebrow: "TU VIDA DEJA RASTROS",
                title: "Ya dejas\nrastros de ti.",
                description:
                    "Lo que repites. Los momentos que evitas. Los días que se sienten distintos. Aks reúne esas señales.",
            },
            {
                eyebrow: "NO SOLO LO PIENSES",
                title: "No improvises.\nPonlo a prueba.",
                description:
                    "Convierte una corazonada en un pequeño experimento. Cambia una cosa, mide qué pasa y descubre qué funciona de verdad para ti.",
            },
            {
                eyebrow: "UNA IMAGEN MÁS NÍTIDA",
                title: "Deja de ser un\nmisterio para ti.",
                description:
                    "Con el tiempo, Aks construye una imagen viva de tus patrones, tus reacciones y los cambios que de verdad marcan la diferencia.",
            },
        ],
    },
    legal: {
        termsTitle: "Términos del servicio",
        privacyTitle: "Política de privacidad",
        acceptance: {
            title: "Antes de empezar.",
            description:
                "Aks trabaja con información personal para ayudarte a entender tus patrones. Esto es lo que debes saber antes de continuar.",
            cardTitle: "Tus datos, tu control.",
            cardBody:
                "Aks usa la información que eliges compartir para identificar patrones y ayudarte a realizar experimentos personales.",
            bullets: [
                "Tú decides qué información proporcionar.",
                "Puedes gestionar tus datos y tus permisos.",
                "Aks no sustituye el asesoramiento médico o de salud mental profesional.",
            ],
            agreePrefix: "Acepto los",
            terms: "términos del servicio",
            andWord: "y la",
            privacy: "política de privacidad",
            continue: "Continuar con Aks",
            retryAction: "Reintentar",
            retry: "Reintentar",
            footnote: "Podrás revisar estos documentos más tarde en los ajustes.",
            consentA11y: "Aceptar los términos del servicio y la política de privacidad",
            notices: {
                unableToSave: "No se pudo guardar la aceptación",
            },
        },
        links: {
            prefix: "Al continuar, aceptas los",
            terms: "términos del servicio",
            andWord: "y la",
            privacy: "política de privacidad",
        },
    },
    login: {
        title: "Nos alegra verte de nuevo.",
        description: "Inicia sesión para seguir descubriendo lo que Aks nota en ti.",
        emailLabel: "Dirección de correo",
        sendLink: "Iniciar sesión",
        sendLinkA11y: "Enviar el enlace de inicio de sesión",
        secureLinkNote: "Te enviamos un enlace de acceso seguro por correo. Sin contraseñas.",
        divider: "O CONTINUAR CON",
        google: "Google",
        googleA11y: "Continuar con Google",
        facebook: "Facebook",
        facebookA11y: "Continuar con Facebook",
        github: "Continuar con GitHub",
        githubA11y: "Continuar con GitHub",
        noAccount: "¿No tienes una cuenta?",
        createOne: "Crea una",
        dismissError: "Toca para cerrar.",
        notices: {
            unableToSendLink: "No se pudo enviar el enlace de inicio de sesión",
            unableToSignIn: "No se pudo iniciar sesión",
        },
    },
    register: {
        title: "Crea tu cuenta.",
        description: "Empieza a construir, con Aks, una imagen más nítida de ti.",
        nameLabel: "Nombre completo",
        namePlaceholder: "Tu nombre completo",
        nameA11y: "Nombre completo",
        emailLabel: "Dirección de correo",
        createAccount: "Crear cuenta",
        createAccountA11y: "Crear una cuenta con el correo",
        secureLinkNote: "Te enviamos un enlace de acceso seguro. Sin contraseñas.",
        divider: "O REGISTRARSE CON",
        google: "Google",
        googleA11y: "Continuar con Google",
        facebook: "Facebook",
        facebookA11y: "Continuar con Facebook",
        github: "Continuar con GitHub",
        githubA11y: "Continuar con GitHub",
        hasAccount: "¿Ya tienes una cuenta?",
        signIn: "Inicia sesión",
        dismissError: "Toca para cerrar.",
        notices: {
            unableToCreate: "No se pudo crear la cuenta",
            unableToSignIn: "No se pudo iniciar sesión",
        },
    },
    emailConfirmation: {
        title: "Revisa tu correo.",
        body: (email: string) =>
            `Enviamos un enlace de acceso seguro a ${email}. Ábrelo en este dispositivo para continuar.`,
        resendNote: "Si lo reenvías, solo el enlace más reciente funcionará.",
        resend: "Reenviar enlace",
        resendA11y: "Reenviar el enlace de inicio de sesión",
        editEmail: "Cambiar el correo",
        editEmailA11y: "Cambiar la dirección de correo",
    },
    mirror: {
        eyebrow: "ESPEJO",
        greeting: (firstName: string | null, part: DayPart = "morning") => {
            const base =
                part === "afternoon"
                    ? "Buenas tardes"
                    : part === "evening"
                        ? "Buenas noches"
                        : part === "night"
                            ? "Feliz noche"
                            : "Buenos días";
            return `${base}${firstName ? `, ${firstName}` : ""}.`;
        },
        intro: "Soy Aks. Empecemos con algo sencillo.",
        understandTitle: "¿Qué te gustaría entender?",
        differentHint: "O cuéntale a Aks algo completamente distinto.",
        checkInEyebrow: "CHECK-IN RÁPIDO",
        checkInTitle: "¿Cómo va tu día?",
        topics: ["Enfoque", "Energía", "Sueño", "Emociones", "Rutinas", "Relaciones", "Productividad"],
        topicDraft: (topic: string) => `Me gustaría entender mejor: ${topic.toLowerCase()}.`,
        checks: ["Bien", "Regular", "Caos"],
        aksLabel: "AKS",
        errorTitle: "Algo salió mal.",
        retryResponse: "Regenerar respuesta",
        listening: "Escuchando…",
        listeningMeta: (duration: string) => `${duration} · se queda en este dispositivo`,
        stopRecordingA11y: "Detener la grabación",
        voiceReady: "Reflexión de voz lista",
        voiceReadyHint: "Aks la convertirá en una reflexión escrita.",
        discardRecordingA11y: "Descartar la grabación",
        sendRecordingA11y: "Enviar la grabación",
        composerPlaceholder: "Cuéntale a Aks lo que tienes en mente…",
        sendMessageA11y: "Enviar el mensaje",
        recordVoiceA11y: "Grabar una reflexión de voz",
        notices: {
            micUnavailable: "Micrófono no disponible",
            micUnavailableBody:
                "Se necesita acceso al micrófono para grabar una reflexión de voz. También puedes escribir.",
            cantListen: "No se pudo empezar a escuchar",
            cantListenBody: "Inténtalo de nuevo, o escribe lo que tienes en mente.",
            stopRecording: "No se pudo detener la grabación",
            recordingFailed: "No se pudo conservar esta grabación",
            transcriptionNotConfigured:
                "Las reflexiones de voz aún no están disponibles en esta versión. Puedes escribir tu reflexión.",
            audioTooLong: "Esta grabación es demasiado larga. Prueba con algo más corto.",
            subscriptionRequired:
                "Las reflexiones de voz requieren Aks Premium: esta grabación no se ha usado. Puedes escribir en su lugar.",
            emptyTranscription:
                "Aks no escuchó nada en esta grabación. Comprueba que el micrófono funciona e inténtalo de nuevo.",
            unsupportedAudio: "Este formato de grabación no es compatible. Grábala de nuevo.",
            transcriptionUnavailable:
                "Aks no puede procesar esta grabación en este momento. Puedes reintentarlo o escribir.",
            unauthorized: "Inicia sesión e inténtalo de nuevo.",
            recordingFailedFallback:
                "Aks no pudo conservar esta grabación. Puedes reintentarlo o escribir.",
        },
    },
    mirrorBar: {
        newConversation: "Nueva conversación",
        composerPlaceholder: "Cuéntale a Aks lo que tienes en mente…",
        sendMessageA11y: "Enviar el mensaje",
        closeComposerA11y: "Cerrar el campo de escritura",
        openKeyboardA11y: "Abrir el teclado",
        stopVoiceA11y: "Detener la conversación de voz",
        startVoiceA11y: "Iniciar la conversación de voz",
        voiceOffA11y: "Desactivar las respuestas de voz",
        voiceOnA11y: "Activar las respuestas de voz",
        moreOptionsA11y: "Más opciones de conversación",
        hint: "No hace falta ordenar tus ideas primero. Solo empieza a hablar.",
    },
    aiConversation: {
        greeting: (firstName: string | null) => `Hola, ${firstName ?? "tú"} 👋`,
        openingPrompts: [
            "¿Qué tienes en mente?",
            "¿Cómo te sientes hoy?",
            "¿Hay algo que lleves contigo un tiempo?",
            "¿Qué ocupa más espacio en tu cabeza?",
            "¿Quieres hablar de lo que te preocupa?",
            "¿Hay algo que te gustaría decir al fin?",
            "¿Qué es lo que más pesa últimamente?",
            "¿Hay algo que te gustaría decir?",
        ],
        copyAction: "Copiar",
        copiedAction: "Copiado",
        copyA11y: "Copiar el mensaje",
        shareAction: "Compartir",
        shareA11y: "Compartir el mensaje",
        tryAgainAction: "Reintentar",
        tryAgainA11y: "Regenerar esta respuesta",
        motionReadyA11y: "Aks está listo",
        thinking: "Pensando…",
        thinkingDefault: "Aks está pensando…",
        aksTag: "aks",
        youTag: "tú",
        listening: "Escuchando…",
        speaking: "Aks está hablando…",
        loadingConversation: "Cargando la conversación…",
        youPrefix: "Tú: ",
        errorTitle: "Algo salió mal.",
        retryResponse: "Regenerar respuesta",
        voicePaused: "Voz en pausa.",
        editPlaceholder: "Reescribe tu mensaje…",
        saveAndSend: "Guardar y enviar",
        saveAndSendA11y: "Guardar y enviar el mensaje editado",
        cancelEditingA11y: "Cancelar la edición",
        cancel: "Cancelar",
        editMessage: "Editar mensaje",
        editMessageA11y: "Editar tu mensaje",
    },
    timeline: {
        header: "Cronología",
        headerCaption: "Tu recorrido con Aks, a lo largo del tiempo.",
        eyebrow: "TU RECORRIDO",
        title: "Tu historia, que se va escribiendo.",
        description:
            "Mira los momentos, patrones, experimentos y lecciones que han dado forma a tu recorrido con Aks.",
        errorTitle: "No se pudo cargar tu cronología.",
        errorBody: "Tu historia sigue ahí. Inténtalo de nuevo en un momento.",
        loadMoreError: "No se pudo cargar el resto de tu historia.",
        empty: {
            allTitle: "Tu historia apenas comienza.",
            allBody:
                "A medida que hablas con Aks, los momentos, patrones, experimentos y lecciones destacados aparecerán aquí.",
            insightsTitle: "Aún no hay hallazgos.",
            insightsBody: "Los hallazgos útiles aparecerán a medida que Aks reúna suficientes señales con el tiempo.",
            experimentsTitle: "Aún no hay experimentos.",
            experimentsBody: "Los experimentos que inicies aparecerán aquí.",
            checkInsTitle: "Aún no hay check-ins.",
            checkInsBody: "Tus check-ins memorables aparecerán aquí.",
            decisionsTitle: "Aún no hay decisiones.",
            decisionsBody: "Las decisiones y los patrones que Aks note aparecerán aquí, refinándose.",
            learningsTitle: "Aún no hay lecciones.",
            learningsBody: "Nuevas lecciones aparecerán aquí a medida que tu historia se aclare.",
        },
    },
    you: {
        title: "Tú",
        fallbackName: "Miembro de Aks",
        subtitle: "Tu espacio personal",
        knowsTitle: "Lo que Aks sabe",
        knowsEmpty: "Aks todavía está aprendiendo a conocerte",
        memoriesCount: (count: number) => `${count} ${count === 1 ? "recuerdo" : "recuerdos"}`,
        exploringTitle: "Lo que estás explorando",
        exploringEmpty: "Elige tu enfoque",
        unnoticedTitle: "Lo que aún no has notado",
        insightsCount: (count: number) => `${count} ${count === 1 ? "hallazgo" : "hallazgos"} para revisar`,
        insightsEmpty: "Nada confirmado por ahora",
        journeySection: "TU RECORRIDO",
        patternsTitle: "Patrones",
        patternsDescription: "Lo que Aks ha notado",
        experimentsTitle: "Experimentos",
        experimentsDescription: "Lo que estás probando ahora mismo",
        yourDataTitle: "Tus datos",
        yourDataDescription: "Consulta y gestiona tu información",
        preferencesSection: "PREFERENCIAS",
        notificationsTitle: "Notificaciones",
        notificationsDescription: "Cuándo puede escribierte Aks",
        appearanceTitle: "Apariencia",
        appearanceDescription: "Sistema · Claro · Oscuro",
        privacyTitle: "Privacidad",
        privacyDescription: "Permisos y controles de privacidad",
        supportSection: "AYUDA",
        helpTitle: "Ayuda y comentarios",
    },
    settings: {
        header: "Ajustes",
        eyebrow: "AJUSTES",
        title: "Tu Aks, a tu manera.",
        description: "Gestiona tu cuenta, tu plan y la información sobre Aks.",
        accountSection: "CUENTA",
        profileTitle: "Perfil",
        profileDescription: "Gestiona tu información personal",
        accountTitle: "Cuenta",
        accountDescription: "Cierra sesión o elimina tu cuenta",
        subscriptionTitle: "Suscripción",
        subscriptionDescription: "Gestiona tu plan de Aks y la facturación",
        preferencesSection: "PREFERENCIAS",
        languageTitle: "Idioma",
        aboutSection: "ACERCA DE",
        aboutTitle: "Acerca de Aks",
        aboutDescription: "Conoce más sobre Aks",
        termsTitle: "Términos del servicio",
        privacyTitle: "Política de privacidad",
    },
    profile: {
        header: "Perfil",
        fallbackName: "Miembro de Aks",
        fallbackEmail: "Correo no disponible",
        editName: "Editar nombre",
        editNameA11y: "Editar el nombre",
        changePhotoA11y: "Cambiar la foto de perfil",
        photoA11y: "Foto de perfil",
        photoSheetTitle: "Foto de perfil",
        chooseImage: "Elegir una imagen",
        removePhoto: "Quitar la foto",
        aksSection: "AKS",
        exploringTitle: "Lo que estás explorando",
        exploringEmpty: "Sin definir",
        noticeTitle: "Lo que Aks debe notar",
        noticeEmpty: "Sin definir",
        preferencesSection: "PREFERENCIAS",
        timezoneTitle: "Zona horaria",
        languageTitle: "Idioma",
        accountSection: "CUENTA",
        emailTitle: "Correo",
        emailUnavailable: "No disponible",
        memberSince: "Miembro desde",
        memberSinceUnavailable: "No disponible",
        signInMethod: "Método de acceso",
        signInMethodFallback: "Correo",
        editNameTitle: "Edita tu nombre",
        editNameMessage: "Así es como Aks se dirige a ti.",
        nameA11y: "Nombre completo",
        namePlaceholder: "Tu nombre",
        saving: "Guardando…",
        saveChanges: "Guardar cambios",
        fullName: "Nombre completo",
        notices: {
            unableToSaveName: "No se pudo guardar el perfil",
            unableToUpdatePhoto: "No se pudo actualizar la foto",
            unableToRemovePhoto: "No se pudo quitar la foto",
            checkConnection: "Comprueba tu conexión e inténtalo de nuevo.",
            tryAgain: "Inténtalo de nuevo.",
        },
    },
    exploring: {
        header: "Lo que estás explorando",
        eyebrow: "PERSONAL",
        title: "Elige tu enfoque.",
        description: "Selecciona las áreas que quieres entender mejor.",
        options: ["Enfoque", "Energía", "Sueño", "Ánimo", "Hábitos", "Estrés"],
    },
    noticeAreas: {
        header: "Lo que Aks debe notar",
        eyebrow: "PERSONAL",
        title: "Guía lo que Aks nota.",
        description: "Elige las áreas que Aks debe priorizar para detectar posibles patrones.",
        options: ["Rutinas diarias", "Cambios de energía", "Patrones de enfoque", "Calidad del sueño", "Variaciones de ánimo", "Resultados de experimentos"],
    },
    timezone: {
        header: "Zona horaria",
        eyebrow: "PREFERENCIAS",
        title: "Tu hora local.",
        description: "Elige la zona horaria que Aks usa para la planificación.",
    },
    language: {
        header: "Idioma",
        eyebrow: "PREFERENCIAS",
        title: "Elige tu idioma.",
        description: "Selecciona el idioma que se usará en todo Aks.",
        notAvailableYet: (name: string) => `${name} aún no está disponible. Se usará el inglés hasta que llegue su traducción.`,
        comingSoon: "Próximamente",
    },
    appearance: {
        header: "Apariencia",
        eyebrow: "TU EXPERIENCIA",
        title: "Ajusta su apariencia.",
        description: "Elige cómo se ve Aks en toda la aplicación.",
        themeSection: "TEMA",
        themes: {
            systemTitle: "Sistema",
            systemDescription: "Sigue la apariencia de tu dispositivo.",
            lightTitle: "Claro",
            lightDescription: "Mantiene Aks luminoso y nítido.",
            darkTitle: "Oscuro",
            darkDescription: "Una experiencia más suave con poca luz.",
        },
        noteCaption: "UNA NOTA DE AKS",
        noteBody: "La apariencia solo cambia cómo se ve Aks.",
        notices: {
            unableToSave: "No se pudo guardar la apariencia",
        },
    },
    account: {
        header: "Cuenta",
        signedInAs: "SESIÓN INICIADA COMO",
        emailUnavailable: "Correo no disponible",
        signOut: "Cerrar sesión",
        deleteAccount: "Eliminar cuenta",
        confirmSignOutTitle: "¿Cerrar sesión?",
        confirmSignOutMessage: "Tendrás que volver a iniciar sesión para seguir usando Aks.",
        confirmDeleteTitle: "¿Eliminar la cuenta?",
        confirmDeleteMessage:
            "Esto elimina permanentemente tu cuenta y los datos asociados. No se puede deshacer.",
        notices: {
            unableToSignOut: "No se pudo cerrar la sesión",
            unableToDelete: "No se pudo eliminar la cuenta",
            deleteUnavailable:
                "La eliminación de la cuenta no está disponible en este momento. Inténtalo más tarde.",
        },
    },
    about: {
        header: "Acerca de Aks",
        eyebrow: "ACERCA DE",
        title: "Entenderse, de otra manera.",
        description:
            "Aks te ayuda a reflexionar sobre tu actividad, a notar posibles patrones y a realizar experimentos personales con más intención.",
        productLabel: "Producto",
        productValue: "Aks.ai",
        versionLabel: "Versión",
        versionValue: "1.0.0",
        note: "Aks apoya la reflexión personal y no sustituye el asesoramiento médico o de salud mental profesional.",
    },
    subscription: {
        header: "Suscripción",
        eyebrow: "TU PLAN",
        title: "Plan y facturación de Aks.",
        description:
            "Consulta tu plan y el estado de la facturación. La gestión de la suscripción se podrá conectar cuando exista la facturación.",
        checkingPlan: "Comprobando tu plan…",
        fallbackError: "No se pudo comprobar tu plan. Inténtalo de nuevo.",
        currentPlan: "PLAN ACTUAL",
        activeBadge: "Activo",
        planActive: "Tu plan está activo.",
        renewsOn: (date: string) => `Se renueva el ${date}`,
        accessUntil: (date: string) => `Acceso hasta el ${date}`,
        autoRenewOff: "La renovación automática está desactivada.",
        billing: "FACTURACIÓN",
        manage: "Gestionar la suscripción",
        restore: "Restaurar compras",
        choosePlan: "ELIGE TU PLAN",
        chooseTitle: "Pasa más tiempo con Aks.",
        chooseDescription:
            "Elige el ritmo que te convenga. Puedes gestionar o restaurar tu suscripción en cualquier momento.",
        expiredWithDate: (date: string) => `Tu acceso Premium terminó el ${date}.`,
        expiredFallback: "Tu acceso Premium ha terminado.",
        plansEmpty: "No hay planes disponibles por ahora. Vuelve en un momento.",
        premiumEyebrow: "AKS PREMIUM",
        bestValue: "MEJOR VALOR",
        premiumAccess: "Acceso completo a Aks Premium",
        continueWith: (title: string) => `Continuar con ${title}`,
        unavailableTitle: "Las suscripciones aún no están conectadas en este dispositivo.",
        unavailableBody:
            "Cuando la facturación esté disponible en este dispositivo, los planes aparecerán aquí y podrás verlos y gestionarlos desde esta pantalla.",
        noteCaption: "UNA NOTA DE AKS",
        noteBody: "Los pagos los gestiona la tienda de tu dispositivo.",
    },
    notifications: {
        header: "Notificaciones",
        eyebrow: "MANTENTE AL TANTO",
        title: "Solo cuando importa.",
        description: "Elige cuándo puede escribierte Aks. Puedes cambiar estas preferencias en cualquier momento.",
        sectionMain: "NOTIFICACIONES",
        allowTitle: "Permitir notificaciones",
        allowDescription: "Pausar o reanudar todas las notificaciones de Aks.",
        categoriesSection: "LO QUE AKS PUEDE ENVIAR",
        categories: {
            insightsTitle: "Nuevos hallazgos",
            insightsDescription: "Cuando Aks note un patrón que merezca atención.",
            experimentsTitle: "Seguimiento de experimentos",
            experimentsDescription: "Recordatorios y resultados de los experimentos activos.",
            checkInsTitle: "Recordatorios de check-in",
            checkInsDescription: "Una invitación amable para hacer balance de tu día.",
            weeklyTitle: "Reflexión semanal",
            weeklyDescription: "Un resumen de lo que cambió durante la semana.",
        },
        quietSection: "HORAS DE SILENCIO",
        quietTitle: "Horas de silencio",
        quietDescription: "Silenciar las notificaciones de 22:00 a 8:00.",
        deviceSection: "AJUSTES DEL DISPOSITIVO",
        deviceTitle: "Gestionar las notificaciones del dispositivo",
        deviceDescription: "Abre los ajustes del dispositivo para gestionar los permisos de Aks.",
        noteCaption: "UNA NOTA DE AKS",
        noteBody: "Aks solo te escribe cuando importa.",
    },
    yourData: {
        header: "Tus datos",
        eyebrow: "TUS DATOS",
        title: "Lo que Aks conserva.",
        description:
            "Mira la información que Aks ha reunido de tu actividad y de lo que has elegido compartir.",
        glanceSection: "DE UN VISTAZO",
        remembersSection: "LO QUE AKS CONSERVA",
        sourcesSection: "FUENTES DE DATOS",
        sourcesTitle: "Fuentes conectadas",
        sourcesUnknown: "Comprueba qué fuentes están conectadas.",
        sourcesNone: "No hay fuentes conectadas. Disponible cuando esté admitido.",
        sourcesCount: (count: number) => `${count} conectada${count === 1 ? "" : "s"} · gestiona o desconecta cuando quieras.`,
        choiceSection: "TU DECISIÓN",
        choiceTitle: "Tú decides qué se queda.",
        choiceBody: "Consulta, exporta o elimina tu información en cualquier momento.",
        exportAction: "Exportar datos",
        deleteAction: "Eliminar datos",
        noteCaption: "UNA NOTA DE AKS",
        noteBody: "Tus datos siguen siendo legibles y bajo tu control.",
        loadingData: "Cargando el resumen de datos",
        retry: "Reintentar",
    },
    reflections: {
        header: "Reflexiones",
        eyebrow: "TUS REFLEXIONES",
        title: "Lo que has compartido.",
        description: "Vuelve a las reflexiones que dan a Aks contexto sobre tus experiencias.",
        itemTitle: "Reflexión",
        emptyTitle: "Aún no hay reflexiones.",
        emptyBody: "Tus reflexiones aparecerán aquí en cuanto empieces a compartirlas con Aks.",
    },
    checkIns: {
        header: "Check-ins",
        eyebrow: "TUS CHECK-INS",
        title: "Pequeños momentos, guardados.",
        description: "Vuelve a los check-ins con los que fuiste anotando cómo iban las cosas a lo largo del tiempo.",
        itemFallback: "Check-in",
        itemTitle: (mood: string) => `Check-in: ${mood}`,
        energy: (value: number) => `Energía ${value}`,
        focus: (value: number) => `Enfoque ${value}`,
        stress: (value: number) => `Estrés ${value}`,
        noDetails: "Sin detalles adicionales",
        emptyTitle: "Aún no hay check-ins.",
        emptyBody: "Tus check-ins aparecerán aquí en cuanto empieces a registrarlos.",
    },
    conversations: {
        header: "Conversaciones",
        eyebrow: "TUS CONVERSACIONES",
        title: "Tus conversaciones con Aks.",
        description:
            "Vuelve a lo que compartiste, sin mezclarlo con interpretaciones futuras. La búsqueda incluye los títulos y lo que se dijo.",
        searchA11y: "Buscar conversaciones",
        searchPlaceholder: "Buscar en tus conversaciones",
        clearSearch: "Borrar",
        loadingA11y: "Cargando las conversaciones",
        loadErrorTitle: "No se pudieron cargar las conversaciones.",
        emptyQueryTitle: "Ninguna conversación coincide.",
        emptyQueryBody: "Prueba con otra palabra: Aks busca lo que dijiste, no solo los títulos.",
        emptyTitle: "Aún no hay conversaciones.",
        emptyBody: "Las conversaciones que inicies con Aks aparecerán aquí.",
        archiveHint: "Mantén pulsado para archivar",
        loadMore: "Cargar más",
        archiveTitle: "¿Archivar esta conversación?",
        archiveMessage: "Se ocultará de tu historial activo.",
        archiveConfirm: "Archivar",
        notices: {
            unableToArchive: "No se pudo archivar",
        },
    },
    conversationDetail: {
        fallbackTitle: "Conversación",
        renameA11y: "Renombrar la conversación",
        loadingA11y: "Cargando la conversación",
        unavailableTitle: "Conversación no disponible.",
        archivedBody: "Puede que se haya archivado o eliminado.",
        renameSection: "RENOMBRAR LA CONVERSACIÓN",
        titleA11y: "Título de la conversación",
        titlePlaceholder: "Título de la conversación",
        saveRename: "Guardar",
        cancelRename: "Cancelar",
        cancelRenameA11y: "Cancelar el cambio de nombre",
        historySection: "HISTORIAL DE LA CONVERSACIÓN",
        startedAt: (date: string) => `Comenzó el ${date}`,
        continueMirror: "Continuar en Espejo",
        loadEarlier: "Cargar mensajes anteriores",
        youLabel: "Tú",
        aksLabel: "Aks",
        systemLabel: "Sistema",
        emptyTitle: "Aún no hay mensajes.",
    },
    memories: {
        header: "Lo que Aks retiene",
        eyebrow: "LO QUE AKS RETIENE",
        title: "Contexto útil, guardado con cuidado.",
        description:
            "Lo que Aks retuvo de información repetida y sustentada que compartiste.",
        observationsCount: (count: number) => `${count} ${count === 1 ? "observación" : "observaciones"}`,
        lastNoticed: (date: string) => `Notado por última vez ${date}`,
        emptyTitle: "Aks todavía está aprendiendo tus patrones.",
        emptyBody:
            "El contexto repetido y útil aparecerá aquí cuando haya suficientes señales para conservarlo.",
    },
    memoryDetail: {
        header: "Recuerdo",
        loadingA11y: "Cargando el recuerdo",
        unavailableTitle: "Recuerdo no disponible.",
        archivedFallback: "Puede que se haya archivado o eliminado.",
        eyebrow: "LO QUE AKS RETIENE",
        reasonTitle: "Por qué Aks lo recuerda",
        reasonFallback: (count: number) => `Apareció en ${count} ${count === 1 ? "elemento que compartiste" : "elementos que compartiste"}.`,
        lastNoticed: (date: string) => `Notado por última vez ${date}`,
        evidenceSection: "INDICIOS",
        viewConversation: " · Ver la conversación",
        archiveAction: "Archivar el recuerdo",
        removeAction: "Eliminar el recuerdo",
        archiveTitle: "¿Archivar este recuerdo?",
        archiveMessage:
            "Aks dejará de usarlo ahora. Lo que compartas más adelante puede volver a sustentarlo. Tus conversaciones, reflexiones y check-ins originales quedan intactos.",
        archiveConfirm: "Archivar",
        removeTitle: "¿Eliminar este recuerdo?",
        removeMessage:
            "Esto elimina solo el recuerdo que Aks conserva. La información original que compartiste no se elimina.",
        removeConfirm: "Eliminar",
        notices: {
            unableToArchive: "No se pudo archivar",
            unableToRemove: "No se pudo eliminar",
        },
    },
    patterns: {
        header: "Patrones",
        eyebrow: "TUS PATRONES",
        title: "Conexiones que merecen atención.",
        description: "Relaciones posibles, basadas en señales repetidas de lo que has compartido.",
        observationsCount: (count: number) => `${count} ${count === 1 ? "observación" : "observaciones"}`,
        emptyTitle: "Aún no hay patrones.",
        emptyBody: "Aks necesita un poco más de tiempo y señales para detectar conexiones útiles.",
        status: {
            possible: "Patrón posible",
            notSupported: "Sin respaldo",
            supported: "Con respaldo",
            testing: "En prueba",
            fallback: "Candidato",
        },
    },
    patternDetail: {
        header: "Patrón",
        loadingA11y: "Cargando el patrón",
        unavailableTitle: "Patrón no disponible.",
        archivedFallback: "Puede que se haya archivado o eliminado.",
        reasonTitle: "Por qué Aks lo notó",
        evidenceLine: (supporting: number, contradicting: number) =>
            `Esta conexión se basa en ${supporting} ${supporting === 1 ? "observación" : "observaciones"} a favor` +
            (contradicting ? ` y ${contradicting} ${contradicting === 1 ? "observación" : "observaciones"} en contra` : "") +
            ".",
        confidencePending: "Nivel de confianza en evaluación",
        confidenceValue: (percent: number) => `Confianza de los indicios: ${percent} %`,
        firstNoticed: (date: string) => `Notado por primera vez ${date}`,
        lastObserved: (date: string) => `Observado por última vez ${date}`,
        alternativeTitle: "Otra posibilidad",
        evidenceSection: "INDICIOS",
        supporting: "A favor",
        contradicting: "En contra",
        viewConversation: " · Ver la conversación",
        notReadyA11y: "Este patrón aún no está listo para probarse",
        testA11y: "Probar este patrón",
        notReady: "Aún no está listo para probarse",
        testAction: "Probar este patrón",
        archiveAction: "Archivar el patrón",
        removeAction: "Eliminar el patrón",
        statusLabels: {
            candidate: "Candidato",
            possible: "Patrón posible",
            testing: "En prueba",
            supported: "Con respaldo",
            notSupported: "Sin respaldo",
            archived: "Archivado",
        },
        archiveTitle: "¿Archivar este patrón?",
        archiveMessage:
            "Aks dejará de mostrar este patrón. Observaciones futuras pueden justificar volver a considerarlo.",
        archiveConfirm: "Archivar",
        removeTitle: "¿Eliminar este patrón?",
        removeMessage:
            "Esto elimina solo el patrón derivado y sus vínculos de indicios. Tus señales y la información original permanecen.",
        removeConfirm: "Eliminar",
        notices: {
            unableToArchive: "No se pudo archivar",
            unableToRemove: "No se pudo eliminar",
        },
    },
    experiments: {
        header: "Experimentos",
        eyebrow: "TUS EXPERIMENTOS",
        title: "Pruebas pequeñas, señales útiles.",
        description: "Los experimentos ayudan a poner a prueba un patrón posible sin tomarlo como un hecho.",
        observationsCount: (count: number) => `${count} ${count === 1 ? "observación" : "observaciones"}`,
        emptyTitle: "Aún no hay experimentos.",
        emptyBody: "Cuando un patrón merezca ponerse a prueba, podrás iniciar un pequeño experimento a su alrededor.",
        status: {
            active: "Activo",
            completed: "Completado",
            cancelled: "Cancelado",
            fallback: "Borrador",
        },
    },
    experimentSetup: {
        header: "Preparar el experimento",
        patternSection: "PATRÓN EN PRUEBA",
        titleLabel: "TÍTULO",
        titlePlaceholder: "Un título corto para el experimento",
        hypothesisLabel: "HIPÓTESIS",
        hypothesisPlaceholder: "Un pequeño cambio podría…",
        hypothesisDefault: "Un pequeño cambio podría influir en lo que observas en este patrón.",
        descriptionLabel: "QUÉ PROBAR Y OBSERVAR",
        descriptionPlaceholder: "Describe un pequeño cambio y lo que vas a registrar.",
        descriptionDefault:
            "Elige un cambio pequeño y reversible. Registra en cada ocasión si el resultado se sintió más fácil, igual o más difícil.",
        durationLabel: "DURACIÓN",
        durationA11y: (days: number) => `Duración de ${days} día${days === 1 ? "" : "s"}`,
        durationDays: (days: number) => `${days} d`,
        defaultTitle: (patternTitle: string) => `Prueba: ${patternTitle}`.slice(0, 120),
        createAction: "Crear borrador",
        createA11y: "Crear el borrador del experimento",
        createError: "No se pudo crear este experimento. Revisa los detalles e inténtalo de nuevo.",
        patternUnavailable: "Este patrón no está disponible.",
    },
    experimentDetail: {
        header: "Experimento",
        unavailableTitle: "Experimento no disponible.",
        hypothesisTitle: "Hipótesis",
        whatToTryTitle: "Qué probar",
        startAction: "Iniciar experimento",
        startA11y: "Iniciar el experimento",
        removeAction: "Eliminar el experimento",
        removeA11y: "Eliminar el experimento",
        removeTitle: "¿Eliminar este experimento?",
        removeMessage:
            "Esto elimina el experimento, sus observaciones y cualquier lección respaldada solo por este experimento. El patrón y las señales originales permanecen.",
        removeConfirm: "Eliminar",
        recordedFallback: "Registrado",
        observationsSection: "OBSERVACIONES",
        emptyObservations: "Aún no hay observaciones registradas.",
        resultSection: "RESULTADO",
        analysisPending: "Análisis pendiente",
        confidenceValue: (percent: number) => `Confianza de los indicios: ${percent} %`,
        promptTitle: "¿Cómo fue esta vez?",
        resultEasier: "Más fácil",
        resultSame: "Igual",
        resultHarder: "Más difícil",
        recordA11y: (result: string) => `Registrar: ${result}`,
        observationPlaceholder: "Nota opcional",
        observationA11y: "Nota de observación opcional",
        observationsMeta: (count: number) => `${count} ${count === 1 ? "observación registrada" : "observaciones registradas"}`,
        observationsDay: (current: number, total: number | null) =>
            total ? ` · Día ${current} de ${total}` : "",
        observationsThrough: (date: string) => ` · Hasta el ${date}`,
        completeAction: "Completar experimento",
        completeA11y: "Completar el experimento",
        cancelAction: "Cancelar experimento",
        cancelA11y: "Cancelar el experimento",
        resultPendingBody: "Tus observaciones se registran mientras se prepara el resultado.",
        retryAnalysis: "Reintentar la interpretación",
        retryAnalysisA11y: "Reintentar el análisis del experimento",
        retryLearning: "Reintentar la síntesis de lección",
        retryLearningA11y: "Reintentar la síntesis de la lección",
        retryInsight: "Reintentar la generación de hallazgo",
        retryInsightA11y: "Reintentar la generación del hallazgo",
        resultLabels: {
            easier: "Más fácil",
            same: "Igual",
            harder: "Más difícil",
        },
        outcomeLabels: {
            supports: "Respaldan la hipótesis",
            mixed: "Resultado mixto",
            doesNotSupport: "No respaldan la hipótesis",
            insufficientData: "Datos insuficientes",
        },
        confirmCompleteTitle: "¿Completar este experimento?",
        confirmCompleteMessage: "Aks resumirá lo que sugieren tus observaciones.",
        confirmCompleteLabel: "Completar",
        confirmCancelTitle: "¿Cancelar este experimento?",
        confirmCancelMessage: "Tus observaciones registradas seguirán disponibles para consultarlas.",
        confirmCancelLabel: "Cancelar el experimento",
        keepGoing: "Continuar",
        notices: {
            unableToUpdate: "No se pudo actualizar",
            unableToRecord: "No se pudo registrar",
            recordRetry: "Tu intento anterior se puede reanudar sin riesgo.",
        },
    },
    learnings: {
        header: "Lecciones",
        eyebrow: "TUS LECCIONES",
        title: "Lo que sugieren las señales.",
        description:
            "Conclusiones prudentes extraídas de los experimentos completados y de las observaciones registradas.",
        statusRevised: "Revisada",
        statusActive: "Activa",
        observationsCount: (count: number) => `${count} ${count === 1 ? "observación" : "observaciones"}`,
        emptyTitle: "Aún no hay lecciones.",
        emptyBody:
            "Cuando hayas puesto algo a prueba y reunido suficientes señales, Aks podrá ayudarte a entender qué cambió.",
    },
    learningDetail: {
        header: "Lección",
        unavailableTitle: "Lección no disponible.",
        evidenceTitle: "¿Qué llevó a esto?",
        evidenceLine: (experiments: number, observations: number) =>
            `Basada en ${experiments} ${experiments === 1 ? "experimento completado" : "experimentos completados"} y ${observations} ${observations === 1 ? "observación registrada" : "observaciones registradas"}.`,
        confidenceValue: (percent: number) => `Confianza de los indicios: ${percent} %`,
        updatedAt: (date: string) => `Actualizada ${date}`,
        sourceSection: "EXPERIMENTOS DE ORIGEN",
        openExperimentA11y: (title: string) => `Abrir el experimento ${title}`,
        observationsCount: (count: number) => `${count} ${count === 1 ? "observación" : "observaciones"}`,
        archiveAction: "Archivar la lección",
        archiveA11y: "Archivar la lección",
        removeAction: "Eliminar la lección",
        removeA11y: "Eliminar la lección",
        resultLabels: {
            supports: "Respaldó la hipótesis",
            mixed: "Resultado mixto",
            doesNotSupport: "No respaldó la hipótesis",
            insufficientData: "Datos insuficientes",
        },
        archiveTitle: "¿Archivar esta lección?",
        archiveMessage: "Los experimentos y observaciones de origen seguirán disponibles para consultarlos.",
        archiveConfirm: "Archivar",
        removeTitle: "¿Eliminar esta lección?",
        removeMessage:
            "Esto elimina solo la lección derivada. Experimentos, observaciones, patrones y señales permanecen.",
        removeConfirm: "Eliminar",
        notices: {
            unableToArchive: "No se pudo archivar",
            unableToRemove: "No se pudo eliminar",
        },
    },
    insights: {
        header: "Hallazgos",
        eyebrow: "HALLAZGOS",
        title: "Algo que notar.",
        description: "Un conjunto pequeño de observaciones útiles, basadas en lo que has probado y aprendido.",
        statusNew: "Nuevo",
        statusSeen: "Visto",
        emptyTitle: "Aún no hay hallazgos.",
        emptyBody: "A medida que Aks reúna señales, empezarán a salir cosas útiles.",
    },
    insightDetail: {
        header: "Hallazgo",
        eyebrow: "HALLAZGO",
        unavailableTitle: "Hallazgo no disponible.",
        reasonTitle: "Por qué Aks lo notó",
        openExperimentA11y: (title: string) => `Abrir el experimento de origen ${title}`,
        openLearningA11y: (title: string) => `Abrir la lección de origen ${title}`,
        observationsCount: (count: number) => `${count} ${count === 1 ? "observación registrada" : "observaciones registradas"} · Ver el experimento`,
        viewLearning: "Ver la lección de origen",
        confidenceValue: (percent: number) => `Confianza de los indicios: ${percent} %`,
        createdAt: (date: string) => `Creado ${date}`,
        dismissAction: "Descartar el hallazgo",
        dismissA11y: "Descartar el hallazgo",
        removeAction: "Eliminar el hallazgo",
        removeA11y: "Eliminar el hallazgo",
        dismissTitle: "¿Descartar este hallazgo?",
        dismissMessage: "La lección, el experimento, el patrón y los indicios permanecen.",
        dismissConfirm: "Descartar",
        removeTitle: "¿Eliminar este hallazgo?",
        removeMessage: "Esto elimina solo el hallazgo. Toda la información de origen permanece.",
        removeConfirm: "Eliminar",
        notices: {
            unableToDismiss: "No se pudo descartar",
            unableToRemove: "No se pudo eliminar",
        },
    },
    privacyHome: {
        header: "Privacidad",
        eyebrow: "TU PRIVACIDAD",
        title: "Tu vida es tuya.",
        description:
            "Aks te ayuda a entenderte mientras tú mantienes el control de la información que hay detrás de tu experiencia.",
        dataSection: "TUS DATOS",
        knowsTitle: "Lo que Aks sabe",
        knowsDescription: "Entiende la información que crea tu experiencia.",
        accessTitle: "A qué puede acceder Aks",
        accessDescription: "Mira lo que proporcionas o eliges conectar.",
        controlsSection: "CONTROLES DE DATOS",
        usageTitle: "Cómo se usan tus datos",
        usageDescription: "Mira cómo la información sustenta los hallazgos y los experimentos.",
        exportTitle: "Exportar tus datos",
        exportDescription: "Solicitar una copia de tu información de Aks.",
        deleteTitle: "Eliminar tus datos",
        deleteDescription: "Iniciar una solicitud de eliminación deliberada de los datos de la cuenta.",
        legalSection: "LEGAL",
        privacyPolicyTitle: "Política de privacidad",
        privacyPolicyDescription: "Leer la política de privacidad completa de Aks.",
    },
    dataAccess: {
        header: "A qué puede acceder Aks",
        title: "Claro por diseño.",
        description:
            "Aks trabaja con la información que proporcionas y con las fuentes que eliges conectar deliberadamente.",
        sourcesSection: "FUENTES CONECTADAS",
        loadingSources: "Cargando tus fuentes conectadas…",
        loadError: "No se pudieron cargar tus fuentes conectadas en este momento.",
        emptyTitle: "Aún no hay fuentes conectadas",
        emptyBody:
            "Aks no lee servicios externos hasta que los conectes explícitamente. Puedes gestionar cada conexión desde los ajustes de la cuenta.",
        connectedNeedsPermission: "Conectada · permiso necesario",
        connectedSynced: (relative: string) => `Conectada y leyendo datos · sincronizada ${relative}`,
        connectedNotSynced: "Conectada y leyendo datos · aún sin sincronizar",
        holdsSection: "LO QUE AKS CONSERVA",
        items: [
            {
                title: "La información que proporcionas",
                body: "Lo que introduces directamente en Aks, como la información del perfil y las preferencias.",
            },
            {
                title: "Reflexiones y check-ins",
                body: "Entradas que creas para describir tus experiencias, ánimo, enfoque, energía o rutinas.",
            },
            {
                title: "Datos de experimentos",
                body: "Los experimentos que creas y los resultados o notas que registras.",
            },
            {
                title: "Información de la cuenta",
                body: "Los datos básicos necesarios para identificar y gestionar tu cuenta de Aks.",
            },
            {
                title: "Fuentes de datos conectadas",
                body: "Solo información de los servicios que eliges conectar explícitamente, cuando esas conexiones están disponibles.",
            },
        ],
        controlTitle: "Tú tienes el control",
        controlBody: "Aks solo usa lo que introduces o conectas explícitamente.",
    },
    dataUsage: {
        header: "Cómo se usan tus datos",
        title: "Tus datos tienen un propósito.",
        description:
            "Aks usa tu información dentro del producto para hacer tu experiencia más pertinente y más clara.",
        sections: [
            {
                title: "Por qué Aks usa tus datos",
                body: "La información que compartes ayuda a Aks a personalizar las reflexiones, destacar temas útiles y apoyar tus objetivos.",
            },
            {
                title: "Reflexiones y check-ins",
                body: "Tus entradas pueden informar cómo cambian tu ánimo, energía, enfoque y rutinas a lo largo del tiempo.",
            },
            {
                title: "Detección de patrones",
                body: "Aks puede relacionar la información que proporcionas para destacar posibles patrones a considerar. Son invitaciones a reflexionar, no conclusiones médicas.",
            },
            {
                title: "Memoria",
                body: "Aks puede conservar algo de contexto repetido y útil. Cada recuerdo sigue vinculado a la información que lo sustenta y puede quitarse sin eliminar la fuente original.",
            },
            {
                title: "Experimentos y resultados",
                body: "Las entradas de experimentos ayudan a comparar lo que probaste y los resultados que registraste.",
            },
            {
                title: "Comprensión asistida por IA",
                body: "La IA puede ayudar a organizar y resumir la información que proporcionas. Revisa los hallazgos importantes y conserva tu propio criterio.",
            },
        ],
        privacyPolicyAction: "Leer la política de privacidad completa",
    },
    exportData: {
        header: "Exportar tus datos",
        preparingTitle: "Preparando tu exportación",
        preparingBody:
            "Estamos reuniendo tus conversaciones, reflexiones, recuerdos, patrones, experimentos y hallazgos. Suele tardar unos segundos.",
        errorTitle: "Llévate tus datos.",
        errorBody: "Hay una copia descargable de tu información de Aks disponible a petición.",
        failedTitle: "No se pudo crear tu exportación.",
        failedFallback: "Hubo un problema al preparar tu exportación. Inténtalo de nuevo.",
        retryA11y: "Reintentar la creación de la exportación",
        cancelAction: "Cancelar",
        cancelA11y: "Volver a la introducción de la exportación",
        readyTitle: "Tu exportación está lista.",
        readyBody:
            "Acabamos de preparar una instantánea de tu información de Aks. Cubre las mismas secciones que se enumeran cuando la solicitas.",
        expiresIn: (countdown: string) => `El enlace expira en ${countdown}`,
        expiresSoon: "un momento",
        saveAction: "Guardar la exportación",
        saveA11y: "Guardar la exportación",
        requestAnother: "Solicitar otra exportación",
        requestAnotherA11y: "Solicitar otra exportación",
        idleTitle: "Llévate tus datos.",
        idleBody:
            "Hay una copia descargable de tu información de Aks disponible a petición. Cada exportación es un único archivo que refleja tu cuenta en el momento de la solicitud.",
        includedSection: "QUÉ INCLUYE",
        included: [
            "Perfil y preferencias",
            "Conversaciones y mensajes",
            "Reflexiones",
            "Check-ins",
            "Señales",
            "Recuerdos y vínculos de indicios",
            "Patrones y vínculos de indicios",
            "Experimentos y observaciones",
            "Lecciones y vínculos de origen",
            "Hallazgos y referencias de origen",
        ],
        requestAction: "Solicitar la exportación de datos",
        requestA11y: "Solicitar la exportación",
    },
    deleteData: {
        header: "Eliminar tus datos",
        title: "No dejar nada atrás.",
        description:
            "Eliminar la cuenta borra de forma permanente los datos creados en Aks. También cierra tu sesión en este dispositivo.",
        warningTitle: "Esto no se puede deshacer.",
        warningBody:
            "Una vez eliminada tu cuenta, tus datos de Aks se pierden y no se pueden recuperar. Considera exportar tus datos primero si quieres una copia.",
        removedSection: "QUÉ SE ELIMINARÁ",
        removed: [
            "Conversaciones y mensajes",
            "Reflexiones",
            "Check-ins",
            "Señales derivadas",
            "Recuerdos y vínculos de indicios",
            "Patrones y vínculos de indicios",
            "Experimentos y observaciones",
            "Lecciones y vínculos de origen",
            "Hallazgos y referencias de origen",
        ],
        confirmA11y: "Confirmar que entiendes que la acción es permanente",
        confirmLabel: "Entiendo que esta acción es permanente y que se eliminarán todos mis datos de Aks.",
        deleteAction: "Eliminar mi cuenta y mis datos",
        deleteActionA11y: "Eliminar mi cuenta y mis datos",
        deletingAction: "Eliminando tu cuenta…",
        deletedTitle: "Tu cuenta se está eliminando.",
        deletedBody: "Se cerrará tu sesión mientras termina la eliminación.",
        backToSettings: "Volver a los ajustes",
        backToSettingsA11y: "Volver a los ajustes",
        keepAccount: "Conservar mi cuenta",
        keepAccountA11y: "Conservar mi cuenta",
        keepNote: "Eliminar la cuenta también borra los archivos de exportación creados para ella.",
    },
    helpHome: {
        header: "Ayuda y comentarios",
        title: "Te escuchamos.",
        description: "¿Algo no funciona, te confunde, o hay algo que sueñas que Aks hiciera?",
        supportTitle: "¿Necesitas una mano?",
        supportBody: "Nuestro equipo de soporte está para ayudarte.",
        supportAction: "Contactar con soporte",
        getHelpSection: "OBTENER AYUDA",
        faqTitle: "Preguntas frecuentes",
        faqDescription: "Encuentra rápidamente respuestas a preguntas comunes",
        reportTitle: "Informar de un problema",
        reportDescription: "Cuéntanos cuando algo no funcione",
        improveSection: "MEJORAR AKS",
        suggestTitle: "Sugerir una idea",
        suggestDescription: "Cuéntanos qué te gustaría que Aks aprendiera o hiciera",
        shareTitle: "Comparte tu experiencia",
        shareDescription: "Cuéntanos qué te gusta o qué podría mejorar",
        contactSection: "CONTACTO",
        supportEmail: "support@aks.ai",
        supportResponse: "Suele responder en 1 o 2 días laborables",
        footerVersion: "1.0.0",
    },
    faq: {
        header: "Ayuda y comentarios",
        title: "Preguntas frecuentes",
        description: "Respuestas rápidas sobre cómo funciona Aks y cómo se gestionan tus datos.",
        searchPlaceholder: "Buscar preguntas",
        clearSearch: "Borrar",
        resultsCount: (count: number) => `${count} RESULTADOS`,
        popularSection: "PREGUNTAS POPULARES",
        questionsCount: (count: number) => `${count} preguntas`,
        items: [
            {
                question: "¿Cómo descubre patrones Aks?",
                answer: "Aks busca conexiones útiles en la información y las reflexiones que eliges compartir.",
            },
            {
                question: "¿Puedo controlar los datos que usa Aks?",
                answer: "Sí. Puedes revisar tu información y gestionar los permisos disponibles desde Tus datos y Privacidad.",
            },
            {
                question: "¿Cómo funcionan los experimentos?",
                answer: "Los experimentos ayudan a probar pequeños cambios y a reflexionar sobre lo que influye en tu enfoque, energía, sueño y rutinas.",
            },
            {
                question: "¿Puedo cambiar los ajustes de notificaciones?",
                answer: "Sí. Abre Notificaciones desde la pantalla Tú para elegir cuándo puede escribierte Aks.",
            },
            {
                question: "¿Aks es un consejo médico?",
                answer: "No. Aks apoya la reflexión personal y no sustituye el asesoramiento médico o de salud mental profesional.",
            },
        ],
        emptyTitle: "Sin resultados",
        emptyBody: "Prueba con otra palabra o echa un vistazo a las preguntas de arriba.",
        clearAction: "Borrar la búsqueda",
        helpTitle: "¿Aún necesitas ayuda?",
        helpBody: "Cuéntanos qué pasa y te ayudaremos a verlo con claridad.",
        contactAction: "Contáctanos",
    },
    sendFeedback: {
        header: "Enviar un comentario",
        title: "Ayuda a dar forma a Aks.",
        description: "Comparte una idea, pide una función o cuéntanos qué ya funciona bien.",
        optionLabel: "TIPO DE COMENTARIO",
        optionHint: "Elige una",
        options: ["Idea", "Solicitud de función", "Comentario general", "Algo que me gustó"],
        initialOption: "Comentario general",
        messageLabel: "TU COMENTARIO",
        messagePlaceholder: "¿Qué haría que Aks sea más útil para ti?",
        messageHint: "Ideas, sugerencias o cosas que te hayan gustado: todo es bienvenido.",
        emailHint: "Deja tu correo solo si esperas una respuesta.",
        noteTitle: "Tu comentario importa.",
        noteBody: "Lo que compartes nos ayuda a decidir qué se convertirá Aks.",
        submit: "Enviar comentario",
        leaveMessage: "Puedes salir de esta pantalla sin enviar nada.",
    },
    reportProblem: {
        header: "Informar de un problema",
        title: "¿Qué salió mal?",
        description:
            "Cuéntanos qué pasó. Cuanto más contexto des, más fácil será entenderlo y corregirlo.",
        optionLabel: "CATEGORÍA DEL PROBLEMA",
        optionHint: "Elige una",
        options: [
            "Algo no funciona",
            "La app se cerró inesperadamente",
            "Hallazgo incorrecto",
            "Problema de datos",
            "Problema de notificaciones",
            "Otra cosa",
        ],
        messageLabel: "¿QUÉ PASÓ?",
        messagePlaceholder: "Describe qué esperabas y qué pasó en su lugar…",
        messageHint: "Si puedes, incluye los pasos que provocaron el problema.",
        emailHint: "Añade un correo solo si quieres un seguimiento.",
        noteTitle: "Gracias por ayudar a mejorar Aks.",
        noteBody: "Tu reporte hace que Aks sea más confiable para todo el mundo.",
        submit: "Enviar reporte",
        leaveMessage: "Puedes salir de esta pantalla sin enviar.",
    },
    feedbackForm: {
        selectedState: "Seleccionado",
        contactEmail: "CORREO DE CONTACTO",
        optionalMark: " OPCIONAL",
        emailPlaceholder: "tu@ejemplo.com",
        charLimit: 1000,
    },
    profilePreference: {
        saveAction: "Guardar preferencia",
        saveA11y: (title: string) => `Guardar ${title}`,
        noteCaption: "GUARDADO EN TU PERFIL",
        noteBody: "Tus elecciones se guardan en tu perfil.",
        notices: {
            unableToSave: "No se pudo guardar la preferencia",
        },
    },
    dataCategory: {
        recentSection: "RECIENTE",
        loadingA11y: (title: string) => `Cargando ${title}`,
        loadErrorTitle: "No se pudieron cargar estos datos.",
        tryAgain: "Reintentar",
        loadMore: "Cargar más",
        noteCaption: "UNA NOTA DE AKS",
        noteBody: "Tus entradas aparecerán aquí en cuanto se creen.",
    },
    bottomSheet: {
        dismissA11y: "Cerrar",
        defaultConfirm: "Entendido",
        cancel: "Cancelar",
    },
    connectedSources: {
        header: "Fuentes conectadas",
        eyebrow: "CONTEXTO Y PERMISOS",
        title: "Tú decides lo que Aks sabe.",
        description:
            "Aks funciona por completo sin ninguna fuente conectada. Cada fuente es opcional, independiente y explica exactamente qué comparte. Puedes desconectar todo en cualquier momento.",
        loadingA11y: "Cargando las fuentes",
        loadError: "No se pudieron cargar tus fuentes conectadas.",
        status: {
            connected: "Conectada",
            permissionRequired: "Permiso necesario",
            notConnected: "No conectada",
            notAvailable: "No disponible en este dispositivo",
            revoked: "Desconectada",
            temporarilyUnavailable: "Temporalmente no disponible",
            error: "No disponible en este momento",
        },
        syncedAgo: (relative: string) => `sincronizada ${relative}`,
        notSynced: "aún sin sincronizar",
        whyHelps: "CÓMO AYUDA",
        whatReceives: "LO QUE AKS RECIBE",
        whatStored: "LO QUE SE GUARDA",
        howToStop: "CÓMO DETENERLO",
        goodToKnow: "BUENO SABER",
        disconnect: "Desconectar",
        deleteData: "Eliminar los datos importados",
        allow: "Permitir",
        connect: "Conectar",
        reconnect: "Volver a conectar",
        choiceSection: "TU DECISIÓN",
        choiceBody: "Solo se usan las fuentes que conectas. Detente en cualquier momento, con un gesto.",
        confirmations: {
            cancelAction: "Cancelar",
        },
        notices: {
            providerNotConfigured: "Este proveedor aún no está configurado en esta versión.",
            unableToConnect: "No se pudo conectar esta fuente en este momento.",
        },
        groups: {
            productivity: "PRODUCTIVIDAD",
            work: "TRABAJO",
            device: "DISPOSITIVO / COMPORTAMIENTO",
        },
    },
    sources: {
        location: {
            name: "Ubicación",
            purpose:
                "Permite que Aks entienda dónde se desarrolla tu día. Eso ayuda a distinguir un día difícil de uno alterado por un viaje o un cambio inesperado.",
            receives:
                "Contexto de ubicación aproximado (zona de casa, zona de trabajo, desplazamiento, lugar desconocido) y ventanas de desplazamiento; nunca seguimiento continuo.",
            stored: "Ventanas de observación como «desplazamiento, 45 minutos, alrededor de las 18:30». Nunca se guardan coordenadas precisas.",
            stop: "Desconecta Ubicación en cualquier momento. La recopilación se detiene de inmediato; las observaciones ya guardadas pueden eliminarse por separado.",
            batteryNote:
                "Usa comprobaciones de ubicación ocasionales mientras la fuente está conectada. Activarla puede aumentar ligeramente el consumo de batería.",
        },
        calendar: {
            name: "Calendario",
            purpose:
                "Los eventos programados ayudan a Aks a distinguir un plan que cambió de una motivación en descenso.",
            receives:
                "Horarios de eventos y una categoría amplia. Títulos solo cuando definen el plan; nunca listas de invitados, notas ni enlaces de reunión.",
            stored: "Registros de eventos mínimos: horario, duración, categoría, confirmado/cancelado.",
            stop: "Desconecta Calendario en cualquier momento. La recopilación se detiene de inmediato.",
        },
        reminders: {
            name: "Tareas y recordatorios",
            purpose:
                "Lo que estaba previsto frente a lo que ocurrió realmente, sin que Aks afirme jamás que «lo dejaste caer».",
            receives: "Fechas límite y estado de completado de los recordatorios que elijas sincronizar.",
            stored: "Fecha límite y estado completado/pendiente.",
            stop: "Desconecta Tareas y recordatorios en cualquier momento.",
        },
        screenTime: {
            name: "Tiempo en pantalla",
            purpose:
                "El contexto de uso agregado del dispositivo puede iluminar cambios de enfoque; nunca se trata como prueba de distracción.",
            receives: "Tiempos de uso agregados por categoría amplia y por ventana de tiempo.",
            stored: "Ventanas agregadas como «redes sociales, 60 minutos, 21:00–22:00». Ningún dato por interacción.",
            stop: "Desconecta Tiempo en pantalla en cualquier momento.",
        },
        googleCalendar: {
            name: "Google Calendar",
            purpose:
                "Tus eventos de Google dan a Aks el mismo contexto de planificación que tu calendario del dispositivo, para las cuentas que conectes explícitamente.",
            receives:
                "Horarios de eventos y una categoría amplia de los calendarios que selecciones. Nunca listas de invitados, notas ni enlaces de reunión.",
            stored: "Registros de eventos mínimos: horario, duración, categoría, confirmado/cancelado.",
            stop: "Desconecta Google Calendar en cualquier momento y revoca el acceso en los ajustes de tu cuenta de Google.",
        },
        appleCalendar: {
            name: "Calendario de Apple",
            purpose: "En iPhone y iPad, el mismo contexto de calendario del dispositivo a través del calendario de Apple.",
            receives: "Horarios de eventos y una categoría amplia. Nunca listas de invitados, notas ni enlaces de reunión.",
            stored: "Registros de eventos mínimos: horario, duración, categoría, confirmado/cancelado.",
            stop: "Desconecta Calendario de Apple en cualquier momento.",
        },
        googleTasks: {
            name: "Google Tasks",
            purpose:
                "Tareas previstas de una cuenta de Google que conectes, para que Aks vea lo que pretendías hacer sin concluir jamás que fallaste.",
            receives: "Fechas límite y estado de completado de las tareas.",
            stored: "Fecha límite y estado completado/pendiente.",
            stop: "Desconecta Google Tasks en cualquier momento y revoca el acceso en los ajustes de tu cuenta de Google.",
        },
        appleReminders: {
            name: "Recordatorios de Apple",
            purpose:
                "En iPhone y iPad, las acciones previstas de Recordatorios de Apple alimentan el mismo contexto previsto-frente-a-realizado.",
            receives: "Fechas límite y estado de completado de los recordatorios.",
            stored: "Fecha límite y estado completado/pendiente.",
            stop: "Desconecta Recordatorios de Apple en cualquier momento.",
        },
        notion: {
            name: "Notion",
            purpose:
                "Páginas y bases de datos que compartes explícitamente con la integración de Aks, para que el contexto de trabajo nutra las conversaciones.",
            receives:
                "Títulos, horarios y una categoría amplia del contenido compartido con la integración de Notion de Aks. Nunca el cuerpo de las páginas.",
            stored: "Registros mínimos de elementos: título-categoría, horario, estado.",
            stop: "Desconecta Notion en cualquier momento y retira la integración de Aks de tu espacio de Notion.",
        },
        todoist: {
            name: "Todoist",
            purpose: "Un proveedor de tareas conectado (Todoist o similar) para que los planes externos a Aks también cuenten.",
            receives: "Fechas límite y estado de completado de las tareas.",
            stored: "Fecha límite y estado completado/pendiente.",
            stop: "Desconecta Todoist en cualquier momento y revoca el acceso en los ajustes de la cuenta del proveedor.",
        },
        github: {
            name: "GitHub",
            purpose: "Tu propia actividad de commits y PR como contexto de trabajo objetivo, nunca los datos de otras personas.",
            receives: "Recuentos y horarios de tus commits y pull requests en los repositorios que selecciones.",
            stored: "Ventanas de actividad agregadas como «2 commits, 22:00–23:00». Ningún contenido de código.",
            stop: "Desconecta GitHub en cualquier momento y revoca la app OAuth de Aks en tus ajustes de GitHub.",
        },
        slack: {
            name: "Slack",
            purpose: "Señales de bloques de enfoque y disponibilidad de los espacios que conectes explícitamente.",
            receives: "Tus propias ventanas de actividad y el estado de No molestar. Nunca el contenido de los mensajes.",
            stored: "Ventanas de actividad agregadas. Ningún mensaje, canal ni dato de compañeros.",
            stop: "Desconecta Slack en cualquier momento y retira la app de Aks de tu espacio de trabajo.",
        },
        email: {
            name: "Correo",
            purpose: "Un contexto ligero de volumen de correo (solo contadores) para los proveedores que conectes, como Gmail u otros.",
            receives: "Recuentos y horarios de los correos recibidos. Nunca asuntos, cuerpos ni remitentes.",
            stored: "Contadores agregados por ventana. Ningún contenido ni dirección.",
            stop: "Desconecta Correo en cualquier momento y revoca el acceso en los ajustes de seguridad del proveedor.",
        },
        voiceSession: {
            name: "Micrófono",
            purpose:
                "Las conversaciones de voz son una acción explícita que inicias. El micrófono solo se usa durante una sesión de voz activa.",
            receives: "Audio únicamente mientras una conversación de voz está en curso.",
            stored: "Las transcripciones que conservas; el audio no se guarda.",
            stop: "Termina la sesión de voz y el micrófono se apaga. Aks nunca escucha en segundo plano.",
        },
    },
    transparency: {
        connectedWith: (sources: string) =>
            `Has conectado: ${sources}. Aks puede ver ese contexto además de lo que compartes aquí.`,
        names: {
            location: "ubicación",
            calendar: "calendario",
            googleCalendar: "Google Calendar",
            appleCalendar: "Calendario de Apple",
            reminders: "tareas",
            googleTasks: "Google Tasks",
            appleReminders: "Recordatorios",
            todoist: "Todoist",
            notion: "Notion",
            github: "GitHub",
            slack: "Slack",
            email: "correo",
            screenTime: "tiempo en pantalla",
            voiceSession: "voz",
        },
    },
    oauth: {
        googleCalendar: "Google Calendar",
        googleTasks: "Google Tasks",
        notion: "Notion",
        todoist: "Todoist",
        github: "GitHub",
        slack: "Slack",
        email: "Correo",
    },
    errors: {
        pagedData: "No se pudieron cargar estos datos. Inténtalo de nuevo.",
        pagedDataMore: "No se pudieron cargar más datos. Inténtalo de nuevo.",
        dataSummary: "No se pudo cargar tu resumen de datos. Inténtalo de nuevo.",
        dataAccess: "No se pudieron cargar tus fuentes conectadas. Inténtalo de nuevo.",
        memory: "No se pudo cargar este recuerdo.",
        pattern: "No se pudo cargar este patrón.",
        experiment: "No se pudo cargar este experimento.",
        learning: "No se pudo cargar esta lección.",
        insight: "No se pudo cargar este hallazgo.",
        conversation: "No se pudo cargar esta conversación. Inténtalo de nuevo.",
        conversationEarlier: "No se pudieron cargar los mensajes anteriores. Inténtalo de nuevo.",
        conversationPlain: "No se pudo cargar esta conversación.",
        conversationEarlierPlain: "No se pudieron cargar los mensajes anteriores.",
        messageEmptySave: "Escribe algo antes de guardar.",
        exportLinkExpired: "El enlace de exportación expiró. Solicita una nueva.",
        renameConversation: "No se pudo renombrar esta conversación. Inténtalo de nuevo.",
        exportExpired: "El enlace de exportación expiró. Solicita una nueva.",
        exportCreate: "No se pudo crear la exportación. Inténtalo de nuevo.",
        exportDownload: "No se pudo descargar la exportación. Inténtalo de nuevo.",
        deleteAccount: "La eliminación de la cuenta no está disponible en este momento. Inténtalo más tarde.",
        preferences: "No se pudieron cargar tus preferencias.",
        appSetup: "No se pudo completar la configuración de tu cuenta. Inténtalo de nuevo.",
        exportSaveTitle: "Guardar tu exportación de Aks",
        exportClearDevice: "Los datos de tu cuenta se están eliminando, pero se necesita un nuevo intento para borrar este dispositivo.",
        shareUnavailable: "Compartir no está disponible en este dispositivo. Inténtalo de nuevo.",
        exportIncomplete: "La respuesta de la exportación estaba incompleta. Inténtalo de nuevo.",
        exportInterrupted: "La descarga se interrumpió. Inténtalo de nuevo.",
        exportGeneric: "Algo salió mal. Inténtalo de nuevo.",
        connectedSources: "No se pudieron cargar tus fuentes conectadas.",
        sourceUnavailable: "Esta fuente no está disponible en tu dispositivo.",
        sourcePermission: "Aks necesita este permiso para conectar esta fuente. Puedes intentarlo más tarde.",
        sourceConnect: "No se pudo conectar esta fuente.",
        sourceDisconnect: "No se pudo desconectar esta fuente.",
        sourceDelete: "No se pudo eliminar los datos de esta fuente.",
        oauthRecord: "No se pudo registrar esta conexión.",
        oauthDisconnect: "No se pudo desconectar esta cuenta.",
        webPage: "No se pudo cargar esta página.",
        webPageBody: "Comprueba tu conexión a Internet e inténtalo de nuevo.",
        generic: "Algo salió mal. Inténtalo de nuevo.",
        signInUnavailable: "El inicio de sesión no está disponible en este momento. Inténtalo más tarde.",
        signInStart: "No se pudo iniciar el inicio de sesión.",
        authRequest: "No se pudo completar esta solicitud. Inténtalo de nuevo.",
        storeUnreachable: "No se pudo contactar con la tienda. Comprueba tu conexión e inténtalo de nuevo.",
        plansUnavailable: "Los planes no están disponibles en este momento. Inténtalo en un momento.",
        planUnavailable: "Este plan no está disponible en este momento. Inténtalo en un momento.",
        storeFailed: "La tienda no pudo completar tu solicitud. Inténtalo de nuevo.",
        subscriptionGeneric: "Hubo un problema al procesar tu suscripción. Inténtalo de nuevo.",
        purchaseCancelled: "El pago fue cancelado. No se realizó ningún cargo.",
        purchasePending:
            "Tu compra está pendiente de confirmación por la tienda. Aparecerá aquí cuando se complete.",
        alreadySubscribed: "Ya tienes una suscripción a este plan.",
        checkoutPendingPremium:
            "El pago se completó, pero Premium aún no está activo en tu cuenta. Las compras de Test Store en emulador no activan Premium: usa un dispositivo con Play Store. De lo contrario, espera un momento y prueba Restaurar compras.",
        restoreEmpty: "No hay compras anteriores para restaurar.",
        emptyMessage: "Escribe algo antes de enviar.",
        mirror: {
            noReply: "Aks aún no ha respondido a tu último mensaje.",
            unsavedRetry: "Puede que tu último mensaje no haya terminado de guardarse. Puedes reenviarlo sin riesgo.",
            resolvePending: "Reenvía o resuelve tu mensaje anterior antes de enviar otro.",
            refreshFailed: "Aks no pudo regenerar esta respuesta. La anterior sigue visible.",
            refreshFailedConversation:
                "Aks no pudo completar esta respuesta tras varios intentos. Tu mensaje está guardado.",
            refreshFailedUnsafe: "Aks no pudo interpretar la respuesta de forma segura. Tu mensaje está guardado.",
            refreshFallback: "Aks no pudo procesar esto en este momento. Tu mensaje está guardado.",
            updateMessage: "No se pudo actualizar este mensaje. Puede que Aks ya haya respondido.",
            checkInFailed: "No se pudo guardar tu check-in. Inténtalo de nuevo.",
            saveFailed: "No se pudo guardar tu mensaje. Comprueba tu conexión e inténtalo de nuevo.",
            outboxQueued: "Guardado en este dispositivo. Aks lo enviará cuando vuelvas a estar en línea.",
            signInForVoice: "Las conversaciones de voz están disponibles después de iniciar sesión.",
            voiceStartFailed: "No se pudo iniciar la conversación de voz.",
        },
        voice: {
            realtimeNotConfigured: "Las conversaciones de voz no están configuradas en esta versión.",
            sessionUnavailable: "No se pudo iniciar una sesión de voz. Inténtalo de nuevo.",
            transportUnavailable: "Esta opción de conversación requiere una versión de desarrollo de Aks.",
            audioUnavailable: "La voz en directo requiere una versión de desarrollo con el motor de audio de Aks.",
            micDenied: "Se necesita acceso al micrófono para una conversación de voz.",
            transcriptionFailed: "Aks no pudo entender lo que dijiste. Inténtalo de nuevo.",
            providerError: "Aks no puede iniciar la conversación de voz en este momento.",
            sessionExpired: "La conversación de voz expiró. Vuelve a iniciar sesión para continuar.",
            voiceFailed: "La conversación de voz falló.",
            saveVoiceMessage: "No se pudo guardar tu mensaje de voz. Se mantendrá solo en esta sesión.",
            saveVoiceReply: "No se pudo guardar la respuesta de Aks. Se mantendrá solo en esta sesión.",
            audioCaptureFailed: "Error al capturar el audio.",
            audioFailed: "Error de audio.",
        },
        writes: {
            signInRequired: "Inicia sesión para continuar.",
            experimentInvalid: "La respuesta del experimento no era válida.",
            observation: "No se pudo registrar esta observación.",
            reflection: "No se pudo guardar esta reflexión.",
            message: "No se pudo guardar este mensaje.",
            checkIn: "No se pudo guardar este check-in.",
            insightUpdate: "No se pudo actualizar este hallazgo.",
            experimentUpdate: "No se pudo actualizar este experimento.",
            startConversation: "No se pudo iniciar esta conversación.",
            sendMessage: "No se pudo guardar tu mensaje.",
            confirmMessage: "No se pudo confirmar tu mensaje guardado.",
            searchConversations: "No se pudo buscar en tus conversaciones.",
            updateConversation: "No se pudo actualizar esta conversación.",
            updateMessage: "No se pudo actualizar este mensaje.",
            confirmUpdatedMessage: "No se pudo confirmar tu mensaje actualizado.",
            archiveConversation: "No se pudo archivar esta conversación.",
            archivePattern: "No se pudo archivar este patrón.",
            removePattern: "No se pudo eliminar este patrón.",
            archiveMemory: "No se pudo archivar este recuerdo.",
            removeMemory: "No se pudo eliminar este recuerdo.",
            archiveLearning: "No se pudo archivar esta lección.",
            removeLearning: "No se pudo eliminar esta lección.",
        },
    },
    timelineEntries: {
        patternForming: "PATRÓN EN FORMACIÓN",
        insight: "HALLAZGO",
        newLearning: "NUEVA LECCIÓN",
        outcomeRecorded: "RESULTADO REGISTRADO",
        experimentStarted: "EXPERIMENTO INICIADO",
        experimentActive: "EXPERIMENTO ACTIVO",
        reflection: "REFLEXIÓN",
        checkIn: "CHECK-IN",
        experimentOutcomeTitle: "Resultado de experimento registrado",
        reflectionTitle: "Registraste una reflexión",
    },
};

export default es;
