import type { Translation } from "@/constants/copy";
import type { DayPart } from "@/lib/dayPart";

/**
 * French translation.
 *
 * Every key of the English source of truth is required; the compiler rejects
 * missing or extra keys. Uses formal "vous" throughout, which suits a
 * reflective personal app. Proper nouns (Aks, Google, Notion, GitHub…) stay
 * as-is; "Google Calendar" uses its official French name "Google Agenda".
 * French typography notes: spaces before colons in display strings, " %"
 * after numbers, and « » guillemets in stored-data examples.
 */
const fr: Translation = {
    common: {
        back: "Retour",
        cancel: "Annuler",
        save: "Enregistrer",
        dismiss: "Fermer",
        clear: "Effacer",
        loading: "Chargement…",
        tryAgain: "Réessayer",
        loadMore: "Charger plus",
        pleaseTryAgain: "Veuillez réessayer.",
        checkConnection: "Vérifiez votre connexion et réessayez.",
        emailPlaceholder: "you@example.com",
        justNow: "à l'instant",
        dateUnavailable: "Date indisponible",
        version: (value: string) => `Version ${value}`,
    },
    brand: {
        name: "Aks.ai",
        tagline: "Se comprendre, autrement.",
    },
    splash: {
        appName: "Aks.ai",
        subtitle: "Se comprendre, autrement.",
    },
    onboarding: {
        skip: "Passer",
        moveForward: "Continuer",
        getStarted: "Commencer",
        notices: {
            unableToContinue: "Impossible de continuer",
        },
        slides: [
            {
                eyebrow: "VOTRE VIE LAISSE DES INDICES",
                title: "Vous laissez déjà\ndes indices sur vous.",
                description:
                    "Ce que vous répétez. Les moments que vous évitez. Les journées qui semblent différentes. Aks réunit ces signaux.",
            },
            {
                eyebrow: "NE PAS SEULEMENT RÉFLÉCHIR",
                title: "N'improvisez pas.\nTestez.",
                description:
                    "Transformez une intuition en petite expérience. Changez une chose, mesurez ce qui se passe, et découvrez ce qui marche vraiment pour vous.",
            },
            {
                eyebrow: "UNE IMAGE PLUS NETTE",
                title: "Devenez moins\nmystérieux pour vous-même.",
                description:
                    "Avec le temps, Aks construit une image vivante de vos schémas, de vos réactions et des changements qui font vraiment la différence.",
            },
        ],
    },
    legal: {
        termsTitle: "Conditions d'utilisation",
        privacyTitle: "Politique de confidentialité",
        acceptance: {
            title: "Avant de commencer.",
            description:
                "Aks travaille avec des informations personnelles pour vous aider à comprendre vos schémas. Voici ce qu'il faut savoir avant de continuer.",
            cardTitle: "Vos données, votre contrôle.",
            cardBody:
                "Aks utilise les informations que vous choisissez de partager pour repérer des schémas et vous aider à mener des expériences personnelles.",
            bullets: [
                "Vous décidez quelles informations fournir.",
                "Vous pouvez gérer vos données et vos autorisations.",
                "Aks ne remplace pas un avis médical ou de santé mentale professionnel.",
            ],
            agreePrefix: "J'accepte les",
            terms: "conditions d'utilisation",
            andWord: "et la",
            privacy: "politique de confidentialité",
            continue: "Continuer vers Aks",
            retryAction: "Réessayer",
            retry: "Réessayer",
            footnote: "Vous pourrez revoir ces documents plus tard dans les réglages.",
            consentA11y: "Accepter les conditions d'utilisation et la politique de confidentialité",
            notices: {
                unableToSave: "Impossible d'enregistrer l'acceptation",
            },
        },
        links: {
            prefix: "En continuant, vous acceptez les",
            terms: "conditions d'utilisation",
            andWord: "et la",
            privacy: "politique de confidentialité",
        },
    },
    login: {
        title: "Content de vous revoir.",
        description: "Connectez-vous pour continuer à découvrir ce que Aks remarque chez vous.",
        emailLabel: "Adresse e-mail",
        sendLink: "Se connecter",
        sendLinkA11y: "Envoyer le lien de connexion",
        secureLinkNote: "Nous vous envoyons un lien de connexion sécurisé par e-mail. Sans mot de passe.",
        divider: "OU CONTINUER AVEC",
        google: "Google",
        googleA11y: "Continuer avec Google",
        facebook: "Facebook",
        facebookA11y: "Continuer avec Facebook",
        github: "Continuer avec GitHub",
        githubA11y: "Continuer avec GitHub",
        noAccount: "Pas encore de compte ?",
        createOne: "Créez-en un",
        dismissError: "Touchez pour masquer.",
        notices: {
            unableToSendLink: "Impossible d'envoyer le lien de connexion",
            unableToSignIn: "Impossible de se connecter",
        },
    },
    register: {
        title: "Créez votre compte.",
        description: "Commencez à construire, avec Aks, une image plus nette de vous.",
        nameLabel: "Nom complet",
        namePlaceholder: "Votre nom complet",
        nameA11y: "Nom complet",
        emailLabel: "Adresse e-mail",
        createAccount: "Créer un compte",
        createAccountA11y: "Créer un compte avec l'e-mail",
        secureLinkNote: "Nous vous envoyons un lien de connexion sécurisé. Sans mot de passe.",
        divider: "OU S'INSCRIRE AVEC",
        google: "Google",
        googleA11y: "Continuer avec Google",
        facebook: "Facebook",
        facebookA11y: "Continuer avec Facebook",
        github: "Continuer avec GitHub",
        githubA11y: "Continuer avec GitHub",
        hasAccount: "Vous avez déjà un compte ?",
        signIn: "Se connecter",
        dismissError: "Touchez pour masquer.",
        notices: {
            unableToCreate: "Impossible de créer le compte",
            unableToSignIn: "Impossible de se connecter",
        },
    },
    emailConfirmation: {
        title: "Consultez votre e-mail.",
        body: (email: string) =>
            `Nous avons envoyé un lien de connexion sécurisé à ${email}. Ouvrez-le sur cet appareil pour continuer.`,
        resendNote: "Si vous le renvoyez, seul le lien le plus récent fonctionnera.",
        resend: "Renvoyer le lien",
        resendA11y: "Renvoyer le lien de connexion",
        editEmail: "Modifier l'e-mail",
        editEmailA11y: "Modifier l'adresse e-mail",
    },
    mirror: {
        eyebrow: "MIROIR",
        greeting: (firstName: string | null, part: DayPart = "morning") => {
            const base =
                part === "afternoon"
                    ? "Bon après-midi"
                    : part === "evening"
                        ? "Bonsoir"
                        : part === "night"
                            ? "Bonne nuit"
                            : "Bonjour";
            return `${base}${firstName ? `, ${firstName}` : ""}.`;
        },
        intro: "Je suis Aks. Commençons par quelque chose de simple.",
        understandTitle: "Que souhaitez-vous comprendre ?",
        differentHint: "Ou racontez à Aks quelque chose de complètement différent.",
        checkInEyebrow: "CHECK-IN RAPIDE",
        checkInTitle: "Comment se passe votre journée ?",
        topics: ["Focus", "Énergie", "Sommeil", "Émotions", "Routines", "Relations", "Productivité"],
        topicDraft: (topic: string) => `Je voudrais mieux comprendre : ${topic.toLowerCase()}.`,
        checks: ["Bien", "Ça va", "Chaos"],
        aksLabel: "AKS",
        errorTitle: "Quelque chose s'est mal passé.",
        retryResponse: "Régénérer la réponse",
        listening: "Écoute…",
        listeningMeta: (duration: string) => `${duration} · reste sur cet appareil`,
        stopRecordingA11y: "Arrêter l'enregistrement",
        voiceReady: "Réflexion vocale prête",
        voiceReadyHint: "Aks la transformera en réflexion écrite.",
        discardRecordingA11y: "Supprimer l'enregistrement",
        sendRecordingA11y: "Envoyer l'enregistrement",
        composerPlaceholder: "Dites à Aks ce que vous avez en tête…",
        sendMessageA11y: "Envoyer le message",
        recordVoiceA11y: "Enregistrer une réflexion vocale",
        notices: {
            micUnavailable: "Micro indisponible",
            micUnavailableBody:
                "L'accès au microphone est nécessaire pour enregistrer une réflexion vocale. Vous pouvez aussi écrire.",
            cantListen: "Impossible de démarrer l'écoute",
            cantListenBody: "Réessayez, ou écrivez ce que vous avez en tête.",
            stopRecording: "Impossible d'arrêter l'enregistrement",
            recordingFailed: "Impossible de conserver cet enregistrement",
            transcriptionNotConfigured:
                "Les réflexions vocales ne sont pas encore disponibles sur cette version. Vous pouvez écrire votre réflexion.",
            audioTooLong: "Cet enregistrement est trop long. Essayez plus court.",
            subscriptionRequired:
                "Les réflexions vocales nécessitent Aks Premium : cet enregistrement n'a donc pas été utilisé. Vous pouvez écrire à la place.",
            emptyTranscription:
                "Aks n'a rien entendu dans cet enregistrement. Vérifiez que le microphone fonctionne et réessayez.",
            unsupportedAudio: "Ce format d'enregistrement n'est pas pris en charge. Enregistrez à nouveau.",
            transcriptionUnavailable:
                "Aks ne peut pas analyser cet enregistrement pour le moment. Vous pouvez réessayer ou écrire.",
            unauthorized: "Veuillez vous connecter et réessayer.",
            recordingFailedFallback:
                "Aks n'a pas pu conserver cet enregistrement. Vous pouvez réessayer ou écrire.",
        },
    },
    mirrorBar: {
        newConversation: "Nouvelle conversation",
        composerPlaceholder: "Dites à Aks ce que vous avez en tête…",
        sendMessageA11y: "Envoyer le message",
        closeComposerA11y: "Fermer le champ de saisie",
        openKeyboardA11y: "Ouvrir le clavier",
        stopVoiceA11y: "Arrêter la conversation vocale",
        startVoiceA11y: "Démarrer la conversation vocale",
        voiceOffA11y: "Désactiver les réponses vocales",
        voiceOnA11y: "Activer les réponses vocales",
        moreOptionsA11y: "Plus d'options de conversation",
        hint: "Pas besoin d'organiser vos idées d'abord. Commencez simplement à parler.",
    },
    aiConversation: {
        greeting: (firstName: string | null) => `Salut, ${firstName ?? "toi"} 👋`,
        openingPrompts: [
            "Qu'est-ce qui vous occupe ?",
            "Comment vous sentez-vous aujourd'hui ?",
            "Y a-t-il quelque chose que vous portez depuis quelque temps ?",
            "Qu'est-ce qui prend le plus de place dans votre tête ?",
            "Voulez-vous parler de ce qui vous préoccupe ?",
            "Quelque chose que vous aimeriez enfin dire ?",
            "Qu'est-ce qui pèse le plus ces derniers temps ?",
            "Y a-t-il quelque chose que vous aimeriez dire ?",
        ],
        copyAction: "Copier",
        copiedAction: "Copié",
        copyA11y: "Copier le message",
        shareAction: "Partager",
        shareA11y: "Partager le message",
        tryAgainAction: "Réessayer",
        tryAgainA11y: "Régénérer cette réponse",
        motionReadyA11y: "Aks est prêt",
        thinking: "Réflexion…",
        thinkingDefault: "Aks réfléchit…",
        aksTag: "aks",
        youTag: "vous",
        listening: "Écoute…",
        speaking: "Aks parle…",
        loadingConversation: "Chargement de la conversation…",
        youPrefix: "Vous : ",
        errorTitle: "Quelque chose s'est mal passé.",
        retryResponse: "Régénérer la réponse",
        voicePaused: "Voix en pause.",
        editPlaceholder: "Réécrivez votre message…",
        saveAndSend: "Enregistrer et envoyer",
        saveAndSendA11y: "Enregistrer et envoyer le message modifié",
        cancelEditingA11y: "Annuler la modification",
        cancel: "Annuler",
        editMessage: "Modifier le message",
        editMessageA11y: "Modifier votre message",
    },
    timeline: {
        header: "Chronologie",
        headerCaption: "Votre parcours avec Aks, au fil du temps.",
        eyebrow: "VOTRE PARCOURS",
        title: "Votre histoire, qui s'écrit.",
        description:
            "Voyez les moments, schémas, expériences et leçons qui ont façonné votre parcours avec Aks.",
        errorTitle: "Impossible de charger votre chronologie.",
        errorBody: "Votre histoire est bien là. Réessayez dans un instant.",
        loadMoreError: "Impossible de charger la suite de votre histoire.",
        empty: {
            allTitle: "Votre histoire commence à peine.",
            allBody:
                "À mesure que vous échangez avec Aks, des moments, schémas, expériences et leçons marquants apparaîtront ici.",
            insightsTitle: "Aucun constat pour l'instant.",
            insightsBody: "Des constats utiles apparaîtront quand Aks aura réuni assez d'indices avec le temps.",
            experimentsTitle: "Aucune expérience pour l'instant.",
            experimentsBody: "Les expériences que vous lancerez apparaîtront ici.",
            checkInsTitle: "Aucun check-in pour l'instant.",
            checkInsBody: "Vos check-ins marquants apparaîtront ici.",
            decisionsTitle: "Aucune décision pour l'instant.",
            decisionsBody: "Les décisions et schémas que Aks remarque apparaîtront ici, en se précisant.",
            learningsTitle: "Aucune leçon pour l'instant.",
            learningsBody: "De nouvelles leçons apparaîtront ici, à mesure que votre histoire s'éclaircit.",
        },
    },
    you: {
        title: "Vous",
        fallbackName: "Membre Aks",
        subtitle: "Votre espace personnel",
        knowsTitle: "Ce que Aks sait",
        knowsEmpty: "Aks apprend encore à vous connaître",
        memoriesCount: (count: number) => `${count} ${count === 1 ? "souvenir" : "souvenirs"}`,
        exploringTitle: "Ce que vous explorez",
        exploringEmpty: "Choisissez votre focus",
        unnoticedTitle: "Ce que vous n'avez pas encore remarqué",
        insightsCount: (count: number) => `${count} ${count === 1 ? "constat" : "constats"} à regarder`,
        insightsEmpty: "Rien de confirmé pour l'instant",
        journeySection: "VOTRE PARCOURS",
        patternsTitle: "Schémas",
        patternsDescription: "Ce que Aks a remarqué",
        experimentsTitle: "Expériences",
        experimentsDescription: "Ce que vous testez en ce moment",
        yourDataTitle: "Vos données",
        yourDataDescription: "Consultez et gérez vos informations",
        preferencesSection: "PRÉFÉRENCES",
        notificationsTitle: "Notifications",
        notificationsDescription: "Quand Aks peut vous écrire",
        appearanceTitle: "Apparence",
        appearanceDescription: "Système · Clair · Sombre",
        privacyTitle: "Confidentialité",
        privacyDescription: "Autorisations et contrôles de confidentialité",
        supportSection: "ASSISTANCE",
        helpTitle: "Aide et commentaires",
    },
    settings: {
        header: "Réglages",
        eyebrow: "RÉGLAGES",
        title: "Votre Aks, à votre façon.",
        description: "Gérez votre compte, votre offre et les informations sur Aks.",
        accountSection: "COMPTE",
        profileTitle: "Profil",
        profileDescription: "Gérez vos informations personnelles",
        accountTitle: "Compte",
        accountDescription: "Se déconnecter ou supprimer votre compte",
        subscriptionTitle: "Abonnement",
        subscriptionDescription: "Gérez votre offre Aks et la facturation",
        preferencesSection: "PRÉFÉRENCES",
        languageTitle: "Langue",
        aboutSection: "À PROPOS",
        aboutTitle: "À propos d'Aks",
        aboutDescription: "En savoir plus sur Aks",
        termsTitle: "Conditions d'utilisation",
        privacyTitle: "Politique de confidentialité",
    },
    profile: {
        header: "Profil",
        fallbackName: "Membre Aks",
        fallbackEmail: "E-mail indisponible",
        editName: "Modifier le nom",
        editNameA11y: "Modifier le nom",
        changePhotoA11y: "Changer la photo de profil",
        photoA11y: "Photo de profil",
        photoSheetTitle: "Photo de profil",
        chooseImage: "Choisir une image",
        removePhoto: "Supprimer la photo",
        aksSection: "AKS",
        exploringTitle: "Ce que vous explorez",
        exploringEmpty: "Non défini",
        noticeTitle: "Ce que Aks doit remarquer",
        noticeEmpty: "Non défini",
        preferencesSection: "PRÉFÉRENCES",
        timezoneTitle: "Fuseau horaire",
        languageTitle: "Langue",
        accountSection: "COMPTE",
        emailTitle: "E-mail",
        emailUnavailable: "Indisponible",
        memberSince: "Membre depuis",
        memberSinceUnavailable: "Indisponible",
        signInMethod: "Méthode de connexion",
        signInMethodFallback: "E-mail",
        editNameTitle: "Modifiez votre nom",
        editNameMessage: "C'est ainsi que Aks s'adresse à vous.",
        nameA11y: "Nom complet",
        namePlaceholder: "Votre nom",
        saving: "Enregistrement…",
        saveChanges: "Enregistrer les modifications",
        fullName: "Nom complet",
        notices: {
            unableToSaveName: "Impossible d'enregistrer le profil",
            unableToUpdatePhoto: "Impossible de mettre à jour la photo",
            unableToRemovePhoto: "Impossible de supprimer la photo",
            checkConnection: "Vérifiez votre connexion et réessayez.",
            tryAgain: "Veuillez réessayer.",
        },
    },
    exploring: {
        header: "Ce que vous explorez",
        eyebrow: "PERSONNEL",
        title: "Choisissez votre focus.",
        description: "Sélectionnez les domaines que vous voulez mieux comprendre.",
        options: ["Focus", "Énergie", "Sommeil", "Humeur", "Habitudes", "Stress"],
    },
    noticeAreas: {
        header: "Ce que Aks doit remarquer",
        eyebrow: "PERSONNEL",
        title: "Guidez ce que Aks remarque.",
        description: "Choisissez les domaines que Aks doit prioriser pour repérer d'éventuels schémas.",
        options: ["Routines quotidiennes", "Changements d'énergie", "Schémas de focus", "Qualité du sommeil", "Variations d'humeur", "Résultats d'expériences"],
    },
    timezone: {
        header: "Fuseau horaire",
        eyebrow: "PRÉFÉRENCES",
        title: "Votre heure locale.",
        description: "Choisissez le fuseau horaire que Aks utilise pour la planification.",
    },
    language: {
        header: "Langue",
        eyebrow: "PRÉFÉRENCES",
        title: "Choisissez votre langue.",
        description: "Sélectionnez la langue utilisée dans tout Aks.",
        notAvailableYet: (name: string) => `${name} n'est pas encore disponible. L'anglais est utilisé jusqu'à l'arrivée de sa traduction.`,
        comingSoon: "Bientôt disponible",
    },
    appearance: {
        header: "Apparence",
        eyebrow: "VOTRE EXPÉRIENCE",
        title: "Adaptez-le à votre image.",
        description: "Choisissez l'apparence d'Aks dans toute l'application.",
        themeSection: "THÈME",
        themes: {
            systemTitle: "Système",
            systemDescription: "Suit l'apparence de votre appareil.",
            lightTitle: "Clair",
            lightDescription: "Garde Aks lumineux et net.",
            darkTitle: "Sombre",
            darkDescription: "Une expérience plus douce dans la pénombre.",
        },
        noteCaption: "UN MOT D'AKS",
        noteBody: "L'apparence ne change que l'apparence d'Aks.",
        notices: {
            unableToSave: "Impossible d'enregistrer l'apparence",
        },
    },
    account: {
        header: "Compte",
        signedInAs: "CONNECTÉ EN TANT QUE",
        emailUnavailable: "E-mail indisponible",
        signOut: "Se déconnecter",
        deleteAccount: "Supprimer le compte",
        confirmSignOutTitle: "Se déconnecter ?",
        confirmSignOutMessage: "Vous devrez vous reconnecter pour continuer à utiliser Aks.",
        confirmDeleteTitle: "Supprimer le compte ?",
        confirmDeleteMessage:
            "Cette action supprime définitivement votre compte et les données associées. Elle est irréversible.",
        notices: {
            unableToSignOut: "Impossible de se déconnecter",
            unableToDelete: "Impossible de supprimer le compte",
            deleteUnavailable:
                "La suppression du compte n'est pas disponible pour le moment. Réessayez plus tard.",
        },
    },
    about: {
        header: "À propos d'Aks",
        eyebrow: "À PROPOS",
        title: "Se comprendre, autrement.",
        description:
            "Aks vous aide à réfléchir à votre activité, à remarquer d'éventuels schémas et à mener des expériences personnelles avec plus d'intention.",
        productLabel: "Produit",
        productValue: "Aks.ai",
        versionLabel: "Version",
        versionValue: "1.0.0",
        note: "Aks soutient la réflexion personnelle et ne remplace pas un avis médical ou de santé mentale professionnel.",
    },
    subscription: {
        header: "Abonnement",
        eyebrow: "VOTRE OFFRE",
        title: "Offre Aks et facturation.",
        description:
            "Consultez votre offre et l'état de facturation. La gestion d'abonnement pourra être connectée quand la facturation sera disponible.",
        checkingPlan: "Vérification de votre offre…",
        fallbackError: "Impossible de vérifier votre offre. Veuillez réessayer.",
        currentPlan: "OFFRE ACTUELLE",
        activeBadge: "Active",
        planActive: "Votre offre est active.",
        renewsOn: (date: string) => `Renouvellement le ${date}`,
        accessUntil: (date: string) => `Accès jusqu'au ${date}`,
        autoRenewOff: "Le renouvellement automatique est désactivé.",
        billing: "FACTURATION",
        manage: "Gérer l'abonnement",
        restore: "Restaurer les achats",
        choosePlan: "CHOISIR VOTRE OFFRE",
        chooseTitle: "Passez plus de temps avec Aks.",
        chooseDescription:
            "Choisissez le rythme qui vous convient. Vous pouvez gérer ou restaurer votre abonnement à tout moment.",
        expiredWithDate: (date: string) => `Votre accès Premium a pris fin le ${date}.`,
        expiredFallback: "Votre accès Premium est terminé.",
        plansEmpty: "Aucune offre n'est affichée pour l'instant. Revenez dans un instant.",
        premiumEyebrow: "AKS PREMIUM",
        bestValue: "MEILLEURE OFFRE",
        premiumAccess: "Accès complet à Aks Premium",
        continueWith: (title: string) => `Continuer avec ${title}`,
        unavailableTitle: "Les abonnements ne sont pas encore connectés sur cet appareil.",
        unavailableBody:
            "Dès que la facturation sera disponible sur cet appareil, les offres apparaîtront ici et vous pourrez les consulter ou les gérer depuis cet écran.",
        noteCaption: "UN MOT D'AKS",
        noteBody: "Les paiements sont traités par la boutique de votre appareil.",
    },
    notifications: {
        header: "Notifications",
        eyebrow: "RESTEZ INFORMÉ",
        title: "Seulement quand c'est important.",
        description: "Choisissez quand Aks peut vous écrire. Vous pouvez modifier ces préférences à tout moment.",
        sectionMain: "NOTIFICATIONS",
        allowTitle: "Autoriser les notifications",
        allowDescription: "Suspendre ou reprendre toutes les notifications d'Aks.",
        categoriesSection: "CE QUE AKS PEUT ENVOYER",
        categories: {
            insightsTitle: "Nouveaux constats",
            insightsDescription: "Quand Aks remarque un schéma marquant.",
            experimentsTitle: "Suivi des expériences",
            experimentsDescription: "Rappels et résultats des expériences actives.",
            checkInsTitle: "Rappels de check-in",
            checkInsDescription: "Une invite douce pour faire le point sur votre journée.",
            weeklyTitle: "Réflexion hebdomadaire",
            weeklyDescription: "Un résumé de ce qui a changé dans la semaine.",
        },
        quietSection: "HEURES CALMES",
        quietTitle: "Heures calmes",
        quietDescription: "Couper les notifications de 22 h à 8 h.",
        deviceSection: "RÉGLAGES DE L'APPAREIL",
        deviceTitle: "Gérer les notifications de l'appareil",
        deviceDescription: "Ouvrez les réglages de l'appareil pour gérer les autorisations d'Aks.",
        noteCaption: "UN MOT D'AKS",
        noteBody: "Aks ne vous écrit que quand c'est important.",
    },
    yourData: {
        header: "Vos données",
        eyebrow: "VOS DONNÉES",
        title: "Ce que Aks retient.",
        description:
            "Voyez les informations que Aks a recueillies dans votre activité et dans ce que vous avez choisi de partager.",
        glanceSection: "EN UN COUP D'ŒIL",
        remembersSection: "CE QUE AKS RETIENT",
        sourcesSection: "SOURCES DE DONNÉES",
        sourcesTitle: "Sources connectées",
        sourcesUnknown: "Vérifiez quelles sources sont connectées.",
        sourcesNone: "Aucune source connectée. Disponible quand cela sera pris en charge.",
        sourcesCount: (count: number) => `${count} connectée${count === 1 ? "" : "s"} · gérez ou déconnectez à tout moment.`,
        choiceSection: "VOTRE CHOIX",
        choiceTitle: "C'est vous qui décidez de ce qui reste.",
        choiceBody: "Consultez, exportez ou supprimez vos informations à tout moment.",
        exportAction: "Exporter les données",
        deleteAction: "Supprimer les données",
        noteCaption: "UN MOT D'AKS",
        noteBody: "Vos données restent lisibles et sous votre contrôle.",
        loadingData: "Chargement du résumé des données",
        retry: "Réessayer",
    },
    reflections: {
        header: "Réflexions",
        eyebrow: "VOS RÉFLEXIONS",
        title: "Ce que vous avez partagé.",
        description: "Retrouvez les réflexions qui donnent à Aks du contexte sur vos expériences.",
        itemTitle: "Réflexion",
        emptyTitle: "Aucune réflexion pour l'instant.",
        emptyBody: "Vos réflexions apparaîtront ici dès que vous commencerez à les partager avec Aks.",
    },
    checkIns: {
        header: "Check-ins",
        eyebrow: "VOS CHECK-INS",
        title: "Des petits moments, retenus.",
        description: "Retrouvez les check-ins qui vous ont servi à noter comment les choses se passaient dans le temps.",
        itemFallback: "Check-in",
        itemTitle: (mood: string) => `Check-in : ${mood}`,
        energy: (value: number) => `Énergie ${value}`,
        focus: (value: number) => `Focus ${value}`,
        stress: (value: number) => `Stress ${value}`,
        noDetails: "Aucun détail supplémentaire",
        emptyTitle: "Aucun check-in pour l'instant.",
        emptyBody: "Vos check-ins apparaîtront ici dès que vous commencerez à en noter.",
    },
    conversations: {
        header: "Conversations",
        eyebrow: "VOS CONVERSATIONS",
        title: "Vos conversations avec Aks.",
        description:
            "Retrouvez ce que vous avez partagé, sans le mêler aux interprétations futures. La recherche porte sur les titres et sur ce qui a été dit.",
        searchA11y: "Rechercher des conversations",
        searchPlaceholder: "Rechercher vos conversations",
        clearSearch: "Effacer",
        loadingA11y: "Chargement des conversations",
        loadErrorTitle: "Impossible de charger les conversations.",
        emptyQueryTitle: "Aucune conversation correspondante.",
        emptyQueryBody: "Essayez un autre mot : Aks cherche ce que vous avez dit, pas seulement les titres.",
        emptyTitle: "Aucune conversation pour l'instant.",
        emptyBody: "Les conversations que vous démarrez avec Aks apparaîtront ici.",
        archiveHint: "Appui long pour archiver",
        loadMore: "Charger plus",
        archiveTitle: "Archiver la conversation ?",
        archiveMessage: "Elle sera masquée de votre historique actif.",
        archiveConfirm: "Archiver",
        notices: {
            unableToArchive: "Impossible d'archiver",
        },
    },
    conversationDetail: {
        fallbackTitle: "Conversation",
        renameA11y: "Renommer la conversation",
        loadingA11y: "Chargement de la conversation",
        unavailableTitle: "Conversation indisponible.",
        archivedBody: "Elle a peut-être été archivée ou supprimée.",
        renameSection: "RENOMMER LA CONVERSATION",
        titleA11y: "Titre de la conversation",
        titlePlaceholder: "Titre de la conversation",
        saveRename: "Enregistrer",
        cancelRename: "Annuler",
        cancelRenameA11y: "Annuler le renommage",
        historySection: "HISTORIQUE DE LA CONVERSATION",
        startedAt: (date: string) => `Commencée le ${date}`,
        continueMirror: "Continuer dans Miroir",
        loadEarlier: "Charger les messages précédents",
        youLabel: "Vous",
        aksLabel: "Aks",
        systemLabel: "Système",
        emptyTitle: "Aucun message pour l'instant.",
    },
    memories: {
        header: "Ce que Aks retient",
        eyebrow: "CE QUE AKS RETIENT",
        title: "Du contexte utile, soigneusement gardé.",
        description:
            "Ce que Aks a retenu d'informations répétées et étayées que vous avez partagées.",
        observationsCount: (count: number) => `${count} ${count === 1 ? "observation" : "observations"}`,
        lastNoticed: (date: string) => `Remarqué pour la dernière fois ${date}`,
        emptyTitle: "Aks apprend encore vos schémas.",
        emptyBody:
            "Du contexte répété et utile apparaîtra ici quand il y aura assez d'indices pour le retenir.",
    },
    memoryDetail: {
        header: "Souvenir",
        loadingA11y: "Chargement du souvenir",
        unavailableTitle: "Souvenir indisponible.",
        archivedFallback: "Il a peut-être été archivé ou supprimé.",
        eyebrow: "CE QUE AKS RETIENT",
        reasonTitle: "Pourquoi Aks s'en souvient",
        reasonFallback: (count: number) => `C'est apparu dans ${count} ${count === 1 ? "élément" : "éléments"} que vous avez partagé${count === 1 ? "" : "s"}.`,
        lastNoticed: (date: string) => `Remarqué pour la dernière fois ${date}`,
        evidenceSection: "INDICES",
        viewConversation: " · Voir la conversation",
        archiveAction: "Archiver le souvenir",
        removeAction: "Supprimer le souvenir",
        archiveTitle: "Archiver ce souvenir ?",
        archiveMessage:
            "Aks cessera de s'en servir maintenant. Ce que vous partagerez plus tard pourra de nouveau l'étayer. Vos conversations, réflexions et check-ins d'origine resteront intacts.",
        archiveConfirm: "Archiver",
        removeTitle: "Supprimer ce souvenir ?",
        removeMessage:
            "Cela ne supprime que le souvenir gardé par Aks. Les informations d'origine que vous avez partagées ne sont pas supprimées.",
        removeConfirm: "Supprimer",
        notices: {
            unableToArchive: "Impossible d'archiver",
            unableToRemove: "Impossible de supprimer",
        },
    },
    patterns: {
        header: "Schémas",
        eyebrow: "VOS SCHÉMAS",
        title: "Des liens qui méritent l'attention.",
        description: "Des relations possibles, ancrées dans des signaux répétés de ce que vous avez partagé.",
        observationsCount: (count: number) => `${count} observations`,
        emptyTitle: "Aucun schéma pour l'instant.",
        emptyBody: "Aks a besoin d'un peu plus de temps et d'indices pour repérer des liens utiles.",
        status: {
            possible: "Schéma possible",
            notSupported: "Non étayé",
            supported: "Étayé",
            testing: "En cours de test",
            fallback: "Candidat",
        },
    },
    patternDetail: {
        header: "Schéma",
        loadingA11y: "Chargement du schéma",
        unavailableTitle: "Schéma indisponible.",
        archivedFallback: "Il a peut-être été archivé ou supprimé.",
        reasonTitle: "Pourquoi Aks l'a remarqué",
        evidenceLine: (supporting: number, contradicting: number) =>
            `Ce lien repose sur ${supporting} ${supporting === 1 ? "observation" : "observations"} à l'appui` +
            (contradicting ? ` et ${contradicting} ${contradicting === 1 ? "observation" : "observations"} contradictoire${contradicting === 1 ? "" : "s"}` : "") +
            ".",
        confidencePending: "Niveau de confiance en cours d'évaluation",
        confidenceValue: (percent: number) => `Confiance des indices : ${percent} %`,
        firstNoticed: (date: string) => `Première remarque ${date}`,
        lastObserved: (date: string) => `Dernière observation ${date}`,
        alternativeTitle: "Une autre possibilité",
        evidenceSection: "INDICES",
        supporting: "À l'appui",
        contradicting: "Contradictoires",
        viewConversation: " · Voir la conversation",
        notReadyA11y: "Ce schéma n'est pas prêt à être testé",
        testA11y: "Tester ce schéma",
        notReady: "Pas encore prêt à tester",
        testAction: "Tester ce schéma",
        archiveAction: "Archiver le schéma",
        removeAction: "Supprimer le schéma",
        statusLabels: {
            candidate: "Candidat",
            possible: "Schéma possible",
            testing: "En cours de test",
            supported: "Étayé",
            notSupported: "Non étayé",
            archived: "Archivé",
        },
        archiveTitle: "Archiver ce schéma ?",
        archiveMessage:
            "Aks cessera d'afficher ce schéma. De futures observations pourront justifier un nouvel examen.",
        archiveConfirm: "Archiver",
        removeTitle: "Supprimer ce schéma ?",
        removeMessage:
            "Cela ne supprime que le schéma dérivé et ses liens d'indices. Vos signaux et vos informations d'origine restent en place.",
        removeConfirm: "Supprimer",
        notices: {
            unableToArchive: "Impossible d'archiver",
            unableToRemove: "Impossible de supprimer",
        },
    },
    experiments: {
        header: "Expériences",
        eyebrow: "VOS EXPÉRIENCES",
        title: "De petits tests, des indices utiles.",
        description: "Les expériences aident à tester un schéma possible sans le prendre pour un fait.",
        observationsCount: (count: number) => `${count} observations`,
        emptyTitle: "Aucune expérience pour l'instant.",
        emptyBody: "Quand un schéma mérite d'être testé, vous pourrez lancer une petite expérience autour de lui.",
        status: {
            active: "Active",
            completed: "Terminée",
            cancelled: "Annulée",
            fallback: "Brouillon",
        },
    },
    experimentSetup: {
        header: "Préparer l'expérience",
        patternSection: "SCHÉMA TESTÉ",
        titleLabel: "TITRE",
        titlePlaceholder: "Titre court de l'expérience",
        hypothesisLabel: "HYPOTHÈSE",
        hypothesisPlaceholder: "Un petit changement pourrait…",
        hypothesisDefault: "Un petit changement pourrait influencer ce que vous observez dans ce schéma.",
        descriptionLabel: "QUOI ESSAYER ET OBSERVER",
        descriptionPlaceholder: "Décrivez un petit changement et ce que vous noterez.",
        descriptionDefault:
            "Choisissez un petit changement réversible. Notez à chaque fois si le résultat vous a semblé plus facile, identique ou plus difficile.",
        durationLabel: "DURÉE",
        durationA11y: (days: number) => `Durée de ${days} jour${days === 1 ? "" : "s"}`,
        durationDays: (days: number) => `${days} j`,
        defaultTitle: (patternTitle: string) => `Test : ${patternTitle}`.slice(0, 120),
        createAction: "Créer le brouillon",
        createA11y: "Créer le brouillon d'expérience",
        createError: "Impossible de créer cette expérience. Vérifiez les détails et réessayez.",
        patternUnavailable: "Ce schéma n'est pas disponible.",
    },
    experimentDetail: {
        header: "Expérience",
        unavailableTitle: "Expérience indisponible.",
        hypothesisTitle: "Hypothèse",
        whatToTryTitle: "Quoi essayer",
        startAction: "Lancer l'expérience",
        startA11y: "Lancer l'expérience",
        removeAction: "Supprimer l'expérience",
        removeA11y: "Supprimer l'expérience",
        removeTitle: "Supprimer l'expérience ?",
        removeMessage:
            "Cela supprime l'expérience, les observations et toute leçon étayée uniquement par cette expérience. Le schéma et les signaux d'origine restent.",
        removeConfirm: "Supprimer",
        recordedFallback: "Noté",
        observationsSection: "OBSERVATIONS",
        emptyObservations: "Aucune observation enregistrée pour l'instant.",
        resultSection: "RÉSULTAT",
        analysisPending: "Analyse en attente",
        confidenceValue: (percent: number) => `Confiance des indices : ${percent} %`,
        promptTitle: "Comment cela s'est-il passé cette fois ?",
        resultEasier: "Plus facile",
        resultSame: "Identique",
        resultHarder: "Plus difficile",
        recordA11y: (result: string) => `Noter : ${result}`,
        observationPlaceholder: "Note facultative",
        observationA11y: "Note d'observation facultative",
        observationsMeta: (count: number) => `${count} observations notées`,
        observationsDay: (current: number, total: number | null) =>
            total ? ` · Jour ${current} sur ${total}` : "",
        observationsThrough: (date: string) => ` · Jusqu'au ${date}`,
        completeAction: "Terminer l'expérience",
        completeA11y: "Terminer l'expérience",
        cancelAction: "Annuler l'expérience",
        cancelA11y: "Annuler l'expérience",
        resultPendingBody: "Vos observations sont enregistrées pendant que le résultat se prépare.",
        retryAnalysis: "Relancer l'interprétation",
        retryAnalysisA11y: "Relancer l'analyse de l'expérience",
        retryLearning: "Relancer la synthèse de leçon",
        retryLearningA11y: "Relancer la synthèse de leçon",
        retryInsight: "Relancer la génération de constat",
        retryInsightA11y: "Relancer la génération de constat",
        resultLabels: {
            easier: "Plus facile",
            same: "Identique",
            harder: "Plus difficile",
        },
        outcomeLabels: {
            supports: "Étayent l'hypothèse",
            mixed: "Résultat mitigé",
            doesNotSupport: "N'étayent pas l'hypothèse",
            insufficientData: "Pas assez de données",
        },
        confirmCompleteTitle: "Terminer cette expérience ?",
        confirmCompleteMessage: "Aks résumera ce que vos observations suggèrent.",
        confirmCompleteLabel: "Terminer",
        confirmCancelTitle: "Annuler cette expérience ?",
        confirmCancelMessage: "Vos observations notées restent consultables.",
        confirmCancelLabel: "Annuler l'expérience",
        keepGoing: "Continuer",
        notices: {
            unableToUpdate: "Impossible de mettre à jour",
            unableToRecord: "Impossible de noter",
            recordRetry: "Votre essai précédent peut être repris sans risque.",
        },
    },
    learnings: {
        header: "Leçons",
        eyebrow: "VOS LEÇONS",
        title: "Ce que suggèrent les indices.",
        description:
            "Des conclusions prudentes tirées des expériences terminées et des observations notées.",
        statusRevised: "Révisée",
        statusActive: "Active",
        observationsCount: (count: number) => `${count} observations`,
        emptyTitle: "Aucune leçon pour l'instant.",
        emptyBody:
            "Quand vous aurez testé quelque chose et réuni assez d'indices, Aks pourra aider à comprendre ce qui a changé.",
    },
    learningDetail: {
        header: "Leçon",
        unavailableTitle: "Leçon indisponible.",
        evidenceTitle: "Qu'est-ce qui y a mené ?",
        evidenceLine: (experiments: number, observations: number) =>
            `Fondée sur ${experiments} ${experiments === 1 ? "expérience terminée" : "expériences terminées"} et ${observations} ${observations === 1 ? "observation enregistrée" : "observations enregistrées"}.`,
        confidenceValue: (percent: number) => `Confiance des indices : ${percent} %`,
        updatedAt: (date: string) => `Mise à jour ${date}`,
        sourceSection: "EXPÉRIENCES SOURCE",
        openExperimentA11y: (title: string) => `Ouvrir l'expérience ${title}`,
        observationsCount: (count: number) => `${count} observations`,
        archiveAction: "Archiver la leçon",
        archiveA11y: "Archiver la leçon",
        removeAction: "Supprimer la leçon",
        removeA11y: "Supprimer la leçon",
        resultLabels: {
            supports: "A étayé l'hypothèse",
            mixed: "Résultat mitigé",
            doesNotSupport: "N'a pas étayé l'hypothèse",
            insufficientData: "Pas assez de données",
        },
        archiveTitle: "Archiver cette leçon ?",
        archiveMessage: "Les expériences et observations source resteront consultables.",
        archiveConfirm: "Archiver",
        removeTitle: "Supprimer cette leçon ?",
        removeMessage:
            "Cela ne supprime que la leçon dérivée. Expériences, observations, schémas et signaux restent en place.",
        removeConfirm: "Supprimer",
        notices: {
            unableToArchive: "Impossible d'archiver",
            unableToRemove: "Impossible de supprimer",
        },
    },
    insights: {
        header: "Constats",
        eyebrow: "CONSTATS",
        title: "Quelque chose à remarquer.",
        description: "Un petit ensemble d'observations utiles, ancrées dans ce que vous avez testé et appris.",
        statusNew: "Nouveau",
        statusSeen: "Vu",
        emptyTitle: "Aucun constat pour l'instant.",
        emptyBody: "À mesure que Aks accumule des indices, des choses utiles commenceront à ressortir.",
    },
    insightDetail: {
        header: "Constat",
        eyebrow: "CONSTAT",
        unavailableTitle: "Constat indisponible.",
        reasonTitle: "Pourquoi Aks l'a remarqué",
        openExperimentA11y: (title: string) => `Ouvrir l'expérience source ${title}`,
        openLearningA11y: (title: string) => `Ouvrir la leçon source ${title}`,
        observationsCount: (count: number) => `${count} observations notées · Voir l'expérience`,
        viewLearning: "Voir la leçon source",
        confidenceValue: (percent: number) => `Confiance des indices : ${percent} %`,
        createdAt: (date: string) => `Créé ${date}`,
        dismissAction: "Écarter le constat",
        dismissA11y: "Écarter le constat",
        removeAction: "Supprimer le constat",
        removeA11y: "Supprimer le constat",
        dismissTitle: "Écarter ce constat ?",
        dismissMessage: "La leçon, l'expérience, le schéma et les indices resteront en place.",
        dismissConfirm: "Écarter",
        removeTitle: "Supprimer ce constat ?",
        removeMessage: "Cela ne supprime que le constat. Toutes les informations sources resteront.",
        removeConfirm: "Supprimer",
        notices: {
            unableToDismiss: "Impossible d'écarter",
            unableToRemove: "Impossible de supprimer",
        },
    },
    privacyHome: {
        header: "Confidentialité",
        eyebrow: "VOTRE CONFIDENTIALITÉ",
        title: "Votre vie vous appartient.",
        description:
            "Aks vous aide à vous comprendre tout en vous laissant le contrôle des informations derrière votre expérience.",
        dataSection: "VOS DONNÉES",
        knowsTitle: "Ce que Aks sait",
        knowsDescription: "Comprenez les informations qui créent votre expérience.",
        accessTitle: "Ce que Aks peut consulter",
        accessDescription: "Voyez ce que vous fournissez ou choisissez de connecter.",
        controlsSection: "CONTRÔLES DES DONNÉES",
        usageTitle: "Comment vos données sont utilisées",
        usageDescription: "Voyez comment les informations soutiennent les constats et les expériences.",
        exportTitle: "Exporter vos données",
        exportDescription: "Demander une copie de vos informations Aks.",
        deleteTitle: "Supprimer vos données",
        deleteDescription: "Lancer une demande de suppression réfléchie des données du compte.",
        legalSection: "JURIDIQUE",
        privacyPolicyTitle: "Politique de confidentialité",
        privacyPolicyDescription: "Lire la politique de confidentialité complète d'Aks.",
    },
    dataAccess: {
        header: "Ce que Aks peut consulter",
        title: "Clair dès la conception.",
        description:
            "Aks travaille avec les informations que vous fournissez et les sources que vous choisissez délibérément de connecter.",
        sourcesSection: "SOURCES CONNECTÉES",
        loadingSources: "Chargement de vos sources connectées…",
        loadError: "Impossible de charger vos sources connectées pour le moment.",
        emptyTitle: "Aucune source connectée pour l'instant",
        emptyBody:
            "Aks ne lit des services externes qu'après que vous les avez explicitement connectés. Vous pouvez gérer chaque connexion depuis les réglages du compte.",
        connectedNeedsPermission: "Connectée · autorisation nécessaire",
        connectedSynced: (relative: string) => `Connectée et lecture des données · synchronisée ${relative}`,
        connectedNotSynced: "Connectée et lecture des données · pas encore synchronisée",
        holdsSection: "CE QUE AKS DÉTIENT",
        items: [
            {
                title: "Les informations que vous fournissez",
                body: "Ce que vous saisissez directement dans Aks, comme les informations de profil et les préférences.",
            },
            {
                title: "Réflexions et check-ins",
                body: "Les entrées que vous créez pour décrire vos expériences, votre humeur, votre focus, votre énergie ou vos routines.",
            },
            {
                title: "Données d'expériences",
                body: "Les expériences que vous créez et les résultats ou notes que vous enregistrez.",
            },
            {
                title: "Informations de compte",
                body: "Les informations de base nécessaires pour identifier et gérer votre compte Aks.",
            },
            {
                title: "Sources de données connectées",
                body: "Uniquement les informations des services que vous choisissez explicitement de connecter, quand ces connexions sont disponibles.",
            },
        ],
        controlTitle: "C'est vous qui contrôlez",
        controlBody: "Aks n'utilise que ce que vous saisissez ou connectez explicitement.",
    },
    dataUsage: {
        header: "Comment vos données sont utilisées",
        title: "Vos données ont une raison d'être.",
        description:
            "Aks utilise vos informations au sein du produit pour rendre votre expérience plus pertinente et plus lisible.",
        sections: [
            {
                title: "Pourquoi Aks utilise vos données",
                body: "Les informations que vous partagez aident Aks à personnaliser les réflexions, repérer des thèmes utiles et soutenir vos objectifs.",
            },
            {
                title: "Réflexions et check-ins",
                body: "Vos entrées peuvent éclairer l'évolution de votre humeur, de votre énergie, de votre focus et de vos routines dans le temps.",
            },
            {
                title: "Détection de schémas",
                body: "Aks peut croiser les informations que vous fournissez pour faire remonter d'éventuels schémas à examiner. Ce sont des invitations à réfléchir, pas des conclusions médicales.",
            },
            {
                title: "Mémoire",
                body: "Aks peut garder un peu de contexte répété et utile. Chaque souvenir reste lié aux informations qui l'étayent et peut être retiré sans supprimer la source d'origine.",
            },
            {
                title: "Expériences et résultats",
                body: "Les entrées d'expérience aident à comparer ce que vous avez essayé et les résultats que vous avez notés.",
            },
            {
                title: "Compréhension assistée par l'IA",
                body: "L'IA peut aider à organiser et résumer les informations que vous fournissez. Relisez les constats importants et gardez votre propre jugement.",
            },
        ],
        privacyPolicyAction: "Lire la politique de confidentialité complète",
    },
    exportData: {
        header: "Exporter vos données",
        preparingTitle: "Préparation de votre export",
        preparingBody:
            "Nous rassemblons vos conversations, réflexions, souvenirs, schémas, expériences et constats. Cela prend généralement quelques secondes.",
        errorTitle: "Emportez vos données.",
        errorBody: "Une copie téléchargeable de vos informations Aks est disponible sur demande.",
        failedTitle: "Impossible de créer votre export.",
        failedFallback: "Un problème est survenu pendant la préparation de votre export. Veuillez réessayer.",
        retryA11y: "Relancer la création de l'export",
        cancelAction: "Annuler",
        cancelA11y: "Revenir à l'introduction de l'export",
        readyTitle: "Votre export est prêt.",
        readyBody:
            "Un instantané de vos informations Aks vient d'être préparé. Il couvre les mêmes sections que celles listées lors de votre demande.",
        expiresIn: (countdown: string) => `Le lien expire dans ${countdown}`,
        expiresSoon: "un instant",
        saveAction: "Enregistrer l'export",
        saveA11y: "Enregistrer l'export",
        requestAnother: "Demander un autre export",
        requestAnotherA11y: "Demander un autre export",
        idleTitle: "Emportez vos données.",
        idleBody:
            "Une copie téléchargeable de vos informations Aks est disponible sur demande. Chaque export est un fichier unique qui reflète votre compte au moment de la demande.",
        includedSection: "CE QUI EST INCLUS",
        included: [
            "Profil et préférences",
            "Conversations et messages",
            "Réflexions",
            "Check-ins",
            "Signaux",
            "Souvenirs et liens d'indices",
            "Schémas et liens d'indices",
            "Expériences et observations",
            "Leçons et liens sources",
            "Constats et références sources",
        ],
        requestAction: "Demander l'export des données",
        requestA11y: "Demander l'export",
    },
    deleteData: {
        header: "Supprimer vos données",
        title: "Ne rien laisser derrière soi.",
        description:
            "La suppression du compte efface définitivement les données créées dans Aks. Elle vous déconnecte aussi de cet appareil.",
        warningTitle: "C'est irréversible.",
        warningBody:
            "Une fois votre compte supprimé, vos données Aks sont perdues et ne peuvent pas être récupérées. Pensez à exporter vos données d'abord si vous en voulez une copie.",
        removedSection: "CE QUI SERA SUPPRIMÉ",
        removed: [
            "Conversations et messages",
            "Réflexions",
            "Check-ins",
            "Signaux dérivés",
            "Souvenirs et liens d'indices",
            "Schémas et liens d'indices",
            "Expériences et observations",
            "Leçons et liens sources",
            "Constats et références sources",
        ],
        confirmA11y: "Confirmer que vous comprenez le caractère définitif de l'action",
        confirmLabel: "Je comprends que cette action est définitive et que toutes mes données Aks seront supprimées.",
        deleteAction: "Supprimer mon compte et mes données",
        deleteActionA11y: "Supprimer mon compte et mes données",
        deletingAction: "Suppression de votre compte…",
        deletedTitle: "Votre compte est en cours de suppression.",
        deletedBody: "Vous serez déconnecté pendant que la suppression se termine.",
        backToSettings: "Retour aux réglages",
        backToSettingsA11y: "Revenir aux réglages",
        keepAccount: "Garder mon compte",
        keepAccountA11y: "Garder mon compte",
        keepNote: "La suppression du compte efface aussi les fichiers d'export créés pour ce compte.",
    },
    helpHome: {
        header: "Aide et commentaires",
        title: "Nous vous écoutons.",
        description: "Quelque chose ne fonctionne pas, vous embrouille, ou une fonctionnalité que vous rêveriez pour Aks ?",
        supportTitle: "Besoin d'un coup de main ?",
        supportBody: "Notre équipe d'assistance est là pour vous aider.",
        supportAction: "Contacter l'assistance",
        getHelpSection: "OBTENIR DE L'AIDE",
        faqTitle: "Questions fréquentes",
        faqDescription: "Trouvez vite des réponses aux questions courantes",
        reportTitle: "Signaler un problème",
        reportDescription: "Dites-nous quand quelque chose ne fonctionne pas",
        improveSection: "AMÉLIORER AKS",
        suggestTitle: "Suggérer une idée",
        suggestDescription: "Dites-nous ce que vous aimeriez que Aks apprenne ou fasse",
        shareTitle: "Partager votre expérience",
        shareDescription: "Dites-nous ce qui vous plaît ou ce qui pourrait être mieux",
        contactSection: "CONTACT",
        supportEmail: "support@aks.ai",
        supportResponse: "Répond généralement en 1 à 2 jours ouvrés",
        footerVersion: "1.0.0",
    },
    faq: {
        header: "Aide et commentaires",
        title: "Questions fréquentes",
        description: "Des réponses rapides sur le fonctionnement d'Aks et la gestion de vos données.",
        searchPlaceholder: "Rechercher des questions",
        clearSearch: "Effacer",
        resultsCount: (count: number) => `${count} RÉSULTATS`,
        popularSection: "QUESTIONS POPULAIRES",
        questionsCount: (count: number) => `${count} questions`,
        items: [
            {
                question: "Comment Aks découvre-t-il des schémas ?",
                answer: "Aks cherche des liens utiles dans les informations et réflexions que vous choisissez de partager.",
            },
            {
                question: "Puis-je contrôler les données utilisées par Aks ?",
                answer: "Oui. Vous pouvez consulter vos informations et gérer les autorisations disponibles depuis Vos données et Confidentialité.",
            },
            {
                question: "Comment fonctionnent les expériences ?",
                answer: "Les expériences aident à tester de petits changements et à réfléchir à ce qui influence votre focus, votre énergie, votre sommeil et vos routines.",
            },
            {
                question: "Puis-je modifier les réglages de notification ?",
                answer: "Oui. Ouvrez Notifications depuis la page Vous pour choisir quand Aks peut vous écrire.",
            },
            {
                question: "Aks est-il un avis médical ?",
                answer: "Non. Aks soutient la réflexion personnelle et ne remplace pas un avis médical ou de santé mentale professionnel.",
            },
        ],
        emptyTitle: "Aucun résultat",
        emptyBody: "Essayez un autre mot ou parcourez les questions ci-dessus.",
        clearAction: "Effacer la recherche",
        helpTitle: "Encore besoin d'aide ?",
        helpBody: "Dites-nous ce qui se passe et nous vous aiderons à y voir clair.",
        contactAction: "Nous contacter",
    },
    sendFeedback: {
        header: "Envoyer un commentaire",
        title: "Aidez à façonner Aks.",
        description: "Partagez une idée, demandez une fonctionnalité ou dites-nous ce qui marche déjà bien.",
        optionLabel: "TYPE DE COMMENTAIRE",
        optionHint: "Choisissez-en une",
        options: ["Idée", "Demande de fonctionnalité", "Commentaire général", "Un truc que j'ai aimé"],
        initialOption: "Commentaire général",
        messageLabel: "VOTRE COMMENTAIRE",
        messagePlaceholder: "Qu'est-ce qui rendrait Aks plus utile pour vous ?",
        messageHint: "Idées, suggestions ou choses que vous avez aimées : tout est bienvenu.",
        emailHint: "Laissez votre e-mail seulement si vous attendez une réponse.",
        noteTitle: "Votre commentaire compte.",
        noteBody: "Ce que vous partagez nous aide à décider ce que Aks deviendra.",
        submit: "Envoyer le commentaire",
        leaveMessage: "Vous pouvez quitter cette page sans rien envoyer.",
    },
    reportProblem: {
        header: "Signaler un problème",
        title: "Qu'est-ce qui s'est mal passé ?",
        description:
            "Racontez ce qui s'est passé. Plus vous donnez de contexte, plus il est facile de comprendre et de corriger.",
        optionLabel: "CATÉGORIE DU PROBLÈME",
        optionHint: "Choisissez-en une",
        options: [
            "Quelque chose ne fonctionne pas",
            "L'application a planté",
            "Constat erroné",
            "Problème de données",
            "Problème de notification",
            "Autre",
        ],
        messageLabel: "QUE S'EST-IL PASSÉ ?",
        messagePlaceholder: "Décrivez ce que vous attendiez et ce qui s'est passé à la place…",
        messageHint: "Indiquez si possible les étapes qui ont provoqué le problème.",
        emailHint: "Ajoutez un e-mail seulement si vous souhaitez un suivi.",
        noteTitle: "Merci d'aider à améliorer Aks.",
        noteBody: "Votre signalement rend Aks plus fiable pour tout le monde.",
        submit: "Envoyer le signalement",
        leaveMessage: "Vous pouvez quitter cette page sans envoyer.",
    },
    feedbackForm: {
        selectedState: "Sélectionné",
        contactEmail: "E-MAIL DE CONTACT",
        optionalMark: " FACULTATIF",
        emailPlaceholder: "you@example.com",
        charLimit: 1000,
    },
    profilePreference: {
        saveAction: "Enregistrer les préférences",
        saveA11y: (title: string) => `Enregistrer ${title}`,
        noteCaption: "ENREGISTRÉ DANS VOTRE PROFIL",
        noteBody: "Vos choix sont enregistrés dans votre profil.",
        notices: {
            unableToSave: "Impossible d'enregistrer les préférences",
        },
    },
    dataCategory: {
        recentSection: "RÉCENT",
        loadingA11y: (title: string) => `Chargement de ${title}`,
        loadErrorTitle: "Impossible de charger ces données.",
        tryAgain: "Réessayer",
        loadMore: "Charger plus",
        noteCaption: "UN MOT D'AKS",
        noteBody: "Vos entrées apparaîtront ici dès leur création.",
    },
    bottomSheet: {
        dismissA11y: "Fermer",
        defaultConfirm: "Compris",
        cancel: "Annuler",
    },
    connectedSources: {
        header: "Sources connectées",
        eyebrow: "CONTEXTE ET AUTORISATIONS",
        title: "C'est vous qui décidez de ce que Aks sait.",
        description:
            "Aks fonctionne entièrement sans aucune source connectée. Chaque source est facultative, indépendante et explique précisément ce qu'elle partage. Vous pouvez tout déconnecter à tout moment.",
        loadingA11y: "Chargement des sources",
        loadError: "Impossible de charger vos sources connectées.",
        status: {
            connected: "Connectée",
            permissionRequired: "Autorisation nécessaire",
            notConnected: "Non connectée",
            notAvailable: "Indisponible sur cet appareil",
            revoked: "Déconnectée",
            temporarilyUnavailable: "Temporairement indisponible",
            error: "Indisponible pour le moment",
        },
        syncedAgo: (relative: string) => `synchronisée ${relative}`,
        notSynced: "pas encore synchronisée",
        whyHelps: "EN QUOI C'AIDE",
        whatReceives: "CE QUE AKS REÇOIT",
        whatStored: "CE QUI EST CONSERVÉ",
        howToStop: "COMMENT ARRÊTER",
        goodToKnow: "BON À SAVOIR",
        disconnect: "Déconnecter",
        deleteData: "Supprimer les données importées",
        allow: "Autoriser",
        connect: "Connecter",
        reconnect: "Reconnecter",
        choiceSection: "VOTRE CHOIX",
        choiceBody: "Seules les sources que vous connectez sont utilisées. Arrêtez à tout moment, en un geste.",
        confirmations: {
            cancelAction: "Annuler",
        },
        notices: {
            providerNotConfigured: "Ce fournisseur n'est pas encore configuré sur cette version.",
            unableToConnect: "Impossible de connecter cette source pour le moment.",
        },
        groups: {
            productivity: "PRODUCTIVITÉ",
            work: "TRAVAIL",
            device: "APPAREIL / COMPORTEMENT",
        },
    },
    sources: {
        location: {
            name: "Localisation",
            purpose:
                "Permettez à Aks de comprendre où se passe votre journée. Cela aide à distinguer une journée difficile d'une journée bouleversée par un voyage ou un changement imprévu.",
            receives:
                "Un contexte de lieu approximatif (zone domicile, zone travail, déplacement, lieu inconnu) et des fenêtres de déplacement — jamais de suivi continu.",
            stored: "Des fenêtres d'observation comme « déplacement, 45 minutes vers 18 h 30 ». Aucune coordonnée précise n'est conservée.",
            stop: "Déconnectez la Localisation à tout moment. La collecte cesse immédiatement ; les observations déjà conservées peuvent être supprimées séparément.",
            batteryNote:
                "Utilise des vérifications de localisation occasionnelles tant que la source est connectée. L'activer peut légèrement augmenter la consommation de batterie.",
        },
        calendar: {
            name: "Calendrier",
            purpose:
                "Les événements prévus aident Aks à distinguer un plan qui a changé d'une motivation en baisse.",
            receives:
                "Les horaires d'événements et une grande catégorie. Les titres seulement s'ils définissent le plan ; jamais les listes d'invités, les notes ni les liens de réunion.",
            stored: "Des enregistrements d'événements minimaux : horaire, durée, catégorie, confirmé/annulé.",
            stop: "Déconnectez le Calendrier à tout moment. La collecte cesse immédiatement.",
        },
        reminders: {
            name: "Tâches et rappels",
            purpose:
                "Ce qui était prévu face à ce qui s'est réellement passé — sans que Aks affirme jamais que vous avez « laissé tomber ».",
            receives: "Les échéances et l'état d'accomplissement des rappels que vous choisissez de synchroniser.",
            stored: "Échéance et état terminé/non relevé.",
            stop: "Déconnectez Tâches et rappels à tout moment.",
        },
        screenTime: {
            name: "Temps d'écran",
            purpose:
                "Le contexte d'usage agrégé de l'appareil peut éclairer des variations de focus — il n'est jamais considéré comme la preuve d'une distraction.",
            receives: "Des durées d'usage agrégées par grande catégorie et par fenêtre de temps.",
            stored: "Des fenêtres agrégées comme « réseaux sociaux, 60 minutes, 21 h–22 h ». Aucune donnée par interaction.",
            stop: "Déconnectez le Temps d'écran à tout moment.",
        },
        googleCalendar: {
            name: "Google Agenda",
            purpose:
                "Vos événements Google donnent à Aks le même contexte de planification que votre calendrier d'appareil, pour les comptes que vous connectez explicitement.",
            receives:
                "Les horaires d'événements et une grande catégorie issus des calendriers que vous sélectionnez. Jamais les listes d'invités, les notes ni les liens de réunion.",
            stored: "Des enregistrements d'événements minimaux : horaire, durée, catégorie, confirmé/annulé.",
            stop: "Déconnectez Google Agenda à tout moment — et révoquez l'accès dans les réglages de votre compte Google.",
        },
        appleCalendar: {
            name: "Calendrier Apple",
            purpose: "Sur iPhone et iPad, le même contexte de calendrier d'appareil via le calendrier d'Apple.",
            receives: "Les horaires d'événements et une grande catégorie. Jamais les listes d'invités, les notes ni les liens de réunion.",
            stored: "Des enregistrements d'événements minimaux : horaire, durée, catégorie, confirmé/annulé.",
            stop: "Déconnectez le Calendrier Apple à tout moment.",
        },
        googleTasks: {
            name: "Google Tasks",
            purpose:
                "Les tâches prévues d'un compte Google que vous connectez, pour que Aks voie ce que vous aviez l'intention de faire — sans jamais conclure à un échec.",
            receives: "Les échéances et l'état d'accomplissement des tâches.",
            stored: "Échéance et état terminé/non relevé.",
            stop: "Déconnectez Google Tasks à tout moment — et révoquez l'accès dans les réglages de votre compte Google.",
        },
        appleReminders: {
            name: "Rappels Apple",
            purpose:
                "Sur iPhone et iPad, les actions prévues des Rappels Apple alimentent le même contexte prévu-versus-réalisé.",
            receives: "Les échéances et l'état d'accomplissement des rappels.",
            stored: "Échéance et état terminé/non relevé.",
            stop: "Déconnectez les Rappels Apple à tout moment.",
        },
        notion: {
            name: "Notion",
            purpose:
                "Les pages et bases de données que vous partagez explicitement avec l'intégration Aks, pour que le contexte de travail nourrisse les conversations.",
            receives:
                "Titres, horaires et une grande catégorie pour le contenu partagé avec l'intégration Notion d'Aks. Jamais le corps des pages.",
            stored: "Des enregistrements d'éléments minimaux : titre-catégorie, horaire, statut.",
            stop: "Déconnectez Notion à tout moment — et retirez l'intégration Aks de votre espace Notion.",
        },
        todoist: {
            name: "Todoist",
            purpose: "Un fournisseur de tâches connecté (Todoist ou équivalent) pour que les plans extérieurs à Aks comptent aussi.",
            receives: "Les échéances et l'état d'accomplissement des tâches.",
            stored: "Échéance et état terminé/non relevé.",
            stop: "Déconnectez Todoist à tout moment — et révoquez l'accès dans les réglages du compte du fournisseur.",
        },
        github: {
            name: "GitHub",
            purpose: "Votre propre activité de commits et de PR comme contexte de travail objectif — jamais les données d'autres personnes.",
            receives: "Le nombre et les horaires de vos commits et pull requests dans les dépôts que vous sélectionnez.",
            stored: "Des fenêtres d'activité agrégées comme « 2 commits, 22 h–23 h ». Aucun contenu de code.",
            stop: "Déconnectez GitHub à tout moment — et révoquez l'application OAuth Aks dans vos réglages GitHub.",
        },
        slack: {
            name: "Slack",
            purpose: "Des signaux de blocs de focus et de disponibilité issus des espaces que vous connectez explicitement.",
            receives: "Vos propres fenêtres d'activité et l'état Ne pas déranger. Jamais le contenu des messages.",
            stored: "Des fenêtres d'activité agrégées. Aucun message, aucun canal, aucune donnée de collègues.",
            stop: "Déconnectez Slack à tout moment — et retirez l'application Aks de votre espace de travail.",
        },
        email: {
            name: "E-mail",
            purpose: "Un contexte léger de charge e-mail (compteurs seulement) pour les fournisseurs que vous connectez — Gmail ou autres.",
            receives: "Le nombre et les horaires des e-mails reçus. Jamais les objets, les corps ni les expéditeurs.",
            stored: "Des compteurs agrégés par fenêtre. Aucun contenu, aucune adresse.",
            stop: "Déconnectez l'E-mail à tout moment — et révoquez l'accès dans les réglages de sécurité du fournisseur.",
        },
        voiceSession: {
            name: "Microphone",
            purpose:
                "Les conversations vocales sont une action explicite que vous démarrez. Le micro n'est utilisé que pendant une session vocale active.",
            receives: "De l'audio uniquement pendant qu'une conversation vocale est en cours.",
            stored: "Les transcriptions que vous conservez ; l'audio n'est pas conservé.",
            stop: "Terminez la session vocale — le micro s'éteint. Aks n'écoute jamais en arrière-plan.",
        },
    },
    transparency: {
        connectedWith: (sources: string) =>
            `Vous avez connecté : ${sources}. Aks peut donc voir ce contexte en plus de ce que vous partagez ici.`,
        names: {
            location: "localisation",
            calendar: "calendrier",
            googleCalendar: "Google Agenda",
            appleCalendar: "Calendrier Apple",
            reminders: "tâches",
            googleTasks: "Google Tasks",
            appleReminders: "Rappels Apple",
            todoist: "Todoist",
            notion: "Notion",
            github: "GitHub",
            slack: "Slack",
            email: "e-mail",
            screenTime: "temps d'écran",
            voiceSession: "voix",
        },
    },
    oauth: {
        googleCalendar: "Google Agenda",
        googleTasks: "Google Tasks",
        notion: "Notion",
        todoist: "Todoist",
        github: "GitHub",
        slack: "Slack",
        email: "E-mail",
    },
    errors: {
        pagedData: "Impossible de charger ces données. Veuillez réessayer.",
        pagedDataMore: "Impossible de charger plus de données. Veuillez réessayer.",
        dataSummary: "Impossible de charger votre résumé de données. Veuillez réessayer.",
        dataAccess: "Impossible de charger vos sources connectées. Veuillez réessayer.",
        memory: "Impossible de charger ce souvenir.",
        pattern: "Impossible de charger ce schéma.",
        experiment: "Impossible de charger cette expérience.",
        learning: "Impossible de charger cette leçon.",
        insight: "Impossible de charger ce constat.",
        conversation: "Impossible de charger cette conversation. Veuillez réessayer.",
        conversationEarlier: "Impossible de charger les messages précédents. Veuillez réessayer.",
        conversationPlain: "Impossible de charger cette conversation.",
        conversationEarlierPlain: "Impossible de charger les messages précédents.",
        messageEmptySave: "Écrivez quelque chose avant d'enregistrer.",
        exportLinkExpired: "Le lien d'export a expiré. Demandez un nouvel export.",
        renameConversation: "Impossible de renommer cette conversation. Veuillez réessayer.",
        exportExpired: "Le lien d'export a expiré. Demandez un nouvel export.",
        exportCreate: "L'export n'a pas pu être créé. Veuillez réessayer.",
        exportDownload: "L'export n'a pas pu être téléchargé. Veuillez réessayer.",
        deleteAccount: "La suppression du compte n'est pas disponible pour le moment. Réessayez plus tard.",
        preferences: "Impossible de charger vos préférences.",
        appSetup: "Impossible de terminer la configuration de votre compte. Veuillez réessayer.",
        exportSaveTitle: "Enregistrer votre export Aks",
        exportClearDevice: "Les données de votre compte sont en cours de suppression, mais un nouvel essai est nécessaire pour effacer cet appareil.",
        shareUnavailable: "Le partage n'est pas disponible sur cet appareil. Veuillez réessayer.",
        exportIncomplete: "La réponse d'export était incomplète. Veuillez réessayer.",
        exportInterrupted: "Le téléchargement a été interrompu. Veuillez réessayer.",
        exportGeneric: "Quelque chose s'est mal passé. Veuillez réessayer.",
        connectedSources: "Impossible de charger vos sources connectées.",
        sourceUnavailable: "Cette source n'est pas disponible sur votre appareil.",
        sourcePermission: "Aks a besoin de cette autorisation pour connecter cette source. Vous pourrez réessayer plus tard.",
        sourceConnect: "Impossible de connecter cette source.",
        sourceDisconnect: "Impossible de déconnecter cette source.",
        sourceDelete: "Impossible de supprimer les données de cette source.",
        oauthRecord: "Impossible d'enregistrer cette connexion.",
        oauthDisconnect: "Impossible de déconnecter ce compte.",
        webPage: "Impossible de charger cette page.",
        webPageBody: "Vérifiez votre connexion Internet et réessayez.",
        generic: "Quelque chose s'est mal passé. Veuillez réessayer.",
        signInUnavailable: "La connexion n'est pas disponible pour le moment. Réessayez plus tard.",
        signInStart: "Impossible de démarrer la connexion.",
        authRequest: "Impossible de mener cette requête à bien. Veuillez réessayer.",
        storeUnreachable: "Impossible de joindre la boutique. Vérifiez votre connexion et réessayez.",
        plansUnavailable: "Les offres ne sont pas disponibles pour le moment. Réessayez dans un instant.",
        planUnavailable: "Cette offre n'est pas disponible pour le moment. Réessayez dans un instant.",
        storeFailed: "La boutique n'a pas pu mener votre requête à bien. Veuillez réessayer.",
        subscriptionGeneric: "Un problème est survenu lors du traitement de votre abonnement. Veuillez réessayer.",
        purchaseCancelled: "Le paiement a été annulé. Rien n'a été débité.",
        purchasePending:
            "Votre achat attend la confirmation de la boutique. Il apparaîtra ici une fois terminé.",
        alreadySubscribed: "Vous avez déjà souscrit à cette offre.",
        checkoutPendingPremium:
            "Le paiement est terminé, mais Premium n'est pas encore actif sur votre compte. Les achats Test Store sur émulateur n'activent pas Premium — utilisez un appareil avec le Play Store. Sinon, attendez un instant, puis essayez Restaurer les achats.",
        restoreEmpty: "Aucun achat antérieur à restaurer.",
        emptyMessage: "Écrivez quelque chose avant d'envoyer.",
        mirror: {
            noReply: "Aks n'a pas encore répondu à votre dernier message.",
            unsavedRetry: "Votre dernier message n'a peut-être pas terminé son enregistrement. Vous pouvez le renvoyer sans risque.",
            resolvePending: "Renvoyez ou réglez votre message précédent avant d'en envoyer un autre.",
            refreshFailed: "Aks n'a pas pu régénérer cette réponse. La précédente reste affichée.",
            refreshFailedConversation:
                "Aks n'a pas pu mener cette réponse à son terme après plusieurs essais. Votre message est bien enregistré.",
            refreshFailedUnsafe: "Aks n'a pas pu interpréter la réponse sans risque. Votre message est enregistré.",
            refreshFallback: "Aks n'a pas pu traiter cela pour le moment. Votre message est enregistré.",
            updateMessage: "Impossible de mettre à jour ce message. Il a peut-être déjà reçu une réponse d'Aks.",
            checkInFailed: "Impossible d'enregistrer votre check-in. Veuillez réessayer.",
            saveFailed: "Impossible d'enregistrer votre message. Vérifiez votre connexion et réessayez.",
            outboxQueued: "Enregistré sur cet appareil. Aks l'enverra dès votre retour en ligne.",
            signInForVoice: "Les conversations vocales sont disponibles après connexion.",
            voiceStartFailed: "Impossible de démarrer la conversation vocale.",
        },
        voice: {
            realtimeNotConfigured: "Les conversations vocales ne sont pas configurées sur cette version.",
            sessionUnavailable: "Impossible de démarrer une session vocale. Veuillez réessayer.",
            transportUnavailable: "Cette option de conversation demande une version de développement d'Aks.",
            audioUnavailable: "La voix en direct demande une version de développement avec le moteur audio d'Aks.",
            micDenied: "L'accès au microphone est nécessaire pour une conversation vocale.",
            transcriptionFailed: "Aks n'a pas compris ce que vous avez dit. Veuillez réessayer.",
            providerError: "Aks ne peut pas démarrer la conversation vocale pour le moment.",
            sessionExpired: "La conversation vocale a expiré. Reconnectez-vous pour continuer.",
            voiceFailed: "La conversation vocale a échoué.",
            saveVoiceMessage: "Impossible d'enregistrer votre message vocal. Il restera propre à cette session.",
            saveVoiceReply: "Impossible d'enregistrer la réponse d'Aks. Elle restera propre à cette session.",
            audioCaptureFailed: "Échec de la capture audio.",
            audioFailed: "Échec de l'audio.",
        },
        writes: {
            signInRequired: "Veuillez vous connecter pour continuer.",
            experimentInvalid: "La réponse d'expérience était invalide.",
            observation: "Impossible d'enregistrer cette observation.",
            reflection: "Impossible d'enregistrer cette réflexion.",
            message: "Impossible d'enregistrer ce message.",
            checkIn: "Impossible d'enregistrer ce check-in.",
            insightUpdate: "Impossible de mettre à jour ce constat.",
            experimentUpdate: "Impossible de mettre à jour cette expérience.",
            startConversation: "Impossible de démarrer cette conversation.",
            sendMessage: "Impossible d'enregistrer votre message.",
            confirmMessage: "Impossible de confirmer votre message enregistré.",
            searchConversations: "Impossible de rechercher dans vos conversations.",
            updateConversation: "Impossible de mettre à jour cette conversation.",
            updateMessage: "Impossible de mettre à jour ce message.",
            confirmUpdatedMessage: "Impossible de confirmer votre message mis à jour.",
            archiveConversation: "Impossible d'archiver cette conversation.",
            archivePattern: "Impossible d'archiver ce schéma.",
            removePattern: "Impossible de supprimer ce schéma.",
            archiveMemory: "Impossible d'archiver ce souvenir.",
            removeMemory: "Impossible de supprimer ce souvenir.",
            archiveLearning: "Impossible d'archiver cette leçon.",
            removeLearning: "Impossible de supprimer cette leçon.",
        },
    },
    timelineEntries: {
        patternForming: "SCHÉMA EN FORMATION",
        insight: "CONSTAT",
        newLearning: "NOUVELLE LEÇON",
        outcomeRecorded: "RÉSULTAT NOTÉ",
        experimentStarted: "EXPÉRIENCE LANCÉE",
        experimentActive: "EXPÉRIENCE ACTIVE",
        reflection: "RÉFLEXION",
        checkIn: "CHECK-IN",
        experimentOutcomeTitle: "Résultat d'expérience noté",
        reflectionTitle: "Vous avez noté une réflexion",
    },
};

export default fr;
