import type { Translation } from "@/constants/copy";
import type { DayPart } from "@/lib/dayPart";

/**
 * Hindi translation.
 *
 * Every key of the English source of truth is required; the compiler rejects
 * missing or extra keys. Devanagari uses formal-polite "आप" throughout, which
 * suits a reflective personal app. Proper nouns (Aks, Google, Notion, GitHub…)
 * stay Latin by convention. Digits in dynamic values render via the callers'
 * existing formatters.
 */
const hi: Translation = {
    common: {
        back: "वापस",
        cancel: "रद्द करें",
        save: "सेव करें",
        dismiss: "हटाएँ",
        clear: "साफ़ करें",
        loading: "लोड हो रहा है…",
        tryAgain: "फिर कोशिश करें",
        loadMore: "और लोड करें",
        pleaseTryAgain: "कृपया फिर कोशिश करें।",
        checkConnection: "अपना कनेक्शन जाँचें और फिर कोशिश करें।",
        emailPlaceholder: "you@example.com",
        justNow: "अभी-अभी",
        dateUnavailable: "तारीख उपलब्ध नहीं",
        version: (value: string) => `वर्शन ${value}`,
    },
    brand: {
        name: "Aks.ai",
        tagline: "अपने आप को अलग नज़रिए से समझें।",
    },
    splash: {
        appName: "Aks.ai",
        subtitle: "अपने आप को अलग नज़रिए से समझें।",
    },
    onboarding: {
        skip: "छोड़ें",
        moveForward: "आगे बढ़ें",
        getStarted: "शुरू करें",
        notices: {
            unableToContinue: "आगे नहीं बढ़ा जा सका",
        },
        slides: [
            {
                eyebrow: "आपकी ज़िंदगी संकेत छोड़ती है",
                title: "आप पहले से ही\nअपने बारे में संकेत छोड़ते हैं।",
                description:
                    "जो चीज़ें आप दोहराते हैं। जो पल आप टालते हैं। जो दिन अलग महसूस होते हैं। Aks इन संकेतों को एक साथ लाता है।",
            },
            {
                eyebrow: "सिर्फ़ सोचें नहीं",
                title: "अनुमान न लगाएँ.\nपरखें।",
                description:
                    "एक अंदाज़े को छोटे प्रयोग में बदलें। एक चीज़ बदलें, जो होता है उसे मापें, और जानें कि आपके लिए असल में क्या काम करता है।",
            },
            {
                eyebrow: "एक साफ़ तस्वीर",
                title: "अपने आप के लिए\nकम रहस्य बनें।",
                description:
                    "समय के साथ Aks आपके पैटर्न, आपकी प्रतिक्रियाओं और उन बदलावों की जीवंत तस्वीर बनाता है जो असर डालते हैं।",
            },
        ],
    },
    legal: {
        termsTitle: "सेवा की शर्तें",
        privacyTitle: "गोपनीयता नीति",
        acceptance: {
            title: "शुरू करने से पहले।",
            description:
                "Aks आपके पैटर्न समझने में मदद के लिए व्यक्तिगत जानकारी के साथ काम करता है। आगे बढ़ने से पहले ये बातें जान लें।",
            cardTitle: "आपका डेटा, आपका नियंत्रण।",
            cardBody:
                "Aks आपके चुने हुए विवरण का उपयोग पैटर्न पहचानने और व्यक्तिगत प्रयोग चलाने में मदद के लिए करता है।",
            bullets: [
                "आप तय करते हैं कि कौन-सी जानकारी देनी है।",
                "आप अपना डेटा और अनुमतियाँ प्रबंधित कर सकते हैं।",
                "Aks पेशेवर चिकित्सकीय या मानसिक-स्वास्थ्य सलाह का विकल्प नहीं है।",
            ],
            agreePrefix: "मैं Aks.ai की",
            terms: "सेवा की शर्तें",
            andWord: "और",
            privacy: "गोपनीयता नीति",
            continue: "Aks पर जारी रखें",
            retryAction: "फिर कोशिश करें",
            retry: "फिर कोशिश करें",
            footnote: "आप ये दस्तावेज़ बाद में सेटिंग्स से दोबारा देख सकते हैं।",
            consentA11y: "सेवा की शर्तें और गोपनीयता नीति स्वीकार करें",
            notices: {
                unableToSave: "स्वीकृति सेव नहीं हुई",
            },
        },
        links: {
            prefix: "जारी रखने से आप Aks.ai की",
            terms: "सेवा की शर्तें",
            andWord: "और",
            privacy: "गोपनीयता नीति",
        },
    },
    login: {
        title: "वापसी पर स्वागत है।",
        description: "जारी रखने के लिए साइन इन करें और देखें कि Aks आपके बारे में क्या नोटिस करता है।",
        emailLabel: "ईमेल पता",
        sendLink: "साइन इन करें",
        sendLinkA11y: "साइन-इन लिंक भेजें",
        secureLinkNote: "हम आपको सुरक्षित साइन-इन लिंक ईमेल करेंगे। पासवर्ड की ज़रूरत नहीं।",
        divider: "या जारी रखें",
        google: "Google",
        googleA11y: "Google से जारी रखें",
        facebook: "Facebook",
        facebookA11y: "Facebook से जारी रखें",
        github: "GitHub से जारी रखें",
        githubA11y: "GitHub से जारी रखें",
        noAccount: "खाता नहीं है?",
        createOne: "बनाएँ",
        dismissError: "छिपाने के लिए टैप करें।",
        notices: {
            unableToSendLink: "साइन-इन लिंक नहीं भेजा जा सका",
            unableToSignIn: "साइन इन नहीं हो सका",
        },
    },
    register: {
        title: "अपना खाता बनाएँ।",
        description: "Aks के साथ अपनी साफ़ तस्वीर बनाना शुरू करें।",
        nameLabel: "पूरा नाम",
        namePlaceholder: "आपका पूरा नाम",
        nameA11y: "पूरा नाम",
        emailLabel: "ईमेल पता",
        createAccount: "खाता बनाएँ",
        createAccountA11y: "ईमेल से खाता बनाएँ",
        secureLinkNote: "हम आपको सुरक्षित साइन-इन लिंक भेजेंगे। पासवर्ड की ज़रूरत नहीं।",
        divider: "या इससे साइन अप करें",
        google: "Google",
        googleA11y: "Google से जारी रखें",
        facebook: "Facebook",
        facebookA11y: "Facebook से जारी रखें",
        github: "GitHub से जारी रखें",
        githubA11y: "GitHub से जारी रखें",
        hasAccount: "पहले से खाता है?",
        signIn: "साइन इन करें",
        dismissError: "छिपाने के लिए टैप करें।",
        notices: {
            unableToCreate: "खाता नहीं बनाया जा सका",
            unableToSignIn: "साइन इन नहीं हो सका",
        },
    },
    emailConfirmation: {
        title: "अपना ईमेल देखें।",
        body: (email: string) =>
            `हमने ${email} पर सुरक्षित साइन-इन लिंक भेजा है। जारी रखने के लिए इसे इसी डिवाइस पर खोलें।`,
        resendNote: "दोबारा भेजने पर केवल नवीनतम लिंक काम करेगा।",
        resend: "लिंक दोबारा भेजें",
        resendA11y: "साइन-इन लिंक दोबारा भेजें",
        editEmail: "ईमेल बदलें",
        editEmailA11y: "ईमेल पता बदलें",
    },
    mirror: {
        eyebrow: "मिरर",
        greeting: (firstName: string | null, part: DayPart = "morning") => {
            const base =
                part === "afternoon"
                    ? "शुभ दोपहर"
                    : part === "evening"
                        ? "शुभ संध्या"
                        : part === "night"
                            ? "शुभ रात्रि"
                            : "सुप्रभात";
            return `${base}${firstName ? `, ${firstName}` : ""}।`;
        },
        intro: "मैं Aks हूँ। चलिए किसी छोटी चीज़ से शुरू करें।",
        understandTitle: "आप क्या समझना चाहेंगे?",
        differentHint: "या Aks को कुछ बिल्कुल अलग बताएँ।",
        checkInEyebrow: "क्विक चेक-इन",
        checkInTitle: "आज कैसा लग रहा है?",
        topics: ["ध्यान", "ऊर्जा", "नींद", "भावनाएँ", "दिनचर्या", "रिश्ते", "उत्पादकता"],
        topicDraft: (topic: string) => `मैं अपनी ${topic} को समझना चाहूँगा।`,
        checks: ["अच्छा", "ठीक-ठाक", "अव्यवस्थित"],
        aksLabel: "AKS",
        errorTitle: "कुछ ग़लत हो गया।",
        retryResponse: "जवाब फिर से लाएँ",
        listening: "सुन रहा है…",
        listeningMeta: (duration: string) => `${duration} · इसी डिवाइस पर रहता है`,
        stopRecordingA11y: "रिकॉर्डिंग रोकें",
        voiceReady: "वॉइस रिफ़्लेक्शन तैयार",
        voiceReadyHint: "Aks इसे लिखकर एक रिफ़्लेक्शन बनाएगा।",
        discardRecordingA11y: "रिकॉर्डिंग हटाएँ",
        sendRecordingA11y: "रिकॉर्डिंग भेजें",
        composerPlaceholder: "Aks को बताएँ मन में क्या है…",
        sendMessageA11y: "संदेश भेजें",
        recordVoiceA11y: "वॉइस रिफ़्लेक्शन रिकॉर्ड करें",
        notices: {
            micUnavailable: "माइक्रोफ़ोन उपलब्ध नहीं",
            micUnavailableBody:
                "वॉइस रिफ़्लेक्शन रिकॉर्ड करने के लिए माइक्रोफ़ोन की अनुमति चाहिए। आप टाइप करके भी बता सकते हैं।",
            cantListen: "सुनना शुरू नहीं हो सका",
            cantListenBody: "कृपया फिर कोशिश करें, या टाइप करके बताएँ मन में क्या है।",
            stopRecording: "रिकॉर्डिंग रोकी नहीं जा सकी",
            recordingFailed: "वह रिकॉर्डिंग सेव नहीं हुई",
            transcriptionNotConfigured:
                "इस बिल्ड में वॉइस रिफ़्लेक्शन अभी उपलब्ध नहीं हैं। आप टाइप करके रिफ़्लेक्शन दे सकते हैं।",
            audioTooLong: "यह रिकॉर्डिंग बहुत लंबी है। छोटी रिकॉर्डिंग आज़माएँ।",
            subscriptionRequired:
                "वॉइस रिफ़्लेक्शन के लिए Aks Premium चाहिए, इसलिए यह रिकॉर्डिंग इस्तेमाल नहीं हुई। आप टाइप करके भी बता सकते हैं।",
            emptyTranscription:
                "Aks को उस रिकॉर्डिंग में कुछ सुनाई नहीं दिया। जाँचें कि माइक्रोफ़ोन काम कर रहा है और फिर कोशिश करें।",
            unsupportedAudio: "वह रिकॉर्डिंग फ़ॉर्मैट समर्थित नहीं है। दोबारा रिकॉर्ड करें।",
            transcriptionUnavailable:
                "Aks उस रिकॉर्डिंग को अभी सुन नहीं सका। आप फिर कोशिश कर सकते हैं या टाइप कर सकते हैं।",
            unauthorized: "कृपया साइन इन करके फिर कोशिश करें।",
            recordingFailedFallback:
                "Aks वह रिकॉर्डिंग अभी सेव नहीं कर सका। आप फिर कोशिश कर सकते हैं या टाइप कर सकते हैं।",
        },
    },
    mirrorBar: {
        newConversation: "नई बातचीत",
        composerPlaceholder: "Aks को बताएँ मन में क्या है…",
        sendMessageA11y: "संदेश भेजें",
        closeComposerA11y: "कंपोज़र बंद करें",
        openKeyboardA11y: "कीबोर्ड खोलें",
        stopVoiceA11y: "वॉइस बातचीत रोकें",
        startVoiceA11y: "वॉइस बातचीत शुरू करें",
        voiceOffA11y: "बोलकर जवाब बंद करें",
        voiceOnA11y: "बोलकर जवाब चालू करें",
        moreOptionsA11y: "और बातचीत विकल्प",
        hint: "पहले विचारों को व्यवस्थित करने की ज़रूरत नहीं। बस बोलना शुरू करें।",
    },
    aiConversation: {
        greeting: (firstName: string | null) => `अरे, ${firstName ?? "दोस्त"} 👋`,
        openingPrompts: [
            "क्या चल रहा है मन में?",
            "आज कैसा महसूस हो रहा है?",
            "क्या कोई बात है जो आप दिन भर लिए घूम रहे हैं?",
            "आपके दिमाग़ में क्या सबसे ज़्यादा घर कर रहा है?",
            "परेशान करने वाली बात के बारे में बात करना चाहेंगे?",
            "कोई बात जो दिल से निकालनी हो?",
            "हाल के दिनों में क्या सबसे भारी लग रहा है?",
            "क्या कोई बात है जो आप कहना चाहते हैं?",
        ],
        copyAction: "कॉपी करें",
        copiedAction: "कॉपी हो गया",
        copyA11y: "संदेश कॉपी करें",
        shareAction: "साझा करें",
        shareA11y: "संदेश साझा करें",
        tryAgainAction: "फिर कोशिश करें",
        tryAgainA11y: "यह जवाब दोबारा लाएँ",
        motionReadyA11y: "Aks तैयार है",
        thinking: "सोच रहा है…",
        thinkingDefault: "Aks सोच रहा है…",
        aksTag: "aks",
        youTag: "आप",
        listening: "सुन रहा है…",
        speaking: "बोल रहा है…",
        loadingConversation: "बातचीत लोड हो रही है…",
        youPrefix: "आप: ",
        errorTitle: "कुछ ग़लत हो गया।",
        retryResponse: "जवाब फिर से लाएँ",
        voicePaused: "वॉइस रुका हुआ है।",
        editPlaceholder: "अपना संदेश दोबारा लिखें…",
        saveAndSend: "सेव करके भेजें",
        saveAndSendA11y: "संपादित संदेश सेव करके भेजें",
        cancelEditingA11y: "संपादन रद्द करें",
        cancel: "रद्द करें",
        editMessage: "संदेश संपादित करें",
        editMessageA11y: "अपना संदेश संपादित करें",
    },
    timeline: {
        header: "टाइमलाइन",
        headerCaption: "Aks के साथ आपकी यात्रा, समय के साथ।",
        eyebrow: "आपकी यात्रा",
        title: "आपकी कहानी, जैसे-जैसे बनती है।",
        description:
            "वे पल, पैटर्न, प्रयोग और सीख देखें जिन्होंने Aks के साथ आपकी यात्रा रूप दी।",
        errorTitle: "आपकी टाइमलाइन लोड नहीं हुई।",
        errorBody: "आपकी कहानी यहीं है। थोड़ी देर में फिर कोशिश करें।",
        loadMoreError: "आपकी कहानी का और हिस्सा लोड नहीं हुआ।",
        empty: {
            allTitle: "आपकी कहानी अभी बन रही है।",
            allBody:
                "जैसे-जैसे आप Aks से बात करेंगे, मायने रखने वाले पल, पैटर्न, प्रयोग और सीख यहाँ दिखाई देंगी।",
            insightsTitle: "अभी कोई अंतर्दृष्टि नहीं।",
            insightsBody: "समय के साथ जब Aks के पास पर्याप्त सबूत होंगे, अर्थपूर्ण अंतर्दृष्टि यहाँ दिखेंगी।",
            experimentsTitle: "अभी कोई प्रयोग नहीं।",
            experimentsBody: "जैसे ही आप प्रयोग सेट करेंगे, वे यहाँ दिखाई देंगे।",
            checkInsTitle: "अभी कोई चेक-इन नहीं।",
            checkInsBody: "आपके मायने रखने वाले चेक-इन यहाँ दिखेंगे।",
            decisionsTitle: "अभी कोई निर्णय नहीं।",
            decisionsBody: "जैसे-जैसे बनेंगे, निर्णय और पैटर्न यहाँ दिखेंगे।",
            learningsTitle: "अभी कोई सीख नहीं।",
            learningsBody: "जैसे-जैसे आपकी कहानी साफ़ होगी, नई सीख यहाँ दिखेगी।",
        },
    },
    you: {
        title: "आप",
        fallbackName: "Aks सदस्य",
        subtitle: "आपकी व्यक्तिगत जगह",
        knowsTitle: "Aks क्या जानता है",
        knowsEmpty: "अभी आपको जान रहा है",
        memoriesCount: (count: number) => `${count} ${count === 1 ? "स्मृति" : "स्मृतियाँ"}`,
        exploringTitle: "आप क्या जानने की कोशिश कर रहे हैं",
        exploringEmpty: "अपना ध्यान चुनें",
        unnoticedTitle: "जो आपने अभी नोटिस नहीं किया",
        insightsCount: (count: number) => `${count} ${count === 1 ? "अंतर्दृष्टि" : "अंतर्दृष्टियाँ"} देखने लायक`,
        insightsEmpty: "अभी कुछ तय नहीं हुआ",
        journeySection: "आपकी यात्रा",
        patternsTitle: "पैटर्न",
        patternsDescription: "जो Aks ने नोटिस किया",
        experimentsTitle: "प्रयोग",
        experimentsDescription: "आप अभी क्या परख रहे हैं",
        yourDataTitle: "आपका डेटा",
        yourDataDescription: "अपनी जानकारी देखें और प्रबंधित करें",
        preferencesSection: "प्राथमिकताएँ",
        notificationsTitle: "सूचनाएँ",
        notificationsDescription: "Aks कब संपर्क करे",
        appearanceTitle: "रूप-रंग",
        appearanceDescription: "सिस्टम · लाइट · डार्क",
        privacyTitle: "गोपनीयता",
        privacyDescription: "अनुमतियाँ और गोपनीयता नियंत्रण",
        supportSection: "सहायता",
        helpTitle: "सहायता और सुझाव",
    },
    settings: {
        header: "सेटिंग्स",
        eyebrow: "सेटिंग्स",
        title: "आपका Aks, आपके तरीके से।",
        description: "अपना खाता, प्लान और Aks के बारे में जानकारी प्रबंधित करें।",
        accountSection: "खाता",
        profileTitle: "प्रोफ़ाइल",
        profileDescription: "अपनी व्यक्तिगत जानकारी प्रबंधित करें",
        accountTitle: "खाता",
        accountDescription: "साइन आउट करें या खाता हटाएँ",
        subscriptionTitle: "सदस्यता",
        subscriptionDescription: "अपना Aks प्लान और बिलिंग प्रबंधित करें",
        preferencesSection: "प्राथमिकताएँ",
        languageTitle: "भाषा",
        aboutSection: "बारे में",
        aboutTitle: "Aks के बारे में",
        aboutDescription: "Aks के बारे में और जानें",
        termsTitle: "सेवा की शर्तें",
        privacyTitle: "गोपनीयता नीति",
    },
    profile: {
        header: "प्रोफ़ाइल",
        fallbackName: "Aks सदस्य",
        fallbackEmail: "ईमेल उपलब्ध नहीं",
        editName: "नाम बदलें",
        editNameA11y: "नाम बदलें",
        changePhotoA11y: "प्रोफ़ाइल फ़ोटो बदलें",
        photoA11y: "प्रोफ़ाइल फ़ोटो",
        photoSheetTitle: "प्रोफ़ाइल फ़ोटो",
        chooseImage: "इमेज चुनें",
        removePhoto: "फ़ोटो हटाएँ",
        aksSection: "AKS",
        exploringTitle: "आप क्या जानने की कोशिश कर रहे हैं",
        exploringEmpty: "सेट नहीं",
        noticeTitle: "Aks क्या नोटिस करे",
        noticeEmpty: "सेट नहीं",
        preferencesSection: "प्राथमिकताएँ",
        timezoneTitle: "समय क्षेत्र",
        languageTitle: "भाषा",
        accountSection: "खाता",
        emailTitle: "ईमेल",
        emailUnavailable: "उपलब्ध नहीं",
        memberSince: "सदस्य तब से",
        memberSinceUnavailable: "उपलब्ध नहीं",
        signInMethod: "साइन-इन तरीका",
        signInMethodFallback: "ईमेल",
        editNameTitle: "अपना नाम बदलें",
        editNameMessage: "Aks आपको इसी नाम से संबोधित करेगा।",
        nameA11y: "पूरा नाम",
        namePlaceholder: "आपका नाम",
        saving: "सेव हो रहा है…",
        saveChanges: "बदलाव सेव करें",
        fullName: "पूरा नाम",
        notices: {
            unableToSaveName: "प्रोफ़ाइल सेव नहीं हुई",
            unableToUpdatePhoto: "फ़ोटो अपडेट नहीं हुई",
            unableToRemovePhoto: "फ़ोटो नहीं हटी",
            checkConnection: "अपना कनेक्शन जाँचें और फिर कोशिश करें।",
            tryAgain: "कृपया फिर कोशिश करें।",
        },
    },
    exploring: {
        header: "आप क्या जानने की कोशिश कर रहे हैं",
        eyebrow: "व्यक्तिगत",
        title: "अपना ध्यान चुनें।",
        description: "वे क्षेत्र चुनें जिन्हें आप अधिक साफ़ रूप से समझना चाहते हैं।",
        options: ["ध्यान", "ऊर्जा", "नींद", "मनोदशा", "आदतें", "तनाव"],
    },
    noticeAreas: {
        header: "Aks क्या नोटिस करे",
        eyebrow: "व्यक्तिगत",
        title: "बताएँ Aks क्या नोटिस करे।",
        description: "वे क्षेत्र चुनें जिन्हें Aks संभावित पैटर्न ढूँढते समय प्राथमिकता दे।",
        options: ["दैनिक दिनचर्या", "ऊर्जा में बदलाव", "ध्यान के पैटर्न", "नींद की गुणवत्ता", "मनोदशा में उतार-चढ़ाव", "प्रयोग के परिणाम"],
    },
    timezone: {
        header: "समय क्षेत्र",
        eyebrow: "प्राथमिकताएँ",
        title: "आपका स्थानीय समय।",
        description: "वह समय क्षेत्र चुनें जिसका उपयोग Aks शेड्यूलिंग के लिए करे।",
    },
    language: {
        header: "भाषा",
        eyebrow: "प्राथमिकताएँ",
        title: "अपनी भाषा चुनें।",
        description: "पूरे Aks में इस्तेमाल होने वाली भाषा चुनें।",
        notAvailableYet: (name: string) => `${name} अभी उपलब्ध नहीं है। इसका अनुवाद आने तक अंग्रेज़ी उपयोग होगी।`,
        comingSoon: "जल्द आ रही है",
    },
    appearance: {
        header: "रूप-रंग",
        eyebrow: "आपका अनुभव",
        title: "इसे अपना सा महसूस कराएँ।",
        description: "चुनें कि Aks पूरे ऐप में कैसा दिखे।",
        themeSection: "थीम",
        themes: {
            systemTitle: "सिस्टम",
            systemDescription: "डिवाइस के रूप का पालन करें।",
            lightTitle: "लाइट",
            lightDescription: "Aks को चमकदार और साफ़ रखें।",
            darkTitle: "डार्क",
            darkDescription: "कम रोशनी में नरम अनुभव।",
        },
        noteCaption: "AKS की ओर से एक बात",
        noteBody: "रूप-रंग सिर्फ़ दिखावट बदलता है।",
        notices: {
            unableToSave: "रूप-रंग सेव नहीं हुआ",
        },
    },
    account: {
        header: "खाता",
        signedInAs: "इस रूप में साइन इन",
        emailUnavailable: "ईमेल उपलब्ध नहीं",
        signOut: "साइन आउट करें",
        deleteAccount: "खाता हटाएँ",
        confirmSignOutTitle: "साइन आउट करें?",
        confirmSignOutMessage: "Aks जारी रखने के लिए आपको दोबारा साइन इन करना होगा।",
        confirmDeleteTitle: "खाता हटाएँ?",
        confirmDeleteMessage:
            "इससे आपका खाता और उससे जुड़ा डेटा हमेशा के लिए हट जाएगा। इसे पूर्ववत नहीं किया जा सकता।",
        notices: {
            unableToSignOut: "साइन आउट नहीं हो सका",
            unableToDelete: "खाता नहीं हटाया जा सका",
            deleteUnavailable:
                "खाता हटाना अभी उपलब्ध नहीं है। कृपया थोड़ी देर बाद कोशिश करें।",
        },
    },
    about: {
        header: "Aks के बारे में",
        eyebrow: "बारे में",
        title: "अपने आप को अलग नज़रिए से समझें।",
        description:
            "Aks आपकी गतिविधि पर चिंतन करने, संभावित पैटर्न नोटिस करने और अधिक जानबूझकर व्यक्तिगत प्रयोग चलाने में मदद करता है।",
        productLabel: "प्रोडक्ट",
        productValue: "Aks.ai",
        versionLabel: "वर्शन",
        versionValue: "1.0.0",
        note: "Aks व्यक्तिगत चिंतन में सहायता करता है और पेशेवर चिकित्सकीय या मानसिक-स्वास्थ्य सलाह का विकल्प नहीं है।",
    },
    subscription: {
        header: "सदस्यता",
        eyebrow: "आपका प्लान",
        title: "Aks प्लान और बिलिंग।",
        description:
            "अपना मौजूदा प्लान और बिलिंग स्थिति देखें। बिलिंग उपलब्ध होने पर सदस्यता प्रबंधन जुड़ सकता है।",
        checkingPlan: "आपका प्लान जाँचा जा रहा है…",
        fallbackError: "हम आपका प्लान जाँच नहीं सके। कृपया फिर कोशिश करें।",
        currentPlan: "मौजूदा प्लान",
        activeBadge: "सक्रिय",
        planActive: "आपका प्लान सक्रिय है।",
        renewsOn: (date: string) => `${date} को नवीनीकरण`,
        accessUntil: (date: string) => `${date} तक एक्सेस`,
        autoRenewOff: "ऑटो-रिन्यूअल बंद है।",
        billing: "बिलिंग",
        manage: "सदस्यता प्रबंधित करें",
        restore: "खरीदारी पुनर्स्थापित करें",
        choosePlan: "अपना प्लान चुनें",
        chooseTitle: "Aks के साथ और समय बिताएँ।",
        chooseDescription:
            "वह लय चुनें जो आपको ठीक लगे। आप अपनी सदस्यता कभी भी प्रबंधित या पुनर्स्थापित कर सकते हैं।",
        expiredWithDate: (date: string) => `आपकी Premium एक्सेस ${date} को समाप्त हुई।`,
        expiredFallback: "आपकी Premium एक्सेस समाप्त हो गई है।",
        plansEmpty: "प्लान अभी सूचीबद्ध नहीं हैं। कृपया थोड़ी देर बाद देखें।",
        premiumEyebrow: "AKS PREMIUM",
        bestValue: "सबसे उपयुक्त",
        premiumAccess: "Aks Premium की पूरी एक्सेस",
        continueWith: (title: string) => `${title} के साथ जारी रखें`,
        unavailableTitle: "इस डिवाइस पर सदस्यताएँ अभी जुड़ी नहीं हैं।",
        unavailableBody:
            "इस डिवाइस पर बिलिंग उपलब्ध होते ही प्लान यहाँ दिखेंगे और आप इसी स्क्रीन से उन्हें देख या प्रबंधित कर सकेंगे।",
        noteCaption: "AKS की ओर से एक बात",
        noteBody: "भुगतान आपके डिवाइस के स्टोर द्वारा संभाले जाते हैं।",
    },
    notifications: {
        header: "सूचनाएँ",
        eyebrow: "ज़रूरी बातों के लिए",
        title: "सिर्फ़ ज़रूरी समय पर।",
        description: "चुनें कि Aks कब संपर्क कर सके। आप ये प्राथमिकताएँ कभी भी बदल सकते हैं।",
        sectionMain: "सूचनाएँ",
        allowTitle: "सूचनाओं की अनुमति दें",
        allowDescription: "सभी Aks सूचनाएँ रोकें या फिर से चालू करें।",
        categoriesSection: "AKS क्या भेज सकता है",
        categories: {
            insightsTitle: "नई अंतर्दृष्टि",
            insightsDescription: "जब Aks कोई मायने रखने वाला पैटर्न नोटिस करे।",
            experimentsTitle: "प्रयोग अपडेट",
            experimentsDescription: "सक्रिय प्रयोगों के रिमाइंडर और परिणाम।",
            checkInsTitle: "चेक-इन रिमाइंडर",
            checkInsDescription: "अपने दिन पर चिंतन के लिए एक सौम्य संकेत।",
            weeklyTitle: "साप्ताहिक चिंतन",
            weeklyDescription: "सप्ताह में क्या बदला, उसका सार।",
        },
        quietSection: "शांत घंटे",
        quietTitle: "शांत घंटे",
        quietDescription: "रात 10:00 से सुबह 8:00 तक सूचनाएँ बंद रखें।",
        deviceSection: "डिवाइस सेटिंग्स",
        deviceTitle: "डिवाइस की सूचनाएँ प्रबंधित करें",
        deviceDescription: "Aks की अनुमतियाँ प्रबंधित करने के लिए डिवाइस सेटिंग्स खोलें।",
        noteCaption: "AKS की ओर से एक बात",
        noteBody: "Aks तभी संपर्क करता है जब बात मायने रखती है।",
    },
    yourData: {
        header: "आपका डेटा",
        eyebrow: "आपका डेटा",
        title: "Aks क्या याद रखता है।",
        description:
            "देखें कि Aks ने आपकी गतिविधि और आपके द्वारा साझा की गई चीज़ों से क्या जानकारी इकट्ठा की है।",
        glanceSection: "एक नज़र में",
        remembersSection: "AKS क्या याद रखता है",
        sourcesSection: "डेटा स्रोत",
        sourcesTitle: "जुड़े स्रोत",
        sourcesUnknown: "देखें कौन-से स्रोत जुड़े हैं।",
        sourcesNone: "कोई जुड़ा स्रोत नहीं। समर्थन उपलब्ध होने पर जोड़े जा सकते हैं।",
        sourcesCount: (count: number) => `${count} जुड़े हैं · कभी भी प्रबंधित या डिस्कनेक्ट करें।`,
        choiceSection: "आपका निर्णय",
        choiceTitle: "तय करते आप हैं कि क्या रहे।",
        choiceBody: "अपनी जानकारी कभी भी देखें, निर्यात करें या हटाएँ।",
        exportAction: "डेटा निर्यात करें",
        deleteAction: "डेटा हटाएँ",
        noteCaption: "AKS की ओर से एक बात",
        noteBody: "आपका डेटा समझदारी भरा और आपके नियंत्रण में रहता है।",
        loadingData: "डेटा सारांश लोड हो रहा है",
        retry: "फिर कोशिश करें",
    },
    reflections: {
        header: "चिंतन",
        eyebrow: "आपके चिंतन",
        title: "वे बातें जो आपने साझा कीं।",
        description: "वे चिंतन देखें जो Aks को आपके अनुभवों का संदर्भ देते हैं।",
        itemTitle: "चिंतन",
        emptyTitle: "अभी कोई चिंतन नहीं।",
        emptyBody: "जैसे ही आप Aks के साथ साझा करना शुरू करेंगे, आपके चिंतन यहाँ दिखेंगे।",
    },
    checkIns: {
        header: "चेक-इन",
        eyebrow: "आपके चेक-इन",
        title: "छोटे पल, याद रखे गए।",
        description: "वे चेक-इन देखें जिनसे आपने समय के साथ चीज़ें कैसी लगीं, दर्ज किया।",
        itemFallback: "चेक-इन",
        itemTitle: (mood: string) => `${mood} चेक-इन`,
        energy: (value: number) => `ऊर्जा ${value}`,
        focus: (value: number) => `ध्यान ${value}`,
        stress: (value: number) => `तनाव ${value}`,
        noDetails: "कोई अतिरिक्त विवरण नहीं",
        emptyTitle: "अभी कोई चेक-इन नहीं।",
        emptyBody: "जैसे ही आप दर्ज करना शुरू करेंगे, आपके चेक-इन यहाँ दिखेंगे।",
    },
    conversations: {
        header: "बातचीत",
        eyebrow: "आपकी बातचीत",
        title: "Aks के साथ आपकी बातचीत।",
        description:
            "जो साझा किया था उसे दोबारा देखें, भविष्य की व्याख्याओं से अलग रखते हुए। खोज शीर्षक और कही गई बातें, दोनों देखती है।",
        searchA11y: "बातचीत खोजें",
        searchPlaceholder: "अपनी बातचीत खोजें",
        clearSearch: "साफ़ करें",
        loadingA11y: "बातचीत लोड हो रही हैं",
        loadErrorTitle: "बातचीत लोड नहीं हुईं।",
        emptyQueryTitle: "कोई मेल खाती बातचीत नहीं।",
        emptyQueryBody: "दूसरा शब्द आज़माएँ — Aks सिर्फ़ शीर्षक नहीं, आपकी कही बातें भी खोजता है।",
        emptyTitle: "अभी कोई बातचीत नहीं।",
        emptyBody: "Aks से शुरू की गई बातचीत यहाँ दिखाई देगी।",
        archiveHint: "आर्काइव करने के लिए देर तक दबाएँ",
        loadMore: "और लोड करें",
        archiveTitle: "बातचीत आर्काइव करें?",
        archiveMessage: "यह आपके सक्रिय इतिहास से हट जाएगी।",
        archiveConfirm: "आर्काइव करें",
        notices: {
            unableToArchive: "आर्काइव नहीं हुई",
        },
    },
    conversationDetail: {
        fallbackTitle: "बातचीत",
        renameA11y: "बातचीत का नाम बदलें",
        loadingA11y: "बातचीत लोड हो रही है",
        unavailableTitle: "बातचीत उपलब्ध नहीं।",
        archivedBody: "हो सकता है वह आर्काइव हुई या हट गई हो।",
        renameSection: "नाम बदलें",
        titleA11y: "बातचीत का शीर्षक",
        titlePlaceholder: "बातचीत का शीर्षक",
        saveRename: "सेव करें",
        cancelRename: "रद्द करें",
        cancelRenameA11y: "नाम बदलना रद्द करें",
        historySection: "बातचीत का इतिहास",
        startedAt: (date: string) => `${date} को शुरू हुई`,
        continueMirror: "मिरर में जारी रखें",
        loadEarlier: "पुराने संदेश लोड करें",
        youLabel: "आप",
        aksLabel: "Aks",
        systemLabel: "सिस्टम",
        emptyTitle: "अभी कोई संदेश नहीं।",
    },
    memories: {
        header: "Aks क्या याद रखता है",
        eyebrow: "AKS क्या याद रखता है",
        title: "काम आने वाला संदर्भ, सोच-समझकर रखा।",
        description:
            "बार-बार, सबूत के साथ दी गई जानकारी से Aks जो उठाता है।",
        observationsCount: (count: number) => `${count} ${count === 1 ? "अवलोकन" : "अवलोकन"}`,
        lastNoticed: (date: string) => `आख़िरी बार नोटिस हुआ ${date}`,
        emptyTitle: "Aks अभी आपके पैटर्न जान रहा है।",
        emptyBody:
            "जब पर्याप्त सबूत होगा, बार-बार काम आने वाला संदर्भ यहाँ दिखेगा।",
    },
    memoryDetail: {
        header: "स्मृति",
        loadingA11y: "स्मृति लोड हो रही है",
        unavailableTitle: "स्मृति उपलब्ध नहीं।",
        archivedFallback: "हो सकता है वह आर्काइव हुई या हट गई हो।",
        eyebrow: "AKS क्या याद रखता है",
        reasonTitle: "Aks यह क्यों याद रखता है",
        reasonFallback: (count: number) => `यह आपके साझा किए ${count} ${count === 1 ? "बात" : "बातों"} में दिखा है।`,
        lastNoticed: (date: string) => `आख़िरी बार नोटिस हुआ ${date}`,
        evidenceSection: "सबूत",
        viewConversation: " · बातचीत देखें",
        archiveAction: "स्मृति आर्काइव करें",
        removeAction: "स्मृति हटाएँ",
        archiveTitle: "यह स्मृति आर्काइव करें?",
        archiveMessage:
            "Aks अब इस स्मृति का उपयोग बंद कर देगा। भविष्य में आपके साझा किए विवरण इसे फिर से समर्थन दे सकते हैं। आपकी मूल बातचीत, चिंतन और चेक-इन सुरक्षित रहेंगी।",
        archiveConfirm: "आर्काइव करें",
        removeTitle: "यह स्मृति हटाएँ?",
        removeMessage:
            "इससे केवल Aks की संग्रहीत स्मृति हटती है। आपकी साझा की गई मूल जानकारी नहीं हटती।",
        removeConfirm: "हटाएँ",
        notices: {
            unableToArchive: "आर्काइव नहीं हुई",
            unableToRemove: "नहीं हटी",
        },
    },
    patterns: {
        header: "पैटर्न",
        eyebrow: "आपके पैटर्न",
        title: "नोटिस करने लायक संबंध।",
        description: "आपके साझा किए बार-बार के संकेतों पर आधारित संभावित संबंध।",
        observationsCount: (count: number) => `${count} अवलोकन`,
        emptyTitle: "अभी कोई पैटर्न नहीं।",
        emptyBody: "उपयोगी संबंध पहचानने से पहले Aks को थोड़ा और समय और सबूत चाहिए।",
        status: {
            possible: "संभावित पैटर्न",
            notSupported: "समर्थित नहीं",
            supported: "समर्थित",
            testing: "परखा जा रहा है",
            fallback: "उम्मीदवार",
        },
    },
    patternDetail: {
        header: "पैटर्न",
        loadingA11y: "पैटर्न लोड हो रहा है",
        unavailableTitle: "पैटर्न उपलब्ध नहीं।",
        archivedFallback: "हो सकता है वह आर्काइव हुआ या हट गया हो।",
        reasonTitle: "Aks ने यह क्यों नोटिस किया",
        evidenceLine: (supporting: number, contradicting: number) =>
            `यह संबंध ${supporting} समर्थक अवलोकनों से जुड़ा है` +
            (contradicting ? ` और ${contradicting} विरोधी अवलोकनों से` : "") +
            "।",
        confidencePending: "विश्वास स्तर अभी आँका जा रहा है",
        confidenceValue: (percent: number) => `सबूत का विश्वास स्तर ${percent}%`,
        firstNoticed: (date: string) => `पहली बार नोटिस हुआ ${date}`,
        lastObserved: (date: string) => `आख़िरी बार देखा गया ${date}`,
        alternativeTitle: "एक और संभावना",
        evidenceSection: "सबूत",
        supporting: "समर्थक",
        contradicting: "विरोधी",
        viewConversation: " · बातचीत देखें",
        notReadyA11y: "यह पैटर्न अभी परखने के लिए तैयार नहीं",
        testA11y: "इस पैटर्न को परखें",
        notReady: "अभी परखने के लिए तैयार नहीं",
        testAction: "इस पैटर्न को परखें",
        archiveAction: "पैटर्न आर्काइव करें",
        removeAction: "पैटर्न हटाएँ",
        statusLabels: {
            candidate: "उम्मीदवार",
            possible: "संभावित पैटर्न",
            testing: "परखा जा रहा है",
            supported: "समर्थित",
            notSupported: "समर्थित नहीं",
            archived: "आर्काइव किया गया",
        },
        archiveTitle: "यह पैटर्न आर्काइव करें?",
        archiveMessage:
            "Aks यह पैटर्न दिखाना बंद कर देगा। भविष्य के अवलोकन नई समीक्षा को समर्थन दे सकते हैं।",
        archiveConfirm: "आर्काइव करें",
        removeTitle: "यह पैटर्न हटाएँ?",
        removeMessage:
            "इससे केवल प्राप्त पैटर्न और उसके सबूत-लिंक हटते हैं। आपके संकेत और मूल जानकारी सुरक्षित रहेंगी।",
        removeConfirm: "हटाएँ",
        notices: {
            unableToArchive: "आर्काइव नहीं हुआ",
            unableToRemove: "नहीं हटा",
        },
    },
    experiments: {
        header: "प्रयोग",
        eyebrow: "आपके प्रयोग",
        title: "छोटे परीक्षण, काम आने वाले सबूत।",
        description: "प्रयोग आपको किसी संभावित पैटर्न को तथ्य माने बिना परखने में मदद करते हैं।",
        observationsCount: (count: number) => `${count} अवलोकन`,
        emptyTitle: "अभी कोई प्रयोग नहीं।",
        emptyBody: "जब कोई पैटर्न परखने लायक होगा, आप उसके इर्द-गिर्द छोटा प्रयोग चला सकते हैं।",
        status: {
            active: "सक्रिय",
            completed: "पूर्ण",
            cancelled: "रद्द",
            fallback: "ड्राफ़्ट",
        },
    },
    experimentSetup: {
        header: "प्रयोग सेट करें",
        patternSection: "परखा जा रहा पैटर्न",
        titleLabel: "शीर्षक",
        titlePlaceholder: "छोटा प्रयोग शीर्षक",
        hypothesisLabel: "परिकल्पना",
        hypothesisPlaceholder: "एक छोटा बदलाव हो सकता है…",
        hypothesisDefault: "एक छोटा बदलाव आपके देखे चीज़ों को प्रभावित कर सकता है।",
        descriptionLabel: "क्या आज़माना और क्या दर्ज करना है",
        descriptionPlaceholder: "एक छोटा बदलाव और आप क्या दर्ज करेंगे, बताएँ।",
        descriptionDefault:
            "एक छोटा, पलटने योग्य बदलाव चुनें। हर बार दर्ज करें कि नतीजा आसान लगा, वैसा ही, या कठिन।",
        durationLabel: "अवधि",
        durationA11y: (days: number) => `${days} दिन की अवधि`,
        durationDays: (days: number) => `${days}द`,
        defaultTitle: (patternTitle: string) => `परीक्षण: ${patternTitle}`.slice(0, 120),
        createAction: "ड्राफ़्ट बनाएँ",
        createA11y: "प्रयोग ड्राफ़्ट बनाएँ",
        createError: "यह प्रयोग नहीं बनाया जा सका। विवरण जाँचें और फिर कोशिश करें।",
        patternUnavailable: "यह पैटर्न उपलब्ध नहीं है।",
    },
    experimentDetail: {
        header: "प्रयोग",
        unavailableTitle: "प्रयोग उपलब्ध नहीं।",
        hypothesisTitle: "परिकल्पना",
        whatToTryTitle: "क्या आज़माना है",
        startAction: "प्रयोग शुरू करें",
        startA11y: "प्रयोग शुरू करें",
        removeAction: "प्रयोग हटाएँ",
        removeA11y: "प्रयोग हटाएँ",
        removeTitle: "प्रयोग हटाएँ?",
        removeMessage:
            "इससे प्रयोग, अवलोकन और कोई सीख हट जाएगी जो केवल इसी प्रयोग से समर्थित थी। मूल पैटर्न और संकेत सुरक्षित रहेंगे।",
        removeConfirm: "हटाएँ",
        recordedFallback: "दर्ज हुआ",
        observationsSection: "अवलोकन",
        emptyObservations: "अभी कोई अवलोकन दर्ज नहीं हुआ।",
        resultSection: "परिणाम",
        analysisPending: "विश्लेषण बाकी",
        confidenceValue: (percent: number) => `सबूत का विश्वास स्तर ${percent}%`,
        promptTitle: "इस बार कैसा लगा?",
        resultEasier: "आसान",
        resultSame: "वैसा ही",
        resultHarder: "कठिन",
        recordA11y: (result: string) => `${result} दर्ज करें`,
        observationPlaceholder: "वैकल्पिक नोट",
        observationA11y: "वैकल्पिक अवलोकन नोट",
        observationsMeta: (count: number) => `${count} अवलोकन दर्ज हुए`,
        observationsDay: (current: number, total: number | null) =>
            total ? ` · दिन ${current} / ${total}` : "",
        observationsThrough: (date: string) => ` · ${date} तक`,
        completeAction: "प्रयोग पूरा करें",
        completeA11y: "प्रयोग पूरा करें",
        cancelAction: "प्रयोग रद्द करें",
        cancelA11y: "प्रयोग रद्द करें",
        resultPendingBody: "आपके अवलोकन सेव हैं जब तक परिणाम तैयार होता है।",
        retryAnalysis: "व्याख्या फिर से लाएँ",
        retryAnalysisA11y: "प्रयोग विश्लेषण फिर से लाएँ",
        retryLearning: "सीख संश्लेषण फिर से लाएँ",
        retryLearningA11y: "सीख संश्लेषण फिर से लाएँ",
        retryInsight: "अंतर्दृष्टि फिर से लाएँ",
        retryInsightA11y: "अंतर्दृष्टि निर्माण फिर से लाएँ",
        resultLabels: {
            easier: "आसान",
            same: "वैसा ही",
            harder: "कठिन",
        },
        outcomeLabels: {
            supports: "परिकल्पना को समर्थन",
            mixed: "मिश्रित परिणाम",
            doesNotSupport: "परिकल्पना को समर्थन नहीं",
            insufficientData: "पर्याप्त डेटा नहीं",
        },
        confirmCompleteTitle: "यह प्रयोग पूरा करें?",
        confirmCompleteMessage: "Aks आपके अवलोकनों से क्या निकलता है, उसका सार देगा।",
        confirmCompleteLabel: "पूरा करें",
        confirmCancelTitle: "यह प्रयोग रद्द करें?",
        confirmCancelMessage: "आपके दर्ज अवलोकन उपलब्ध रहेंगे।",
        confirmCancelLabel: "प्रयोग रद्द करें",
        keepGoing: "जारी रखें",
        notices: {
            unableToUpdate: "अपडेट नहीं हुआ",
            unableToRecord: "दर्ज नहीं हुआ",
            recordRetry: "आपका पिछला प्रयास सुरक्षित रूप से फिर से किया जा सकता है।",
        },
    },
    learnings: {
        header: "सीख",
        eyebrow: "आपकी सीख",
        title: "सबूत क्या सुझाता है।",
        description:
            "पूरे किए प्रयोगों और दर्ज किए अवलोकनों से सोचे-समझे निष्कर्ष।",
        statusRevised: "संशोधित",
        statusActive: "सक्रिय",
        observationsCount: (count: number) => `${count} अवलोकन`,
        emptyTitle: "अभी कोई सीख नहीं।",
        emptyBody:
            "जैसे ही आप कुछ परखेंगे और पर्याप्त सबूत जुटाएँगे, Aks समझने में मदद कर सकता है कि क्या बदला।",
    },
    learningDetail: {
        header: "सीख",
        unavailableTitle: "सीख उपलब्ध नहीं।",
        evidenceTitle: "इस तक कैसे पहुँचे?",
        evidenceLine: (experiments: number, observations: number) =>
            `${experiments} पूरे ${experiments === 1 ? "प्रयोग" : "प्रयोगों"} और ${observations} दर्ज ${observations === 1 ? "अवलोकन" : "अवलोकनों"} पर आधारित।`,
        confidenceValue: (percent: number) => `सबूत का विश्वास स्तर ${percent}%`,
        updatedAt: (date: string) => `${date} को अपडेट हुई`,
        sourceSection: "स्रोत प्रयोग",
        openExperimentA11y: (title: string) => `प्रयोग ${title} खोलें`,
        observationsCount: (count: number) => `${count} अवलोकन`,
        archiveAction: "सीख आर्काइव करें",
        archiveA11y: "सीख आर्काइव करें",
        removeAction: "सीख हटाएँ",
        removeA11y: "सीख हटाएँ",
        resultLabels: {
            supports: "परिकल्पना का समर्थन किया",
            mixed: "मिश्रित परिणाम",
            doesNotSupport: "परिकल्पना का समर्थन नहीं किया",
            insufficientData: "पर्याप्त डेटा नहीं",
        },
        archiveTitle: "यह सीख आर्काइव करें?",
        archiveMessage: "स्रोत प्रयोग और अवलोकन उपलब्ध रहेंगे।",
        archiveConfirm: "आर्काइव करें",
        removeTitle: "यह सीख हटाएँ?",
        removeMessage:
            "इससे केवल प्राप्त सीख हटती है। प्रयोग, अवलोकन, पैटर्न और संकेत सुरक्षित रहेंगे।",
        removeConfirm: "हटाएँ",
        notices: {
            unableToArchive: "आर्काइव नहीं हुई",
            unableToRemove: "नहीं हटी",
        },
    },
    insights: {
        header: "अंतर्दृष्टि",
        eyebrow: "अंतर्दृष्टि",
        title: "कुछ ऐसा जो नोटिस करने लायक है।",
        description: "आपने जो परखा और सीखा, उस पर आधारित कुछ समय पर सटीक अवलोकन।",
        statusNew: "नई",
        statusSeen: "देखी हुई",
        emptyTitle: "अभी कोई अंतर्दृष्टि नहीं।",
        emptyBody: "जैसे-जैसे Aks को समय के साथ पर्याप्त सबूत मिलेंगे, काम आने वाली बातें उभरेंगी।",
    },
    insightDetail: {
        header: "अंतर्दृष्टि",
        eyebrow: "अंतर्दृष्टि",
        unavailableTitle: "अंतर्दृष्टि उपलब्ध नहीं।",
        reasonTitle: "Aks ने यह क्यों नोटिस किया",
        openExperimentA11y: (title: string) => `स्रोत प्रयोग ${title} खोलें`,
        openLearningA11y: (title: string) => `स्रोत सीख ${title} खोलें`,
        observationsCount: (count: number) => `${count} दर्ज अवलोकन · प्रयोग देखें`,
        viewLearning: "स्रोत सीख देखें",
        confidenceValue: (percent: number) => `सबूत का विश्वास स्तर ${percent}%`,
        createdAt: (date: string) => `${date} को बनी`,
        dismissAction: "अंतर्दृष्टि हटाएँ",
        dismissA11y: "अंतर्दृष्टि हटाएँ",
        removeAction: "अंतर्दृष्टि हटाएँ",
        removeA11y: "अंतर्दृष्टि हटाएँ",
        dismissTitle: "यह अंतर्दृष्टि हटाएँ?",
        dismissMessage: "सीख, प्रयोग, पैटर्न और सबूत सुरक्षित रहेंगे।",
        dismissConfirm: "हटाएँ",
        removeTitle: "यह अंतर्दृष्टि हटाएँ?",
        removeMessage: "इससे केवल अंतर्दृष्टि हटती है। सभी स्रोत जानकारी सुरक्षित रहेगी।",
        removeConfirm: "हटाएँ",
        notices: {
            unableToDismiss: "नहीं हटी",
            unableToRemove: "नहीं हटी",
        },
    },
    privacyHome: {
        header: "गोपनीयता",
        eyebrow: "आपकी गोपनीयता",
        title: "आपकी ज़िंदगी आपकी है।",
        description:
            "Aks आपको खुद समझने में मदद करता है और आपके अनुभव के पीछे की जानकारी का नियंत्रण आपके पास रखता है।",
        dataSection: "आपका डेटा",
        knowsTitle: "Aks क्या जानता है",
        knowsDescription: "वह जानकारी समझें जिससे आपका अनुभव बनता है।",
        accessTitle: "Aks क्या एक्सेस कर सकता है",
        accessDescription: "देखें आप क्या देते हैं या जोड़ना चुनते हैं।",
        controlsSection: "डेटा नियंत्रण",
        usageTitle: "आपका डेटा कैसे इस्तेमाल होता है",
        usageDescription: "देखें जानकारी अंतर्दृष्टि और प्रयोगों को कैसे सहारा देती है।",
        exportTitle: "अपना डेटा निर्यात करें",
        exportDescription: "अपनी Aks जानकारी की प्रति लेने का अनुरोध करें।",
        deleteTitle: "अपना डेटा हटाएँ",
        deleteDescription: "खाता डेटा हटाने की सावधानी भरी प्रक्रिया शुरू करें।",
        legalSection: "कानूनी",
        privacyPolicyTitle: "गोपनीयता नीति",
        privacyPolicyDescription: "पूरी Aks गोपनीयता नीति पढ़ें।",
    },
    dataAccess: {
        header: "Aks क्या एक्सेस कर सकता है",
        title: "डिज़ाइन से ही साफ़।",
        description:
            "Aks आपके दी गई जानकारी और उन स्रोतों पर काम करता है जिन्हें आप जानबूझकर जोड़ते हैं।",
        sourcesSection: "जुड़े स्रोत",
        loadingSources: "आपके जुड़े स्रोत लोड हो रहे हैं…",
        loadError: "हम आपके जुड़े स्रोत अभी लोड नहीं कर सके।",
        emptyTitle: "अभी कोई जुड़ा स्रोत नहीं",
        emptyBody:
            "Aks बाहरी सेवाओं से तभी पढ़ता है जब आप उन्हें साफ़ तौर पर जोड़ते हैं। आप कोई भी कनेक्शन खाता सेटिंग्स से प्रबंधित कर सकते हैं।",
        connectedNeedsPermission: "जुड़ा है · अनुमति चाहिए",
        connectedSynced: (relative: string) => `जुड़ा है और डेटा पढ़ रहा है · ${relative} सिंक हुआ`,
        connectedNotSynced: "जुड़ा है और डेटा पढ़ रहा है · अभी सिंक नहीं हुआ",
        holdsSection: "AKS के पास क्या है",
        items: [
            {
                title: "आपके दी गई जानकारी",
                body: "विवरण जो आप सीधे Aks में दर्ज करते हैं, जैसे प्रोफ़ाइल जानकारी और प्राथमिकताएँ।",
            },
            {
                title: "चिंतन और चेक-इन",
                body: "आपके अनुभव, मनोदशा, ध्यान, ऊर्जा या दिनचर्या बताने के लिए बनाई प्रविष्टियाँ।",
            },
            {
                title: "प्रयोग का डेटा",
                body: "आपके बनाए प्रयोग और दर्ज किए परिणाम या नोट।",
            },
            {
                title: "खाता जानकारी",
                body: "आपका Aks खाता पहचानने और प्रबंधित करने के लिए बुनियादी जानकारी।",
            },
            {
                title: "जुड़े डेटा स्रोत",
                body: "केवल उन सेवाओं की जानकारी जिन्हें आप साफ़ तौर पर जोड़ते हैं, जहाँ वे कनेक्शन उपलब्ध हों।",
            },
        ],
        controlTitle: "नियंत्रण आपके पास है",
        controlBody: "Aks केवल वही उपयोग करता है जो आप दर्ज करते हैं या साफ़ तौर पर जोड़ते हैं।",
    },
    dataUsage: {
        header: "आपका डेटा कैसे इस्तेमाल होता है",
        title: "आपके डेटा का एक उद्देश्य है।",
        description:
            "Aks आपकी जानकारी प्रोडक्ट के भीतर उपयोग करता है ताकि आपका अनुभव अधिक सटीक और समझदारी भरा हो।",
        sections: [
            {
                title: "Aks आपका डेटा क्यों उपयोग करता है",
                body: "आपके द्वारा साझा की गई जानकारी चिंतन को वैयक्तिक बनाने, उपयोगी विषय पहचानने और आपके लक्ष्यों को सहारा देने में मदद करती है।",
            },
            {
                title: "चिंतन और चेक-इन",
                body: "आपकी प्रविष्टियाँ समय के साथ मनोदशा, ऊर्जा, ध्यान और दिनचर्या में बदलाव का संदर्भ दे सकती हैं।",
            },
            {
                title: "पैटर्न पहचान",
                body: "Aks आपकी दी गई जानकारी की तुलना कर संभावित पैटर्न उभार सकता है जिन्हें आप समीक्षा करें। ये चिंतन के संकेत हैं, चिकित्सकीय निष्कर्ष नहीं।",
            },
            {
                title: "स्मृति",
                body: "Aks थोड़ा बार-बार काम आने वाला संदर्भ याद रख सकता है। हर स्मृति उस जानकारी से जुड़ी रहती है जो उसे समर्थन देती है, और मूल स्रोत हटाए बिना हटाई जा सकती है।",
            },
            {
                title: "प्रयोग और परिणाम",
                body: "प्रयोग की प्रविष्टियाँ यह तुलना करने में मदद करती हैं कि आपने क्या आज़माया और क्या दर्ज हुआ।",
            },
            {
                title: "AI सहायता प्राप्त समझ",
                body: "AI आपकी दी गई जानकारी को व्यवस्थित और सारांशित करने में मदद कर सकता है। महत्वपूर्ण अंतर्दृष्टि की समीक्षा करें और अपना निर्णय उपयोग करें।",
            },
        ],
        privacyPolicyAction: "पूरी गोपनीयता नीति पढ़ें",
    },
    exportData: {
        header: "अपना डेटा निर्यात करें",
        preparingTitle: "आपका निर्यात तैयार हो रहा है",
        preparingBody:
            "आपकी बातचीत, चिंतन, स्मृतियाँ, पैटर्न, प्रयोग और अंतर्दृष्टियाँ जुटाई जा रही हैं। इसमें आमतौर पर कुछ सेकंड लगते हैं।",
        errorTitle: "अपना डेटा साथ ले जाएँ।",
        errorBody: "आपकी Aks जानकारी की डाउनलोड करने योग्य प्रति अनुरोध पर उपलब्ध है।",
        failedTitle: "आपका निर्यात नहीं बनाया जा सका।",
        failedFallback: "निर्यात तैयार करते समय कुछ ग़लत हुआ। कृपया फिर कोशिश करें।",
        retryA11y: "निर्यात फिर से बनाएँ",
        cancelAction: "रद्द करें",
        cancelA11y: "निर्यात परिचय पर वापस जाएँ",
        readyTitle: "आपका निर्यात तैयार है।",
        readyBody:
            "आपकी Aks जानकारी की स्नैपशॉट अभी तैयार हुई। यह उन्हीं विभागों को कवर करती है जो अनुरोध के समय सूचीबद्ध थे।",
        expiresIn: (countdown: string) => `लिंक ${countdown} में समाप्त होगा`,
        expiresSoon: "एक पल",
        saveAction: "निर्यात सेव करें",
        saveA11y: "निर्यात सेव करें",
        requestAnother: "दूसरा निर्यात अनुरोध करें",
        requestAnotherA11y: "दूसरा निर्यात अनुरोध करें",
        idleTitle: "अपना डेटा साथ ले जाएँ।",
        idleBody:
            "आपकी Aks जानकारी की डाउनलोड करने योग्य प्रति अनुरोध पर उपलब्ध है। हर निर्यात एक फ़ाइल होती है जो अनुरोध के क्षण आपके खाते को दर्शाती है।",
        includedSection: "क्या-क्या शामिल है",
        included: [
            "प्रोफ़ाइल और प्राथमिकताएँ",
            "बातचीत और संदेश",
            "चिंतन",
            "चेक-इन",
            "संकेत",
            "स्मृतियाँ और सबूत-लिंक",
            "पैटर्न और सबूत-लिंक",
            "प्रयोग और अवलोकन",
            "सीख और स्रोत-लिंक",
            "अंतर्दृष्टियाँ और स्रोत संदर्भ",
        ],
        requestAction: "डेटा निर्यात का अनुरोध करें",
        requestA11y: "निर्यात का अनुरोध करें",
    },
    deleteData: {
        header: "अपना डेटा हटाएँ",
        title: "कुछ भी पीछे न रहे।",
        description:
            "खाता हटाने से Aks में बनाया गया आपका डेटा हमेशा के लिए हट जाता है। यह आपको इस डिवाइस से भी साइन आउट कर देता है।",
        warningTitle: "इसे पूर्ववत नहीं किया जा सकता।",
        warningBody:
            "खाता हटने के बाद आपका Aks डेटा चला जाता है और लौटाया नहीं जा सकता। यदि प्रति चाहिए तो पहले अपना डेटा निर्यात करने पर विचार करें।",
        removedSection: "क्या हटाया जाएगा",
        removed: [
            "बातचीत और संदेश",
            "चिंतन",
            "चेक-इन",
            "प्राप्त संकेत",
            "स्मृतियाँ और सबूत-लिंक",
            "पैटर्न और सबूत-लिंक",
            "प्रयोग और अवलोकन",
            "सीख और स्रोत-लिंक",
            "अंतर्दृष्टियाँ और स्रोत संदर्भ",
        ],
        confirmA11y: "पुष्टि करें कि आप समझते हैं यह स्थायी है",
        confirmLabel: "मैं समझता/समझती हूँ कि यह क्रिया स्थायी है और मेरा सारा Aks डेटा हट जाएगा।",
        deleteAction: "मेरा खाता और डेटा हटाएँ",
        deleteActionA11y: "मेरा खाता और डेटा हटाएँ",
        deletingAction: "आपका खाता हटाया जा रहा है…",
        deletedTitle: "आपका खाता हटाया जा रहा है।",
        deletedBody: "हटाना पूरा होते ही आप साइन आउट हो जाएँगे।",
        backToSettings: "सेटिंग्स पर वापस जाएँ",
        backToSettingsA11y: "सेटिंग्स पर वापस जाएँ",
        keepAccount: "मेरा खाता रखें",
        keepAccountA11y: "मेरा खाता रखें",
        keepNote: "खाता हटाने से इस खाते के लिए बनाई गई निर्यात फ़ाइलें भी हट जाती हैं।",
    },
    helpHome: {
        header: "सहायता और सुझाव",
        title: "हम सुन रहे हैं।",
        description: "कुछ काम नहीं कर रहा, कुछ भ्रमित कर रहा है, या कोई चीज़ है जो आप चाहते हैं Aks कर सके?",
        supportTitle: "मदद चाहिए?",
        supportBody: "हमारी सहायता टीम आपकी मदद के लिए यहाँ है।",
        supportAction: "सहायता से संपर्क करें",
        getHelpSection: "सहायता पाएँ",
        faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
        faqDescription: "आम सवालों के तुरंत जवाब पाएँ",
        reportTitle: "समस्या रिपोर्ट करें",
        reportDescription: "जब कुछ काम न करे, हमें बताएँ",
        improveSection: "AKS को बेहतर बनाएँ",
        suggestTitle: "विचार सुझाएँ",
        suggestDescription: "बताएँ आप चाहते हैं Aks क्या सीखे या करे",
        shareTitle: "अपना अनुभव साझा करें",
        shareDescription: "बताएँ क्या अच्छा लगा या क्या बेहतर हो सकता है",
        contactSection: "संपर्क",
        supportEmail: "support@aks.ai",
        supportResponse: "आमतौर पर 1–2 कार्य दिवस में जवाब",
        footerVersion: "1.0.0",
    },
    faq: {
        header: "सहायता और सुझाव",
        title: "अक्सर पूछे जाने वाले प्रश्न",
        description: "जानें Aks कैसे काम करता है और आपका डेटा कैसे संभाला जाता है।",
        searchPlaceholder: "प्रश्न खोजें",
        clearSearch: "साफ़ करें",
        resultsCount: (count: number) => `${count} परिणाम`,
        popularSection: "लोकप्रिय प्रश्न",
        questionsCount: (count: number) => `${count} प्रश्न`,
        items: [
            {
                question: "Aks पैटर्न कैसे खोजता है?",
                answer: "Aks उस जानकारी और चिंतन में उपयोगी संबंध ढूँढता है जिसे आप साझा करना चुनते हैं।",
            },
            {
                question: "क्या मैं नियंत्रित कर सकता हूँ कि Aks कौन-सा डेटा उपयोग करे?",
                answer: "हाँ। आप अपनी जानकारी देख सकते हैं और आपका डेटा और गोपनीयता से उपलब्ध अनुमतियाँ प्रबंधित कर सकते हैं।",
            },
            {
                question: "प्रयोग कैसे काम करते हैं?",
                answer: "प्रयोग छोटे बदलाव परखने और देखने में मदद करते हैं कि क्या आपके ध्यान, ऊर्जा, नींद और दिनचर्या को प्रभावित करता है।",
            },
            {
                question: "क्या मैं सूचना सेटिंग्स बदल सकता हूँ?",
                answer: "हाँ। आप पेज से सूचनाएँ खोलें और चुनें कि Aks कब संपर्क करे।",
            },
            {
                question: "क्या Aks चिकित्सकीय सलाह है?",
                answer: "नहीं। Aks व्यक्तिगत चिंतन में सहायता करता है और पेशेवर चिकित्सकीय या मानसिक-स्वास्थ्य सलाह का विकल्प नहीं है।",
            },
        ],
        emptyTitle: "कुछ मेल नहीं खाया",
        emptyBody: "दूसरा शब्द आज़माएँ या ऊपर दिए प्रश्नों को देखें।",
        clearAction: "खोज साफ़ करें",
        helpTitle: "फिर भी मदद चाहिए?",
        helpBody: "बताएँ क्या हो रहा है, हम आपको समझने में मदद करेंगे।",
        contactAction: "संपर्क करें",
    },
    sendFeedback: {
        header: "सुझाव भेजें",
        title: "Aks को बनाने में मदद करें।",
        description: "विचार साझा करें, सुविधा माँगें, या बताएँ क्या अच्छा चल रहा है।",
        optionLabel: "सुझाव का प्रकार",
        optionHint: "एक चुनें",
        options: ["विचार", "सुविधा अनुरोध", "सामान्य सुझाव", "जो पसंद आया"],
        initialOption: "सामान्य सुझाव",
        messageLabel: "आपका सुझाव",
        messagePlaceholder: "Aks को और उपयोगी क्या बनाएगा?",
        messageHint: "विचार, सुझाव या पसंद आई चीज़ें — सब आपका स्वागत है।",
        emailHint: "ईमेल तभी दें जब आप जवाब चाहते हैं।",
        noteTitle: "आपका सुझाव मायने रखता है।",
        noteBody: "आपने जो साझा किया है वह तय करने में मदद करता है कि Aks आगे क्या बनेगा।",
        submit: "सुझाव भेजें",
        leaveMessage: "आप कुछ भेजे बिना इस पेज को छोड़ सकते हैं।",
    },
    reportProblem: {
        header: "समस्या रिपोर्ट करें",
        title: "क्या ग़लत हुआ?",
        description:
            "बताएँ क्या हुआ। जितना संदर्भ साझा करेंगे, समझना और ठीक करना उतना आसान होगा।",
        optionLabel: "समस्या की श्रेणी",
        optionHint: "एक चुनें",
        options: [
            "कुछ काम नहीं कर रहा",
            "ऐप क्रैश हुआ",
            "ग़लत अंतर्दृष्टि",
            "डेटा की समस्या",
            "सूचना की समस्या",
            "अन्य",
        ],
        messageLabel: "क्या हुआ?",
        messagePlaceholder: "बताएँ आपने क्या अपेक्षा की और असल में क्या हुआ…",
        messageHint: "कृपया वे कदम भी लिखें जिनसे समस्या हुई।",
        emailHint: "ईमेल तभी दें जब आप फ़ॉलो-अप चाहते हैं।",
        noteTitle: "Aks बेहतर बनाने में मदद के लिए धन्यवाद।",
        noteBody: "आपकी रिपोर्ट Aks को सबके लिए अधिक भरोसेमंद बनाने में मदद करती है।",
        submit: "रिपोर्ट भेजें",
        leaveMessage: "आप बिना भेजे इस पेज को छोड़ सकते हैं।",
    },
    feedbackForm: {
        selectedState: "चुना गया",
        contactEmail: "संपर्क ईमेल",
        optionalMark: " वैकल्पिक",
        emailPlaceholder: "you@example.com",
        charLimit: 1000,
    },
    profilePreference: {
        saveAction: "प्राथमिकताएँ सेव करें",
        saveA11y: (title: string) => `${title} सेव करें`,
        noteCaption: "आपकी प्रोफ़ाइल में सेव हुआ",
        noteBody: "आपकी पसंद आपकी प्रोफ़ाइल में सेव होती हैं।",
        notices: {
            unableToSave: "प्राथमिकताएँ सेव नहीं हुईं",
        },
    },
    dataCategory: {
        recentSection: "हाल की",
        loadingA11y: (title: string) => `${title} लोड हो रहा है`,
        loadErrorTitle: "यह डेटा लोड नहीं हुआ।",
        tryAgain: "फिर कोशिश करें",
        loadMore: "और लोड करें",
        noteCaption: "AKS की ओर से एक बात",
        noteBody: "बनते ही आपकी प्रविष्टियाँ यहाँ दिखेंगी।",
    },
    bottomSheet: {
        dismissA11y: "हटाएँ",
        defaultConfirm: "समझ गए",
        cancel: "रद्द करें",
    },
    connectedSources: {
        header: "जुड़े स्रोत",
        eyebrow: "संदर्भ और अनुमतियाँ",
        title: "तय करते आप हैं कि Aks क्या जाने।",
        description:
            "बिना किसी जुड़े स्रोत के Aks पूरी तरह काम करता है। हर स्रोत वैकल्पिक, स्वतंत्र है और साफ़ बताता है कि क्या साझा करता है। कुछ भी कभी भी डिस्कनेक्ट कर सकते हैं।",
        loadingA11y: "स्रोत लोड हो रहे हैं",
        loadError: "हम आपके जुड़े स्रोत लोड नहीं कर सके।",
        status: {
            connected: "जुड़ा है",
            permissionRequired: "अनुमति चाहिए",
            notConnected: "जुड़ा नहीं है",
            notAvailable: "इस डिवाइस पर उपलब्ध नहीं",
            revoked: "डिस्कनेक्ट किया गया",
            temporarilyUnavailable: "अस्थायी रूप से उपलब्ध नहीं",
            error: "अभी उपलब्ध नहीं",
        },
        syncedAgo: (relative: string) => `${relative} सिंक हुआ`,
        notSynced: "अभी सिंक नहीं हुआ",
        whyHelps: "यह क्यों मदद करता है",
        whatReceives: "AKS क्या प्राप्त करता है",
        whatStored: "क्या संग्रहीत होता है",
        howToStop: "कैसे रोकें",
        goodToKnow: "जानने लायक बात",
        disconnect: "डिस्कनेक्ट करें",
        deleteData: "आयातित डेटा हटाएँ",
        allow: "अनुमति दें",
        connect: "जोड़ें",
        reconnect: "दोबारा जोड़ें",
        choiceSection: "आपका निर्णय",
        choiceBody: "केवल आपके जोड़े स्रोत उपयोग होते हैं। एक टैप में कभी भी बंद करें।",
        confirmations: {
            cancelAction: "रद्द करें",
        },
        notices: {
            providerNotConfigured: "वह प्रदाता इस बिल्ड में अभी कॉन्फ़िगर नहीं है।",
            unableToConnect: "वह स्रोत अभी जोड़ा नहीं जा सका।",
        },
        groups: {
            productivity: "उत्पादकता",
            work: "काम",
            device: "डिवाइस / व्यवहार",
        },
    },
    sources: {
        location: {
            name: "स्थान",
            purpose:
                "Aks को समझने दें कि आपका दिन कहाँ बीतता है। इससे कठिन दिन और यात्रा या अचानक बदलाव से बिगड़ा दिन अलग करने में मदद मिल सकती है।",
            receives:
                "मोटा स्थान-संदर्भ (घर का इलाक़ा, काम का इलाक़ा, यात्रा, अनजान जगह) और चलने की अवधियाँ — कभी भी लगातार ट्रैकिंग नहीं।",
            stored: "'यात्रा, शाम 6:30 के आसपास 45 मिनट' जैसी अवलोकन अवधियाँ। सटीक निर्देशांक संग्रहीत नहीं होते।",
            stop: "स्थान कभी भी डिस्कनेक्ट करें। आगे का संग्रह तुरंत रुक जाता है; पहले से संग्रहीत अवलोकन अलग से हटाए जा सकते हैं।",
            batteryNote:
                "जुड़े रहने पर कभी-कभी स्थान जाँच होती है। चालू करने से बैटरी उपयोग थोड़ा बढ़ सकता है।",
        },
        calendar: {
            name: "कैलेंडर",
            purpose:
                "नियोजित कार्यक्रम Aks को यह समझने में मदद करते हैं कि योजना बदली या रुचि घटी।",
            receives:
                "कार्यक्रम के समय और व्यापक श्रेणी। शीर्षक केवल तब जब वे योजना बताते हों; कभी भी उपस्थिति सूची, नोट्स या मीटिंग लिंक नहीं।",
            stored: "न्यूनतम कार्यक्रम रिकॉर्ड: समय, अवधि, श्रेणी, पुष्ट/रद्द।",
            stop: "कैलेंडर कभी भी डिस्कनेक्ट करें। आगे का संग्रह तुरंत रुक जाता है।",
        },
        reminders: {
            name: "कार्य और रिमाइंडर",
            purpose:
                "योजना बनाम असल में क्या हुआ — Aks यह कभी नहीं कहता कि आपने कुछ 'छोड़ दिया'।",
            receives: "आपके चुने सिंक किए रिमाइंडर के नियत समय और पूर्ण स्थिति।",
            stored: "नियत समय और पूर्ण/दर्ज-नहीं-हुआ स्थिति।",
            stop: "कार्य और रिमाइंडर कभी भी डिस्कनेक्ट करें।",
        },
        screenTime: {
            name: "स्क्रीन समय",
            purpose:
                "समग्र डिवाइस-उपयोग संदर्भ ध्यान में बदलाव समझा सकता है — इसे कभी विचलन का प्रमाण नहीं माना जाता।",
            receives: "प्रति समय-अवधि व्यापक श्रेणी के अनुसार समग्र उपयोग अवधियाँ।",
            stored: "'सोशल ऐप्स, 60 मिनट, 9–10 रात' जैसी समग्र अवधियाँ। कोई प्रति-टैप डेटा नहीं।",
            stop: "स्क्रीन समय कभी भी डिस्कनेक्ट करें।",
        },
        googleCalendar: {
            name: "Google कैलेंडर",
            purpose:
                "आपके Google कार्यक्रम Aks को डिवाइस कैलेंडर जैसा ही योजना-संदर्भ देते हैं, उन खातों के लिए जिन्हें आप साफ़ तौर पर जोड़ते हैं।",
            receives:
                "आपके चुने कैलेंडर से कार्यक्रम के समय और व्यापक श्रेणी। कभी उपस्थिति सूची, नोट्स या मीटिंग लिंक नहीं।",
            stored: "न्यूनतम कार्यक्रम रिकॉर्ड: समय, अवधि, श्रेणी, पुष्ट/रद्द।",
            stop: "Google कैलेंडर कभी भी डिस्कनेक्ट करें — और अपनी Google खाता सेटिंग्स से एक्सेस रद्द करें।",
        },
        appleCalendar: {
            name: "Apple कैलेंडर",
            purpose: "iPhone और iPad पर, Apple के कैलेंडर स्टोर के ज़रिए वही डिवाइस कैलेंडर संदर्भ।",
            receives: "कार्यक्रम के समय और व्यापक श्रेणी। कभी उपस्थिति सूची, नोट्स या मीटिंग लिंक नहीं।",
            stored: "न्यूनतम कार्यक्रम रिकॉर्ड: समय, अवधि, श्रेणी, पुष्ट/रद्द।",
            stop: "Apple कैलेंडर कभी भी डिस्कनेक्ट करें।",
        },
        googleTasks: {
            name: "Google Tasks",
            purpose:
                "आपके जुड़े Google खाते के नियोजित कार्य, ताकि Aks देखे आपका इरादा क्या था — यह कभी निष्कर्ष नहीं निकालता कि आप असफल रहे।",
            receives: "कार्यों का नियत समय और पूर्ण स्थिति।",
            stored: "नियत समय और पूर्ण/दर्ज-नहीं-हुआ स्थिति।",
            stop: "Google Tasks कभी भी डिस्कनेक्ट करें — और अपनी Google खाता सेटिंग्स से एक्सेस रद्द करें।",
        },
        appleReminders: {
            name: "Apple Reminders",
            purpose:
                "iPhone और iPad पर, Apple Reminders के नियोजित कार्य वही योजना-बनाम-हुआ संदर्भ देते हैं।",
            receives: "रिमाइंडर का नियत समय और पूर्ण स्थिति।",
            stored: "नियत समय और पूर्ण/दर्ज-नहीं-हुआ स्थिति।",
            stop: "Apple Reminders कभी भी डिस्कनेक्ट करें।",
        },
        notion: {
            name: "Notion",
            purpose:
                "वे पेज और डेटाबेस जो आपने Aks इंटीग्रेशन के साथ साझा किए, ताकि काम का संदर्भ बातचीत में मदद करे।",
            receives:
                "Aks Notion इंटीग्रेशन से साझा की गई सामग्री के शीर्षक, समय और व्यापक श्रेणी। कभी पेज की सामग्री नहीं।",
            stored: "न्यूनतम आइटम रिकॉर्ड: शीर्षक-श्रेणी, समय, स्थिति।",
            stop: "Notion कभी भी डिस्कनेक्ट करें — और अपने Notion वर्कस्पेस से Aks इंटीग्रेशन हटाएँ।",
        },
        todoist: {
            name: "Todoist",
            purpose: "जुड़ा कार्य प्रदाता (Todoist या ऐसा ही), ताकि Aks के बाहर की योजनाएँ भी गिनी जाएँ।",
            receives: "कार्यों का नियत समय और पूर्ण स्थिति।",
            stored: "नियत समय और पूर्ण/दर्ज-नहीं-हुआ स्थिति।",
            stop: "Todoist कभी भी डिस्कनेक्ट करें — और प्रदाता की खाता सेटिंग्स से एक्सेस रद्द करें।",
        },
        github: {
            name: "GitHub",
            purpose: "आपकी अपनी कमिट और PR गतिविधि उद्देश्यपूर्ण काम का संदर्भ — कभी दूसरों का डेटा नहीं।",
            receives: "आपके चुने रिपोज़ से कमिट और पुल-रिक्वेस्ट गतिविधि की गिनती और समय।",
            stored: "'2 कमिट, 10–11 रात' जैसी समग्र गतिविधि अवधियाँ। कोई कोड सामग्री नहीं।",
            stop: "GitHub कभी भी डिस्कनेक्ट करें — और अपनी GitHub सेटिंग्स से Aks OAuth ऐप रद्द करें।",
        },
        slack: {
            name: "Slack",
            purpose: "आपके साफ़ तौर पर जोड़े वर्कस्पेस से फ़ोकस-ब्लॉक और उपलब्धता संकेत।",
            receives: "आपकी अपनी गतिविधि अवधियाँ और डू-नॉट-डिस्टर्ब स्थिति। कभी संदेश सामग्री नहीं।",
            stored: "समग्र गतिविधि अवधियाँ। कोई संदेश नहीं, कोई चैनल नहीं, सहकर्मियों का कोई डेटा नहीं।",
            stop: "Slack कभी भी डिस्कनेक्ट करें — और अपने वर्कस्पेस से Aks ऐप हटाएँ।",
        },
        email: {
            name: "ईमेल",
            purpose: "आपके जोड़े प्रदाताओं — Gmail या अन्य — से हल्का ईमेल-भार संदर्भ (केवल गिनती)।",
            receives: "प्राप्त ईमेल की गिनती और समय। कभी विषय, सामग्री या प्रेषक नहीं।",
            stored: "प्रति अवधि समग्र गिनती। कोई सामग्री नहीं, कोई पता नहीं।",
            stop: "ईमेल कभी भी डिस्कनेक्ट करें — और प्रदाता की सुरक्षा सेटिंग्स से एक्सेस रद्द करें।",
        },
        voiceSession: {
            name: "माइक्रोफ़ोन",
            purpose:
                "वॉइस बातचीत एक साफ़ क्रिया है जो आप शुरू करते हैं। माइक्रोफ़ोन केवल सक्रिय वॉइस सत्र के दौरान उपयोग होता है।",
            receives: "ऑडियो केवल तब जब वॉइस बातचीत चल रही हो।",
            stored: "आपके रखे ट्रांसक्रिप्ट; ऑडियो संग्रहीत नहीं होता।",
            stop: "वॉइस सत्र समाप्त करें — माइक्रोफ़ोन बंद हो जाता है। Aks बैकग्राउंड में कभी नहीं सुनता।",
        },
    },
    transparency: {
        connectedWith: (sources: string) =>
            `आपने अपना ${sources} जोड़ा है, इसलिए Aks यहाँ आपके साझा किए साथ वह संदर्भ भी देख सकता है।`,
        names: {
            location: "स्थान",
            calendar: "कैलेंडर",
            googleCalendar: "Google कैलेंडर",
            appleCalendar: "Apple कैलेंडर",
            reminders: "कार्य",
            googleTasks: "Google Tasks",
            appleReminders: "Apple Reminders",
            todoist: "Todoist",
            notion: "Notion",
            github: "GitHub",
            slack: "Slack",
            email: "ईमेल",
            screenTime: "स्क्रीन समय",
            voiceSession: "वॉइस",
        },
    },
    oauth: {
        googleCalendar: "Google कैलेंडर",
        googleTasks: "Google Tasks",
        notion: "Notion",
        todoist: "Todoist",
        github: "GitHub",
        slack: "Slack",
        email: "ईमेल",
    },
    errors: {
        pagedData: "यह डेटा लोड नहीं हुआ। कृपया फिर कोशिश करें।",
        pagedDataMore: "और डेटा लोड नहीं हुआ। कृपया फिर कोशिश करें।",
        dataSummary: "आपका डेटा सारांश लोड नहीं हुआ। कृपया फिर कोशिश करें।",
        dataAccess: "आपके जुड़े स्रोत लोड नहीं हुए। कृपया फिर कोशिश करें।",
        memory: "यह स्मृति लोड नहीं हुई।",
        pattern: "यह पैटर्न लोड नहीं हुआ।",
        experiment: "यह प्रयोग लोड नहीं हुआ।",
        learning: "यह सीख लोड नहीं हुई।",
        insight: "यह अंतर्दृष्टि लोड नहीं हुई।",
        conversation: "यह बातचीत लोड नहीं हुई। कृपया फिर कोशिश करें।",
        conversationEarlier: "पुराने संदेश लोड नहीं हुए। कृपया फिर कोशिश करें।",
        conversationPlain: "यह बातचीत लोड नहीं हुई।",
        conversationEarlierPlain: "पुराने संदेश लोड नहीं हुए।",
        messageEmptySave: "सेव करने से पहले कुछ लिखें।",
        exportLinkExpired: "निर्यात लिंक समाप्त हो गया। कृपया नया निर्यात अनुरोध करें।",
        renameConversation: "उस बातचीत का नाम नहीं बदला जा सका। कृपया फिर कोशिश करें।",
        exportExpired: "निर्यात लिंक समाप्त हो गया। कृपया नया निर्यात अनुरोध करें।",
        exportCreate: "निर्यात नहीं बनाया जा सका। कृपया फिर कोशिश करें।",
        exportDownload: "निर्यात डाउनलोड नहीं हो सका। कृपया फिर कोशिश करें।",
        deleteAccount: "खाता हटाना अभी उपलब्ध नहीं है। कृपया थोड़ी देर बाद कोशिश करें।",
        preferences: "आपकी प्राथमिकताएँ लोड नहीं हुईं।",
        appSetup: "आपके खाते का सेटअप पूरा नहीं हुआ। कृपया फिर कोशिश करें।",
        exportSaveTitle: "अपना Aks निर्यात सेव करें",
        exportClearDevice: "आपका खाता डेटा हट रहा है, पर इस डिवाइस को साफ़ करने के लिए एक और प्रयास चाहिए।",
        shareUnavailable: "इस डिवाइस पर साझा करना उपलब्ध नहीं है। कृपया फिर कोशिश करें।",
        exportIncomplete: "निर्यात की प्रतिक्रिया अधूरी थी। कृपया फिर कोशिश करें।",
        exportInterrupted: "डाउनलोड बाधित हुआ। कृपया फिर कोशिश करें।",
        exportGeneric: "कुछ ग़लत हो गया। कृपया फिर कोशिश करें।",
        connectedSources: "हम आपके जुड़े स्रोत लोड नहीं कर सके।",
        sourceUnavailable: "यह स्रोत आपके डिवाइस पर उपलब्ध नहीं है।",
        sourcePermission: "इस स्रोत को जोड़ने के लिए Aks को वह अनुमति चाहिए। आप बाद में कोशिश कर सकते हैं।",
        sourceConnect: "वह स्रोत जोड़ा नहीं जा सका।",
        sourceDisconnect: "वह स्रोत डिस्कनेक्ट नहीं हुआ।",
        sourceDelete: "उस स्रोत का डेटा नहीं हटाया जा सका।",
        oauthRecord: "वह कनेक्शन दर्ज नहीं हुआ।",
        oauthDisconnect: "वह खाता डिस्कनेक्ट नहीं हुआ।",
        webPage: "यह पेज लोड नहीं हुआ।",
        webPageBody: "कृपया अपना इंटरनेट कनेक्शन जाँचें और फिर कोशिश करें।",
        generic: "कुछ ग़लत हो गया। कृपया फिर कोशिश करें।",
        signInUnavailable: "साइन इन अभी उपलब्ध नहीं है। कृपया थोड़ी देर बाद कोशिश करें।",
        signInStart: "साइन इन शुरू नहीं हो सका।",
        authRequest: "वह अनुरोध पूरा नहीं हुआ। कृपया फिर कोशिश करें।",
        storeUnreachable: "स्टोर तक नहीं पहुँचे। अपना कनेक्शन जाँचें और फिर कोशिश करें।",
        plansUnavailable: "प्लान अभी उपलब्ध नहीं हैं। कृपया थोड़ी देर बाद कोशिश करें।",
        planUnavailable: "वह प्लान अभी उपलब्ध नहीं है। कृपया थोड़ी देर बाद कोशिश करें।",
        storeFailed: "स्टोर आपका अनुरोध पूरा नहीं कर सका। कृपया फिर कोशिश करें।",
        subscriptionGeneric: "आपकी सदस्यता संभालते समय कुछ ग़लत हुआ। कृपया फिर कोशिश करें।",
        purchaseCancelled: "चेकआउट रद्द हुआ। कुछ भी चार्ज नहीं हुआ।",
        purchasePending:
            "आपकी खरीदारी स्टोर की पुष्टि की प्रतीक्षा में है। पूरी होने पर यह यहाँ दिखाई देगी।",
        alreadySubscribed: "आप इस प्लान की पहले से सदस्यता ले चुके हैं।",
        checkoutPendingPremium:
            "चेकआउट पूरा हुआ, पर Premium अभी आपके खाते पर सक्रिय नहीं है। एमुलेटर Test Store की खरीदारी Premium सक्रिय नहीं करती — Play Store वाले डिवाइस का उपयोग करें। अन्यथा थोड़ी देर प्रतीक्षा करके खरीदारी पुनर्स्थापित करें।",
        restoreEmpty: "पुनर्स्थापित करने के लिए कोई पुरानी खरीदारी नहीं मिली।",
        emptyMessage: "भेजने से पहले कुछ लिखें।",
        mirror: {
            noReply: "Aks ने आपके आख़िरी संदेश का जवाब अभी नहीं दिया है।",
            unsavedRetry: "आपका आख़िरी संदेश हो सकता है पूरी तरह सेव नहीं हुआ। आप इसे सुरक्षित रूप से फिर से भेज सकते हैं।",
            resolvePending: "दूसरा संदेश भेजने से पहले पिछला संदेश फिर से भेजें या उसे हल करें।",
            refreshFailed: "Aks वह जवाब नवीनीकृत नहीं कर सका। पिछला जवाब यहीं है।",
            refreshFailedConversation:
                "Aks कई कोशिशों के बाद यह जवाब पूरा नहीं कर सका। आपका संदेश सेव है।",
            refreshFailedUnsafe: "Aks जवाब को सुरक्षित रूप से नहीं समझ सका। आपका संदेश सेव है।",
            refreshFallback: "Aks वह अभी प्रोसेस नहीं कर सका। आपका संदेश सेव है।",
            updateMessage: "वह संदेश अपडेट नहीं हुआ। संभव है उसका जवाब Aks पहले ही दे चुका हो।",
            checkInFailed: "आपका चेक-इन सेव नहीं हुआ। कृपया फिर कोशिश करें।",
            saveFailed: "आपका संदेश सेव नहीं हुआ। अपना कनेक्शन जाँचें और फिर कोशिश करें।",
            outboxQueued: "इस डिवाइस पर सेव हुआ। आप ऑनलाइन आएँगे तो Aks इसे भेज देगा।",
            signInForVoice: "वॉइस बातचीत साइन इन करने के बाद उपलब्ध है।",
            voiceStartFailed: "वॉइस बातचीत शुरू नहीं हो सकी।",
        },
        voice: {
            realtimeNotConfigured: "वॉइस बातचीत इस बिल्ड में अभी कॉन्फ़िगर नहीं है।",
            sessionUnavailable: "वॉइस सत्र शुरू नहीं हो सका। कृपया फिर कोशिश करें।",
            transportUnavailable: "यह बातचीत विकल्प Aks के डेवलपमेंट बिल्ड की माँग करता है।",
            audioUnavailable: "लाइव वॉइस के लिए Aks ऑडियो इंजन वाला डेवलपमेंट बिल्ड चाहिए।",
            micDenied: "वॉइस बातचीत के लिए माइक्रोफ़ोन की अनुमति चाहिए।",
            transcriptionFailed: "Aks आपकी बात नहीं समझ सका। कृपया फिर कोशिश करें।",
            providerError: "Aks वॉइस बातचीत अभी शुरू नहीं कर सका।",
            sessionExpired: "वॉइस बातचीत समाप्त हो गई। जारी रखने के लिए दोबारा जुड़ें।",
            voiceFailed: "वॉइस बातचीत विफल हुई।",
            saveVoiceMessage: "आपका वॉइस संदेश सेव नहीं हुआ। वह केवल इसी सत्र में रहेगा।",
            saveVoiceReply: "Aks का जवाब सेव नहीं हुआ। वह केवल इसी सत्र में रहेगा।",
            audioCaptureFailed: "ऑडियो कैप्चर विफल हुआ।",
            audioFailed: "ऑडियो विफल हुआ।",
        },
        writes: {
            signInRequired: "जारी रखने के लिए कृपया साइन इन करें।",
            experimentInvalid: "प्रयोग की प्रतिक्रिया अमान्य थी।",
            observation: "वह अवलोकन सेव नहीं हुआ।",
            reflection: "वह चिंतन सेव नहीं हुआ।",
            message: "वह संदेश सेव नहीं हुआ।",
            checkIn: "वह चेक-इन सेव नहीं हुआ।",
            insightUpdate: "यह अंतर्दृष्टि अपडेट नहीं हुई।",
            experimentUpdate: "यह प्रयोग अपडेट नहीं हुआ।",
            startConversation: "वह बातचीत शुरू नहीं हुई।",
            sendMessage: "आपका संदेश सेव नहीं हुआ।",
            confirmMessage: "आपके सेव हुए संदेश की पुष्टि नहीं हुई।",
            searchConversations: "आपकी बातचीत खोजी नहीं जा सकी।",
            updateConversation: "वह बातचीत अपडेट नहीं हुई।",
            updateMessage: "वह संदेश अपडेट नहीं हुआ।",
            confirmUpdatedMessage: "आपके अपडेट हुए संदेश की पुष्टि नहीं हुई।",
            archiveConversation: "वह बातचीत आर्काइव नहीं हुई।",
            archivePattern: "यह पैटर्न आर्काइव नहीं हुआ।",
            removePattern: "यह पैटर्न नहीं हटा।",
            archiveMemory: "यह स्मृति आर्काइव नहीं हुई।",
            removeMemory: "यह स्मृति नहीं हटी।",
            archiveLearning: "यह सीख आर्काइव नहीं हुई।",
            removeLearning: "यह सीख नहीं हटी।",
        },
    },
    timelineEntries: {
        patternForming: "पैटर्न बन रहा है",
        insight: "अंतर्दृष्टि",
        newLearning: "नई सीख",
        outcomeRecorded: "परिणाम दर्ज हुआ",
        experimentStarted: "प्रयोग शुरू हुआ",
        experimentActive: "प्रयोग सक्रिय है",
        reflection: "चिंतन",
        checkIn: "चेक-इन",
        experimentOutcomeTitle: "प्रयोग का परिणाम दर्ज हुआ",
        reflectionTitle: "आपने एक चिंतन दर्ज किया",
    },
};

export default hi;
