import type { Translation } from "@/constants/copy";
import type { DayPart } from "@/lib/dayPart";

/**
 * Japanese translation.
 *
 * Every key of the English source of truth is required; the compiler rejects
 * missing or extra keys. Uses the polite です・ます register throughout, which
 * suits a reflective personal app and matches how Japanese consumer apps speak
 * to users. Proper nouns keep their official Japanese or Latin forms (Aks,
 * Mirror, Premium, Google カレンダー, Google ToDo リスト, Apple リマインダー,
 * Notion, GitHub, Slack, Todoist).
 *
 * Typography: Japanese punctuation (、。「」) with full-width brackets, a space
 * around Latin words and numerals for readability, and 24-hour times. Counts
 * use counters rather than plurals (観察 3 件). Mirror's deliberately hedged
 * language survives translation — possible patterns are 可能性のあるパターン
 * and observations stay 振り返りのきっかけであり、医学的な結論ではありません.
 */
const ja: Translation = {
    common: {
        back: "戻る",
        cancel: "キャンセル",
        save: "保存",
        dismiss: "閉じる",
        clear: "クリア",
        loading: "読み込み中…",
        tryAgain: "もう一度試す",
        loadMore: "さらに読み込む",
        pleaseTryAgain: "もう一度お試しください。",
        checkConnection: "接続を確認して、もう一度お試しください。",
        emailPlaceholder: "you@example.com",
        justNow: "たった今",
        dateUnavailable: "日付を取得できません",
        version: (value: string) => `バージョン ${value}`,
    },
    brand: {
        name: "Aks.ai",
        tagline: "自分を、別の角度から知る。",
    },
    splash: {
        appName: "Aks.ai",
        subtitle: "自分を、別の角度から知る。",
    },
    onboarding: {
        skip: "スキップ",
        moveForward: "次へ",
        getStarted: "はじめる",
        notices: {
            unableToContinue: "続行できません",
        },
        slides: [
            {
                eyebrow: "日々の暮らしに手がかりはある",
                title: "あなたはもう、\n自分の手がかりを残している。",
                description:
                    "繰り返していること。避けている瞬間。いつもと違うと感じる日。Aks はそれらのサインを集めます。",
            },
            {
                eyebrow: "振り返るだけで終わらせない",
                title: "推測しない。\n試してみる。",
                description:
                    "直感を小さな実験に変えましょう。ひとつ変えて、何が起きるかを測り、本当に自分に合う方法を見つけます。",
            },
            {
                eyebrow: "もっとクリアな自分",
                title: "自分が\n謎のままでいないように。",
                description:
                    "時間をかけて、Aks はあなたのパターン、反応、そして変化をもたらす要因の生きた全体像を築いていきます。",
            },
        ],
    },
    legal: {
        termsTitle: "利用規約",
        privacyTitle: "プライバシーポリシー",
        acceptance: {
            title: "はじめる前に。",
            description:
                "Aks は個人情報を扱いながら、あなたが自分のパターンに気づく手助けをします。続ける前に知っておいてほしいことがあります。",
            cardTitle: "あなたのデータは、あなたのもの。",
            cardBody:
                "Aks は、あなたが共有を選んだ情報を使ってパターンを見つけ、個人実験を支えます。",
            bullets: [
                "提供する情報は自分で決められます。",
                "データと権限は自分で管理できます。",
                "Aks は専門的な医療やメンタルヘルスの助言の代わりにはなりません。",
            ],
            agreePrefix: "Aks.ai の",
            terms: "利用規約",
            andWord: "と",
            privacy: "プライバシーポリシー",
            continue: "Aks をはじめる",
            retryAction: "再試行",
            retry: "再試行",
            footnote: "これらの文書は「設定」からいつでも確認できます。",
            consentA11y: "利用規約とプライバシーポリシーに同意する",
            notices: {
                unableToSave: "同意を保存できませんでした",
            },
        },
        links: {
            prefix: "続けることで、Aks.ai の",
            terms: "利用規約",
            andWord: "および",
            privacy: "プライバシーポリシーに同意したものとみなされます。",
        },
    },
    login: {
        title: "おかえりなさい。",
        description: "ログインして、Aks があなたについて気づいたことを引き続き見ていきましょう。",
        emailLabel: "メールアドレス",
        sendLink: "ログイン",
        sendLinkA11y: "ログインリンクを送信",
        secureLinkNote: "安全なログインリンクをメールでお送りします。パスワードは不要です。",
        divider: "または次の方法で続ける",
        google: "Google",
        googleA11y: "Google で続ける",
        facebook: "Facebook",
        facebookA11y: "Facebook で続ける",
        github: "GitHub で続ける",
        githubA11y: "GitHub で続ける",
        noAccount: "アカウントをお持ちでないですか？",
        createOne: "作成する",
        dismissError: "タップして閉じる。",
        notices: {
            unableToSendLink: "ログインリンクを送信できませんでした",
            unableToSignIn: "ログインできませんでした",
        },
    },
    register: {
        title: "アカウントを作成しましょう。",
        description: "Aks と一緒に、自分をもっとクリアに見ていきましょう。",
        nameLabel: "氏名",
        namePlaceholder: "お名前",
        nameA11y: "氏名",
        emailLabel: "メールアドレス",
        createAccount: "アカウントを作成",
        createAccountA11y: "メールアドレスでアカウントを作成",
        secureLinkNote: "安全なログインリンクをメールでお送りします。パスワードは不要です。",
        divider: "または次の方法で登録",
        google: "Google",
        googleA11y: "Google で続ける",
        facebook: "Facebook",
        facebookA11y: "Facebook で続ける",
        github: "GitHub で続ける",
        githubA11y: "GitHub で続ける",
        hasAccount: "すでにアカウントをお持ちですか？",
        signIn: "ログイン",
        dismissError: "タップして閉じる。",
        notices: {
            unableToCreate: "アカウントを作成できませんでした",
            unableToSignIn: "ログインできませんでした",
        },
    },
    emailConfirmation: {
        title: "メールをご確認ください。",
        body: (email: string) =>
            `安全なログインリンクを ${email} に送信しました。この端末でリンクを開いて続けてください。`,
        resendNote: "再送した場合、最新のリンクだけが有効です。",
        resend: "リンクを再送",
        resendA11y: "ログインリンクを再送",
        editEmail: "メールアドレスを変更",
        editEmailA11y: "メールアドレスを変更",
    },
    mirror: {
        eyebrow: "MIRROR",
        greeting: (firstName: string | null, part: DayPart = "morning") => {
            const base =
                part === "afternoon"
                    ? "こんにちは"
                    : part === "evening"
                        ? "こんばんは"
                        : part === "night"
                            ? "おやすみなさい"
                            : "おはようございます";
            return `${base}${firstName ? `、${firstName} さん` : ""}。`;
        },
        intro: "Aks です。まずは小さなことから始めましょう。",
        understandTitle: "何を理解したいですか？",
        differentHint: "まったく別のことを Aks に話してもかまいません。",
        checkInEyebrow: "クイックチェックイン",
        checkInTitle: "今日の調子はどうですか？",
        topics: ["集中", "エネルギー", "睡眠", "感情", "生活リズム", "人間関係", "生産性"],
        topicDraft: (topic: string) => `自分の${topic}について理解したいです。`,
        checks: ["いい感じ", "ふつう", "カオス"],
        aksLabel: "AKS",
        errorTitle: "問題が発生しました。",
        retryResponse: "返信を再試行",
        listening: "聞き取り中…",
        listeningMeta: (duration: string) => `${duration} · この端末内にのみ保存`,
        stopRecordingA11y: "録音を停止",
        voiceReady: "音声の振り返りを準備しました",
        voiceReadyHint: "Aks がそれを振り返りとして文字にします。",
        discardRecordingA11y: "録音を破棄",
        sendRecordingA11y: "録音を送信",
        composerPlaceholder: "今考えていることを Aks に話してください…",
        sendMessageA11y: "メッセージを送信",
        recordVoiceA11y: "音声の振り返りを録音",
        notices: {
            micUnavailable: "マイクを利用できません",
            micUnavailableBody:
                "音声の振り返りを録音するにはマイクの許可が必要です。文字で入力することもできます。",
            cantListen: "聞き取りを開始できませんでした",
            cantListenBody: "もう一度お試しいただくか、考えていることを文字で共有してください。",
            stopRecording: "録音を停止できませんでした",
            recordingFailed: "その録音を保存できませんでした",
            transcriptionNotConfigured:
                "このビルドでは音声の振り返りはまだ利用できません。文字で振り返りを入力できます。",
            audioTooLong: "録音が長すぎます。短くしてもう一度お試しください。",
            subscriptionRequired:
                "音声の振り返りには Aks Premium が必要なため、この録音は使用されませんでした。文字での入力もできます。",
            emptyTranscription:
                "Aks はその録音から何も聞き取れませんでした。マイクが正常か確認して、もう一度お試しください。",
            unsupportedAudio: "この録音形式には対応していません。もう一度録音してください。",
            transcriptionUnavailable:
                "Aks は今その録音を聞き取れませんでした。もう一度試すか、文字で入力してください。",
            unauthorized: "ログインしてから、もう一度お試しください。",
            recordingFailedFallback:
                "Aks は今その録音を保存できませんでした。もう一度試すか、文字で入力してください。",
        },
    },
    mirrorBar: {
        newConversation: "新しい会話",
        composerPlaceholder: "今考えていることを Aks に話してください…",
        sendMessageA11y: "メッセージを送信",
        closeComposerA11y: "入力欄を閉じる",
        openKeyboardA11y: "キーボードを開く",
        stopVoiceA11y: "音声会話を終了",
        startVoiceA11y: "音声会話を開始",
        voiceOffA11y: "読み上げ返信をオフにする",
        voiceOnA11y: "読み上げ返信をオンにする",
        moreOptionsA11y: "会話のその他のオプション",
        hint: "考えを整理してから話す必要はありません。まず話しはじめてください。",
    },
    aiConversation: {
        greeting: (firstName: string | null) => (firstName ? `こんにちは、${firstName} さん 👋` : "こんにちは 👋"),
        openingPrompts: [
            "最近、頭から離れないことは？",
            "今日はどんな気分ですか？",
            "最近ずっと抱えていることはありますか？",
            "頭の中を占めているのはどんなこと？",
            "気になっていることを話してみませんか？",
            "誰かに話してすっきりしたいことは？",
            "最近、何が重くのしかかっていますか？",
            "本当は言いたかった言葉はありますか？",
        ],
        copyAction: "コピー",
        copiedAction: "コピーしました",
        copyA11y: "メッセージをコピー",
        shareAction: "共有",
        shareA11y: "メッセージを共有",
        tryAgainAction: "もう一度試す",
        tryAgainA11y: "この返信をもう一度生成する",
        motionReadyA11y: "Aks の準備ができました",
        thinking: "考えています…",
        thinkingDefault: "Aks が考えています…",
        aksTag: "aks",
        youTag: "あなた",
        listening: "聞き取り中…",
        speaking: "話しています…",
        loadingConversation: "会話を読み込み中…",
        youPrefix: "あなた：",
        errorTitle: "問題が発生しました。",
        retryResponse: "返信を再試行",
        voicePaused: "音声を一時停止しました。",
        editPlaceholder: "メッセージを書き直す…",
        saveAndSend: "保存して送信",
        saveAndSendA11y: "編集したメッセージを保存して送信",
        cancelEditingA11y: "編集をキャンセル",
        cancel: "キャンセル",
        editMessage: "メッセージを編集",
        editMessageA11y: "あなたのメッセージを編集",
    },
    timeline: {
        header: "タイムライン",
        headerCaption: "Aks と歩んできたあなたの道のり。",
        eyebrow: "あなたの歩み",
        title: "あなたの物語は、これからも続きます。",
        description:
            "Aks との歩みを形づくった瞬間、パターン、実験、学びをここで見られます。",
        errorTitle: "タイムラインを読み込めませんでした。",
        errorBody: "あなたの物語はここにあります。しばらくしてからもう一度お試しください。",
        loadMoreError: "これ以上読み込めませんでした。",
        empty: {
            allTitle: "あなたの物語はまだ続いています。",
            allBody:
                "Aks と話すうちに、意味のある瞬間やパターン、実験、学びがここに現れます。",
            insightsTitle: "まだインサイトはありません。",
            insightsBody: "Aks が時間をかけて十分な根拠を見つけると、意味のあるインサイトがここに現れます。",
            experimentsTitle: "まだ実験はありません。",
            experimentsBody: "あなたが設定した実験は、実施するとここに現れます。",
            checkInsTitle: "まだチェックインはありません。",
            checkInsBody: "意味のあるチェックインがここに現れます。",
            decisionsTitle: "まだ決定はありません。",
            decisionsBody: "Aks が気づいた決定やパターンは、形になってくるとここに現れます。",
            learningsTitle: "まだ学びはありません。",
            learningsBody: "あなたの物語がよりクリアになると、新しい学びがここに現れます。",
        },
    },
    you: {
        title: "あなた",
        fallbackName: "Aks メンバー",
        subtitle: "あなたの個人的な場所",
        knowsTitle: "Aks が知っていること",
        knowsEmpty: "まだあなたを知る途中です",
        memoriesCount: (count: number) => `記憶 ${count} 件`,
        exploringTitle: "あなたが探っていること",
        exploringEmpty: "関心を選ぶ",
        unnoticedTitle: "まだ気づいていないこと",
        insightsCount: (count: number) => `目を通す価値のあるインサイト ${count} 件`,
        insightsEmpty: "まだ定まっていません",
        journeySection: "あなたの歩み",
        patternsTitle: "パターン",
        patternsDescription: "Aks が気づいたこと",
        experimentsTitle: "実験",
        experimentsDescription: "現在試していること",
        yourDataTitle: "あなたのデータ",
        yourDataDescription: "情報を見て、管理する",
        preferencesSection: "環境設定",
        notificationsTitle: "通知",
        notificationsDescription: "Aks がいつ連絡するか",
        appearanceTitle: "外観",
        appearanceDescription: "システム · ライト · ダーク",
        privacyTitle: "プライバシー",
        privacyDescription: "権限とプライバシーの管理",
        supportSection: "サポート",
        helpTitle: "ヘルプとフィードバック",
    },
    settings: {
        header: "設定",
        eyebrow: "設定",
        title: "あなたらしい Aks に。",
        description: "アカウント、プラン、Aks に関する情報を管理します。",
        accountSection: "アカウント",
        profileTitle: "プロフィール",
        profileDescription: "個人情報を管理する",
        accountTitle: "アカウント",
        accountDescription: "ログアウトまたはアカウント削除",
        subscriptionTitle: "サブスクリプション",
        subscriptionDescription: "Aks のプランと支払いを管理する",
        preferencesSection: "環境設定",
        languageTitle: "言語",
        aboutSection: "Aks について",
        aboutTitle: "Aks について",
        aboutDescription: "Aks をもっと知る",
        termsTitle: "利用規約",
        privacyTitle: "プライバシーポリシー",
    },
    profile: {
        header: "プロフィール",
        fallbackName: "Aks メンバー",
        fallbackEmail: "メールアドレスを取得できません",
        editName: "名前を編集",
        editNameA11y: "名前を編集",
        changePhotoA11y: "プロフィール写真を変更",
        photoA11y: "プロフィール写真",
        photoSheetTitle: "プロフィール写真",
        chooseImage: "画像を選択",
        removePhoto: "写真を削除",
        aksSection: "AKS",
        exploringTitle: "あなたが探っていること",
        exploringEmpty: "未設定",
        noticeTitle: "Aks が注目すべきこと",
        noticeEmpty: "未設定",
        preferencesSection: "環境設定",
        timezoneTitle: "タイムゾーン",
        languageTitle: "言語",
        accountSection: "アカウント",
        emailTitle: "メールアドレス",
        emailUnavailable: "利用できません",
        memberSince: "利用開始",
        memberSinceUnavailable: "利用できません",
        signInMethod: "ログイン方法",
        signInMethodFallback: "メールアドレス",
        editNameTitle: "名前を編集",
        editNameMessage: "Aks はこの名前であなたを呼びかけます。",
        nameA11y: "氏名",
        namePlaceholder: "お名前",
        saving: "保存中…",
        saveChanges: "変更を保存",
        fullName: "氏名",
        notices: {
            unableToSaveName: "プロフィールを保存できませんでした",
            unableToUpdatePhoto: "写真を更新できませんでした",
            unableToRemovePhoto: "写真を削除できませんでした",
            checkConnection: "接続を確認して、もう一度お試しください。",
            tryAgain: "もう一度お試しください。",
        },
    },
    exploring: {
        header: "あなたが探っていること",
        eyebrow: "パーソナル",
        title: "関心を選びましょう。",
        description: "もっとクリアに理解したい領域を選んでください。",
        options: ["集中", "エネルギー", "睡眠", "気分", "習慣", "ストレス"],
    },
    noticeAreas: {
        header: "Aks が注目すべきこと",
        eyebrow: "パーソナル",
        title: "Aks が注目する範囲を決めましょう。",
        description: "可能性のあるパターンを整理するとき、Aks が優先すべき領域を選んでください。",
        options: ["日々の習慣", "エネルギーの変化", "集中のパターン", "睡眠の質", "気分の変化", "実験の結果"],
    },
    timezone: {
        header: "タイムゾーン",
        eyebrow: "環境設定",
        title: "あなたの現地時間。",
        description: "Aks が予定を組むときに使うタイムゾーンを選んでください。",
    },
    language: {
        header: "言語",
        eyebrow: "環境設定",
        title: "言語を選びましょう。",
        description: "Aks 全体で使う言語を選んでください。",
        notAvailableYet: (name: string) => `${name} はまだ利用できません。翻訳が提供されるまでは英語を使用します。`,
        comingSoon: "近日対応",
    },
    appearance: {
        header: "外観",
        eyebrow: "あなたの体験",
        title: "自分らしく感じられるように。",
        description: "アプリ全体での Aks の見え方を選んでください。",
        themeSection: "テーマ",
        themes: {
            systemTitle: "システム",
            systemDescription: "端末の外観に合わせます。",
            lightTitle: "ライト",
            lightDescription: "Aks を明るく、はっきりと。",
            darkTitle: "ダーク",
            darkDescription: "暗い場所でやさしい見え方に。",
        },
        noteCaption: "AKS からのメモ",
        noteBody: "外観は Aks の見え方だけを変えます。",
        notices: {
            unableToSave: "外観を保存できませんでした",
        },
    },
    account: {
        header: "アカウント",
        signedInAs: "ログイン中",
        emailUnavailable: "メールアドレスを取得できません",
        signOut: "ログアウト",
        deleteAccount: "アカウントを削除",
        confirmSignOutTitle: "ログアウトしますか？",
        confirmSignOutMessage: "引き続き Aks を使うには、もう一度ログインが必要です。",
        confirmDeleteTitle: "アカウントを削除しますか？",
        confirmDeleteMessage:
            "アカウントと関連するデータが完全に削除されます。元に戻すことはできません。",
        notices: {
            unableToSignOut: "ログアウトできませんでした",
            unableToDelete: "アカウントを削除できませんでした",
            deleteUnavailable:
                "現在アカウントの削除はご利用いただけません。しばらくしてからもう一度お試しください。",
        },
    },
    about: {
        header: "Aks について",
        eyebrow: "概要",
        title: "自分を、別の角度から知る。",
        description:
            "Aks は、自分の活動を振り返り、可能性のあるパターンに気づき、より意図的に個人実験を行う手助けをします。",
        productLabel: "プロダクト",
        productValue: "Aks.ai",
        versionLabel: "バージョン",
        versionValue: "1.0.0",
        note: "Aks は個人の振り返りを支えるもので、専門的な医療やメンタルヘルスの助言の代わりにはなりません。",
    },
    subscription: {
        header: "サブスクリプション",
        eyebrow: "あなたのプラン",
        title: "Aks のプランと支払い。",
        description:
            "現在のプランと支払い状況を確認できます。支払い機能が利用可能になったら、サブスクリプション管理を接続できます。",
        checkingPlan: "プランを確認しています…",
        fallbackError: "プランを確認できませんでした。もう一度お試しください。",
        currentPlan: "現在のプラン",
        activeBadge: "有効",
        planActive: "プランは有効です。",
        renewsOn: (date: string) => `${date} に更新`,
        accessUntil: (date: string) => `${date} まで利用可能`,
        autoRenewOff: "自動更新はオフです。",
        billing: "支払い",
        manage: "サブスクリプションを管理",
        restore: "購入を復元",
        choosePlan: "プランを選ぶ",
        chooseTitle: "Aks と過ごす時間をもっと。",
        chooseDescription:
            "自分に合ったペースを選んでください。サブスクリプションはいつでも管理・復元できます。",
        expiredWithDate: (date: string) => `Premium の利用は ${date} に終了しました。`,
        expiredFallback: "Premium の利用は終了しました。",
        plansEmpty: "現在表示できるプランがありません。しばらくしてからご確認ください。",
        premiumEyebrow: "AKS PREMIUM",
        bestValue: "いちばんお得",
        premiumAccess: "Aks Premium をフルに利用",
        continueWith: (title: string) => `${title} で続ける`,
        unavailableTitle: "この端末ではまだサブスクリプションに接続していません。",
        unavailableBody:
            "この端末で支払いが利用できるようになると、プランがここに表示され、この画面で確認・管理できます。",
        noteCaption: "AKS からのメモ",
        noteBody: "支払いは端末のストアで処理されます。",
    },
    notifications: {
        header: "通知",
        eyebrow: "必要なときにだけ",
        title: "大切なときだけ。",
        description: "Aks が連絡してよいタイミングを選んでください。これらの設定はいつでも変更できます。",
        sectionMain: "通知",
        allowTitle: "通知を許可",
        allowDescription: "Aks の通知をすべて一時停止または再開します。",
        categoriesSection: "AKS が送信できる内容",
        categories: {
            insightsTitle: "新しいインサイト",
            insightsDescription: "Aks が意味のあるパターンに気づいたとき。",
            experimentsTitle: "実験の更新",
            experimentsDescription: "実施中の実験のリマインダーと結果。",
            checkInsTitle: "チェックインのリマインダー",
            checkInsDescription: "一日を振り返るやさしいきっかけ。",
            weeklyTitle: "週次の振り返り",
            weeklyDescription: "一週間で変わったことのまとめ。",
        },
        quietSection: "静かな時間",
        quietTitle: "静かな時間",
        quietDescription: "22:00 から 8:00 までは通知を送りません。",
        deviceSection: "端末の設定",
        deviceTitle: "端末の通知を管理",
        deviceDescription: "端末の設定を開いて Aks の権限を管理します。",
        noteCaption: "AKS からのメモ",
        noteBody: "Aks は大切なときだけ連絡します。",
    },
    yourData: {
        header: "あなたのデータ",
        eyebrow: "あなたのデータ",
        title: "Aks が覚えていること。",
        description:
            "Aks があなたの活動から集めた情報と、あなたが共有を選んだ内容を確認できます。",
        glanceSection: "概要",
        remembersSection: "AKS が覚えていること",
        sourcesSection: "データソース",
        sourcesTitle: "連携中のソース",
        sourcesUnknown: "どのソースが連携されているか確認できます。",
        sourcesNone: "連携中のソースはありません。対応しているときに利用できます。",
        sourcesCount: (count: number) => `${count} 件連携中 · いつでも管理・解除できます。`,
        choiceSection: "あなたの選択",
        choiceTitle: "何を残すかはあなたが決めます。",
        choiceBody: "情報はいつでも確認・エクスポート・削除できます。",
        exportAction: "データをエクスポート",
        deleteAction: "データを削除",
        noteCaption: "AKS からのメモ",
        noteBody: "あなたのデータは分かりやすく、あなたの管理下にあります。",
        loadingData: "データの概要を読み込み中",
        retry: "もう一度試す",
    },
    reflections: {
        header: "振り返り",
        eyebrow: "あなたの振り返り",
        title: "あなたが共有したこと。",
        description: "Aks にあなたの経験の文脈を伝える振り返りを見返せます。",
        itemTitle: "振り返り",
        emptyTitle: "まだ振り返りはありません。",
        emptyBody: "Aks と共有を始めると、振り返りがここに現れます。",
    },
    checkIns: {
        header: "チェックイン",
        eyebrow: "あなたのチェックイン",
        title: "覚えている小さな瞬間。",
        description: "そのときの感覚を記録するために使ったチェックインを見返せます。",
        itemFallback: "チェックイン",
        itemTitle: (mood: string) => `${mood}のチェックイン`,
        energy: (value: number) => `エネルギー ${value}`,
        focus: (value: number) => `集中 ${value}`,
        stress: (value: number) => `ストレス ${value}`,
        noDetails: "追加の詳細はありません",
        emptyTitle: "まだチェックインはありません。",
        emptyBody: "記録を始めると、チェックインがここに現れます。",
    },
    conversations: {
        header: "会話",
        eyebrow: "あなたの会話",
        title: "Aks との会話。",
        description:
            "後からの解釈と混ざらない形で、共有した内容を見返せます。検索はタイトルと会話の内容が対象です。",
        searchA11y: "会話を検索",
        searchPlaceholder: "会話を検索",
        clearSearch: "クリア",
        loadingA11y: "会話を読み込み中",
        loadErrorTitle: "会話を読み込めませんでした。",
        emptyQueryTitle: "一致する会話がありません。",
        emptyQueryBody: "別の言葉をお試しください — Aks はタイトルだけでなく、あなたが話した内容も検索します。",
        emptyTitle: "まだ会話はありません。",
        emptyBody: "Aks と始めた会話がここに現れます。",
        archiveHint: "長押しでアーカイブ",
        loadMore: "さらに読み込む",
        archiveTitle: "この会話をアーカイブしますか？",
        archiveMessage: "進行中の会話履歴からは非表示になります。",
        archiveConfirm: "アーカイブ",
        notices: {
            unableToArchive: "アーカイブできませんでした",
        },
    },
    conversationDetail: {
        fallbackTitle: "会話",
        renameA11y: "会話の名前を変更",
        loadingA11y: "会話を読み込み中",
        unavailableTitle: "会話を利用できません。",
        archivedBody: "アーカイブまたは削除された可能性があります。",
        renameSection: "会話の名前を変更",
        titleA11y: "会話のタイトル",
        titlePlaceholder: "会話のタイトル",
        saveRename: "保存",
        cancelRename: "キャンセル",
        cancelRenameA11y: "名前の変更をキャンセル",
        historySection: "会話の履歴",
        startedAt: (date: string) => `${date} 開始`,
        continueMirror: "Mirror で続ける",
        loadEarlier: "以前のメッセージを読み込む",
        youLabel: "あなた",
        aksLabel: "Aks",
        systemLabel: "システム",
        emptyTitle: "まだメッセージはありません。",
    },
    memories: {
        header: "Aks が覚えていること",
        eyebrow: "AKS が覚えていること",
        title: "役立つ文脈を、慎重に。",
        description:
            "あなたが繰り返し共有した、根拠のある情報から Aks が得たこと。",
        observationsCount: (count: number) => `観察 ${count} 件`,
        lastNoticed: (date: string) => `最終確認 ${date}`,
        emptyTitle: "Aks はまだあなたのパターンを知る途中です。",
        emptyBody:
            "覚えておくのに十分な根拠がそろうと、繰り返し現れる役立つ文脈がここに表示されます。",
    },
    memoryDetail: {
        header: "記憶",
        loadingA11y: "記憶を読み込み中",
        unavailableTitle: "記憶を利用できません。",
        archivedFallback: "アーカイブまたは削除された可能性があります。",
        eyebrow: "AKS が覚えていること",
        reasonTitle: "Aks がこれを覚えている理由",
        reasonFallback: (count: number) => `あなたが共有した ${count} 件の内容に現れています。`,
        lastNoticed: (date: string) => `最終確認 ${date}`,
        evidenceSection: "根拠",
        viewConversation: " · 会話を見る",
        archiveAction: "記憶をアーカイブ",
        removeAction: "記憶を削除",
        archiveTitle: "この記憶をアーカイブしますか？",
        archiveMessage:
            "Aks はこの記憶を使わなくなります。今後共有する内容が再び支えることもあります。元の会話・振り返り・チェックインはそのまま残ります。",
        archiveConfirm: "アーカイブ",
        removeTitle: "この記憶を削除しますか？",
        removeMessage:
            "Aks が保存した記憶だけを削除します。あなたが共有した元の情報は削除されません。",
        removeConfirm: "削除",
        notices: {
            unableToArchive: "アーカイブできませんでした",
            unableToRemove: "削除できませんでした",
        },
    },
    patterns: {
        header: "パターン",
        eyebrow: "あなたのパターン",
        title: "気づく価値のあるつながり。",
        description: "あなたが共有した内容に繰り返し現れるサインに基づく、可能性のある関係性。",
        observationsCount: (count: number) => `観察 ${count} 件`,
        emptyTitle: "まだパターンはありません。",
        emptyBody: "役立つつながりを見つけるには、もう少し時間と根拠が必要です。",
        status: {
            possible: "可能性のあるパターン",
            notSupported: "支持されず",
            supported: "支持あり",
            testing: "検証中",
            fallback: "候補",
        },
    },
    patternDetail: {
        header: "パターン",
        loadingA11y: "パターンを読み込み中",
        unavailableTitle: "パターンを利用できません。",
        archivedFallback: "アーカイブまたは削除された可能性があります。",
        reasonTitle: "Aks がこれに気づいた理由",
        evidenceLine: (supporting: number, contradicting: number) =>
            `この関係性は ${supporting} 件の支持する観察` +
            (contradicting ? `と ${contradicting} 件の反する観察` : "") +
            "に関連しています。",
        confidencePending: "信頼度を評価中",
        confidenceValue: (percent: number) => `根拠の信頼度 ${percent}%`,
        firstNoticed: (date: string) => `初回 ${date}`,
        lastObserved: (date: string) => `最終観察 ${date}`,
        alternativeTitle: "別の可能性",
        evidenceSection: "根拠",
        supporting: "支持",
        contradicting: "反する",
        viewConversation: " · 会話を見る",
        notReadyA11y: "このパターンはまだ検証できません",
        testA11y: "このパターンを検証する",
        notReady: "まだ検証できません",
        testAction: "このパターンを検証",
        archiveAction: "パターンをアーカイブ",
        removeAction: "パターンを削除",
        statusLabels: {
            candidate: "候補",
            possible: "可能性のあるパターン",
            testing: "検証中",
            supported: "支持あり",
            notSupported: "支持されず",
            archived: "アーカイブ済み",
        },
        archiveTitle: "このパターンをアーカイブしますか？",
        archiveMessage:
            "Aks はこのパターンを表示しなくなります。今後の観察で再評価につながることもあります。",
        archiveConfirm: "アーカイブ",
        removeTitle: "このパターンを削除しますか？",
        removeMessage:
            "導き出されたパターンとその根拠の関連だけを削除します。サインと元の情報はそのまま残ります。",
        removeConfirm: "削除",
        notices: {
            unableToArchive: "アーカイブできませんでした",
            unableToRemove: "削除できませんでした",
        },
    },
    experiments: {
        header: "実験",
        eyebrow: "あなたの実験",
        title: "小さなテスト、役立つ根拠。",
        description: "実験は、可能性のあるパターンを事実として扱わずに試すためのものです。",
        observationsCount: (count: number) => `観察 ${count} 件`,
        emptyTitle: "まだ実験はありません。",
        emptyBody: "検証する価値のあるパターンがあれば、それを小さな実験で試せます。",
        status: {
            active: "実施中",
            completed: "完了",
            cancelled: "キャンセル済み",
            fallback: "下書き",
        },
    },
    experimentSetup: {
        header: "実験を設定",
        patternSection: "検証するパターン",
        titleLabel: "タイトル",
        titlePlaceholder: "短い実験タイトル",
        hypothesisLabel: "仮説",
        hypothesisPlaceholder: "小さな変化で…かもしれない",
        hypothesisDefault: "小さな変化が、このパターンで観察されることに影響するかもしれません。",
        descriptionLabel: "試すこと・観察すること",
        descriptionPlaceholder: "ひとつの小さな変化と、記録する内容を書いてください。",
        descriptionDefault:
            "小さく、元に戻せる変化をひとつ選びましょう。毎回、結果が楽だったか、同じだったか、大変だったかを記録します。",
        durationLabel: "期間",
        durationA11y: (days: number) => `${days} 日間`,
        durationDays: (days: number) => `${days} 日`,
        defaultTitle: (patternTitle: string) => `検証：${patternTitle}`.slice(0, 120),
        createAction: "下書きを作成",
        createA11y: "実験の下書きを作成",
        createError: "この実験を作成できませんでした。内容を確認して、もう一度お試しください。",
        patternUnavailable: "このパターンは利用できません。",
    },
    experimentDetail: {
        header: "実験",
        unavailableTitle: "実験を利用できません。",
        hypothesisTitle: "仮説",
        whatToTryTitle: "試すこと",
        startAction: "実験を開始",
        startA11y: "実験を開始",
        removeAction: "実験を削除",
        removeA11y: "実験を削除",
        removeTitle: "この実験を削除しますか？",
        removeMessage:
            "実験、観察、およびこの実験だけに支えられた学びを削除します。元のパターンとサインは残ります。",
        removeConfirm: "削除",
        recordedFallback: "記録済み",
        observationsSection: "観察",
        emptyObservations: "まだ観察は記録されていません。",
        resultSection: "結果",
        analysisPending: "分析待ち",
        confidenceValue: (percent: number) => `根拠の信頼度 ${percent}%`,
        promptTitle: "今回はどう感じましたか？",
        resultEasier: "楽だった",
        resultSame: "同じ",
        resultHarder: "大変だった",
        recordA11y: (result: string) => `${result}として記録`,
        observationPlaceholder: "任意のメモ",
        observationA11y: "任意の観察メモ",
        observationsMeta: (count: number) => `${count} 件の観察を記録`,
        observationsDay: (current: number, total: number | null) =>
            total ? ` · ${total} 日中 ${current} 日目` : "",
        observationsThrough: (date: string) => ` · ${date} まで`,
        completeAction: "実験を完了",
        completeA11y: "実験を完了",
        cancelAction: "実験をキャンセル",
        cancelA11y: "実験をキャンセル",
        resultPendingBody: "結果をまとめている間も、観察は保存されています。",
        retryAnalysis: "解釈を再試行",
        retryAnalysisA11y: "実験の分析を再試行",
        retryLearning: "学びの整理を再試行",
        retryLearningA11y: "学びの整理を再試行",
        retryInsight: "インサイトの生成を再試行",
        retryInsightA11y: "インサイトの生成を再試行",
        resultLabels: {
            easier: "楽だった",
            same: "同じ",
            harder: "大変だった",
        },
        outcomeLabels: {
            supports: "仮説を支持",
            mixed: "結果は混在",
            doesNotSupport: "仮説を支持せず",
            insufficientData: "データ不足",
        },
        confirmCompleteTitle: "この実験を完了しますか？",
        confirmCompleteMessage: "Aks が観察から何が言えるかをまとめます。",
        confirmCompleteLabel: "完了",
        confirmCancelTitle: "この実験をキャンセルしますか？",
        confirmCancelMessage: "記録した観察はそのまま残ります。",
        confirmCancelLabel: "実験をキャンセル",
        keepGoing: "続ける",
        notices: {
            unableToUpdate: "更新できませんでした",
            unableToRecord: "記録できませんでした",
            recordRetry: "前回の記録は安全に再試行できます。",
        },
    },
    learnings: {
        header: "学び",
        eyebrow: "あなたの学び",
        title: "根拠が示していること。",
        description:
            "完了した実験と記録した観察から得た、慎重な気づき。",
        statusRevised: "更新済み",
        statusActive: "有効",
        observationsCount: (count: number) => `観察 ${count} 件`,
        emptyTitle: "まだ学びはありません。",
        emptyBody:
            "何かを試して十分な根拠が集まると、Aks が何が変わったのかを整理する手助けをします。",
    },
    learningDetail: {
        header: "学び",
        unavailableTitle: "学びを利用できません。",
        evidenceTitle: "これは何から？",
        evidenceLine: (experiments: number, observations: number) =>
            `完了した ${experiments} 件の実験と、記録した ${observations} 件の観察に基づきます。`,
        confidenceValue: (percent: number) => `根拠の信頼度 ${percent}%`,
        updatedAt: (date: string) => `${date} 更新`,
        sourceSection: "元の実験",
        openExperimentA11y: (title: string) => `実験「${title}」を開く`,
        observationsCount: (count: number) => `観察 ${count} 件`,
        archiveAction: "学びをアーカイブ",
        archiveA11y: "学びをアーカイブ",
        removeAction: "学びを削除",
        removeA11y: "学びを削除",
        resultLabels: {
            supports: "仮説を支持",
            mixed: "結果は混在",
            doesNotSupport: "仮説を支持せず",
            insufficientData: "データ不足",
        },
        archiveTitle: "この学びをアーカイブしますか？",
        archiveMessage: "元の実験と観察はそのまま利用できます。",
        archiveConfirm: "アーカイブ",
        removeTitle: "この学びを削除しますか？",
        removeMessage:
            "導き出された学びだけを削除します。実験・観察・パターン・サインはそのまま残ります。",
        removeConfirm: "削除",
        notices: {
            unableToArchive: "アーカイブできませんでした",
            unableToRemove: "削除できませんでした",
        },
    },
    insights: {
        header: "インサイト",
        eyebrow: "インサイト",
        title: "気づく価値のあること。",
        description: "あなたが試し、学んだことに基づく、タイムリーな観察を少しだけ。",
        statusNew: "新着",
        statusSeen: "確認済み",
        emptyTitle: "まだインサイトはありません。",
        emptyBody: "Aks が時間をかけて十分な根拠を見つけると、役立つことが見えてきます。",
    },
    insightDetail: {
        header: "インサイト",
        eyebrow: "インサイト",
        unavailableTitle: "インサイトを利用できません。",
        reasonTitle: "Aks がこれに気づいた理由",
        openExperimentA11y: (title: string) => `元の実験「${title}」を開く`,
        openLearningA11y: (title: string) => `元の学び「${title}」を開く`,
        observationsCount: (count: number) => `記録した観察 ${count} 件 · 実験を見る`,
        viewLearning: "元の学びを見る",
        confidenceValue: (percent: number) => `根拠の信頼度 ${percent}%`,
        createdAt: (date: string) => `${date} 作成`,
        dismissAction: "インサイトを閉じる",
        dismissA11y: "インサイトを閉じる",
        removeAction: "インサイトを削除",
        removeA11y: "インサイトを削除",
        dismissTitle: "このインサイトを閉じますか？",
        dismissMessage: "学び、実験、パターン、根拠はそのまま残ります。",
        dismissConfirm: "閉じる",
        removeTitle: "このインサイトを削除しますか？",
        removeMessage: "このインサイトだけを削除します。元の情報はすべて残ります。",
        removeConfirm: "削除",
        notices: {
            unableToDismiss: "閉じられませんでした",
            unableToRemove: "削除できませんでした",
        },
    },
    privacyHome: {
        header: "プライバシー",
        eyebrow: "あなたのプライバシー",
        title: "あなたの生活はあなたのもの。",
        description:
            "Aks は、この体験を支える情報をあなた自身が管理できる状態のまま、自分を知る手助けをします。",
        dataSection: "あなたのデータ",
        knowsTitle: "Aks が知っていること",
        knowsDescription: "あなたの体験を作るために使われる情報を理解できます。",
        accessTitle: "Aks がアクセスできるもの",
        accessDescription: "あなたが提供・連携した内容を確認できます。",
        controlsSection: "データの管理",
        usageTitle: "データがどう使われるか",
        usageDescription: "情報がインサイトや実験をどう支えるかを確認できます。",
        exportTitle: "データをエクスポート",
        exportDescription: "あなたの Aks 情報のコピーを請求できます。",
        deleteTitle: "データを削除",
        deleteDescription: "慎重なアカウントデータ削除の手続きを始めます。",
        legalSection: "法的情報",
        privacyPolicyTitle: "プライバシーポリシー",
        privacyPolicyDescription: "Aks のプライバシーポリシー全文を読む。",
    },
    dataAccess: {
        header: "Aks がアクセスできるもの",
        title: "設計から分かりやすく。",
        description:
            "Aks は、あなたが提供した情報と、あなたが明確に連携を選んだデータソースだけを扱います。",
        sourcesSection: "連携中のソース",
        loadingSources: "連携中のソースを読み込み中…",
        loadError: "現在、連携中のソースを読み込めませんでした。",
        emptyTitle: "連携中のソースはまだありません",
        emptyBody:
            "Aks は、あなたが明確に連携した後にだけ外部サービスを読み取ります。連携はアカウント設定からいつでも管理できます。",
        connectedNeedsPermission: "連携中 · 権限が必要",
        connectedSynced: (relative: string) => `連携してデータを読み取り中 · ${relative}に同期`,
        connectedNotSynced: "連携してデータを読み取り中 · まだ同期していません",
        holdsSection: "AKS が保持している内容",
        items: [
            {
                title: "あなたが提供した情報",
                body: "プロフィール情報や設定など、Aks に直接入力した内容。",
            },
            {
                title: "振り返りとチェックイン",
                body: "経験、気分、集中、エネルギー、生活リズムを表すために作成した記録。",
            },
            {
                title: "実験データ",
                body: "あなたが作成した実験と、記録した結果やメモ。",
            },
            {
                title: "アカウント情報",
                body: "Aks アカウントを識別・管理するために必要な基本情報。",
            },
            {
                title: "連携したデータソース",
                body: "あなたが明確に連携を選んだサービスからの情報のみ。ただし、その連携が利用可能な場合に限ります。",
            },
        ],
        controlTitle: "あなたが管理しています",
        controlBody: "Aks は、あなたが入力または明確に連携した内容だけを使います。",
    },
    dataUsage: {
        header: "データがどう使われるか",
        title: "データには目的があります。",
        description:
            "Aks は製品内で情報を使い、あなたの体験をより関連性のある、分かりやすいものにします。",
        sections: [
            {
                title: "Aks がデータを使う理由",
                body: "共有を選んだ情報は、Aks が振り返りを個別化し、役立つテーマを見つけ、あなたの目標を支えるのに役立ちます。",
            },
            {
                title: "振り返りとチェックイン",
                body: "記録は、気分・エネルギー・集中・生活リズムの変化に文脈を与えます。",
            },
            {
                title: "パターンの検出",
                body: "Aks は、あなたが提供した情報を比較して、確認できる可能性のあるパターンを示せます。これは振り返りのきっかけであり、医学的な結論ではありません。",
            },
            {
                title: "記憶",
                body: "Aks は、繰り返し現れる役立つ文脈を少しだけ保持することがあります。記憶は常に、それを支える情報と結びついており、元の情報を削除せずに取り除けます。",
            },
            {
                title: "実験と結果",
                body: "実験の記録は、試したことと記録した結果を比べるのに役立ちます。",
            },
            {
                title: "AI による理解の支援",
                body: "AI は、あなたが提供した情報の整理や要約を助けることがあります。重要なインサイトは自分で確かめ、ご自身の判断で受け取ってください。",
            },
        ],
        privacyPolicyAction: "プライバシーポリシー全文を読む",
    },
    exportData: {
        header: "データをエクスポート",
        preparingTitle: "エクスポートを準備しています",
        preparingBody:
            "会話、振り返り、記憶、パターン、実験、インサイトを集めています。通常は数秒で完了します。",
        errorTitle: "データを持ち出しましょう。",
        errorBody: "ご請求に応じて、あなたの Aks 情報をダウンロードできる形で用意します。",
        failedTitle: "エクスポートを作成できませんでした。",
        failedFallback: "エクスポートの準備中に問題が発生しました。もう一度お試しください。",
        retryA11y: "エクスポートの作成をもう一度試す",
        cancelAction: "キャンセル",
        cancelA11y: "エクスポートの説明に戻る",
        readyTitle: "エクスポートの準備ができました。",
        readyBody:
            "たった今、あなたの Aks 情報のスナップショットを作成しました。ご請求時に表示された項目と同じ内容です。",
        expiresIn: (countdown: string) => `リンクは ${countdown} で失効します`,
        expiresSoon: "まもなく",
        saveAction: "エクスポートを保存",
        saveA11y: "エクスポートを保存",
        requestAnother: "もう一度エクスポートを請求",
        requestAnotherA11y: "もう一度エクスポートを請求",
        idleTitle: "データを持ち出しましょう。",
        idleBody:
            "ご請求に応じて、あなたの Aks 情報をダウンロードできる形で用意します。各エクスポートは 1 つのファイルで、請求した時点のアカウントの状態を反映します。",
        includedSection: "含まれる内容",
        included: [
            "プロフィールと設定",
            "会話とメッセージ",
            "振り返り",
            "チェックイン",
            "サイン",
            "記憶と根拠の関連",
            "パターンと根拠の関連",
            "実験と観察",
            "学びと参照元",
            "インサイトと参照元",
        ],
        requestAction: "データのエクスポートを請求",
        requestA11y: "エクスポートを請求",
    },
    deleteData: {
        header: "データを削除",
        title: "何も残さない。",
        description:
            "アカウントを削除すると、Aks で作成したデータが完全に削除されます。この端末からもログアウトされます。",
        warningTitle: "元に戻すことはできません。",
        warningBody:
            "アカウントを削除すると、Aks のデータは失われ、復元できません。コピーが必要な場合は、先にデータをエクスポートすることをご検討ください。",
        removedSection: "削除される内容",
        removed: [
            "会話とメッセージ",
            "振り返り",
            "チェックイン",
            "導き出されたサイン",
            "記憶と根拠の関連",
            "パターンと根拠の関連",
            "実験と観察",
            "学びと参照元",
            "インサイトと参照元",
        ],
        confirmA11y: "この操作が取り消せないことを確認する",
        confirmLabel: "この操作が取り消せず、Aks のすべてのデータが削除されることを理解しました。",
        deleteAction: "アカウントとデータを削除",
        deleteActionA11y: "アカウントとデータを削除",
        deletingAction: "アカウントを削除しています…",
        deletedTitle: "アカウントを削除しています。",
        deletedBody: "削除が完了するとログアウトされます。",
        backToSettings: "設定に戻る",
        backToSettingsA11y: "設定に戻る",
        keepAccount: "アカウントを残す",
        keepAccountA11y: "アカウントを残す",
        keepNote: "アカウントを削除すると、そのアカウント用に作成されたエクスポートファイルも削除されます。",
    },
    helpHome: {
        header: "ヘルプとフィードバック",
        title: "ご意見をお待ちしています。",
        description: "うまく動かない、分かりにくい、または Aks にこうしてほしいことがありますか？",
        supportTitle: "お困りですか？",
        supportBody: "サポートチームがお手伝いします。",
        supportAction: "サポートに問い合わせる",
        getHelpSection: "ヘルプを得る",
        faqTitle: "よくある質問",
        faqDescription: "よくある質問への答えをすばやく見つける",
        reportTitle: "問題を報告",
        reportDescription: "うまくいかないときはお知らせください",
        improveSection: "AKS をよりよくする",
        suggestTitle: "アイデアを提案",
        suggestDescription: "Aks に学んでほしいこと、してほしいことを教えてください",
        shareTitle: "体験を共有",
        shareDescription: "良いと感じたこと、もっと良くできることを教えてください",
        contactSection: "連絡先",
        supportEmail: "support@aks.ai",
        supportResponse: "通常 1〜2 営業日以内に返信します",
        footerVersion: "1.0.0",
    },
    faq: {
        header: "ヘルプとフィードバック",
        title: "よくある質問",
        description: "Aks の仕組みと、データの扱いについての答えをすばやく見つけられます。",
        searchPlaceholder: "質問を検索",
        clearSearch: "クリア",
        resultsCount: (count: number) => `${count} 件の結果`,
        popularSection: "よく見られる質問",
        questionsCount: (count: number) => `${count} 件の質問`,
        items: [
            {
                question: "Aks はどうやってパターンを見つけるのですか？",
                answer: "Aks は、あなたが共有を選んだ情報と振り返りの中から、役立つつながりを探します。",
            },
            {
                question: "Aks が使うデータを自分で選べますか？",
                answer: "はい。「あなたのデータ」と「プライバシー」から情報を確認し、利用できる権限を管理できます。",
            },
            {
                question: "実験はどう機能しますか？",
                answer: "実験は、小さな変化を試し、それが集中・エネルギー・睡眠・生活リズムにどう影響するかを振り返るのに役立ちます。",
            },
            {
                question: "通知の設定は変更できますか？",
                answer: "はい。「あなた」ページから「通知」を開き、Aks が連絡してよいタイミングを選べます。",
            },
            {
                question: "Aks は医療的な助言ですか？",
                answer: "いいえ。Aks は個人の振り返りを支えるもので、専門的な医療やメンタルヘルスの助言の代わりにはなりません。",
            },
        ],
        emptyTitle: "一致するものがありません",
        emptyBody: "別の検索語を試すか、上の質問をご覧ください。",
        clearAction: "検索をクリア",
        helpTitle: "まだお困りですか？",
        helpBody: "状況を教えていただければ、一緒に整理します。",
        contactAction: "問い合わせる",
    },
    sendFeedback: {
        header: "フィードバックを送信",
        title: "Aks を一緒に育てましょう。",
        description: "アイデア、機能のご要望、すでに良いと感じていることをお聞かせください。",
        optionLabel: "フィードバックの種類",
        optionHint: "ひとつ選ぶ",
        options: ["アイデア", "機能の要望", "一般的な感想", "良かった点"],
        initialOption: "一般的な感想",
        messageLabel: "あなたのフィードバック",
        messagePlaceholder: "どんなことがあると Aks がもっと役立ちますか？",
        messageHint: "アイデア、提案、良かった点、どれでも歓迎します。",
        emailHint: "返信が必要な場合のみメールアドレスをご記入ください。",
        noteTitle: "あなたの声は大切です。",
        noteBody: "共有いただいた内容は、Aks の次の姿を決めるのに役立ちます。",
        submit: "フィードバックを送信",
        leaveMessage: "何も送信せずにこのページを離れられます。",
    },
    reportProblem: {
        header: "問題を報告",
        title: "何が起きましたか？",
        description:
            "起きたことを教えてください。背景が多いほど、私たちが理解して修正しやすくなります。",
        optionLabel: "問題の種類",
        optionHint: "ひとつ選ぶ",
        options: [
            "動作しない機能がある",
            "アプリがクラッシュした",
            "インサイトが正しくない",
            "データの問題",
            "通知の問題",
            "その他",
        ],
        messageLabel: "何が起きましたか？",
        messagePlaceholder: "期待したことと、実際に起きたことを書いてください…",
        messageHint: "問題が起きた手順があれば添えてください。",
        emailHint: "こちらから連絡する場合のみメールアドレスをご記入ください。",
        noteTitle: "Aks の改善にご協力ありがとうございます。",
        noteBody: "ご報告は、すべての人にとって Aks をより信頼できるものにする助けになります。",
        submit: "報告を送信",
        leaveMessage: "送信せずにこのページを離れられます。",
    },
    feedbackForm: {
        selectedState: "選択中",
        contactEmail: "連絡先メール",
        optionalMark: "（任意）",
        emailPlaceholder: "you@example.com",
        charLimit: 1000,
    },
    profilePreference: {
        saveAction: "設定を保存",
        saveA11y: (title: string) => `${title}を保存`,
        noteCaption: "プロフィールに保存されました",
        noteBody: "あなたの選択はプロフィールに保存されます。",
        notices: {
            unableToSave: "設定を保存できませんでした",
        },
    },
    dataCategory: {
        recentSection: "最近",
        loadingA11y: (title: string) => `${title}を読み込み中`,
        loadErrorTitle: "このデータを読み込めませんでした。",
        tryAgain: "もう一度試す",
        loadMore: "さらに読み込む",
        noteCaption: "AKS からのメモ",
        noteBody: "作成した記録はここに表示されます。",
    },
    bottomSheet: {
        dismissA11y: "閉じる",
        defaultConfirm: "わかりました",
        cancel: "キャンセル",
    },
    connectedSources: {
        header: "連携中のソース",
        eyebrow: "文脈と権限",
        title: "Aks が何を知るかはあなたが決めます。",
        description:
            "どのソースを連携しなくても Aks は問題なく使えます。各ソースは任意で独立しており、共有する内容を明示します。いつでも解除できます。",
        loadingA11y: "ソースを読み込み中",
        loadError: "連携中のソースを読み込めませんでした。",
        status: {
            connected: "連携中",
            permissionRequired: "権限が必要",
            notConnected: "未連携",
            notAvailable: "この端末では利用できません",
            revoked: "解除済み",
            temporarilyUnavailable: "一時的に利用できません",
            error: "現在利用できません",
        },
        syncedAgo: (relative: string) => `${relative}に同期`,
        notSynced: "まだ同期していません",
        whyHelps: "なぜ役立つのか",
        whatReceives: "AKS が受け取るもの",
        whatStored: "保存されるもの",
        howToStop: "停止する方法",
        goodToKnow: "知っておきたいこと",
        disconnect: "連携を解除",
        deleteData: "取り込んだデータを削除",
        allow: "許可",
        connect: "連携する",
        reconnect: "再接続",
        choiceSection: "あなたの選択",
        choiceBody: "連携したソースだけが使われます。いつでもワンタップで停止できます。",
        confirmations: {
            cancelAction: "キャンセル",
        },
        notices: {
            providerNotConfigured: "このビルドではそのプロバイダーはまだ設定されていません。",
            unableToConnect: "現在そのソースに接続できませんでした。",
        },
        groups: {
            productivity: "生産性",
            work: "仕事",
            device: "端末 / 行動",
        },
    },
    sources: {
        location: {
            name: "位置情報",
            purpose:
                "Aks があなたの一日がどこで起きているかを理解できるようにします。つらい一日と、移動や予期しない変化で乱れた一日を区別する助けになります。",
            receives:
                "おおよその場所の文脈（自宅周辺、職場周辺、移動、見慣れない場所）と時間帯 — 継続的な追跡は行いません。",
            stored: "「移動、18:30 前後 45 分」のような観察の時間枠。正確な座標は保存しません。",
            stop: "位置情報はいつでも解除できます。今後の取得はすぐに停止し、保存済みの観察は別途削除できます。",
            batteryNote:
                "連携中はときどき位置を確認します。オンにするとバッテリー消費が少し増えることがあります。",
        },
        calendar: {
            name: "カレンダー",
            purpose:
                "予定されている出来事があると、Aks は「予定が変わった」と「やる気が落ちた」を区別しやすくなります。",
            receives:
                "予定の時刻と大まかなカテゴリ。タイトルは予定を定義する場合のみ使用し、参加者リスト・メモ・会議リンクは読み取りません。",
            stored: "最小限の予定記録：時刻、長さ、カテゴリ、確定/キャンセル。",
            stop: "カレンダーはいつでも解除できます。今後の取得はすぐに停止します。",
        },
        reminders: {
            name: "タスクとリマインダー",
            purpose:
                "予定していた行動と実際に起きたこと — Aks が「やらなかった」と決めつけることはありません。",
            receives: "同期を選んだリマインダーの期限と完了状態。",
            stored: "期限と完了/未記録の状態。",
            stop: "タスクとリマインダーはいつでも解除できます。",
        },
        screenTime: {
            name: "スクリーンタイム",
            purpose:
                "集計された端末利用の文脈が集中の変化を説明することがあります — 気が散っていた証拠として扱うことはありません。",
            receives: "時間帯ごとの、大まかなカテゴリ別の利用時間（集計）。",
            stored: "「SNS アプリ、60 分、21:00〜22:00」のような集計された時間枠。操作単位のデータはありません。",
            stop: "スクリーンタイムはいつでも解除できます。",
        },
        googleCalendar: {
            name: "Google カレンダー",
            purpose:
                "Google の予定は、あなたが明確に連携したアカウントについて、端末のカレンダーと同じ計画の文脈を Aks に与えます。",
            receives:
                "選択したカレンダーの予定時刻と大まかなカテゴリ。参加者リスト・メモ・会議リンクは読み取りません。",
            stored: "最小限の予定記録：時刻、長さ、カテゴリ、確定/キャンセル。",
            stop: "Google カレンダーはいつでも解除できます — Google アカウントの設定でアクセスも取り消してください。",
        },
        appleCalendar: {
            name: "Apple カレンダー",
            purpose: "iPhone と iPad では、Apple のカレンダーストアを通じて同じ端末カレンダーの文脈を得られます。",
            receives: "予定の時刻と大まかなカテゴリ。参加者リスト・メモ・会議リンクは読み取りません。",
            stored: "最小限の予定記録：時刻、長さ、カテゴリ、確定/キャンセル。",
            stop: "Apple カレンダーはいつでも解除できます。",
        },
        googleTasks: {
            name: "Google ToDo リスト",
            purpose:
                "連携した Google アカウントの予定タスクにより、Aks はあなたの意図を見られます — 失敗したと断定することはありません。",
            receives: "タスクの期限と完了状態。",
            stored: "期限と完了/未記録の状態。",
            stop: "Google ToDo リストはいつでも解除できます — Google アカウントの設定でアクセスも取り消してください。",
        },
        appleReminders: {
            name: "Apple リマインダー",
            purpose:
                "iPhone と iPad では、Apple リマインダーの予定行動が同じ「予定と実際」の文脈になります。",
            receives: "リマインダーの期限と完了状態。",
            stored: "期限と完了/未記録の状態。",
            stop: "Apple リマインダーはいつでも解除できます。",
        },
        notion: {
            name: "Notion",
            purpose:
                "あなたが Aks 連携と明確に共有したページやデータベースにより、仕事の文脈が会話に活かされます。",
            receives:
                "Aks の Notion 連携と共有した内容のタイトル、時刻、大まかなカテゴリ。ページ本文は読み取りません。",
            stored: "最小限の項目記録：タイトルのカテゴリ、時刻、状態。",
            stop: "Notion はいつでも解除できます — Notion ワークスペースから Aks 連携も削除してください。",
        },
        todoist: {
            name: "Todoist",
            purpose: "連携したタスクサービス（Todoist など）により、Aks の外の予定も含めて考えられます。",
            receives: "タスクの期限と完了状態。",
            stored: "期限と完了/未記録の状態。",
            stop: "Todoist はいつでも解除できます — プロバイダーのアカウント設定でアクセスも取り消してください。",
        },
        github: {
            name: "GitHub",
            purpose: "あなた自身のコミットと PR の活動を、客観的な仕事の文脈として — 他人のデータは扱いません。",
            receives: "選択したリポジトリでの、あなたのコミットとプルリクエストの件数と時刻。",
            stored: "「2 件のコミット、22:00〜23:00」のような集計された活動時間枠。コードの内容は含みません。",
            stop: "GitHub はいつでも解除できます — GitHub の設定で Aks の OAuth アプリも取り消してください。",
        },
        slack: {
            name: "Slack",
            purpose: "あなたが明確に連携したワークスペースからの、集中時間と状態のサイン。",
            receives: "あなた自身の活動時間と取り込み中（DND）の状態。メッセージの内容は読み取りません。",
            stored: "集計された活動時間枠。メッセージ、チャンネル、同僚のデータは含みません。",
            stop: "Slack はいつでも解除できます — ワークスペースから Aks アプリも削除してください。",
        },
        email: {
            name: "メール",
            purpose: "連携したプロバイダー（Gmail など）からの、軽いメール負荷の文脈（件数のみ）。",
            receives: "受信メールの件数と時間帯。件名・本文・送信者は読み取りません。",
            stored: "時間枠ごとの集計件数。内容もアドレスも保存しません。",
            stop: "メールはいつでも解除できます — プロバイダーのセキュリティ設定でアクセスも取り消してください。",
        },
        voiceSession: {
            name: "マイク",
            purpose:
                "音声会話はあなたが明示的に開始する行動です。マイクは音声セッション中のみ使われます。",
            receives: "音声会話が動作している間のみ音声。",
            stored: "あなたが残した文字起こし。音声は保存されません。",
            stop: "音声セッションを終了するとマイクがオフになります。Aks がバックグラウンドで聞くことはありません。",
        },
    },
    transparency: {
        connectedWith: (sources: string) =>
            `${sources}を連携しているため、Aks はここで共有した内容とあわせてその文脈も見られます。`,
        names: {
            location: "位置情報",
            calendar: "カレンダー",
            googleCalendar: "Google カレンダー",
            appleCalendar: "Apple カレンダー",
            reminders: "タスク",
            googleTasks: "Google ToDo リスト",
            appleReminders: "Apple リマインダー",
            todoist: "Todoist",
            notion: "Notion",
            github: "GitHub",
            slack: "Slack",
            email: "メール",
            screenTime: "スクリーンタイム",
            voiceSession: "音声",
        },
    },
    oauth: {
        googleCalendar: "Google カレンダー",
        googleTasks: "Google ToDo リスト",
        notion: "Notion",
        todoist: "Todoist",
        github: "GitHub",
        slack: "Slack",
        email: "メール",
    },
    errors: {
        pagedData: "このデータを読み込めませんでした。もう一度お試しください。",
        pagedDataMore: "これ以上データを読み込めませんでした。もう一度お試しください。",
        dataSummary: "データの概要を読み込めませんでした。もう一度お試しください。",
        dataAccess: "連携中のソースを読み込めませんでした。もう一度お試しください。",
        memory: "この記憶を読み込めませんでした。",
        pattern: "このパターンを読み込めませんでした。",
        experiment: "この実験を読み込めませんでした。",
        learning: "この学びを読み込めませんでした。",
        insight: "このインサイトを読み込めませんでした。",
        conversation: "この会話を読み込めませんでした。もう一度お試しください。",
        conversationEarlier: "以前のメッセージを読み込めませんでした。もう一度お試しください。",
        conversationPlain: "この会話を読み込めませんでした。",
        conversationEarlierPlain: "以前のメッセージを読み込めませんでした。",
        messageEmptySave: "保存する前に内容を入力してください。",
        exportLinkExpired: "エクスポートのリンクが失効しました。もう一度請求してください。",
        renameConversation: "その会話の名前を変更できませんでした。もう一度お試しください。",
        exportExpired: "エクスポートのリンクが失効しました。もう一度請求してください。",
        exportCreate: "エクスポートを作成できませんでした。もう一度お試しください。",
        exportDownload: "エクスポートをダウンロードできませんでした。もう一度お試しください。",
        deleteAccount: "現在アカウントの削除はご利用いただけません。しばらくしてからもう一度お試しください。",
        preferences: "設定を読み込めませんでした。",
        appSetup: "アカウントの設定を完了できませんでした。もう一度お試しください。",
        exportSaveTitle: "Aks のエクスポートを保存",
        exportClearDevice: "アカウントデータを削除していますが、この端末のクリアにはもう一度試す必要があります。",
        shareUnavailable: "この端末では共有を利用できません。もう一度お試しください。",
        exportIncomplete: "エクスポートの応答が不完全でした。もう一度お試しください。",
        exportInterrupted: "ダウンロードが中断されました。もう一度お試しください。",
        exportGeneric: "問題が発生しました。もう一度お試しください。",
        connectedSources: "連携中のソースを読み込めませんでした。",
        sourceUnavailable: "このソースはお使いの端末では利用できません。",
        sourcePermission: "このソースを連携するには権限が必要です。あとでもう一度お試しください。",
        sourceConnect: "そのソースに接続できませんでした。",
        sourceDisconnect: "そのソースの連携を解除できませんでした。",
        sourceDelete: "そのソースのデータを削除できませんでした。",
        oauthRecord: "その連携を記録できませんでした。",
        oauthDisconnect: "そのアカウントの連携を解除できませんでした。",
        webPage: "このページを読み込めませんでした。",
        webPageBody: "インターネット接続を確認して、もう一度お試しください。",
        generic: "問題が発生しました。もう一度お試しください。",
        signInUnavailable: "現在ログインをご利用いただけません。しばらくしてからもう一度お試しください。",
        signInStart: "ログインを開始できませんでした。",
        authRequest: "そのリクエストを完了できませんでした。もう一度お試しください。",
        storeUnreachable: "ストアに接続できませんでした。接続を確認して、もう一度お試しください。",
        plansUnavailable: "現在利用できるプランがありません。しばらくしてからもう一度お試しください。",
        planUnavailable: "そのプランは現在利用できません。しばらくしてからもう一度お試しください。",
        storeFailed: "ストアがリクエストを完了できませんでした。もう一度お試しください。",
        subscriptionGeneric: "サブスクリプションの処理中に問題が発生しました。もう一度お試しください。",
        purchaseCancelled: "購入はキャンセルされました。請求は発生していません。",
        purchasePending: "購入はストアの確認待ちです。完了するとここに表示されます。",
        alreadySubscribed: "このプランはすでにご利用中です。",
        checkoutPendingPremium:
            "購入手続きは完了しましたが、アカウントで Premium がまだ有効になっていません。エミュレーターの Test Store での購入では Premium は有効になりません — Play ストアのある端末をご利用ください。それ以外の場合は少し待ってから「購入を復元」をお試しください。",
        restoreEmpty: "復元できる過去の購入が見つかりませんでした。",
        emptyMessage: "送信する前に内容を入力してください。",
        mirror: {
            noReply: "Aks はまだ最後のメッセージに返信していません。",
            unsavedRetry: "最後のメッセージの保存が完了していない可能性があります。安全に再試行できます。",
            resolvePending: "次のメッセージを送る前に、前のメッセージを再試行するか解決してください。",
            refreshFailed: "Aks はその返信を更新できませんでした。前の内容はそのまま残っています。",
            refreshFailedConversation:
                "Aks は何度か試しましたが、この返信を完了できませんでした。あなたのメッセージは保存されています。",
            refreshFailedUnsafe: "Aks はその返信を安全に解釈できませんでした。あなたのメッセージは保存されています。",
            refreshFallback: "Aks は今その内容を処理できませんでした。あなたのメッセージは保存されています。",
            updateMessage: "そのメッセージを更新できませんでした。すでに Aks の返信がある可能性があります。",
            checkInFailed: "チェックインを保存できませんでした。もう一度お試しください。",
            saveFailed: "メッセージを保存できませんでした。接続を確認して、もう一度お試しください。",
            outboxQueued: "この端末に保存しました。オンラインに戻ると Aks が送信します。",
            signInForVoice: "音声会話はログイン後に利用できます。",
            voiceStartFailed: "音声会話を開始できませんでした。",
        },
        voice: {
            realtimeNotConfigured: "このビルドでは音声会話はまだ設定されていません。",
            sessionUnavailable: "音声セッションを開始できませんでした。もう一度お試しください。",
            transportUnavailable: "この会話オプションには Aks の開発ビルドが必要です。",
            audioUnavailable: "ライブ音声には Aks のオーディオエンジンを含む開発ビルドが必要です。",
            micDenied: "音声会話にはマイクの許可が必要です。",
            transcriptionFailed: "Aks はあなたの言葉を聞き取れませんでした。もう一度お試しください。",
            providerError: "Aks は現在音声会話を開始できません。",
            sessionExpired: "音声セッションの期限が切れました。再接続して続けてください。",
            voiceFailed: "音声会話に失敗しました。",
            saveVoiceMessage: "音声メッセージを保存できませんでした。このセッション内にのみ残ります。",
            saveVoiceReply: "Aks の返信を保存できませんでした。このセッション内にのみ残ります。",
            audioCaptureFailed: "音声の取り込みに失敗しました。",
            audioFailed: "音声で問題が発生しました。",
        },
        writes: {
            signInRequired: "続けるにはログインしてください。",
            experimentInvalid: "実験の応答が無効でした。",
            observation: "その観察を保存できませんでした。",
            reflection: "その振り返りを保存できませんでした。",
            message: "そのメッセージを保存できませんでした。",
            checkIn: "そのチェックインを保存できませんでした。",
            insightUpdate: "このインサイトを更新できませんでした。",
            experimentUpdate: "この実験を更新できませんでした。",
            startConversation: "その会話を開始できませんでした。",
            sendMessage: "メッセージを保存できませんでした。",
            confirmMessage: "保存したメッセージを確認できませんでした。",
            searchConversations: "会話を検索できませんでした。",
            updateConversation: "その会話を更新できませんでした。",
            updateMessage: "そのメッセージを更新できませんでした。",
            confirmUpdatedMessage: "更新したメッセージを確認できませんでした。",
            archiveConversation: "その会話をアーカイブできませんでした。",
            archivePattern: "このパターンをアーカイブできませんでした。",
            removePattern: "このパターンを削除できませんでした。",
            archiveMemory: "この記憶をアーカイブできませんでした。",
            removeMemory: "この記憶を削除できませんでした。",
            archiveLearning: "この学びをアーカイブできませんでした。",
            removeLearning: "この学びを削除できませんでした。",
        },
    },
    timelineEntries: {
        patternForming: "パターン形成中",
        insight: "インサイト",
        newLearning: "新しい学び",
        outcomeRecorded: "結果を記録",
        experimentStarted: "実験を開始",
        experimentActive: "実験 実施中",
        reflection: "振り返り",
        checkIn: "チェックイン",
        experimentOutcomeTitle: "実験の結果を記録しました",
        reflectionTitle: "振り返りを記録しました",
    },
};

export default ja;
