import type { Translation } from "@/constants/copy";
import type { DayPart } from "@/lib/dayPart";

/**
 * Korean translation.
 *
 * Every key of the English source of truth is required; the compiler rejects
 * missing or extra keys. Uses the polite 해요체 register throughout, the
 * standard voice for Korean consumer apps talking to a user. Proper nouns keep
 * their official Korean or Latin forms (Aks, Mirror, Premium, Google 캘린더,
 * Google Tasks, Apple 캘린더, Apple 미리 알림, Notion, GitHub, Slack, Todoist).
 *
 * Typography: Korean punctuation (、 → , 。 → . 「」 → " ") with a space between
 * Hangul and Latin words or numerals, and 24-hour times. Counts use counters
 * rather than plurals (관찰 3건). Mirror's deliberately hedged language survives
 * translation — possible patterns are 가능성 있는 패턴 and observations stay
 * 되돌아보기 위한 신호이며 의학적 결론이 아닙니다.
 */
const ko: Translation = {
    common: {
        back: "뒤로",
        cancel: "취소",
        save: "저장",
        dismiss: "닫기",
        clear: "지우기",
        loading: "불러오는 중…",
        tryAgain: "다시 시도",
        loadMore: "더 불러오기",
        pleaseTryAgain: "다시 시도해 주세요.",
        checkConnection: "연결을 확인하고 다시 시도해 주세요.",
        emailPlaceholder: "you@example.com",
        justNow: "방금",
        dateUnavailable: "날짜를 확인할 수 없음",
        version: (value: string) => `버전 ${value}`,
    },
    brand: {
        name: "Aks.ai",
        tagline: "나를 다른 각도에서 이해하기.",
    },
    splash: {
        appName: "Aks.ai",
        subtitle: "나를 다른 각도에서 이해하기.",
    },
    onboarding: {
        skip: "건너뛰기",
        moveForward: "다음",
        getStarted: "시작하기",
        notices: {
            unableToContinue: "계속할 수 없습니다",
        },
        slides: [
            {
                eyebrow: "일상은 이미 신호를 남깁니다",
                title: "당신은 이미\n자신에 대한 단서를 남기고 있어요.",
                description:
                    "반복하는 것. 피하게 되는 순간. 뭔가 다르게 느껴지는 날. Aks는 그런 신호를 모읍니다.",
            },
            {
                eyebrow: "돌아보는 데서 멈추지 않기",
                title: "짐작하지 않고,\n직접 시도합니다.",
                description:
                    "직감을 작은 실험으로 바꿔 보세요. 한 가지를 바꾸고, 어떤 일이 일어나는지 살피며, 실제로 나에게 맞는 방법을 찾습니다.",
            },
            {
                eyebrow: "더 또렷한 나",
                title: "자신이\n미지의 존재로 남지 않도록.",
                description:
                    "시간이 쌓이면 Aks는 당신의 패턴, 반응, 그리고 변화를 만드는 요인에 대한 살아 있는 그림을 그려 갑니다.",
            },
        ],
    },
    legal: {
        termsTitle: "이용약관",
        privacyTitle: "개인정보 처리방침",
        acceptance: {
            title: "시작하기 전에.",
            description:
                "Aks는 개인적인 정보를 다루면서 스스로의 패턴을 알아차리도록 돕습니다. 계속하기 전에 알아 두면 좋은 내용이 있어요.",
            cardTitle: "당신의 데이터는 당신의 것입니다.",
            cardBody: "Aks는 당신이 공유하기로 선택한 정보를 사용해 패턴을 찾고 개인 실험을 돕습니다.",
            bullets: [
                "무엇을 공유할지는 스스로 정할 수 있습니다.",
                "데이터와 권한은 언제든 직접 관리할 수 있습니다.",
                "Aks는 전문적인 의료 또는 정신 건강 조언을 대신하지 않습니다.",
            ],
            agreePrefix: "Aks.ai의",
            terms: "이용약관",
            andWord: "및",
            privacy: "개인정보 처리방침",
            continue: "Aks 시작하기",
            retryAction: "재시도",
            retry: "재시도",
            footnote: "이 문서들은 설정에서 언제든 다시 볼 수 있습니다.",
            consentA11y: "이용약관과 개인정보 처리방침에 동의합니다",
            notices: {
                unableToSave: "동의를 저장할 수 없습니다",
            },
        },
        links: {
            prefix: "계속하면 Aks.ai의",
            terms: "이용약관",
            andWord: "및",
            privacy: "개인정보 처리방침에 동의한 것으로 간주됩니다.",
        },
    },
    login: {
        title: "다시 오셨네요.",
        description: "로그인하고 Aks가 당신에 대해 알아차린 것들을 계속 확인해 보세요.",
        emailLabel: "이메일 주소",
        sendLink: "로그인",
        sendLinkA11y: "로그인 링크 보내기",
        secureLinkNote: "안전한 로그인 링크를 이메일로 보내 드립니다. 비밀번호는 필요하지 않습니다.",
        divider: "또는 다음으로 계속하기",
        google: "Google",
        googleA11y: "Google로 계속하기",
        facebook: "Facebook",
        facebookA11y: "Facebook으로 계속하기",
        github: "GitHub로 계속하기",
        githubA11y: "GitHub로 계속하기",
        noAccount: "계정이 없으신가요?",
        createOne: "만들기",
        dismissError: "닫으려면 탭하세요.",
        notices: {
            unableToSendLink: "로그인 링크를 보낼 수 없습니다",
            unableToSignIn: "로그인할 수 없습니다",
        },
    },
    register: {
        title: "계정을 만들어 보세요.",
        description: "Aks와 함께 자신을 더 또렷하게 바라봐요.",
        nameLabel: "이름",
        namePlaceholder: "이름",
        nameA11y: "이름",
        emailLabel: "이메일 주소",
        createAccount: "계정 만들기",
        createAccountA11y: "이메일 주소로 계정 만들기",
        secureLinkNote: "안전한 로그인 링크를 이메일로 보내 드립니다. 비밀번호는 필요하지 않습니다.",
        divider: "또는 다음으로 가입하기",
        google: "Google",
        googleA11y: "Google로 계속하기",
        facebook: "Facebook",
        facebookA11y: "Facebook으로 계속하기",
        github: "GitHub로 계속하기",
        githubA11y: "GitHub로 계속하기",
        hasAccount: "이미 계정이 있으신가요?",
        signIn: "로그인",
        dismissError: "닫으려면 탭하세요.",
        notices: {
            unableToCreate: "계정을 만들 수 없습니다",
            unableToSignIn: "로그인할 수 없습니다",
        },
    },
    emailConfirmation: {
        title: "이메일을 확인해 주세요.",
        body: (email: string) =>
            `안전한 로그인 링크를 ${email}로 보냈습니다. 이 기기에서 링크를 열어 계속해 주세요.`,
        resendNote: "다시 보내면 가장 최근 링크만 유효합니다.",
        resend: "링크 다시 보내기",
        resendA11y: "로그인 링크 다시 보내기",
        editEmail: "이메일 주소 변경",
        editEmailA11y: "이메일 주소 변경",
    },
    mirror: {
        eyebrow: "MIRROR",
        greeting: (firstName: string | null, part: DayPart = "morning") => {
            const base =
                part === "afternoon"
                    ? "좋은 오후예요"
                    : part === "evening"
                        ? "좋은 저녁이에요"
                        : part === "night"
                            ? "편안한 밤 되세요"
                            : "좋은 아침이에요";
            return `${base}${firstName ? `, ${firstName}님` : ""}.`;
        },
        intro: "Aks예요. 작은 것부터 시작해 볼까요.",
        understandTitle: "무엇을 이해하고 싶으신가요?",
        differentHint: "전혀 다른 이야기를 Aks에게 해도 괜찮아요.",
        checkInEyebrow: "빠른 체크인",
        checkInTitle: "오늘 기분은 어떠세요?",
        topics: ["집중", "에너지", "수면", "감정", "생활 리듬", "관계", "생산성"],
        topicDraft: (topic: string) => `제 ${topic}에 대해 이해하고 싶어요.`,
        checks: ["좋아요", "그저 그래요", "정신없어요"],
        aksLabel: "AKS",
        errorTitle: "문제가 발생했어요.",
        retryResponse: "답변 다시 시도",
        listening: "듣는 중…",
        listeningMeta: (duration: string) => `${duration} · 이 기기에만 저장됩니다`,
        stopRecordingA11y: "녹음 중지",
        voiceReady: "음성 되돌아보기가 준비되었어요",
        voiceReadyHint: "Aks가 이를 되돌아보기로 옮겨 적습니다.",
        discardRecordingA11y: "녹음 버리기",
        sendRecordingA11y: "녹음 보내기",
        composerPlaceholder: "지금 떠오르는 생각을 Aks에게 이야기해 주세요…",
        sendMessageA11y: "메시지 보내기",
        recordVoiceA11y: "음성 되돌아보기 녹음",
        notices: {
            micUnavailable: "마이크를 사용할 수 없습니다",
            micUnavailableBody:
                "음성 되돌아보기를 녹음하려면 마이크 권한이 필요합니다. 직접 입력해도 괜찮아요.",
            cantListen: "듣기를 시작할 수 없습니다",
            cantListenBody: "다시 시도하거나 생각을 직접 적어 주세요.",
            stopRecording: "녹음을 중지할 수 없습니다",
            recordingFailed: "그 녹음을 저장할 수 없습니다",
            transcriptionNotConfigured: "이 빌드에서는 음성 되돌아보기를 아직 사용할 수 없습니다. 직접 적어 주세요.",
            audioTooLong: "녹음이 너무 깁니다. 더 짧게 다시 시도해 주세요.",
            subscriptionRequired:
                "음성 되돌아보기는 Aks Premium이 필요해서 이 녹음은 사용되지 않았습니다. 직접 입력할 수도 있어요.",
            emptyTranscription: "Aks가 그 녹음에서 아무것도 듣지 못했습니다. 마이크를 확인하고 다시 시도해 주세요.",
            unsupportedAudio: "이 녹음 형식은 지원되지 않습니다. 다시 녹음해 주세요.",
            transcriptionUnavailable: "Aks가 지금 그 녹음을 들을 수 없습니다. 다시 시도하거나 직접 적어 주세요.",
            unauthorized: "로그인한 뒤 다시 시도해 주세요.",
            recordingFailedFallback:
                "Aks가 지금 그 녹음을 저장할 수 없습니다. 다시 시도하거나 직접 적어 주세요.",
        },
    },
    mirrorBar: {
        newConversation: "새 대화",
        composerPlaceholder: "지금 떠오르는 생각을 Aks에게 이야기해 주세요…",
        sendMessageA11y: "메시지 보내기",
        closeComposerA11y: "입력창 닫기",
        openKeyboardA11y: "키보드 열기",
        stopVoiceA11y: "음성 대화 종료",
        startVoiceA11y: "음성 대화 시작",
        voiceOffA11y: "음성 답변 끄기",
        voiceOnA11y: "음성 답변 켜기",
        moreOptionsA11y: "대화 추가 옵션",
        hint: "생각을 정리한 뒤에 말할 필요는 없어요. 먼저 말을 꺼내 보세요.",
    },
    aiConversation: {
        greeting: (firstName: string | null) => (firstName ? `안녕하세요, ${firstName}님 👋` : "안녕하세요 👋"),
        openingPrompts: [
            "요즘 머릿속을 떠나지 않는 게 있나요?",
            "오늘 기분은 어떠세요?",
            "요즘 계속 마음에 걸리는 일이 있나요?",
            "무엇이 머릿속을 차지하고 있나요?",
            "마음에 걸리는 걸 이야기해 볼까요?",
            "누군가에게 털어놓고 싶은 게 있나요?",
            "요즘 무엇이 무겁게 느껴지나요?",
            "하고 싶었지만 하지 못한 말이 있나요?",
        ],
        copyAction: "복사",
        copiedAction: "복사됨",
        copyA11y: "메시지 복사",
        shareAction: "공유",
        shareA11y: "메시지 공유",
        tryAgainAction: "다시 시도",
        tryAgainA11y: "이 답변 다시 생성",
        motionReadyA11y: "Aks가 준비되었습니다",
        thinking: "생각하는 중…",
        thinkingDefault: "Aks가 생각하는 중…",
        aksTag: "aks",
        youTag: "나",
        listening: "듣는 중…",
        speaking: "말하는 중…",
        loadingConversation: "대화를 불러오는 중…",
        youPrefix: "나: ",
        errorTitle: "문제가 발생했어요.",
        retryResponse: "답변 다시 시도",
        voicePaused: "음성을 일시중지했습니다.",
        editPlaceholder: "메시지를 다시 작성…",
        saveAndSend: "저장하고 보내기",
        saveAndSendA11y: "수정한 메시지 저장하고 보내기",
        cancelEditingA11y: "수정 취소",
        cancel: "취소",
        editMessage: "메시지 수정",
        editMessageA11y: "내 메시지 수정",
    },
    timeline: {
        header: "타임라인",
        headerCaption: "Aks와 함께 걸어온 길.",
        eyebrow: "당신의 여정",
        title: "당신의 이야기는 계속됩니다.",
        description: "Aks와 함께한 시간을 만들어 온 순간, 패턴, 실험, 배움을 여기에서 볼 수 있습니다.",
        errorTitle: "타임라인을 불러올 수 없습니다.",
        errorBody: "당신의 이야기는 여기에 있습니다. 잠시 후 다시 시도해 주세요.",
        loadMoreError: "더 불러올 수 없습니다.",
        empty: {
            allTitle: "당신의 이야기는 아직 이어지고 있습니다.",
            allBody: "Aks와 이야기를 나누다 보면 의미 있는 순간과 패턴, 실험, 배움이 여기에 나타납니다.",
            insightsTitle: "아직 인사이트가 없습니다.",
            insightsBody: "Aks가 시간을 두고 충분한 근거를 찾으면 의미 있는 인사이트가 여기에 나타납니다.",
            experimentsTitle: "아직 실험이 없습니다.",
            experimentsBody: "직접 설정한 실험은 진행하면 여기에 나타납니다.",
            checkInsTitle: "아직 체크인이 없습니다.",
            checkInsBody: "의미 있는 체크인이 여기에 나타납니다.",
            decisionsTitle: "아직 결정이 없습니다.",
            decisionsBody: "Aks가 알아차린 결정과 패턴은 형태가 잡히면 여기에 나타납니다.",
            learningsTitle: "아직 배움이 없습니다.",
            learningsBody: "당신의 이야기가 더 또렷해지면 새로운 배움이 여기에 나타납니다.",
        },
    },
    you: {
        title: "나",
        fallbackName: "Aks 멤버",
        subtitle: "나만의 공간",
        knowsTitle: "Aks가 알고 있는 것",
        knowsEmpty: "아직 당신을 알아 가는 중이에요",
        memoriesCount: (count: number) => `기억 ${count}개`,
        exploringTitle: "지금 살펴보는 것",
        exploringEmpty: "관심사 선택",
        unnoticedTitle: "아직 알아차리지 못한 것",
        insightsCount: (count: number) => `살펴볼 만한 인사이트 ${count}개`,
        insightsEmpty: "아직 정해지지 않았어요",
        journeySection: "당신의 여정",
        patternsTitle: "패턴",
        patternsDescription: "Aks가 알아차린 것",
        experimentsTitle: "실험",
        experimentsDescription: "지금 시도 중인 것",
        yourDataTitle: "내 데이터",
        yourDataDescription: "정보를 보고 관리하기",
        preferencesSection: "설정",
        notificationsTitle: "알림",
        notificationsDescription: "Aks가 언제 연락할지",
        appearanceTitle: "화면 모드",
        appearanceDescription: "시스템 · 라이트 · 다크",
        privacyTitle: "개인정보",
        privacyDescription: "권한과 개인정보 관리",
        supportSection: "지원",
        helpTitle: "도움말 및 피드백",
    },
    settings: {
        header: "설정",
        eyebrow: "설정",
        title: "나에게 맞는 Aks로.",
        description: "계정, 요금제, Aks에 대한 정보를 관리합니다.",
        accountSection: "계정",
        profileTitle: "프로필",
        profileDescription: "개인 정보 관리하기",
        accountTitle: "계정",
        accountDescription: "로그아웃 또는 계정 삭제",
        subscriptionTitle: "구독",
        subscriptionDescription: "Aks 요금제와 결제 관리하기",
        preferencesSection: "설정",
        languageTitle: "언어",
        aboutSection: "Aks 정보",
        aboutTitle: "Aks 정보",
        aboutDescription: "Aks에 대해 더 알아보기",
        termsTitle: "이용약관",
        privacyTitle: "개인정보 처리방침",
    },
    profile: {
        header: "프로필",
        fallbackName: "Aks 멤버",
        fallbackEmail: "이메일 주소를 확인할 수 없음",
        editName: "이름 수정",
        editNameA11y: "이름 수정",
        changePhotoA11y: "프로필 사진 변경",
        photoA11y: "프로필 사진",
        photoSheetTitle: "프로필 사진",
        chooseImage: "이미지 선택",
        removePhoto: "사진 삭제",
        aksSection: "Aks",
        exploringTitle: "지금 살펴보는 것",
        exploringEmpty: "설정되지 않음",
        noticeTitle: "Aks가 주목해야 할 것",
        noticeEmpty: "설정되지 않음",
        preferencesSection: "설정",
        timezoneTitle: "시간대",
        languageTitle: "언어",
        accountSection: "계정",
        emailTitle: "이메일 주소",
        emailUnavailable: "사용할 수 없음",
        memberSince: "가입일",
        memberSinceUnavailable: "사용할 수 없음",
        signInMethod: "로그인 방법",
        signInMethodFallback: "이메일 주소",
        editNameTitle: "이름 수정",
        editNameMessage: "Aks가 이 이름으로 당신을 부릅니다.",
        nameA11y: "이름",
        namePlaceholder: "이름",
        saving: "저장 중…",
        saveChanges: "변경사항 저장",
        fullName: "이름",
        notices: {
            unableToSaveName: "프로필을 저장할 수 없습니다",
            unableToUpdatePhoto: "사진을 변경할 수 없습니다",
            unableToRemovePhoto: "사진을 삭제할 수 없습니다",
            checkConnection: "연결을 확인하고 다시 시도해 주세요.",
            tryAgain: "다시 시도해 주세요.",
        },
    },
    exploring: {
        header: "지금 살펴보는 것",
        eyebrow: "개인 설정",
        title: "관심사를 선택하세요.",
        description: "더 또렷하게 이해하고 싶은 영역을 골라 주세요.",
        options: ["집중", "에너지", "수면", "기분", "습관", "스트레스"],
    },
    noticeAreas: {
        header: "Aks가 주목해야 할 것",
        eyebrow: "개인 설정",
        title: "Aks가 주목할 범위를 정하세요.",
        description: "가능성 있는 패턴을 정리할 때 Aks가 우선적으로 살펴볼 영역을 선택해 주세요.",
        options: ["일상 습관", "에너지 변화", "집중 패턴", "수면의 질", "기분 변화", "실험 결과"],
    },
    timezone: {
        header: "시간대",
        eyebrow: "설정",
        title: "당신의 현지 시간.",
        description: "Aks가 일정을 잡을 때 사용할 시간대를 선택해 주세요.",
    },
    language: {
        header: "언어",
        eyebrow: "설정",
        title: "언어를 선택하세요.",
        description: "Aks 전체에서 사용할 언어를 골라 주세요.",
        notAvailableYet: (name: string) => `${name}은(는) 아직 사용할 수 없습니다. 번역이 준비될 때까지 영어를 사용합니다.`,
        comingSoon: "준비 중",
    },
    appearance: {
        header: "화면 모드",
        eyebrow: "나의 경험",
        title: "나에게 편안한 방식으로.",
        description: "앱 전체에서 Aks가 보이는 방식을 선택해 주세요.",
        themeSection: "테마",
        themes: {
            systemTitle: "시스템",
            systemDescription: "기기 설정을 따릅니다.",
            lightTitle: "라이트",
            lightDescription: "Aks를 밝고 또렷하게.",
            darkTitle: "다크",
            darkDescription: "어두운 곳에서 편안하게.",
        },
        noteCaption: "AKS의 메모",
        noteBody: "화면 모드는 Aks가 보이는 방식만 바꿉니다.",
        notices: {
            unableToSave: "화면 모드를 저장할 수 없습니다",
        },
    },
    account: {
        header: "계정",
        signedInAs: "로그인 계정",
        emailUnavailable: "이메일 주소를 확인할 수 없음",
        signOut: "로그아웃",
        deleteAccount: "계정 삭제",
        confirmSignOutTitle: "로그아웃할까요?",
        confirmSignOutMessage: "Aks를 계속 사용하려면 다시 로그인해야 합니다.",
        confirmDeleteTitle: "계정을 삭제할까요?",
        confirmDeleteMessage: "계정과 관련 데이터가 영구적으로 삭제됩니다. 되돌릴 수 없습니다.",
        notices: {
            unableToSignOut: "로그아웃할 수 없습니다",
            unableToDelete: "계정을 삭제할 수 없습니다",
            deleteUnavailable: "지금은 계정 삭제를 사용할 수 없습니다. 잠시 후 다시 시도해 주세요.",
        },
    },
    about: {
        header: "Aks 정보",
        eyebrow: "개요",
        title: "나를 다른 각도에서 이해하기.",
        description:
            "Aks는 자신의 활동을 되돌아보고, 가능성 있는 패턴을 알아차리고, 더 의도적으로 개인 실험을 하도록 돕습니다.",
        productLabel: "제품",
        productValue: "Aks.ai",
        versionLabel: "버전",
        versionValue: "1.0.0",
        note: "Aks는 개인적인 되돌아보기를 돕는 도구이며, 전문적인 의료 또는 정신 건강 조언을 대신하지 않습니다.",
    },
    subscription: {
        header: "구독",
        eyebrow: "나의 요금제",
        title: "Aks 요금제와 결제.",
        description:
            "현재 요금제와 결제 상태를 확인할 수 있습니다. 결제가 연결되면 이 화면에서 구독을 관리할 수 있습니다.",
        checkingPlan: "요금제를 확인하는 중…",
        fallbackError: "요금제를 확인할 수 없습니다. 다시 시도해 주세요.",
        currentPlan: "현재 요금제",
        activeBadge: "사용 중",
        planActive: "요금제가 활성화되어 있습니다.",
        renewsOn: (date: string) => `${date}에 갱신`,
        accessUntil: (date: string) => `${date}까지 이용 가능`,
        autoRenewOff: "자동 갱신이 꺼져 있습니다.",
        billing: "결제",
        manage: "구독 관리",
        restore: "구매 복원",
        choosePlan: "요금제 선택",
        chooseTitle: "Aks와 더 많은 시간을.",
        chooseDescription: "나에게 맞는 속도를 선택하세요. 구독은 언제든 관리하고 복원할 수 있습니다.",
        expiredWithDate: (date: string) => `Premium 이용이 ${date}에 종료되었습니다.`,
        expiredFallback: "Premium 이용이 종료되었습니다.",
        plansEmpty: "지금 표시할 수 있는 요금제가 없습니다. 잠시 후 다시 확인해 주세요.",
        premiumEyebrow: "AKS PREMIUM",
        bestValue: "가장 합리적",
        premiumAccess: "Aks Premium 전체 이용",
        continueWith: (title: string) => `${title}(으)로 계속`,
        unavailableTitle: "이 기기에서는 아직 구독이 연결되지 않았습니다.",
        unavailableBody:
            "이 기기에서 결제를 사용할 수 있게 되면 요금제가 여기에 표시되고, 이 화면에서 확인하고 관리할 수 있습니다.",
        noteCaption: "AKS의 메모",
        noteBody: "결제는 기기의 스토어에서 처리됩니다.",
    },
    notifications: {
        header: "알림",
        eyebrow: "필요할 때만",
        title: "정말 필요한 순간에만.",
        description: "Aks가 연락해도 좋은 시점을 선택하세요. 이 설정은 언제든 바꿀 수 있습니다.",
        sectionMain: "알림",
        allowTitle: "알림 허용",
        allowDescription: "Aks의 모든 알림을 일시중지하거나 다시 시작합니다.",
        categoriesSection: "AKS가 보낼 수 있는 내용",
        categories: {
            insightsTitle: "새 인사이트",
            insightsDescription: "Aks가 의미 있는 패턴을 알아차렸을 때.",
            experimentsTitle: "실험 업데이트",
            experimentsDescription: "진행 중인 실험의 알림과 결과.",
            checkInsTitle: "체크인 알림",
            checkInsDescription: "하루를 되돌아보는 부드러운 신호.",
            weeklyTitle: "주간 되돌아보기",
            weeklyDescription: "한 주 동안 달라진 것들의 요약.",
        },
        quietSection: "방해 금지 시간",
        quietTitle: "방해 금지 시간",
        quietDescription: "22:00부터 8:00까지는 알림을 보내지 않습니다.",
        deviceSection: "기기 설정",
        deviceTitle: "기기 알림 관리",
        deviceDescription: "기기 설정을 열어 Aks 권한을 관리합니다.",
        noteCaption: "AKS의 메모",
        noteBody: "Aks는 정말 필요할 때만 연락합니다.",
    },
    yourData: {
        header: "내 데이터",
        eyebrow: "내 데이터",
        title: "Aks가 기억하는 것.",
        description: "Aks가 당신의 활동에서 모은 정보와 당신이 공유하기로 선택한 내용을 확인할 수 있습니다.",
        glanceSection: "한눈에 보기",
        remembersSection: "AKS가 기억하는 것",
        sourcesSection: "데이터 소스",
        sourcesTitle: "연결된 소스",
        sourcesUnknown: "어떤 소스가 연결되어 있는지 확인할 수 있습니다.",
        sourcesNone: "연결된 소스가 없습니다. 지원될 때 사용할 수 있습니다.",
        sourcesCount: (count: number) => `${count}개 연결됨 · 언제든 관리하거나 해제할 수 있습니다.`,
        choiceSection: "당신의 선택",
        choiceTitle: "무엇을 남길지는 당신이 정합니다.",
        choiceBody: "정보는 언제든지 보고, 내보내고, 삭제할 수 있습니다.",
        exportAction: "데이터 내보내기",
        deleteAction: "데이터 삭제",
        noteCaption: "AKS의 메모",
        noteBody: "당신의 데이터는 이해하기 쉽고, 당신의 관리 아래에 있습니다.",
        loadingData: "데이터 요약을 불러오는 중",
        retry: "다시 시도",
    },
    reflections: {
        header: "되돌아보기",
        eyebrow: "나의 되돌아보기",
        title: "당신이 나눈 것.",
        description: "Aks에게 당신의 경험에 대한 맥락을 알려 준 되돌아보기를 다시 볼 수 있습니다.",
        itemTitle: "되돌아보기",
        emptyTitle: "아직 되돌아보기가 없습니다.",
        emptyBody: "Aks와 나누기 시작하면 되돌아보기가 여기에 나타납니다.",
    },
    checkIns: {
        header: "체크인",
        eyebrow: "나의 체크인",
        title: "기억나는 작은 순간들.",
        description: "그때 어떻게 느꼈는지 기록하기 위해 남긴 체크인을 다시 볼 수 있습니다.",
        itemFallback: "체크인",
        itemTitle: (mood: string) => `${mood} 체크인`,
        energy: (value: number) => `에너지 ${value}`,
        focus: (value: number) => `집중 ${value}`,
        stress: (value: number) => `스트레스 ${value}`,
        noDetails: "추가 내용 없음",
        emptyTitle: "아직 체크인이 없습니다.",
        emptyBody: "기록을 시작하면 체크인이 여기에 나타납니다.",
    },
    conversations: {
        header: "대화",
        eyebrow: "나의 대화",
        title: "Aks와 나눈 대화.",
        description:
            "나중의 해석과 섞이지 않은 형태로 나눈 내용을 다시 볼 수 있습니다. 검색은 제목과 대화 내용을 대상으로 합니다.",
        searchA11y: "대화 검색",
        searchPlaceholder: "대화 검색",
        clearSearch: "지우기",
        loadingA11y: "대화를 불러오는 중",
        loadErrorTitle: "대화를 불러올 수 없습니다.",
        emptyQueryTitle: "일치하는 대화가 없습니다.",
        emptyQueryBody: "다른 단어를 시도해 보세요 — Aks는 제목뿐 아니라 나눈 내용도 검색합니다.",
        emptyTitle: "아직 대화가 없습니다.",
        emptyBody: "Aks와 시작한 대화가 여기에 나타납니다.",
        archiveHint: "길게 눌러 보관",
        loadMore: "더 불러오기",
        archiveTitle: "이 대화를 보관할까요?",
        archiveMessage: "진행 중인 대화 목록에서 숨겨집니다.",
        archiveConfirm: "보관",
        notices: {
            unableToArchive: "보관할 수 없습니다",
        },
    },
    conversationDetail: {
        fallbackTitle: "대화",
        renameA11y: "대화 이름 바꾸기",
        loadingA11y: "대화를 불러오는 중",
        unavailableTitle: "대화를 사용할 수 없습니다.",
        archivedBody: "보관되었거나 삭제되었을 수 있습니다.",
        renameSection: "대화 이름 바꾸기",
        titleA11y: "대화 제목",
        titlePlaceholder: "대화 제목",
        saveRename: "저장",
        cancelRename: "취소",
        cancelRenameA11y: "이름 바꾸기 취소",
        historySection: "대화 기록",
        startedAt: (date: string) => `${date} 시작`,
        continueMirror: "Mirror에서 계속하기",
        loadEarlier: "이전 메시지 불러오기",
        youLabel: "나",
        aksLabel: "Aks",
        systemLabel: "시스템",
        emptyTitle: "아직 메시지가 없습니다.",
    },
    memories: {
        header: "Aks가 기억하는 것",
        eyebrow: "AKS가 기억하는 것",
        title: "도움이 되는 맥락을, 신중하게.",
        description: "당신이 반복해서 나눈 근거 있는 정보에서 Aks가 얻은 내용입니다.",
        observationsCount: (count: number) => `관찰 ${count}건`,
        lastNoticed: (date: string) => `마지막 확인 ${date}`,
        emptyTitle: "Aks는 아직 당신의 패턴을 알아 가는 중입니다.",
        emptyBody: "기억할 만큼 충분한 근거가 모이면 반복해서 나타나는 도움이 되는 맥락이 여기에 표시됩니다.",
    },
    memoryDetail: {
        header: "기억",
        loadingA11y: "기억을 불러오는 중",
        unavailableTitle: "기억을 사용할 수 없습니다.",
        archivedFallback: "보관되었거나 삭제되었을 수 있습니다.",
        eyebrow: "AKS가 기억하는 것",
        reasonTitle: "Aks가 이것을 기억하는 이유",
        reasonFallback: (count: number) => `당신이 나눈 ${count}건의 내용에 나타나 있습니다.`,
        lastNoticed: (date: string) => `마지막 확인 ${date}`,
        evidenceSection: "근거",
        viewConversation: " · 대화 보기",
        archiveAction: "기억 보관",
        removeAction: "기억 삭제",
        archiveTitle: "이 기억을 보관할까요?",
        archiveMessage:
            "Aks는 이 기억을 사용하지 않게 됩니다. 앞으로 나누는 내용이 다시 뒷받침할 수도 있습니다. 원래 대화, 되돌아보기, 체크인은 그대로 남습니다.",
        archiveConfirm: "보관",
        removeTitle: "이 기억을 삭제할까요?",
        removeMessage: "Aks가 저장한 기억만 삭제합니다. 당신이 나눈 원래 정보는 삭제되지 않습니다.",
        removeConfirm: "삭제",
        notices: {
            unableToArchive: "보관할 수 없습니다",
            unableToRemove: "삭제할 수 없습니다",
        },
    },
    patterns: {
        header: "패턴",
        eyebrow: "나의 패턴",
        title: "알아차릴 만한 연결.",
        description: "당신이 나눈 내용에서 반복해서 나타나는 신호에 기반한 가능성 있는 관계입니다.",
        observationsCount: (count: number) => `관찰 ${count}건`,
        emptyTitle: "아직 패턴이 없습니다.",
        emptyBody: "도움이 되는 연결을 찾으려면 시간과 근거가 조금 더 필요합니다.",
        status: {
            possible: "가능성 있는 패턴",
            notSupported: "뒷받침되지 않음",
            supported: "뒷받침됨",
            testing: "확인 중",
            fallback: "후보",
        },
    },
    patternDetail: {
        header: "패턴",
        loadingA11y: "패턴을 불러오는 중",
        unavailableTitle: "패턴을 사용할 수 없습니다.",
        archivedFallback: "보관되었거나 삭제되었을 수 있습니다.",
        reasonTitle: "Aks가 이것을 알아차린 이유",
        evidenceLine: (supporting: number, contradicting: number) =>
            `이 관계는 뒷받침하는 관찰 ${supporting}건` +
            (contradicting ? `과 반대되는 관찰 ${contradicting}건` : "") +
            "과 연결되어 있습니다.",
        confidencePending: "신뢰도 평가 중",
        confidenceValue: (percent: number) => `근거 신뢰도 ${percent}%`,
        firstNoticed: (date: string) => `처음 ${date}`,
        lastObserved: (date: string) => `마지막 관찰 ${date}`,
        alternativeTitle: "다른 가능성",
        evidenceSection: "근거",
        supporting: "뒷받침",
        contradicting: "반대",
        viewConversation: " · 대화 보기",
        notReadyA11y: "이 패턴은 아직 확인할 수 없습니다",
        testA11y: "이 패턴 확인하기",
        notReady: "아직 확인할 수 없음",
        testAction: "이 패턴 확인하기",
        archiveAction: "패턴 보관",
        removeAction: "패턴 삭제",
        statusLabels: {
            candidate: "후보",
            possible: "가능성 있는 패턴",
            testing: "확인 중",
            supported: "뒷받침됨",
            notSupported: "뒷받침되지 않음",
            archived: "보관됨",
        },
        archiveTitle: "이 패턴을 보관할까요?",
        archiveMessage: "Aks는 이 패턴을 더 이상 표시하지 않습니다. 앞으로의 관찰로 다시 평가될 수도 있습니다.",
        archiveConfirm: "보관",
        removeTitle: "이 패턴을 삭제할까요?",
        removeMessage: "도출된 패턴과 그 근거의 연결만 삭제합니다. 신호와 원래 정보는 그대로 남습니다.",
        removeConfirm: "삭제",
        notices: {
            unableToArchive: "보관할 수 없습니다",
            unableToRemove: "삭제할 수 없습니다",
        },
    },
    experiments: {
        header: "실험",
        eyebrow: "나의 실험",
        title: "작은 시도, 도움이 되는 근거.",
        description: "실험은 가능성 있는 패턴을 사실로 단정하지 않고 확인하기 위한 방법입니다.",
        observationsCount: (count: number) => `관찰 ${count}건`,
        emptyTitle: "아직 실험이 없습니다.",
        emptyBody: "확인해 볼 만한 패턴이 있으면 그것을 작은 실험으로 시도해 볼 수 있습니다.",
        status: {
            active: "진행 중",
            completed: "완료",
            cancelled: "취소됨",
            fallback: "초안",
        },
    },
    experimentSetup: {
        header: "실험 설정",
        patternSection: "확인할 패턴",
        titleLabel: "제목",
        titlePlaceholder: "짧은 실험 제목",
        hypothesisLabel: "가설",
        hypothesisPlaceholder: "작은 변화가 …에 영향을 줄지도 몰라요",
        hypothesisDefault: "작은 변화가 이 패턴에서 관찰되는 것에 영향을 줄 수 있습니다.",
        descriptionLabel: "시도할 것과 살펴볼 것",
        descriptionPlaceholder: "작은 변화 하나와 기록할 내용을 적어 주세요.",
        descriptionDefault:
            "작고 되돌릴 수 있는 변화를 하나 골라 보세요. 매번 결과가 수월했는지, 비슷했는지, 힘들었는지 기록합니다.",
        durationLabel: "기간",
        durationA11y: (days: number) => `${days}일`,
        durationDays: (days: number) => `${days}일`,
        defaultTitle: (patternTitle: string) => `확인: ${patternTitle}`.slice(0, 120),
        createAction: "초안 만들기",
        createA11y: "실험 초안 만들기",
        createError: "이 실험을 만들 수 없습니다. 내용을 확인하고 다시 시도해 주세요.",
        patternUnavailable: "이 패턴을 사용할 수 없습니다.",
    },
    experimentDetail: {
        header: "실험",
        unavailableTitle: "실험을 사용할 수 없습니다.",
        hypothesisTitle: "가설",
        whatToTryTitle: "시도할 것",
        startAction: "실험 시작",
        startA11y: "실험 시작",
        removeAction: "실험 삭제",
        removeA11y: "실험 삭제",
        removeTitle: "이 실험을 삭제할까요?",
        removeMessage:
            "실험, 관찰, 그리고 이 실험만으로 뒷받침된 배움을 삭제합니다. 원래 패턴과 신호는 남습니다.",
        removeConfirm: "삭제",
        recordedFallback: "기록됨",
        observationsSection: "관찰",
        emptyObservations: "아직 기록된 관찰이 없습니다.",
        resultSection: "결과",
        analysisPending: "분석 대기 중",
        confidenceValue: (percent: number) => `근거 신뢰도 ${percent}%`,
        promptTitle: "이번에는 어떻게 느껴졌나요?",
        resultEasier: "수월했어요",
        resultSame: "비슷했어요",
        resultHarder: "힘들었어요",
        recordA11y: (result: string) => `${result}로 기록`,
        observationPlaceholder: "선택 메모",
        observationA11y: "선택 관찰 메모",
        observationsMeta: (count: number) => `관찰 ${count}건 기록됨`,
        observationsDay: (current: number, total: number | null) =>
            total ? ` · ${total}일 중 ${current}일째` : "",
        observationsThrough: (date: string) => ` · ${date}까지`,
        completeAction: "실험 완료",
        completeA11y: "실험 완료하기",
        cancelAction: "실험 취소",
        cancelA11y: "실험 취소하기",
        resultPendingBody: "결과를 정리하는 동안에도 관찰은 저장됩니다.",
        retryAnalysis: "해석 다시 시도",
        retryAnalysisA11y: "실험 분석 다시 시도",
        retryLearning: "배움 정리 다시 시도",
        retryLearningA11y: "배움 정리 다시 시도",
        retryInsight: "인사이트 생성 다시 시도",
        retryInsightA11y: "인사이트 생성 다시 시도",
        resultLabels: {
            easier: "수월했어요",
            same: "비슷했어요",
            harder: "힘들었어요",
        },
        outcomeLabels: {
            supports: "가설을 뒷받침",
            mixed: "결과 혼재",
            doesNotSupport: "가설을 뒷받침하지 않음",
            insufficientData: "데이터 부족",
        },
        confirmCompleteTitle: "이 실험을 완료할까요?",
        confirmCompleteMessage: "Aks가 관찰을 바탕으로 무엇을 말할 수 있는지 정리합니다.",
        confirmCompleteLabel: "완료",
        confirmCancelTitle: "이 실험을 취소할까요?",
        confirmCancelMessage: "기록한 관찰은 그대로 남습니다.",
        confirmCancelLabel: "실험 취소",
        keepGoing: "계속하기",
        notices: {
            unableToUpdate: "변경할 수 없습니다",
            unableToRecord: "기록할 수 없습니다",
            recordRetry: "마지막 기록은 안전하게 다시 시도할 수 있습니다.",
        },
    },
    learnings: {
        header: "배움",
        eyebrow: "나의 배움",
        title: "근거가 말해 주는 것.",
        description: "완료한 실험과 기록한 관찰에서 얻은 신중한 깨달음입니다.",
        statusRevised: "수정됨",
        statusActive: "유효",
        observationsCount: (count: number) => `관찰 ${count}건`,
        emptyTitle: "아직 배움이 없습니다.",
        emptyBody: "무언가를 시도하고 충분한 근거가 모이면 Aks가 무엇이 달라졌는지 정리하도록 돕습니다.",
    },
    learningDetail: {
        header: "배움",
        unavailableTitle: "배움을 사용할 수 없습니다.",
        evidenceTitle: "이것은 어디에서 왔나요?",
        evidenceLine: (experiments: number, observations: number) =>
            `완료한 실험 ${experiments}건과 기록한 관찰 ${observations}건에 기반합니다.`,
        confidenceValue: (percent: number) => `근거 신뢰도 ${percent}%`,
        updatedAt: (date: string) => `${date} 수정`,
        sourceSection: "원래 실험",
        openExperimentA11y: (title: string) => `${title} 실험 열기`,
        observationsCount: (count: number) => `관찰 ${count}건`,
        archiveAction: "배움 보관",
        archiveA11y: "배움 보관",
        removeAction: "배움 삭제",
        removeA11y: "배움 삭제",
        resultLabels: {
            supports: "가설을 뒷받침",
            mixed: "결과 혼재",
            doesNotSupport: "가설을 뒷받침하지 않음",
            insufficientData: "데이터 부족",
        },
        archiveTitle: "이 배움을 보관할까요?",
        archiveMessage: "원래 실험과 관찰은 그대로 사용할 수 있습니다.",
        archiveConfirm: "보관",
        removeTitle: "이 배움을 삭제할까요?",
        removeMessage: "도출된 배움만 삭제합니다. 실험, 관찰, 패턴, 신호는 그대로 남습니다.",
        removeConfirm: "삭제",
        notices: {
            unableToArchive: "보관할 수 없습니다",
            unableToRemove: "삭제할 수 없습니다",
        },
    },
    insights: {
        header: "인사이트",
        eyebrow: "인사이트",
        title: "알아차릴 만한 것.",
        description: "당신이 시도하고 배운 것을 바탕으로 한, 시의적절한 관찰 몇 가지입니다.",
        statusNew: "새로움",
        statusSeen: "확인함",
        emptyTitle: "아직 인사이트가 없습니다.",
        emptyBody: "Aks가 시간을 두고 충분한 근거를 찾으면 도움이 되는 내용이 보이기 시작합니다.",
    },
    insightDetail: {
        header: "인사이트",
        eyebrow: "인사이트",
        unavailableTitle: "인사이트를 사용할 수 없습니다.",
        reasonTitle: "Aks가 이것을 알아차린 이유",
        openExperimentA11y: (title: string) => `${title} 실험 열기`,
        openLearningA11y: (title: string) => `${title} 배움 열기`,
        observationsCount: (count: number) => `기록한 관찰 ${count}건 · 실험 보기`,
        viewLearning: "원래 배움 보기",
        confidenceValue: (percent: number) => `근거 신뢰도 ${percent}%`,
        createdAt: (date: string) => `${date} 생성`,
        dismissAction: "인사이트 닫기",
        dismissA11y: "인사이트 닫기",
        removeAction: "인사이트 삭제",
        removeA11y: "인사이트 삭제",
        dismissTitle: "이 인사이트를 닫을까요?",
        dismissMessage: "배움, 실험, 패턴, 근거는 그대로 남습니다.",
        dismissConfirm: "닫기",
        removeTitle: "이 인사이트를 삭제할까요?",
        removeMessage: "이 인사이트만 삭제합니다. 원래 정보는 모두 남습니다.",
        removeConfirm: "삭제",
        notices: {
            unableToDismiss: "닫을 수 없습니다",
            unableToRemove: "삭제할 수 없습니다",
        },
    },
    privacyHome: {
        header: "개인정보",
        eyebrow: "나의 개인정보",
        title: "당신의 삶은 당신의 것입니다.",
        description:
            "Aks는 이 경험을 뒷받침하는 정보를 당신이 직접 관리할 수 있는 상태로 두면서, 자신을 이해하도록 돕습니다.",
        dataSection: "내 데이터",
        knowsTitle: "Aks가 알고 있는 것",
        knowsDescription: "당신의 경험을 만드는 데 사용되는 정보를 이해할 수 있습니다.",
        accessTitle: "Aks가 접근할 수 있는 것",
        accessDescription: "당신이 제공하거나 연결한 내용을 확인할 수 있습니다.",
        controlsSection: "데이터 관리",
        usageTitle: "데이터가 사용되는 방식",
        usageDescription: "정보가 인사이트와 실험을 어떻게 뒷받침하는지 확인합니다.",
        exportTitle: "데이터 내보내기",
        exportDescription: "Aks 정보의 사본을 요청할 수 있습니다.",
        deleteTitle: "데이터 삭제",
        deleteDescription: "계정 데이터의 신중한 삭제 절차를 시작합니다.",
        legalSection: "법적 안내",
        privacyPolicyTitle: "개인정보 처리방침",
        privacyPolicyDescription: "Aks 개인정보 처리방침 전문 읽기.",
    },
    dataAccess: {
        header: "Aks가 접근할 수 있는 것",
        title: "설계부터 명확하게.",
        description: "Aks는 당신이 제공한 정보와 명확히 연결하기로 선택한 데이터 소스만 다룹니다.",
        sourcesSection: "연결된 소스",
        loadingSources: "연결된 소스를 불러오는 중…",
        loadError: "지금은 연결된 소스를 불러올 수 없습니다.",
        emptyTitle: "아직 연결된 소스가 없습니다",
        emptyBody:
            "Aks는 당신이 명확히 연결한 뒤에만 외부 서비스를 읽습니다. 연결은 계정 설정에서 언제든 관리할 수 있습니다.",
        connectedNeedsPermission: "연결됨 · 권한 필요",
        connectedSynced: (relative: string) => `연결되어 데이터를 읽는 중 · ${relative} 동기화`,
        connectedNotSynced: "연결되어 데이터를 읽는 중 · 아직 동기화되지 않음",
        holdsSection: "AKS가 보관하는 내용",
        items: [
            {
                title: "당신이 제공한 정보",
                body: "Aks에 직접 입력한 프로필 정보와 환경설정 등.",
            },
            {
                title: "되돌아보기와 체크인",
                body: "경험, 기분, 집중, 에너지, 생활 리듬을 표현하려고 남긴 기록.",
            },
            {
                title: "실험 데이터",
                body: "당신이 만든 실험과 기록한 결과 및 메모.",
            },
            {
                title: "계정 정보",
                body: "Aks 계정을 식별하고 관리하는 데 필요한 기본 정보.",
            },
            {
                title: "연결된 데이터 소스",
                body: "당신이 명확히 연결하기로 선택한 서비스의 정보만, 그리고 그 연결이 가능한 경우에만.",
            },
        ],
        controlTitle: "당신이 관리합니다",
        controlBody: "Aks는 당신이 입력하거나 명확히 연결한 내용만 사용합니다.",
    },
    dataUsage: {
        header: "데이터가 사용되는 방식",
        title: "데이터에는 목적이 있습니다.",
        description: "Aks는 제품 안에서 정보를 사용해 당신의 경험을 더 관련성 있고 분명하게 만듭니다.",
        sections: [
            {
                title: "Aks가 데이터를 사용하는 이유",
                body: "공유하기로 선택한 정보는 Aks가 되돌아보기를 개인화하고, 도움이 되는 주제를 찾고, 당신의 목표를 뒷받침하는 데 도움이 됩니다.",
            },
            {
                title: "되돌아보기와 체크인",
                body: "기록은 기분, 에너지, 집중, 생활 리듬의 변화에 맥락을 더합니다.",
            },
            {
                title: "패턴 감지",
                body: "Aks는 당신이 제공한 정보를 비교해 확인해 볼 수 있는 가능성 있는 패턴을 제시할 수 있습니다. 이는 되돌아보기 위한 신호이며 의학적 결론이 아닙니다.",
            },
            {
                title: "기억",
                body: "Aks는 반복해서 나타나는 도움이 되는 맥락을 조금 보관할 수 있습니다. 기억은 언제나 그것을 뒷받침하는 정보와 연결되어 있고, 원래 정보를 삭제하지 않고도 제거할 수 있습니다.",
            },
            {
                title: "실험과 결과",
                body: "실험 기록은 시도한 것과 기록한 결과를 비교하는 데 도움이 됩니다.",
            },
            {
                title: "AI의 이해 지원",
                body: "AI는 당신이 제공한 정보를 정리하거나 요약하는 데 도움을 줄 수 있습니다. 중요한 인사이트는 스스로 확인하고 자신의 판단으로 받아들이세요.",
            },
        ],
        privacyPolicyAction: "개인정보 처리방침 전문 읽기",
    },
    exportData: {
        header: "데이터 내보내기",
        preparingTitle: "내보내기를 준비하는 중",
        preparingBody:
            "대화, 되돌아보기, 기억, 패턴, 실험, 인사이트를 모으고 있습니다. 보통 몇 초면 끝납니다.",
        errorTitle: "데이터를 가져가세요.",
        errorBody: "요청에 따라 당신의 Aks 정보를 다운로드할 수 있는 형태로 준비합니다.",
        failedTitle: "내보내기를 만들 수 없습니다.",
        failedFallback: "내보내기를 준비하는 중 문제가 발생했습니다. 다시 시도해 주세요.",
        retryA11y: "내보내기 만들기 다시 시도",
        cancelAction: "취소",
        cancelA11y: "내보내기 안내로 돌아가기",
        readyTitle: "내보낼 준비가 되었습니다.",
        readyBody: "방금 당신의 Aks 정보 스냅샷을 만들었습니다. 요청할 때 표시된 항목과 같습니다.",
        expiresIn: (countdown: string) => `링크는 ${countdown} 후에 만료됩니다`,
        expiresSoon: "곧",
        saveAction: "내보내기 저장",
        saveA11y: "내보내기 저장",
        requestAnother: "내보내기 다시 요청",
        requestAnotherA11y: "내보내기 다시 요청",
        idleTitle: "데이터를 가져가세요.",
        idleBody:
            "요청에 따라 당신의 Aks 정보를 다운로드할 수 있는 형태로 준비합니다. 각 내보내기는 하나의 파일이며, 요청한 시점의 계정 상태를 반영합니다.",
        includedSection: "포함되는 내용",
        included: [
            "프로필과 환경설정",
            "대화와 메시지",
            "되돌아보기",
            "체크인",
            "신호",
            "기억과 근거 연결",
            "패턴과 근거 연결",
            "실험과 관찰",
            "배움과 참조",
            "인사이트와 참조",
        ],
        requestAction: "데이터 내보내기 요청",
        requestA11y: "내보내기 요청",
    },
    deleteData: {
        header: "데이터 삭제",
        title: "아무것도 남기지 않습니다.",
        description:
            "계정을 삭제하면 Aks에서 만든 데이터가 영구적으로 삭제되고, 이 기기에서도 로그아웃됩니다.",
        warningTitle: "되돌릴 수 없습니다.",
        warningBody:
            "계정을 삭제하면 Aks 데이터가 사라지고 복구할 수 없습니다. 사본이 필요하다면 먼저 데이터를 내보내는 것을 고려해 주세요.",
        removedSection: "삭제되는 내용",
        removed: [
            "대화와 메시지",
            "되돌아보기",
            "체크인",
            "도출된 신호",
            "기억과 근거 연결",
            "패턴과 근거 연결",
            "실험과 관찰",
            "배움과 참조",
            "인사이트와 참조",
        ],
        confirmA11y: "이 작업이 되돌릴 수 없음을 확인합니다",
        confirmLabel: "이 작업이 되돌릴 수 없으며 Aks 데이터가 모두 삭제된다는 것을 이해했습니다.",
        deleteAction: "계정과 데이터 삭제",
        deleteActionA11y: "계정과 데이터 삭제",
        deletingAction: "계정을 삭제하는 중…",
        deletedTitle: "계정을 삭제하고 있습니다.",
        deletedBody: "삭제가 끝나면 로그아웃됩니다.",
        backToSettings: "설정으로 돌아가기",
        backToSettingsA11y: "설정으로 돌아가기",
        keepAccount: "계정 유지",
        keepAccountA11y: "계정 유지",
        keepNote: "계정을 삭제하면 그 계정을 위해 만들어진 내보내기 파일도 삭제됩니다.",
    },
    helpHome: {
        header: "도움말 및 피드백",
        title: "여러분의 의견을 기다립니다.",
        description: "작동하지 않거나, 헷갈리거나, Aks가 이렇게 해 주면 좋겠다 싶은 게 있나요?",
        supportTitle: "도움이 필요하신가요?",
        supportBody: "지원팀이 도와드립니다.",
        supportAction: "지원팀에 문의",
        getHelpSection: "도움 받기",
        faqTitle: "자주 묻는 질문",
        faqDescription: "자주 묻는 질문의 답을 빠르게 찾기",
        reportTitle: "문제 신고",
        reportDescription: "잘 되지 않는 부분을 알려 주세요",
        improveSection: "AKS를 더 좋게 만들기",
        suggestTitle: "아이디어 제안",
        suggestDescription: "Aks가 배우거나 해 주면 좋겠는 것을 알려 주세요",
        shareTitle: "경험 공유",
        shareDescription: "좋았던 점과 더 나아질 점을 알려 주세요",
        contactSection: "연락처",
        supportEmail: "support@aks.ai",
        supportResponse: "보통 1~2 영업일 이내에 답변드립니다",
        footerVersion: "1.0.0",
    },
    faq: {
        header: "도움말 및 피드백",
        title: "자주 묻는 질문",
        description: "Aks의 작동 방식과 데이터 처리에 대한 답을 빠르게 찾을 수 있습니다.",
        searchPlaceholder: "질문 검색",
        clearSearch: "지우기",
        resultsCount: (count: number) => `${count}개 결과`,
        popularSection: "많이 보는 질문",
        questionsCount: (count: number) => `질문 ${count}개`,
        items: [
            {
                question: "Aks는 어떻게 패턴을 찾나요?",
                answer: "Aks는 당신이 공유하기로 선택한 정보와 되돌아보기에서 도움이 되는 연결을 찾습니다.",
            },
            {
                question: "Aks가 사용하는 데이터를 제가 고를 수 있나요?",
                answer: "네. 내 데이터와 개인정보에서 정보를 확인하고 사용할 수 있는 권한을 관리할 수 있습니다.",
            },
            {
                question: "실험은 어떻게 작동하나요?",
                answer: "실험은 작은 변화를 시도하고 그것이 집중, 에너지, 수면, 생활 리듬에 어떤 영향을 주는지 되돌아보는 데 도움이 됩니다.",
            },
            {
                question: "알림 설정을 바꿀 수 있나요?",
                answer: "네. 나 페이지에서 알림을 열어 Aks가 연락해도 좋은 시점을 선택할 수 있습니다.",
            },
            {
                question: "Aks는 의료 조언인가요?",
                answer: "아니요. Aks는 개인적인 되돌아보기를 돕는 도구이며, 전문적인 의료 또는 정신 건강 조언을 대신하지 않습니다.",
            },
        ],
        emptyTitle: "일치하는 항목이 없습니다",
        emptyBody: "다른 검색어를 시도하거나 위의 질문을 살펴보세요.",
        clearAction: "검색 지우기",
        helpTitle: "아직 도움이 필요하신가요?",
        helpBody: "상황을 알려 주시면 함께 정리해 볼게요.",
        contactAction: "문의하기",
    },
    sendFeedback: {
        header: "피드백 보내기",
        title: "Aks를 함께 만들어요.",
        description: "아이디어, 기능 요청, 또는 이미 좋다고 느낀 점을 알려 주세요.",
        optionLabel: "피드백 유형",
        optionHint: "하나를 선택하세요",
        options: ["아이디어", "기능 요청", "일반적인 의견", "좋았던 점"],
        initialOption: "일반적인 의견",
        messageLabel: "당신의 피드백",
        messagePlaceholder: "어떤 점이 있으면 Aks가 더 도움이 될까요?",
        messageHint: "아이디어, 제안, 좋았던 점 무엇이든 환영합니다.",
        emailHint: "답변이 필요한 경우에만 이메일 주소를 적어 주세요.",
        noteTitle: "당신의 의견은 중요합니다.",
        noteBody: "알려 주신 내용은 Aks의 다음 모습을 정하는 데 도움이 됩니다.",
        submit: "피드백 보내기",
        leaveMessage: "아무것도 보내지 않고 이 페이지를 떠날 수 있습니다.",
    },
    reportProblem: {
        header: "문제 신고",
        title: "무슨 일이 있었나요?",
        description: "있었던 일을 알려 주세요. 맥락이 많을수록 이해하고 고치기 쉬워집니다.",
        optionLabel: "문제 유형",
        optionHint: "하나를 선택하세요",
        options: [
            "기능이 작동하지 않아요",
            "앱이 종료되었어요",
            "인사이트가 맞지 않아요",
            "데이터 문제",
            "알림 문제",
            "기타",
        ],
        messageLabel: "무슨 일이 있었나요?",
        messagePlaceholder: "기대한 것과 실제로 일어난 일을 적어 주세요…",
        messageHint: "문제가 발생한 단계를 적어 주시면 도움이 됩니다.",
        emailHint: "저희가 연락할 경우에만 이메일 주소를 적어 주세요.",
        noteTitle: "Aks를 더 좋게 만드는 데 도움을 주셔서 감사합니다.",
        noteBody: "보내 주신 신고는 모두에게 더 믿음직한 Aks를 만드는 데 도움이 됩니다.",
        submit: "신고 보내기",
        leaveMessage: "보내지 않고 이 페이지를 떠날 수 있습니다.",
    },
    feedbackForm: {
        selectedState: "선택됨",
        contactEmail: "연락 이메일",
        optionalMark: "(선택)",
        emailPlaceholder: "you@example.com",
        charLimit: 1000,
    },
    profilePreference: {
        saveAction: "설정 저장",
        saveA11y: (title: string) => `${title} 저장`,
        noteCaption: "프로필에 저장되었습니다",
        noteBody: "선택한 내용은 프로필에 저장됩니다.",
        notices: {
            unableToSave: "설정을 저장할 수 없습니다",
        },
    },
    dataCategory: {
        recentSection: "최근",
        loadingA11y: (title: string) => `${title} 불러오는 중`,
        loadErrorTitle: "이 데이터를 불러올 수 없습니다.",
        tryAgain: "다시 시도",
        loadMore: "더 불러오기",
        noteCaption: "AKS의 메모",
        noteBody: "직접 만든 기록이 여기에 표시됩니다.",
    },
    bottomSheet: {
        dismissA11y: "닫기",
        defaultConfirm: "알겠어요",
        cancel: "취소",
    },
    connectedSources: {
        header: "연결된 소스",
        eyebrow: "맥락과 권한",
        title: "Aks가 무엇을 아는지는 당신이 정합니다.",
        description:
            "어떤 소스도 연결하지 않고 Aks를 사용해도 괜찮습니다. 각 소스는 선택 사항이고 서로 독립적이며, 공유하는 내용을 분명히 알려 줍니다. 언제든 연결을 해제할 수 있습니다.",
        loadingA11y: "소스를 불러오는 중",
        loadError: "연결된 소스를 불러올 수 없습니다.",
        status: {
            connected: "연결됨",
            permissionRequired: "권한 필요",
            notConnected: "연결되지 않음",
            notAvailable: "이 기기에서 사용할 수 없음",
            revoked: "해제됨",
            temporarilyUnavailable: "일시적으로 사용할 수 없음",
            error: "지금 사용할 수 없음",
        },
        syncedAgo: (relative: string) => `${relative} 동기화`,
        notSynced: "아직 동기화되지 않음",
        whyHelps: "왜 도움이 되나요",
        whatReceives: "AKS가 받는 것",
        whatStored: "저장되는 것",
        howToStop: "중지하는 방법",
        goodToKnow: "알아 두면 좋은 점",
        disconnect: "연결 해제",
        deleteData: "가져온 데이터 삭제",
        allow: "허용",
        connect: "연결하기",
        reconnect: "다시 연결",
        choiceSection: "당신의 선택",
        choiceBody: "연결한 소스만 사용됩니다. 언제든 탭 한 번으로 중지할 수 있습니다.",
        confirmations: {
            cancelAction: "취소",
        },
        notices: {
            providerNotConfigured: "이 빌드에서는 해당 공급자가 아직 설정되지 않았습니다.",
            unableToConnect: "지금은 해당 소스에 연결할 수 없습니다.",
        },
        groups: {
            productivity: "생산성",
            work: "업무",
            device: "기기 / 행동",
        },
    },
    sources: {
        location: {
            name: "위치",
            purpose:
                "Aks가 당신의 하루가 어디에서 일어나는지 이해하도록 돕습니다. 힘든 날과 이동이나 예상치 못한 변화로 흐트러진 날을 구분하는 데 도움이 됩니다.",
            receives:
                "대략적인 위치 맥락(집 근처, 직장 근처, 이동 중, 낯선 곳)과 시간대 — 지속적인 추적은 하지 않습니다.",
            stored: "\"이동, 18:30 무렵 45분\"과 같은 관찰 시간 범위. 정확한 좌표는 저장하지 않습니다.",
            stop: "위치는 언제든 해제할 수 있습니다. 이후 수집은 즉시 멈추고, 저장된 관찰은 따로 삭제할 수 있습니다.",
            batteryNote: "연결 중에는 때때로 위치를 확인합니다. 켜 두면 배터리 사용량이 조금 늘어날 수 있습니다.",
        },
        calendar: {
            name: "캘린더",
            purpose:
                "예정된 일정이 있으면 Aks가 \"계획이 바뀌었다\"와 \"의욕이 떨어졌다\"를 구분하기 쉬워집니다.",
            receives:
                "일정 시간과 대략적인 분류. 제목은 일정을 정의할 때만 사용하며 참석자 명단, 메모, 회의 링크는 읽지 않습니다.",
            stored: "최소한의 일정 기록: 시간, 길이, 분류, 확정 여부.",
            stop: "캘린더는 언제든 해제할 수 있습니다. 이후 수집은 즉시 멈춥니다.",
        },
        reminders: {
            name: "할 일과 미리 알림",
            purpose: "하려고 했던 행동과 실제로 일어난 일 — Aks가 \"하지 않았다\"고 단정하지 않습니다.",
            receives: "동기화하기로 선택한 미리 알림의 마감과 완료 상태.",
            stored: "마감과 완료/미기록 상태.",
            stop: "할 일과 미리 알림은 언제든 해제할 수 있습니다.",
        },
        screenTime: {
            name: "스크린 타임",
            purpose:
                "집계된 기기 사용 맥락이 집중의 변화를 설명할 때가 있습니다 — 산만함의 증거로 다루지 않습니다.",
            receives: "시간대별로 집계된, 대략적인 분류 기준의 사용 시간.",
            stored: "\"SNS 앱, 60분, 21:00~22:00\"처럼 집계된 시간 범위. 개별 조작 단위 데이터는 없습니다.",
            stop: "스크린 타임은 언제든 해제할 수 있습니다.",
        },
        googleCalendar: {
            name: "Google 캘린더",
            purpose:
                "Google 일정은 당신이 명확히 연결한 계정에 대해 기기 캘린더와 같은 계획 맥락을 Aks에 제공합니다.",
            receives:
                "선택한 캘린더의 일정 시간과 대략적인 분류. 참석자 명단, 메모, 회의 링크는 읽지 않습니다.",
            stored: "최소한의 일정 기록: 시간, 길이, 분류, 확정 여부.",
            stop: "Google 캘린더는 언제든 해제할 수 있습니다 — Google 계정 설정에서 접근 권한도 취소해 주세요.",
        },
        appleCalendar: {
            name: "Apple 캘린더",
            purpose:
                "iPhone과 iPad에서는 Apple 캘린더 저장소를 통해 같은 기기 캘린더 맥락을 얻을 수 있습니다.",
            receives: "일정 시간과 대략적인 분류. 참석자 명단, 메모, 회의 링크는 읽지 않습니다.",
            stored: "최소한의 일정 기록: 시간, 길이, 분류, 확정 여부.",
            stop: "Apple 캘린더는 언제든 해제할 수 있습니다.",
        },
        googleTasks: {
            name: "Google Tasks",
            purpose:
                "연결한 Google 계정의 예정된 할 일을 통해 Aks가 당신의 의도를 볼 수 있습니다 — 실패로 단정하지 않습니다.",
            receives: "할 일의 마감과 완료 상태.",
            stored: "마감과 완료/미기록 상태.",
            stop: "Google Tasks는 언제든 해제할 수 있습니다 — Google 계정 설정에서 접근 권한도 취소해 주세요.",
        },
        appleReminders: {
            name: "Apple 미리 알림",
            purpose:
                "iPhone과 iPad에서는 Apple 미리 알림의 예정된 행동이 같은 \"계획과 실제\" 맥락이 됩니다.",
            receives: "미리 알림의 마감과 완료 상태.",
            stored: "마감과 완료/미기록 상태.",
            stop: "Apple 미리 알림은 언제든 해제할 수 있습니다.",
        },
        notion: {
            name: "Notion",
            purpose:
                "당신이 Aks 연동과 명확히 공유한 페이지와 데이터베이스로 업무 맥락이 대화에 반영됩니다.",
            receives:
                "Aks Notion 연동과 공유한 항목의 제목, 시간, 대략적인 분류. 페이지 본문은 읽지 않습니다.",
            stored: "최소한의 항목 기록: 제목 분류, 시간, 상태.",
            stop: "Notion은 언제든 해제할 수 있습니다 — Notion 워크스페이스에서 Aks 연동도 삭제해 주세요.",
        },
        todoist: {
            name: "Todoist",
            purpose: "연결된 할 일 서비스(Todoist 등)를 통해 Aks 밖의 계획까지 함께 볼 수 있습니다.",
            receives: "할 일의 마감과 완료 상태.",
            stored: "마감과 완료/미기록 상태.",
            stop: "Todoist는 언제든 해제할 수 있습니다 — 공급자 계정 설정에서 접근 권한도 취소해 주세요.",
        },
        github: {
            name: "GitHub",
            purpose: "당신 자신의 커밋과 PR 활동을 객관적인 업무 맥락으로 — 다른 사람의 데이터는 다루지 않습니다.",
            receives: "선택한 저장소에서의 당신의 커밋과 풀 리퀘스트 수와 시간.",
            stored: "\"2건의 커밋, 22:00~23:00\"처럼 집계된 활동 시간 범위. 코드 내용은 포함하지 않습니다.",
            stop: "GitHub는 언제든 해제할 수 있습니다 — GitHub 설정에서 Aks OAuth 앱도 취소해 주세요.",
        },
        slack: {
            name: "Slack",
            purpose: "당신이 명확히 연결한 워크스페이스에서 얻는 집중 시간과 상태 신호.",
            receives: "당신 자신의 활동 시간과 방해 금지(DND) 상태. 메시지 내용은 읽지 않습니다.",
            stored: "집계된 활동 시간 범위. 메시지, 채널, 동료 데이터는 포함하지 않습니다.",
            stop: "Slack은 언제든 해제할 수 있습니다 — 워크스페이스에서 Aks 앱도 제거해 주세요.",
        },
        email: {
            name: "이메일",
            purpose: "연결된 공급자(Gmail 등)에서 얻는 가벼운 메일 부담 맥락(수신 건수만).",
            receives: "받은 메일의 수와 시간대. 제목, 본문, 발신자는 읽지 않습니다.",
            stored: "시간 범위별 집계 건수. 내용도 주소도 저장하지 않습니다.",
            stop: "이메일은 언제든 해제할 수 있습니다 — 공급자의 보안 설정에서 접근 권한도 취소해 주세요.",
        },
        voiceSession: {
            name: "마이크",
            purpose: "음성 대화는 당신이 명시적으로 시작하는 행동입니다. 마이크는 음성 세션 중에만 사용됩니다.",
            receives: "음성 대화가 진행되는 동안에만 음성.",
            stored: "당신이 남긴 텍스트 기록. 음성은 저장되지 않습니다.",
            stop: "음성 세션을 끝내면 마이크가 꺼집니다. Aks가 백그라운드에서 듣는 일은 없습니다.",
        },
    },
    transparency: {
        connectedWith: (sources: string) =>
            `${sources}을(를) 연결했기 때문에 Aks는 여기서 나눈 내용과 함께 그 맥락도 볼 수 있습니다.`,
        names: {
            location: "위치",
            calendar: "캘린더",
            googleCalendar: "Google 캘린더",
            appleCalendar: "Apple 캘린더",
            reminders: "할 일",
            googleTasks: "Google Tasks",
            appleReminders: "Apple 미리 알림",
            todoist: "Todoist",
            notion: "Notion",
            github: "GitHub",
            slack: "Slack",
            email: "이메일",
            screenTime: "스크린 타임",
            voiceSession: "음성",
        },
    },
    oauth: {
        googleCalendar: "Google 캘린더",
        googleTasks: "Google Tasks",
        notion: "Notion",
        todoist: "Todoist",
        github: "GitHub",
        slack: "Slack",
        email: "이메일",
    },
    errors: {
        pagedData: "이 데이터를 불러올 수 없습니다. 다시 시도해 주세요.",
        pagedDataMore: "데이터를 더 불러올 수 없습니다. 다시 시도해 주세요.",
        dataSummary: "데이터 요약을 불러올 수 없습니다. 다시 시도해 주세요.",
        dataAccess: "연결된 소스를 불러올 수 없습니다. 다시 시도해 주세요.",
        memory: "이 기억을 불러올 수 없습니다.",
        pattern: "이 패턴을 불러올 수 없습니다.",
        experiment: "이 실험을 불러올 수 없습니다.",
        learning: "이 배움을 불러올 수 없습니다.",
        insight: "이 인사이트를 불러올 수 없습니다.",
        conversation: "이 대화를 불러올 수 없습니다. 다시 시도해 주세요.",
        conversationEarlier: "이전 메시지를 불러올 수 없습니다. 다시 시도해 주세요.",
        conversationPlain: "이 대화를 불러올 수 없습니다.",
        conversationEarlierPlain: "이전 메시지를 불러올 수 없습니다.",
        messageEmptySave: "저장하기 전에 내용을 입력해 주세요.",
        exportLinkExpired: "내보내기 링크가 만료되었습니다. 다시 요청해 주세요.",
        renameConversation: "그 대화의 이름을 바꿀 수 없습니다. 다시 시도해 주세요.",
        exportExpired: "내보내기 링크가 만료되었습니다. 다시 요청해 주세요.",
        exportCreate: "내보내기를 만들 수 없습니다. 다시 시도해 주세요.",
        exportDownload: "내보내기를 다운로드할 수 없습니다. 다시 시도해 주세요.",
        deleteAccount: "지금은 계정 삭제를 사용할 수 없습니다. 잠시 후 다시 시도해 주세요.",
        preferences: "설정을 불러올 수 없습니다.",
        appSetup: "계정 설정을 마치지 못했습니다. 다시 시도해 주세요.",
        exportSaveTitle: "Aks 내보내기 저장",
        exportClearDevice: "계정 데이터를 삭제하고 있지만, 이 기기 정리는 다시 시도해야 합니다.",
        shareUnavailable: "이 기기에서는 공유를 사용할 수 없습니다. 다시 시도해 주세요.",
        exportIncomplete: "내보내기 응답이 불완전했습니다. 다시 시도해 주세요.",
        exportInterrupted: "다운로드가 중단되었습니다. 다시 시도해 주세요.",
        exportGeneric: "문제가 발생했습니다. 다시 시도해 주세요.",
        connectedSources: "연결된 소스를 불러올 수 없습니다.",
        sourceUnavailable: "이 소스는 이 기기에서 사용할 수 없습니다.",
        sourcePermission: "이 소스를 연결하려면 권한이 필요합니다. 나중에 다시 시도해 주세요.",
        sourceConnect: "그 소스에 연결할 수 없습니다.",
        sourceDisconnect: "그 소스의 연결을 해제할 수 없습니다.",
        sourceDelete: "그 소스의 데이터를 삭제할 수 없습니다.",
        oauthRecord: "그 연결을 기록할 수 없습니다.",
        oauthDisconnect: "그 계정의 연결을 해제할 수 없습니다.",
        webPage: "이 페이지를 불러올 수 없습니다.",
        webPageBody: "인터넷 연결을 확인하고 다시 시도해 주세요.",
        generic: "문제가 발생했습니다. 다시 시도해 주세요.",
        signInUnavailable: "지금은 로그인을 사용할 수 없습니다. 잠시 후 다시 시도해 주세요.",
        signInStart: "로그인을 시작할 수 없습니다.",
        authRequest: "그 요청을 완료할 수 없습니다. 다시 시도해 주세요.",
        storeUnreachable: "스토어에 연결할 수 없습니다. 연결을 확인하고 다시 시도해 주세요.",
        plansUnavailable: "지금은 사용할 수 있는 요금제가 없습니다. 잠시 후 다시 시도해 주세요.",
        planUnavailable: "그 요금제는 지금 사용할 수 없습니다. 잠시 후 다시 시도해 주세요.",
        storeFailed: "스토어가 요청을 완료하지 못했습니다. 다시 시도해 주세요.",
        subscriptionGeneric: "구독을 처리하는 중 문제가 발생했습니다. 다시 시도해 주세요.",
        purchaseCancelled: "구매가 취소되었습니다. 결제된 금액은 없습니다.",
        purchasePending: "구매가 스토어 확인을 기다리고 있습니다. 완료되면 여기에 표시됩니다.",
        alreadySubscribed: "이 요금제는 이미 이용 중입니다.",
        checkoutPendingPremium:
            "결제는 완료되었지만 계정에 아직 Premium이 활성화되지 않았습니다. 에뮬레이터의 Test Store 구매는 Premium을 활성화하지 않습니다 — Play 스토어가 있는 기기를 사용해 주세요. 그 외의 경우 잠시 기다린 뒤 구매 복원을 시도해 주세요.",
        restoreEmpty: "복원할 이전 구매를 찾지 못했습니다.",
        emptyMessage: "보내기 전에 내용을 입력해 주세요.",
        mirror: {
            noReply: "Aks가 아직 마지막 메시지에 답하지 않았습니다.",
            unsavedRetry: "마지막 메시지 저장이 끝나지 않았을 수 있습니다. 안전하게 다시 시도할 수 있습니다.",
            resolvePending: "다음 메시지를 보내기 전에 이전 메시지를 다시 시도하거나 정리해 주세요.",
            refreshFailed: "Aks가 그 답변을 새로 고치지 못했습니다. 이전 내용은 그대로 남아 있습니다.",
            refreshFailedConversation:
                "Aks가 여러 번 시도했지만 이 답변을 끝내지 못했습니다. 보낸 메시지는 저장되어 있습니다.",
            refreshFailedUnsafe: "Aks가 그 답변을 안전하게 해석하지 못했습니다. 보낸 메시지는 저장되어 있습니다.",
            refreshFallback: "Aks가 지금 그 내용을 처리할 수 없습니다. 보낸 메시지는 저장되어 있습니다.",
            updateMessage: "그 메시지를 변경할 수 없습니다. 이미 Aks의 답변이 있을 수 있습니다.",
            checkInFailed: "체크인을 저장할 수 없습니다. 다시 시도해 주세요.",
            saveFailed: "메시지를 저장할 수 없습니다. 연결을 확인하고 다시 시도해 주세요.",
            outboxQueued: "이 기기에 저장했습니다. 다시 온라인이 되면 Aks가 보냅니다.",
            signInForVoice: "음성 대화는 로그인 후에 사용할 수 있습니다.",
            voiceStartFailed: "음성 대화를 시작할 수 없습니다.",
        },
        voice: {
            realtimeNotConfigured: "이 빌드에서는 음성 대화가 아직 설정되지 않았습니다.",
            sessionUnavailable: "음성 세션을 시작할 수 없습니다. 다시 시도해 주세요.",
            transportUnavailable: "이 대화 옵션을 사용하려면 Aks 개발 빌드가 필요합니다.",
            audioUnavailable: "실시간 음성은 Aks 오디오 엔진이 포함된 개발 빌드가 필요합니다.",
            micDenied: "음성 대화에는 마이크 권한이 필요합니다.",
            transcriptionFailed: "Aks가 하신 말씀을 듣지 못했습니다. 다시 시도해 주세요.",
            providerError: "Aks가 지금 음성 대화를 시작할 수 없습니다.",
            sessionExpired: "음성 세션이 만료되었습니다. 다시 연결해 계속해 주세요.",
            voiceFailed: "음성 대화가 실패했습니다.",
            saveVoiceMessage: "음성 메시지를 저장할 수 없습니다. 이 세션 안에만 남습니다.",
            saveVoiceReply: "Aks의 답변을 저장할 수 없습니다. 이 세션 안에만 남습니다.",
            audioCaptureFailed: "음성 캡처에 실패했습니다.",
            audioFailed: "음성에서 문제가 발생했습니다.",
        },
        writes: {
            signInRequired: "계속하려면 로그인해 주세요.",
            experimentInvalid: "실험 응답이 유효하지 않았습니다.",
            observation: "그 관찰을 저장할 수 없습니다.",
            reflection: "그 되돌아보기를 저장할 수 없습니다.",
            message: "그 메시지를 저장할 수 없습니다.",
            checkIn: "그 체크인을 저장할 수 없습니다.",
            insightUpdate: "이 인사이트를 변경할 수 없습니다.",
            experimentUpdate: "이 실험을 변경할 수 없습니다.",
            startConversation: "그 대화를 시작할 수 없습니다.",
            sendMessage: "메시지를 저장할 수 없습니다.",
            confirmMessage: "저장한 메시지를 확인할 수 없습니다.",
            searchConversations: "대화를 검색할 수 없습니다.",
            updateConversation: "그 대화를 변경할 수 없습니다.",
            updateMessage: "그 메시지를 변경할 수 없습니다.",
            confirmUpdatedMessage: "변경한 메시지를 확인할 수 없습니다.",
            archiveConversation: "그 대화를 보관할 수 없습니다.",
            archivePattern: "이 패턴을 보관할 수 없습니다.",
            removePattern: "이 패턴을 삭제할 수 없습니다.",
            archiveMemory: "이 기억을 보관할 수 없습니다.",
            removeMemory: "이 기억을 삭제할 수 없습니다.",
            archiveLearning: "이 배움을 보관할 수 없습니다.",
            removeLearning: "이 배움을 삭제할 수 없습니다.",
        },
    },
    timelineEntries: {
        patternForming: "패턴 형성 중",
        insight: "인사이트",
        newLearning: "새로운 배움",
        outcomeRecorded: "결과 기록됨",
        experimentStarted: "실험 시작됨",
        experimentActive: "실험 진행 중",
        reflection: "되돌아보기",
        checkIn: "체크인",
        experimentOutcomeTitle: "실험 결과를 기록했습니다",
        reflectionTitle: "되돌아보기를 기록했습니다",
    },
};

export default ko;
