import type { Translation } from "@/constants/copy";
import type { DayPart } from "@/lib/dayPart";

/**
 * Urdu translation.
 *
 * Every key of the English source of truth is required; the compiler rejects
 * missing or extra keys. Uses respectful آپ address throughout. Urdu's
 * first-person verb forms inflect for the speaker's gender, so every string
 * that English writes as "I …" is phrased gender-neutrally here (imperatives,
 * "مجھے … چاہیے", or "ہم/آپ" constructions) — the app never has to guess the
 * user's gender. Proper nouns keep their Urdu or Latin forms (Aks, Mirror,
 * Premium, Notion, GitHub, Slack, Todoist) and Apple's and Google's apps use
 * their official Urdu or Latin product names.
 *
 * Typography: Urdu punctuation (، ۔ ؟), a space between Urdu and Latin words or
 * numerals for readability, and 24-hour times. Counts use counters rather than
 * plurals (3 مشاہدات). Mirror's deliberately hedged language survives
 * translation — possible patterns are ممکنہ پیٹرن and observations stay
 * غور کی دعوتیں، طبی نتائج نہیں.
 *
 * NOTE ON RENDERING: Urdu's Nastaliq letterforms are substantially different
 * from Arabic's Naskh, and the app's Satoshi typeface has no Arabic-script
 * glyphs. Android and iOS fall back to their bundled Arabic-script font, which
 * shapes Urdu correctly but renders it in Naskh rather than Nastaliq. The
 * surrounding layout is also still left-to-right — mirroring the chrome needs
 * I18nManager.forceRTL plus an app reload, which is separate work.
 */
const ur: Translation = {
    common: {
        back: "واپس",
        cancel: "منسوخ کریں",
        save: "محفوظ کریں",
        dismiss: "بند کریں",
        clear: "صاف کریں",
        loading: "لوڈ ہو رہا ہے…",
        tryAgain: "دوبارہ کوشش کریں",
        loadMore: "مزید لوڈ کریں",
        pleaseTryAgain: "براہ کرم دوبارہ کوشش کریں۔",
        checkConnection: "اپنا کنکشن دیکھیں اور دوبارہ کوشش کریں۔",
        emailPlaceholder: "you@example.com",
        justNow: "ابھی",
        dateUnavailable: "تاریخ دستیاب نہیں",
        version: (value: string) => `ورژن ${value}`,
    },
    brand: {
        name: "Aks.ai",
        tagline: "اپنے آپ کو ایک نئے زاویے سے سمجھیں۔",
    },
    splash: {
        appName: "Aks.ai",
        subtitle: "اپنے آپ کو ایک نئے زاویے سے سمجھیں۔",
    },
    onboarding: {
        skip: "چھوڑ دیں",
        moveForward: "آگے",
        getStarted: "شروع کریں",
        notices: {
            unableToContinue: "جاری نہیں رکھا جا سکا",
        },
        slides: [
            {
                eyebrow: "آپ کے دن نشان چھوڑتے ہیں",
                title: "آپ پہلے ہی اپنے بارے میں\nسراغ چھوڑ رہے ہیں۔",
                description:
                    "جو آپ دہراتے ہیں۔ جن لمحوں سے بچتے ہیں۔ وہ دن جو کچھ مختلف محسوس ہوتے ہیں۔ Aks یہی اشارے جمع کرتا ہے۔",
            },
            {
                eyebrow: "صرف سوچنے تک محدود نہیں",
                title: "ہم اندازہ نہیں لگاتے۔\nہم آزماتے ہیں۔",
                description:
                    "اپنے اندازے کو ایک چھوٹے تجربے میں بدلیں۔ ایک چیز بدلیں، دیکھیں کیا ہوتا ہے، اور جانیں کہ واقعی آپ کے لیے کیا کام کرتا ہے۔",
            },
            {
                eyebrow: "اپنے آپ کی واضح تصویر",
                title: "تاکہ آپ اپنے لیے\nمعمہ نہ رہیں۔",
                description:
                    "وقت کے ساتھ، Aks آپ کے پیٹرن، ردِعمل، اور وہ عوامل جو فرق ڈالتے ہیں، کی ایک زندہ تصویر بناتا ہے۔",
            },
        ],
    },
    legal: {
        termsTitle: "شرائطِ استعمال",
        privacyTitle: "پرائیویسی پالیسی",
        acceptance: {
            title: "شروع کرنے سے پہلے۔",
            description:
                "Aks آپ کی ذاتی معلومات کے ساتھ کام کرتے ہوئے آپ کو اپنے پیٹرن پہچاننے میں مدد کرتا ہے۔ آگے بڑھنے سے پہلے کچھ باتیں جاننا ضروری ہیں۔",
            cardTitle: "آپ کا ڈیٹا آپ کا ہے۔",
            cardBody:
                "Aks اُس معلومات کو استعمال کرتا ہے جو آپ شیئر کرنا چاہیں — پیٹرن ڈھونڈنے اور آپ کے ذاتی تجربات کی مدد کے لیے۔",
            bullets: [
                "آپ خود فیصلہ کرتے ہیں کہ کیا شیئر کرنا ہے۔",
                "آپ کسی بھی وقت اپنا ڈیٹا اور اجازتیں سنبھال سکتے ہیں۔",
                "Aks کسی معالج یا ڈاکٹر کے مشورے کا متبادل نہیں ہے۔",
            ],
            agreePrefix: "میں Aks.ai کی",
            terms: "شرائطِ استعمال",
            andWord: "اور",
            privacy: "پرائیویسی پالیسی سے اتفاق کرتا ہوں",
            continue: "Aks شروع کریں",
            retryAction: "دوبارہ کوشش",
            retry: "دوبارہ کوشش",
            footnote: "آپ یہ دستاویزات سیٹنگز سے کسی بھی وقت دیکھ سکتے ہیں۔",
            consentA11y: "شرائطِ استعمال اور پرائیویسی پالیسی سے اتفاق",
            notices: {
                unableToSave: "رضامندی محفوظ نہیں ہو سکی",
            },
        },
        links: {
            prefix: "جاری رکھنے سے آپ Aks.ai کی",
            terms: "شرائطِ استعمال",
            andWord: "اور",
            privacy: "پرائیویسی پالیسی سے اتفاق کرتے ہیں۔",
        },
    },
    login: {
        title: "خوش آمدید۔",
        description: "لاگ ان کریں اور دیکھیں کہ Aks نے آپ کے بارے میں کیا نوٹ کیا ہے۔",
        emailLabel: "ای میل ایڈریس",
        sendLink: "لاگ ان کریں",
        sendLinkA11y: "لاگ ان لنک بھیجیں",
        secureLinkNote: "ہم آپ کے ای میل پر ایک محفوظ لاگ ان لنک بھیجیں گے۔ پاس ورڈ کی ضرورت نہیں۔",
        divider: "یا اس کے ذریعے جاری رکھیں",
        google: "Google",
        googleA11y: "Google کے ساتھ جاری رکھیں",
        facebook: "Facebook",
        facebookA11y: "Facebook کے ساتھ جاری رکھیں",
        github: "GitHub",
        githubA11y: "GitHub کے ساتھ جاری رکھیں",
        noAccount: "اکاؤنٹ نہیں ہے؟",
        createOne: "بنائیں",
        dismissError: "بند کرنے کے لیے ٹیپ کریں۔",
        notices: {
            unableToSendLink: "لاگ ان لنک نہیں بھیجا جا سکا",
            unableToSignIn: "لاگ ان نہیں ہو سکا",
        },
    },
    register: {
        title: "آئیے آپ کا اکاؤنٹ بنائیں۔",
        description: "Aks کے ساتھ اپنے آپ کو زیادہ واضح طور پر دیکھنا شروع کریں۔",
        nameLabel: "نام",
        namePlaceholder: "آپ کا نام",
        nameA11y: "نام",
        emailLabel: "ای میل ایڈریس",
        createAccount: "اکاؤنٹ بنائیں",
        createAccountA11y: "ای میل سے اکاؤنٹ بنائیں",
        secureLinkNote: "ہم آپ کے ای میل پر ایک محفوظ لاگ ان لنک بھیجیں گے۔ پاس ورڈ کی ضرورت نہیں۔",
        divider: "یا اس کے ذریعے سائن اپ کریں",
        google: "Google",
        googleA11y: "Google کے ساتھ جاری رکھیں",
        facebook: "Facebook",
        facebookA11y: "Facebook کے ساتھ جاری رکھیں",
        github: "GitHub",
        githubA11y: "GitHub کے ساتھ جاری رکھیں",
        hasAccount: "پہلے سے اکاؤنٹ ہے؟",
        signIn: "لاگ ان کریں",
        dismissError: "بند کرنے کے لیے ٹیپ کریں۔",
        notices: {
            unableToCreate: "اکاؤنٹ نہیں بن سکا",
            unableToSignIn: "لاگ ان نہیں ہو سکا",
        },
    },
    emailConfirmation: {
        title: "اپنا ای میل دیکھیں۔",
        body: (email: string) =>
            `ہم نے ${email} پر محفوظ لاگ ان لنک بھیجا ہے۔ جاری رکھنے کے لیے یہ لنک اسی ڈیوائس پر کھولیں۔`,
        resendNote: "دوبارہ بھیجنے پر صرف تازہ ترین لنک کام کرے گا۔",
        resend: "لنک دوبارہ بھیجیں",
        resendA11y: "لاگ ان لنک دوبارہ بھیجیں",
        editEmail: "ای میل تبدیل کریں",
        editEmailA11y: "ای میل ایڈریس تبدیل کریں",
    },
    mirror: {
        eyebrow: "MIRROR",
        greeting: (firstName: string | null, part: DayPart = "morning") => {
            const base =
                part === "afternoon"
                    ? "سہ پہر بخیر"
                    : part === "evening"
                        ? "شام بخیر"
                        : part === "night"
                            ? "شب بخیر"
                            : "صبح بخیر";
            return `${base}${firstName ? `، ${firstName}` : ""}۔`;
        },
        intro: "میں Aks ہوں۔ آئیے کسی چھوٹی بات سے شروع کریں۔",
        understandTitle: "آپ کیا سمجھنا چاہتے ہیں؟",
        differentHint: "آپ Aks سے بالکل مختلف موضوع پر بھی بات کر سکتے ہیں۔",
        checkInEyebrow: "فوری چیک اِن",
        checkInTitle: "آج کیسا محسوس ہو رہا ہے؟",
        topics: ["توجہ", "توانائی", "نیند", "جذبات", "روزمرہ معمول", "رشتے", "پیداواریت"],
        topicDraft: (topic: string) => `مجھے ${topic} کو سمجھنے میں مدد چاہیے۔`,
        checks: ["اچھا", "ٹھیک", "بےترتیب"],
        aksLabel: "AKS",
        errorTitle: "کچھ غلط ہو گیا۔",
        retryResponse: "جواب دوبارہ حاصل کریں",
        listening: "سن رہا ہے…",
        listeningMeta: (duration: string) => `${duration} · صرف اسی ڈیوائس پر محفوظ`,
        stopRecordingA11y: "ریکارڈنگ روکیں",
        voiceReady: "آپ کا صوتی غور تیار ہے",
        voiceReadyHint: "Aks اسے ایک غور کے طور پر لکھ دے گا۔",
        discardRecordingA11y: "ریکارڈنگ رد کریں",
        sendRecordingA11y: "ریکارڈنگ بھیجیں",
        composerPlaceholder: "Aks کو بتائیں کہ اس وقت آپ کے ذہن میں کیا ہے…",
        sendMessageA11y: "پیغام بھیجیں",
        recordVoiceA11y: "صوتی غور ریکارڈ کریں",
        notices: {
            micUnavailable: "مائیک دستیاب نہیں",
            micUnavailableBody:
                "صوتی غور ریکارڈ کرنے کے لیے مائیک کی اجازت درکار ہے۔ آپ ٹائپ بھی کر سکتے ہیں۔",
            cantListen: "سننا شروع نہیں ہو سکا",
            cantListenBody: "دوبارہ کوشش کریں، یا جو ذہن میں ہے وہ لکھ دیں۔",
            stopRecording: "ریکارڈنگ روکی نہیں جا سکی",
            recordingFailed: "وہ ریکارڈنگ محفوظ نہیں ہو سکی",
            transcriptionNotConfigured:
                "اس بلڈ میں صوتی غور ابھی دستیاب نہیں۔ آپ اپنا غور لکھ سکتے ہیں۔",
            audioTooLong: "ریکارڈنگ بہت لمبی ہے۔ مختصر کر کے دوبارہ کوشش کریں۔",
            subscriptionRequired:
                "صوتی غور کے لیے Aks Premium درکار ہے، اس لیے یہ ریکارڈنگ استعمال نہیں کی گئی۔ آپ ٹائپ بھی کر سکتے ہیں۔",
            emptyTranscription: "Aks اس ریکارڈنگ میں کچھ سن نہیں سکا۔ مائیک دیکھیں اور دوبارہ کوشش کریں۔",
            unsupportedAudio: "ریکارڈنگ کا یہ فارمیٹ سپورٹ نہیں ہے۔ دوبارہ ریکارڈ کریں۔",
            transcriptionUnavailable:
                "Aks ابھی وہ ریکارڈنگ نہیں سن سکا۔ دوبارہ کوشش کریں یا ٹائپ کریں۔",
            unauthorized: "لاگ ان کریں، پھر دوبارہ کوشش کریں۔",
            recordingFailedFallback:
                "Aks ابھی وہ ریکارڈنگ محفوظ نہیں کر سکا۔ دوبارہ کوشش کریں یا ٹائپ کریں۔",
        },
    },
    mirrorBar: {
        newConversation: "نئی گفتگو",
        composerPlaceholder: "Aks کو بتائیں کہ اس وقت آپ کے ذہن میں کیا ہے…",
        sendMessageA11y: "پیغام بھیجیں",
        closeComposerA11y: "کمپوزر بند کریں",
        openKeyboardA11y: "کی بورڈ کھولیں",
        stopVoiceA11y: "صوتی گفتگو ختم کریں",
        startVoiceA11y: "صوتی گفتگو شروع کریں",
        voiceOffA11y: "آواز میں جواب بند کریں",
        voiceOnA11y: "آواز میں جواب آن کریں",
        moreOptionsA11y: "گفتگو کے مزید اختیارات",
        hint: "بولنے سے پہلے اپنے خیالات ترتیب دینا ضروری نہیں۔ بس شروع کریں۔",
    },
    aiConversation: {
        greeting: (firstName: string | null) => (firstName ? `خوش آمدید، ${firstName} 👋` : "خوش آمدید 👋"),
        openingPrompts: [
            "ان دنوں آپ کے ذہن میں کیا رہتا ہے؟",
            "آج کیسا محسوس ہو رہا ہے؟",
            "کوئی بات ہے جو کافی عرصے سے ذہن میں ہے؟",
            "آپ کے ذہن میں کیا چل رہا ہے؟",
            "کیا ہم اس بارے میں بات کریں جو آپ کے ذہن میں ہے؟",
            "کوئی بات ہے جو دل سے کہنا چاہیں؟",
            "ان دنوں کیا چیز بھاری لگتی ہے؟",
            "کوئی بات ہے جو کہنی چاہی تھی مگر کہہ نہیں سکے؟",
        ],
        copyAction: "کاپی",
        copiedAction: "کاپی ہو گیا",
        copyA11y: "پیغام کاپی کریں",
        shareAction: "شیئر کریں",
        shareA11y: "پیغام شیئر کریں",
        tryAgainAction: "دوبارہ کوشش",
        tryAgainA11y: "یہ جواب دوبارہ بنائیں",
        motionReadyA11y: "Aks تیار ہے",
        thinking: "سوچ رہا ہے…",
        thinkingDefault: "Aks سوچ رہا ہے…",
        aksTag: "aks",
        youTag: "آپ",
        listening: "سن رہا ہے…",
        speaking: "بول رہا ہے…",
        loadingConversation: "گفتگو لوڈ ہو رہی ہے…",
        youPrefix: "آپ: ",
        errorTitle: "کچھ غلط ہو گیا۔",
        retryResponse: "جواب دوبارہ حاصل کریں",
        voicePaused: "آواز روک دی گئی ہے۔",
        editPlaceholder: "اپنا پیغام دوبارہ لکھیں…",
        saveAndSend: "محفوظ کر کے بھیجیں",
        saveAndSendA11y: "ترمیم شدہ پیغام محفوظ کر کے بھیجیں",
        cancelEditingA11y: "ترمیم منسوخ کریں",
        cancel: "منسوخ کریں",
        editMessage: "پیغام میں ترمیم",
        editMessageA11y: "اپنے پیغام میں ترمیم کریں",
    },
    timeline: {
        header: "ٹائم لائن",
        headerCaption: "Aks کے ساتھ آپ کا سفر۔",
        eyebrow: "آپ کا سفر",
        title: "آپ کی کہانی جاری ہے۔",
        description:
            "یہاں آپ وہ لمحے، پیٹرن، تجربات اور سبق دیکھ سکتے ہیں جنہوں نے Aks کے ساتھ آپ کا وقت بنایا۔",
        errorTitle: "ٹائم لائن لوڈ نہیں ہو سکی۔",
        errorBody: "آپ کی کہانی یہیں محفوظ ہے۔ تھوڑی دیر بعد دوبارہ کوشش کریں۔",
        loadMoreError: "مزید لوڈ نہیں ہو سکا۔",
        empty: {
            allTitle: "آپ کی کہانی اب بھی جاری ہے۔",
            allBody: "Aks کے ساتھ بات کرتے ہوئے بامعنی لمحے، پیٹرن، تجربات اور سبق یہاں آئیں گے۔",
            insightsTitle: "ابھی کوئی بصیرت نہیں۔",
            insightsBody: "جب Aks وقت کے ساتھ کافی شواہد ڈھونڈ لے گا، بامعنی بصیرتیں یہاں آئیں گی۔",
            experimentsTitle: "ابھی کوئی تجربہ نہیں۔",
            experimentsBody: "آپ کے بنائے ہوئے تجربات چلانے پر یہاں آئیں گے۔",
            checkInsTitle: "ابھی کوئی چیک اِن نہیں۔",
            checkInsBody: "بامعنی چیک اِن یہاں آئیں گے۔",
            decisionsTitle: "ابھی کوئی فیصلہ نہیں۔",
            decisionsBody: "Aks کے نوٹ کیے گئے فیصلے اور پیٹرن واضح ہونے پر یہاں آئیں گے۔",
            learningsTitle: "ابھی کوئی سبق نہیں۔",
            learningsBody: "آپ کی کہانی واضح ہونے کے ساتھ نئے سبق یہاں آئیں گے۔",
        },
    },
    you: {
        title: "آپ",
        fallbackName: "Aks ممبر",
        subtitle: "آپ کی ذاتی جگہ",
        knowsTitle: "Aks کیا جانتا ہے",
        knowsEmpty: "ابھی آپ کو جان رہا ہے",
        memoriesCount: (count: number) => `${count} یادیں`,
        exploringTitle: "آپ کیا کھوج رہے ہیں",
        exploringEmpty: "دلچسپیاں چنیں",
        unnoticedTitle: "جو آپ نے ابھی نہیں دیکھا",
        insightsCount: (count: number) => `${count} بصیرتیں دیکھنے کے قابل`,
        insightsEmpty: "ابھی طے نہیں",
        journeySection: "آپ کا سفر",
        patternsTitle: "پیٹرن",
        patternsDescription: "جو Aks نے نوٹ کیا",
        experimentsTitle: "تجربات",
        experimentsDescription: "جو آپ ابھی آزما رہے ہیں",
        yourDataTitle: "آپ کا ڈیٹا",
        yourDataDescription: "معلومات دیکھیں اور سنبھالیں",
        preferencesSection: "ترجیحات",
        notificationsTitle: "اطلاعات",
        notificationsDescription: "Aks کب رابطہ کرے",
        appearanceTitle: "ظاہری شکل",
        appearanceDescription: "سسٹم · لائٹ · ڈارک",
        privacyTitle: "پرائیویسی",
        privacyDescription: "اجازتیں اور پرائیویسی سنبھالیں",
        supportSection: "مدد",
        helpTitle: "مدد اور رائے",
    },
    settings: {
        header: "سیٹنگز",
        eyebrow: "سیٹنگز",
        title: "Aks، آپ کے انداز میں۔",
        description: "اپنا اکاؤنٹ، سبسکرپشن اور Aks سے متعلق چیزیں سنبھالیں۔",
        accountSection: "اکاؤنٹ",
        profileTitle: "پروفائل",
        profileDescription: "اپنی ذاتی معلومات سنبھالیں",
        accountTitle: "اکاؤنٹ",
        accountDescription: "لاگ آؤٹ یا اکاؤنٹ حذف کریں",
        subscriptionTitle: "سبسکرپشن",
        subscriptionDescription: "Aks کے پلان اور ادائیگی سنبھالیں",
        preferencesSection: "ترجیحات",
        languageTitle: "زبان",
        aboutSection: "Aks کے بارے میں",
        aboutTitle: "Aks کے بارے میں",
        aboutDescription: "Aks کے بارے میں مزید جانیں",
        termsTitle: "شرائطِ استعمال",
        privacyTitle: "پرائیویسی پالیسی",
    },
    profile: {
        header: "پروفائل",
        fallbackName: "Aks ممبر",
        fallbackEmail: "ای میل ایڈریس دستیاب نہیں",
        editName: "نام تبدیل کریں",
        editNameA11y: "نام تبدیل کریں",
        changePhotoA11y: "پروفائل تصویر تبدیل کریں",
        photoA11y: "پروفائل تصویر",
        photoSheetTitle: "پروفائل تصویر",
        chooseImage: "تصویر چنیں",
        removePhoto: "تصویر ہٹائیں",
        aksSection: "Aks",
        exploringTitle: "آپ کیا کھوج رہے ہیں",
        exploringEmpty: "طے شدہ نہیں",
        noticeTitle: "Aks کو کس پر توجہ دینی چاہیے",
        noticeEmpty: "طے شدہ نہیں",
        preferencesSection: "ترجیحات",
        timezoneTitle: "ٹائم زون",
        languageTitle: "زبان",
        accountSection: "اکاؤنٹ",
        emailTitle: "ای میل ایڈریس",
        emailUnavailable: "دستیاب نہیں",
        memberSince: "رکنیت کب سے",
        memberSinceUnavailable: "دستیاب نہیں",
        signInMethod: "سائن اِن کا طریقہ",
        signInMethodFallback: "ای میل ایڈریس",
        editNameTitle: "نام تبدیل کریں",
        editNameMessage: "Aks آپ کو اسی نام سے پکارے گا۔",
        nameA11y: "نام",
        namePlaceholder: "آپ کا نام",
        saving: "محفوظ ہو رہا ہے…",
        saveChanges: "تبدیلیاں محفوظ کریں",
        fullName: "پورا نام",
        notices: {
            unableToSaveName: "پروفائل محفوظ نہیں ہو سکا",
            unableToUpdatePhoto: "تصویر اپ ڈیٹ نہیں ہو سکی",
            unableToRemovePhoto: "تصویر ہٹائی نہیں جا سکی",
            checkConnection: "کنکشن دیکھیں اور دوبارہ کوشش کریں۔",
            tryAgain: "براہ کرم دوبارہ کوشش کریں۔",
        },
    },
    exploring: {
        header: "آپ کیا کھوج رہے ہیں",
        eyebrow: "ذاتی",
        title: "اپنی دلچسپیاں چنیں۔",
        description: "وہ شعبے چنیں جنہیں آپ زیادہ واضح طور پر سمجھنا چاہتے ہیں۔",
        options: ["توجہ", "توانائی", "نیند", "مزاج", "عادات", "ذہنی دباؤ"],
    },
    noticeAreas: {
        header: "Aks کو کس پر توجہ دینی چاہیے",
        eyebrow: "ذاتی",
        title: "طے کریں کہ Aks کس پر توجہ دے۔",
        description: "ممکنہ پیٹرن ترتیب دیتے وقت Aks کن شعبوں سے شروع کرے، وہ چنیں۔",
        options: [
            "روزمرہ عادات",
            "توانائی کی تبدیلیاں",
            "توجہ کے پیٹرن",
            "نیند کا معیار",
            "مزاج کی تبدیلیاں",
            "تجربات کے نتائج",
        ],
    },
    timezone: {
        header: "ٹائم زون",
        eyebrow: "ترجیحات",
        title: "آپ کا مقامی وقت۔",
        description: "وہ ٹائم زون چنیں جو Aks وقت بندی کے لیے استعمال کرے۔",
    },
    language: {
        header: "زبان",
        eyebrow: "ترجیحات",
        title: "اپنی زبان چنیں۔",
        description: "وہ زبان چنیں جو پورے Aks میں استعمال ہو۔",
        notAvailableYet: (name: string) => `${name} ابھی دستیاب نہیں۔ ترجمہ آنے تک انگریزی استعمال ہوگی۔`,
        comingSoon: "جلد آ رہی ہے",
    },
    appearance: {
        header: "ظاہری شکل",
        eyebrow: "آپ کا تجربہ",
        title: "جس میں آپ آرام محسوس کریں۔",
        description: "چنیں کہ Aks پوری ایپ میں کیسا دکھے۔",
        themeSection: "تھیم",
        themes: {
            systemTitle: "سسٹم",
            systemDescription: "آپ کی ڈیوائس کی ترتیب کے مطابق۔",
            lightTitle: "لائٹ",
            lightDescription: "Aks روشن اور واضح۔",
            darkTitle: "ڈارک",
            darkDescription: "اندھیرے میں آنکھوں کے لیے نرم۔",
        },
        noteCaption: "AKS کی طرف سے نوٹ",
        noteBody: "ظاہری شکل صرف Aks کے دکھنے کا انداز بدلتی ہے۔",
        notices: {
            unableToSave: "ظاہری شکل محفوظ نہیں ہو سکی",
        },
    },
    account: {
        header: "اکاؤنٹ",
        signedInAs: "سائن اِن بطور",
        emailUnavailable: "ای میل ایڈریس دستیاب نہیں",
        signOut: "لاگ آؤٹ",
        deleteAccount: "اکاؤنٹ حذف کریں",
        confirmSignOutTitle: "لاگ آؤٹ کریں؟",
        confirmSignOutMessage: "Aks استعمال جاری رکھنے کے لیے آپ کو دوبارہ لاگ ان کرنا ہوگا۔",
        confirmDeleteTitle: "اکاؤنٹ حذف کریں؟",
        confirmDeleteMessage:
            "آپ کا اکاؤنٹ اور متعلقہ ڈیٹا مستقل طور پر حذف ہو جائے گا۔ اسے واپس نہیں لایا جا سکتا۔",
        notices: {
            unableToSignOut: "لاگ آؤٹ نہیں ہو سکا",
            unableToDelete: "اکاؤنٹ حذف نہیں ہو سکا",
            deleteUnavailable: "اکاؤنٹ حذف کرنا ابھی دستیاب نہیں۔ تھوڑی دیر بعد دوبارہ کوشش کریں۔",
        },
    },
    about: {
        header: "Aks کے بارے میں",
        eyebrow: "جائزہ",
        title: "اپنے آپ کو ایک نئے زاویے سے سمجھیں۔",
        description:
            "Aks آپ کی سرگرمی پر غور کرنے، ممکنہ پیٹرن نوٹ کرنے، اور زیادہ سوچے سمجھے ذاتی تجربات کرنے میں مدد کرتا ہے۔",
        productLabel: "پروڈکٹ",
        productValue: "Aks.ai",
        versionLabel: "ورژن",
        versionValue: "1.0.0",
        note: "Aks ذاتی غور کی مدد کا ذریعہ ہے، اور کسی معالج یا ڈاکٹر کے مشورے کا متبادل نہیں۔",
    },
    subscription: {
        header: "سبسکرپشن",
        eyebrow: "آپ کا پلان",
        title: "Aks کے پلان اور ادائیگی۔",
        description:
            "اپنا موجودہ پلان اور ادائیگی کی صورتحال دیکھیں۔ ادائیگی دستیاب ہونے پر آپ یہیں سے سبسکرپشن سنبھال سکیں گے۔",
        checkingPlan: "پلان چیک ہو رہا ہے…",
        fallbackError: "آپ کا پلان چیک نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
        currentPlan: "موجودہ پلان",
        activeBadge: "فعال",
        planActive: "آپ کا پلان فعال ہے۔",
        renewsOn: (date: string) => `${date} کو تجدید`,
        accessUntil: (date: string) => `${date} تک رسائی`,
        autoRenewOff: "خودکار تجدید بند ہے۔",
        billing: "ادائیگی",
        manage: "سبسکرپشن سنبھالیں",
        restore: "خریداریاں بحال کریں",
        choosePlan: "پلان چنیں",
        chooseTitle: "Aks کے ساتھ مزید وقت۔",
        chooseDescription:
            "وہ رفتار چنیں جو آپ کے لیے ٹھیک ہو۔ سبسکرپشن کسی بھی وقت سنبھالی اور بحال کی جا سکتی ہے۔",
        expiredWithDate: (date: string) => `${date} کو Premium رسائی ختم ہو گئی۔`,
        expiredFallback: "Premium رسائی ختم ہو گئی ہے۔",
        plansEmpty: "ابھی دکھانے کے لیے کوئی پلان نہیں۔ تھوڑی دیر بعد دیکھیں۔",
        premiumEyebrow: "AKS PREMIUM",
        bestValue: "بہترین قدر",
        premiumAccess: "Aks Premium تک مکمل رسائی",
        continueWith: (title: string) => `${title} کے ساتھ جاری رکھیں`,
        unavailableTitle: "اس ڈیوائس پر ابھی سبسکرپشن منسلک نہیں۔",
        unavailableBody:
            "جب اس ڈیوائس پر ادائیگی دستیاب ہوگی، پلان یہاں دکھیں گے اور آپ اسی اسکرین سے انہیں دیکھ اور سنبھال سکیں گے۔",
        noteCaption: "AKS کی طرف سے نوٹ",
        noteBody: "ادائیگی آپ کی ڈیوائس کے اسٹور سے ہوتی ہے۔",
    },
    notifications: {
        header: "اطلاعات",
        eyebrow: "صرف ضرورت پر",
        title: "صرف اہم لمحوں میں۔",
        description: "چنیں کہ Aks کس وقت رابطہ کرے۔ یہ ترتیبات کسی بھی وقت بدلی جا سکتی ہیں۔",
        sectionMain: "اطلاعات",
        allowTitle: "اطلاعات کی اجازت",
        allowDescription: "Aks کی تمام اطلاعات روکیں یا دوبارہ شروع کریں۔",
        categoriesSection: "AKS کیا بھیج سکتا ہے",
        categories: {
            insightsTitle: "نئی بصیرتیں",
            insightsDescription: "جب Aks کوئی بامعنی پیٹرن نوٹ کرے۔",
            experimentsTitle: "تجربات کی تازہ کاری",
            experimentsDescription: "جاری تجربات کی یاد دہانیاں اور نتائج۔",
            checkInsTitle: "چیک اِن یاد دہانیاں",
            checkInsDescription: "دن پر غور کرنے کی نرم دعوت۔",
            weeklyTitle: "ہفتہ وار غور",
            weeklyDescription: "ہفتے میں کیا بدلا، اس کا خلاصہ۔",
        },
        quietSection: "پرسکون اوقات",
        quietTitle: "پرسکون اوقات",
        quietDescription: "22:00 سے 8:00 تک ہم اطلاعات نہیں بھیجتے۔",
        deviceSection: "ڈیوائس کی ترتیبات",
        deviceTitle: "ڈیوائس اطلاعات سنبھالیں",
        deviceDescription: "Aks کی اجازتیں سنبھالنے کے لیے ڈیوائس کی سیٹنگز کھولیں۔",
        noteCaption: "AKS کی طرف سے نوٹ",
        noteBody: "Aks صرف اہم لمحوں میں رابطہ کرتا ہے۔",
    },
    yourData: {
        header: "آپ کا ڈیٹا",
        eyebrow: "آپ کا ڈیٹا",
        title: "Aks کیا یاد رکھتا ہے۔",
        description: "دیکھیں کہ Aks نے آپ کی سرگرمی سے کیا جمع کیا، اور آپ نے کیا شیئر کرنا چنا۔",
        glanceSection: "ایک نظر میں",
        remembersSection: "AKS کیا یاد رکھتا ہے",
        sourcesSection: "ڈیٹا کے ذرائع",
        sourcesTitle: "منسلک ذرائع",
        sourcesUnknown: "دیکھیں کہ کون سے ذرائع منسلک ہیں۔",
        sourcesNone: "کوئی ذریعہ منسلک نہیں۔ سپورٹ آنے پر دستیاب ہوں گے۔",
        sourcesCount: (count: number) => `${count} منسلک · کسی بھی وقت سنبھالیں یا الگ کریں۔`,
        choiceSection: "آپ کا انتخاب",
        choiceTitle: "کیا رہے گا، یہ آپ طے کرتے ہیں۔",
        choiceBody: "آپ کسی بھی وقت اپنی معلومات دیکھ، برآمد یا حذف کر سکتے ہیں۔",
        exportAction: "ڈیٹا برآمد کریں",
        deleteAction: "ڈیٹا حذف کریں",
        noteCaption: "AKS کی طرف سے نوٹ",
        noteBody: "آپ کا ڈیٹا واضح ہے اور آپ کے اختیار میں۔",
        loadingData: "ڈیٹا کا خلاصہ لوڈ ہو رہا ہے",
        retry: "دوبارہ کوشش",
    },
    reflections: {
        header: "غور",
        eyebrow: "آپ کے غور",
        title: "جو آپ نے شیئر کیا۔",
        description: "وہ غور دیکھیں جنہوں نے Aks کو آپ کے تجربے کا سیاق دیا۔",
        itemTitle: "غور",
        emptyTitle: "ابھی کوئی غور نہیں۔",
        emptyBody: "جب آپ Aks کے ساتھ شیئر کرنا شروع کریں گے، غور یہاں آئیں گے۔",
    },
    checkIns: {
        header: "چیک اِن",
        eyebrow: "آپ کے چیک اِن",
        title: "چھوٹے لمحے جو یاد رہے۔",
        description: "وہ چیک اِن دیکھیں جو آپ نے اُس وقت کے احساس کو ریکارڈ کرنے کے لیے استعمال کیے۔",
        itemFallback: "چیک اِن",
        itemTitle: (mood: string) => `${mood} موڈ کا چیک اِن`,
        energy: (value: number) => `توانائی ${value}`,
        focus: (value: number) => `توجہ ${value}`,
        stress: (value: number) => `ذہنی دباؤ ${value}`,
        noDetails: "مزید تفصیل نہیں",
        emptyTitle: "ابھی کوئی چیک اِن نہیں۔",
        emptyBody: "جب آپ ریکارڈ کرنا شروع کریں گے، چیک اِن یہاں آئیں گے۔",
    },
    conversations: {
        header: "گفتگوئیں",
        eyebrow: "آپ کی گفتگوئیں",
        title: "Aks کے ساتھ آپ کی گفتگو۔",
        description:
            "جو شیئر کیا، اسے اُسی طرح دیکھیں — بعد کی تشریحات کے بغیر۔ تلاش میں عنوانات اور گفتگو کا مواد دونوں شامل ہیں۔",
        searchA11y: "گفتگوئیں تلاش کریں",
        searchPlaceholder: "گفتگوئیں تلاش کریں",
        clearSearch: "صاف کریں",
        loadingA11y: "گفتگوئیں لوڈ ہو رہی ہیں",
        loadErrorTitle: "آپ کی گفتگوئیں لوڈ نہیں ہو سکیں۔",
        emptyQueryTitle: "کوئی ملتی گفتگو نہیں۔",
        emptyQueryBody: "کوئی اور لفظ آزمائیں — Aks عنوانات کے علاوہ آپ کی باتوں میں بھی تلاش کرتا ہے۔",
        emptyTitle: "ابھی کوئی گفتگو نہیں۔",
        emptyBody: "Aks کے ساتھ شروع کی گئی گفتگوئیں یہاں آئیں گی۔",
        archiveHint: "آرکائیو کے لیے دبا کر رکھیں",
        loadMore: "مزید لوڈ کریں",
        archiveTitle: "اس گفتگو کو آرکائیو کریں؟",
        archiveMessage: "یہ جاری گفتگو کی فہرست سے چھپ جائے گی۔",
        archiveConfirm: "آرکائیو",
        notices: {
            unableToArchive: "آرکائیو نہیں ہو سکی",
        },
    },
    conversationDetail: {
        fallbackTitle: "گفتگو",
        renameA11y: "گفتگو کا نام بدلیں",
        loadingA11y: "گفتگو لوڈ ہو رہی ہے",
        unavailableTitle: "گفتگو دستیاب نہیں۔",
        archivedBody: "یہ آرکائیو شدہ یا حذف شدہ ہو سکتی ہے۔",
        renameSection: "گفتگو کا نام بدلیں",
        titleA11y: "گفتگو کا عنوان",
        titlePlaceholder: "گفتگو کا عنوان",
        saveRename: "محفوظ کریں",
        cancelRename: "منسوخ کریں",
        cancelRenameA11y: "نام تبدیل کرنا منسوخ کریں",
        historySection: "گفتگو کی تاریخ",
        startedAt: (date: string) => `${date} کو شروع`,
        continueMirror: "Mirror میں جاری رکھیں",
        loadEarlier: "پرانے پیغامات لوڈ کریں",
        youLabel: "آپ",
        aksLabel: "Aks",
        systemLabel: "سسٹم",
        emptyTitle: "ابھی کوئی پیغام نہیں۔",
    },
    memories: {
        header: "Aks کیا یاد رکھتا ہے",
        eyebrow: "AKS کیا یاد رکھتا ہے",
        title: "کارآمد سیاق، احتیاط کے ساتھ۔",
        description: "وہ سب کچھ جو Aks نے آپ کی بار بار شیئر کی گئی، شواہد پر مبنی معلومات سے حاصل کیا۔",
        observationsCount: (count: number) => `${count} مشاہدات`,
        lastNoticed: (date: string) => `آخری بار ${date}`,
        emptyTitle: "Aks ابھی آپ کے پیٹرن جان رہا ہے۔",
        emptyBody: "جب یاد رکھنے کے لیے کافی شواہد جمع ہوں گے، بار بار آنے والا کارآمد سیاق یہاں دکھے گا۔",
    },
    memoryDetail: {
        header: "یاد",
        loadingA11y: "یاد لوڈ ہو رہی ہے",
        unavailableTitle: "یاد دستیاب نہیں۔",
        archivedFallback: "یہ آرکائیو شدہ یا حذف شدہ ہو سکتی ہے۔",
        eyebrow: "AKS کیا یاد رکھتا ہے",
        reasonTitle: "Aks اسے کیوں یاد رکھتا ہے",
        reasonFallback: (count: number) => `یہ آپ کی شیئر کی گئی ${count} باتوں میں آیا ہے۔`,
        lastNoticed: (date: string) => `آخری بار ${date}`,
        evidenceSection: "شواہد",
        viewConversation: " · گفتگو دیکھیں",
        archiveAction: "یاد آرکائیو کریں",
        removeAction: "یاد حذف کریں",
        archiveTitle: "یہ یاد آرکائیو کریں؟",
        archiveMessage:
            "Aks یہ یاد استعمال کرنا بند کر دے گا۔ آگے شیئر کی گئی باتیں دوبارہ اس کی تائید کر سکتی ہیں۔ اصل گفتگوئیں، غور اور چیک اِن اپنی جگہ رہیں گے۔",
        archiveConfirm: "آرکائیو",
        removeTitle: "یہ یاد حذف کریں؟",
        removeMessage:
            "اس سے صرف وہ یاد حذف ہوتی ہے جو Aks نے محفوظ کی۔ آپ کی شیئر کردہ اصل معلومات حذف نہیں ہوتیں۔",
        removeConfirm: "حذف کریں",
        notices: {
            unableToArchive: "آرکائیو نہیں ہو سکی",
            unableToRemove: "حذف نہیں ہو سکی",
        },
    },
    patterns: {
        header: "پیٹرن",
        eyebrow: "آپ کے پیٹرن",
        title: "غور کے قابل ربط۔",
        description: "آپ کی شیئر کردہ باتوں میں بار بار آنے والے اشاروں پر مبنی ممکنہ تعلقات۔",
        observationsCount: (count: number) => `${count} مشاہدات`,
        emptyTitle: "ابھی کوئی پیٹرن نہیں۔",
        emptyBody: "کارآمد ربط ڈھونڈنے کے لیے مزید وقت اور شواہد درکار ہیں۔",
        status: {
            possible: "ممکنہ پیٹرن",
            notSupported: "تائید نہیں",
            supported: "تائید شدہ",
            testing: "جانچ میں",
            fallback: "امیدوار",
        },
    },
    patternDetail: {
        header: "پیٹرن",
        loadingA11y: "پیٹرن لوڈ ہو رہا ہے",
        unavailableTitle: "پیٹرن دستیاب نہیں۔",
        archivedFallback: "یہ آرکائیو شدہ یا حذف شدہ ہو سکتا ہے۔",
        reasonTitle: "Aks نے یہ کیوں نوٹ کیا",
        evidenceLine: (supporting: number, contradicting: number) =>
            `یہ تعلق ${supporting} تائید کرنے والے مشاہدات` +
            (contradicting ? ` اور ${contradicting} مخالف مشاہدات` : "") +
            " سے جڑا ہے۔",
        confidencePending: "اعتماد کا جائزہ جاری",
        confidenceValue: (percent: number) => `شواہد کا اعتماد ${percent}%`,
        firstNoticed: (date: string) => `پہلی بار ${date}`,
        lastObserved: (date: string) => `آخری مشاہدہ ${date}`,
        alternativeTitle: "ایک اور وضاحت",
        evidenceSection: "شواہد",
        supporting: "تائید",
        contradicting: "مخالفت",
        viewConversation: " · گفتگو دیکھیں",
        notReadyA11y: "یہ پیٹرن ابھی جانچا نہیں جا سکتا",
        testA11y: "یہ پیٹرن آزمائیں",
        notReady: "ابھی تیار نہیں",
        testAction: "یہ پیٹرن آزمائیں",
        archiveAction: "پیٹرن آرکائیو کریں",
        removeAction: "پیٹرن حذف کریں",
        statusLabels: {
            candidate: "امیدوار",
            possible: "ممکنہ پیٹرن",
            testing: "جانچ میں",
            supported: "تائید شدہ",
            notSupported: "تائید نہیں",
            archived: "آرکائیو شدہ",
        },
        archiveTitle: "یہ پیٹرن آرکائیو کریں؟",
        archiveMessage:
            "Aks یہ پیٹرن دکھانا بند کر دے گا۔ آگے کے مشاہدات اس کے دوبارہ جائزے کا سبب بن سکتے ہیں۔",
        archiveConfirm: "آرکائیو",
        removeTitle: "یہ پیٹرن حذف کریں؟",
        removeMessage:
            "اس سے صرف اخذ کردہ پیٹرن اور اس کے شواہد کا ربط حذف ہوتا ہے۔ اشارے اور اصل معلومات اپنی جگہ رہتے ہیں۔",
        removeConfirm: "حذف کریں",
        notices: {
            unableToArchive: "آرکائیو نہیں ہو سکا",
            unableToRemove: "حذف نہیں ہو سکا",
        },
    },
    experiments: {
        header: "تجربات",
        eyebrow: "آپ کے تجربات",
        title: "چھوٹی آزمائشیں، کارآمد شواہد۔",
        description: "تجربات ممکنہ پیٹرن کو حقیقت ماننے کے بجائے آزمانے کا طریقہ ہیں۔",
        observationsCount: (count: number) => `${count} مشاہدات`,
        emptyTitle: "ابھی کوئی تجربہ نہیں۔",
        emptyBody: "جب کوئی پیٹرن جانچنے کے قابل ہوگا، آپ اسے ایک چھوٹے تجربے میں آزما سکیں گے۔",
        status: {
            active: "جاری",
            completed: "مکمل",
            cancelled: "منسوخ",
            fallback: "ڈرافٹ",
        },
    },
    experimentSetup: {
        header: "تجربہ ترتیب دیں",
        patternSection: "جانچنے والا پیٹرن",
        titleLabel: "عنوان",
        titlePlaceholder: "تجربے کا مختصر عنوان",
        hypothesisLabel: "مفروضہ",
        hypothesisPlaceholder: "ایک چھوٹی تبدیلی … پر اثر ڈال سکتی ہے",
        hypothesisDefault: "ایک چھوٹی تبدیلی اس پیٹرن میں دیکھی جانے والی چیزوں پر اثر ڈال سکتی ہے۔",
        descriptionLabel: "کیا آزمائیں اور کیا دیکھیں",
        descriptionPlaceholder: "ایک چھوٹی تبدیلی اور جو آپ ریکارڈ کریں گے، لکھیں۔",
        descriptionDefault:
            "ایک چھوٹی، واپس لی جا سکنے والی تبدیلی چنیں۔ ہر بار ریکارڈ کریں کہ معاملہ آسان رہا، ویسا ہی رہا، یا مشکل رہا۔",
        durationLabel: "دورانیہ",
        durationA11y: (days: number) => `${days} دن`,
        durationDays: (days: number) => `${days} دن`,
        defaultTitle: (patternTitle: string) => `آزمائش: ${patternTitle}`.slice(0, 120),
        createAction: "ڈرافٹ بنائیں",
        createA11y: "تجربے کا ڈرافٹ بنائیں",
        createError: "یہ تجربہ نہیں بن سکا۔ تفصیلات دیکھ کر دوبارہ کوشش کریں۔",
        patternUnavailable: "یہ پیٹرن دستیاب نہیں۔",
    },
    experimentDetail: {
        header: "تجربہ",
        unavailableTitle: "تجربہ دستیاب نہیں۔",
        hypothesisTitle: "مفروضہ",
        whatToTryTitle: "کیا آزمائیں",
        startAction: "تجربہ شروع کریں",
        startA11y: "تجربہ شروع کریں",
        removeAction: "تجربہ حذف کریں",
        removeA11y: "تجربہ حذف کریں",
        removeTitle: "یہ تجربہ حذف کریں؟",
        removeMessage:
            "یہ تجربہ، اس کے مشاہدات، اور وہ سبق جو صرف اسی تجربے سے تائید پاتے تھے، حذف ہو جائیں گے۔ اصل پیٹرن اور اشارے رہیں گے۔",
        removeConfirm: "حذف کریں",
        recordedFallback: "ریکارڈ شدہ",
        observationsSection: "مشاہدات",
        emptyObservations: "ابھی کوئی مشاہدہ ریکارڈ نہیں ہوا۔",
        resultSection: "نتیجہ",
        analysisPending: "تجزیے کے منتظر",
        confidenceValue: (percent: number) => `شواہد کا اعتماد ${percent}%`,
        promptTitle: "اس بار کیسا محسوس ہوا؟",
        resultEasier: "آسان رہا",
        resultSame: "ویسا ہی رہا",
        resultHarder: "مشکل رہا",
        recordA11y: (result: string) => `${result} کے طور پر ریکارڈ کریں`,
        observationPlaceholder: "اختیاری نوٹ",
        observationA11y: "اختیاری مشاہدہ نوٹ",
        observationsMeta: (count: number) => `${count} مشاہدات ریکارڈ`,
        observationsDay: (current: number, total: number | null) =>
            total ? ` · ${total} میں سے دن ${current}` : "",
        observationsThrough: (date: string) => ` · ${date} تک`,
        completeAction: "تجربہ مکمل کریں",
        completeA11y: "تجربہ مکمل کریں",
        cancelAction: "تجربہ منسوخ کریں",
        cancelA11y: "تجربہ منسوخ کریں",
        resultPendingBody: "نتیجہ ترتیب دیتے وقت آپ کے مشاہدات محفوظ رہتے ہیں۔",
        retryAnalysis: "تشریح دوبارہ آزمائیں",
        retryAnalysisA11y: "تجربے کا تجزیہ دوبارہ آزمائیں",
        retryLearning: "سبق دوبارہ ترتیب دیں",
        retryLearningA11y: "سبق دوبارہ ترتیب دیں",
        retryInsight: "بصیرت دوبارہ بنائیں",
        retryInsightA11y: "بصیرت دوبارہ بنائیں",
        resultLabels: {
            easier: "آسان رہا",
            same: "ویسا ہی رہا",
            harder: "مشکل رہا",
        },
        outcomeLabels: {
            supports: "مفروضے کی تائید",
            mixed: "نتائج ملی جلی",
            doesNotSupport: "مفروضے کی تائید نہیں",
            insufficientData: "ناکافی ڈیٹا",
        },
        confirmCompleteTitle: "یہ تجربہ مکمل کریں؟",
        confirmCompleteMessage: "Aks آپ کے مشاہدات کی بنیاد پر جو کہا جا سکتا ہے، اس کا خلاصہ کرے گا۔",
        confirmCompleteLabel: "مکمل کریں",
        confirmCancelTitle: "یہ تجربہ منسوخ کریں؟",
        confirmCancelMessage: "ریکارڈ کیے گئے مشاہدات اپنی جگہ رہیں گے۔",
        confirmCancelLabel: "تجربہ منسوخ کریں",
        keepGoing: "جاری رکھیں",
        notices: {
            unableToUpdate: "اپ ڈیٹ نہیں ہو سکا",
            unableToRecord: "ریکارڈ نہیں ہو سکا",
            recordRetry: "آخری ریکارڈ محفوظ ہے اور دوبارہ کوشش محفوظ ہے۔",
        },
    },
    learnings: {
        header: "سبق",
        eyebrow: "آپ کے سبق",
        title: "شواہد کیا بتاتے ہیں۔",
        description: "مکمل ہوئے تجربات اور ریکارڈ شدہ مشاہدات سے احتیاط کے ساتھ نکالے گئے نتائج۔",
        statusRevised: "نظرثانی شدہ",
        statusActive: "فعال",
        observationsCount: (count: number) => `${count} مشاہدات`,
        emptyTitle: "ابھی کوئی سبق نہیں۔",
        emptyBody:
            "جب آپ کچھ آزمائیں گے اور کافی شواہد جمع ہوں گے، Aks یہ ترتیب دینے میں مدد کرے گا کہ کیا بدلا۔",
    },
    learningDetail: {
        header: "سبق",
        unavailableTitle: "سبق دستیاب نہیں۔",
        evidenceTitle: "یہ کہاں سے آیا؟",
        evidenceLine: (experiments: number, observations: number) =>
            `یہ ${experiments} مکمل تجربات اور آپ کے ریکارڈ کیے ${observations} مشاہدات پر مبنی ہے۔`,
        confidenceValue: (percent: number) => `شواہد کا اعتماد ${percent}%`,
        updatedAt: (date: string) => `${date} کو اپ ڈیٹ`,
        sourceSection: "ذریعہ تجربہ",
        openExperimentA11y: (title: string) => `${title} تجربہ کھولیں`,
        observationsCount: (count: number) => `${count} مشاہدات`,
        archiveAction: "سبق آرکائیو کریں",
        archiveA11y: "سبق آرکائیو کریں",
        removeAction: "سبق حذف کریں",
        removeA11y: "سبق حذف کریں",
        resultLabels: {
            supports: "مفروضے کی تائید",
            mixed: "نتائج ملی جلی",
            doesNotSupport: "مفروضے کی تائید نہیں",
            insufficientData: "ناکافی ڈیٹا",
        },
        archiveTitle: "یہ سبق آرکائیو کریں؟",
        archiveMessage: "ذریعہ تجربہ اور اس کے مشاہدات دستیاب رہیں گے۔",
        archiveConfirm: "آرکائیو",
        removeTitle: "یہ سبق حذف کریں؟",
        removeMessage:
            "اس سے صرف اخذ کردہ سبق حذف ہوتا ہے۔ تجربات، مشاہدات، پیٹرن اور اشارے اپنی جگہ رہتے ہیں۔",
        removeConfirm: "حذف کریں",
        notices: {
            unableToArchive: "آرکائیو نہیں ہو سکا",
            unableToRemove: "حذف نہیں ہو سکا",
        },
    },
    insights: {
        header: "بصیرتیں",
        eyebrow: "بصیرتیں",
        title: "غور کے قابل باتیں۔",
        description: "آپ نے کیا آزمایا اور سیکھا، اس پر مبنی چند بروقت مشاہدات۔",
        statusNew: "نئی",
        statusSeen: "دیکھی گئی",
        emptyTitle: "ابھی کوئی بصیرت نہیں۔",
        emptyBody: "جب Aks وقت کے ساتھ کافی شواہد ڈھونڈے گا، کارآمد باتیں سامنے آنے لگیں گی۔",
    },
    insightDetail: {
        header: "بصیرت",
        eyebrow: "بصیرتیں",
        unavailableTitle: "بصیرت دستیاب نہیں۔",
        reasonTitle: "Aks نے یہ کیوں نوٹ کیا",
        openExperimentA11y: (title: string) => `${title} تجربہ کھولیں`,
        openLearningA11y: (title: string) => `${title} سبق کھولیں`,
        observationsCount: (count: number) => `${count} مشاہدات ریکارڈ · تجربہ دیکھیں`,
        viewLearning: "ذریعہ سبق دیکھیں",
        confidenceValue: (percent: number) => `شواہد کا اعتماد ${percent}%`,
        createdAt: (date: string) => `${date} کو بنائی گئی`,
        dismissAction: "بصیرت بند کریں",
        dismissA11y: "بصیرت بند کریں",
        removeAction: "بصیرت حذف کریں",
        removeA11y: "بصیرت حذف کریں",
        dismissTitle: "یہ بصیرت بند کریں؟",
        dismissMessage: "سبق، تجربات، پیٹرن اور شواہد اپنی جگہ رہیں گے۔",
        dismissConfirm: "بند کریں",
        removeTitle: "یہ بصیرت حذف کریں؟",
        removeMessage: "صرف یہی بصیرت حذف ہوتی ہے۔ باقی تمام اصل معلومات اپنی جگہ رہتی ہیں۔",
        removeConfirm: "حذف کریں",
        notices: {
            unableToDismiss: "بند نہیں ہو سکی",
            unableToRemove: "حذف نہیں ہو سکی",
        },
    },
    privacyHome: {
        header: "پرائیویسی",
        eyebrow: "آپ کی پرائیویسی",
        title: "آپ کی زندگی آپ کی ہے۔",
        description:
            "Aks آپ کو اپنے آپ کو سمجھنے میں مدد دیتا ہے، جبکہ اس تجربے کو ممکن بنانے والی معلومات آپ کے اختیار میں رہتی ہیں۔",
        dataSection: "آپ کا ڈیٹا",
        knowsTitle: "Aks کیا جانتا ہے",
        knowsDescription: "وہ معلومات سمجھیں جو آپ کے تجربے کی بنیاد ہیں۔",
        accessTitle: "Aks کس تک رسائی رکھتا ہے",
        accessDescription: "دیکھیں کہ آپ نے کیا فراہم یا منسلک کیا۔",
        controlsSection: "اپنے ڈیٹا کا انتظام",
        usageTitle: "ڈیٹا کیسے استعمال ہوتا ہے",
        usageDescription: "دیکھیں کہ معلومات بصیرتوں اور تجربات کی مدد کیسے کرتی ہیں۔",
        exportTitle: "ڈیٹا برآمد کریں",
        exportDescription: "اپنی Aks معلومات کی نقل کی درخواست کریں۔",
        deleteTitle: "ڈیٹا حذف کریں",
        deleteDescription: "اکاؤنٹ ڈیٹا حذف کرنے کا محتاط عمل شروع کریں۔",
        legalSection: "قانونی معلومات",
        privacyPolicyTitle: "پرائیویسی پالیسی",
        privacyPolicyDescription: "Aks کی مکمل پرائیویسی پالیسی پڑھیں۔",
    },
    dataAccess: {
        header: "Aks کس تک رسائی رکھتا ہے",
        title: "ڈیزائن سے واضح۔",
        description:
            "Aks صرف وہ معلومات استعمال کرتا ہے جو آپ نے فراہم کیں، اور وہ ڈیٹا ذرائع جو آپ نے واضح طور پر منسلک کیے۔",
        sourcesSection: "منسلک ذرائع",
        loadingSources: "منسلک ذرائع لوڈ ہو رہے ہیں…",
        loadError: "ابھی منسلک ذرائع لوڈ نہیں ہو سکے۔",
        emptyTitle: "ابھی کوئی ذریعہ منسلک نہیں",
        emptyBody:
            "Aks کسی بیرونی سروس کو صرف اُس وقت پڑھتا ہے جب آپ واضح طور پر منسلک کریں۔ آپ اکاؤنٹ سیٹنگز سے کسی بھی وقت منسلکات سنبھال سکتے ہیں۔",
        connectedNeedsPermission: "منسلک · اجازت درکار",
        connectedSynced: (relative: string) => `منسلک اور ڈیٹا پڑھ رہا ہے · آخری مطابقت ${relative}`,
        connectedNotSynced: "منسلک اور ڈیٹا پڑھ رہا ہے · ابھی مطابقت نہیں ہوئی",
        holdsSection: "AKS کیا محفوظ رکھتا ہے",
        items: [
            {
                title: "وہ معلومات جو آپ نے فراہم کیں",
                body: "جیسے آپ کی پروفائل تفصیلات اور ترجیحات، اور جو کچھ آپ نے سیدھا Aks میں درج کیا۔",
            },
            {
                title: "غور اور چیک اِن",
                body: "وہ ریکارڈ جو آپ نے اپنے تجربے، مزاج، توجہ، توانائی اور روزمرہ معمول کو ظاہر کرنے کے لیے بنائے۔",
            },
            {
                title: "تجربات کا ڈیٹا",
                body: "آپ کے بنائے ہوئے تجربات، اور آپ کے ریکارڈ کیے نتائج اور نوٹس۔",
            },
            {
                title: "اکاؤنٹ کی معلومات",
                body: "وہ بنیادی باتیں جو آپ کے Aks اکاؤنٹ کی شناخت اور دیکھ بھال کے لیے ضروری ہیں۔",
            },
            {
                title: "منسلک ڈیٹا ذرائع",
                body: "صرف اُن خدمات کی معلومات جو آپ نے واضح طور پر منسلک کرنے کا انتخاب کیا — اور صرف اُس وقت جب وہ منسلکہ دستیاب ہو۔",
            },
        ],
        controlTitle: "اختیار آپ کے پاس ہے",
        controlBody: "Aks صرف وہی استعمال کرتا ہے جو آپ نے خود درج کیا یا واضح طور پر منسلک کیا۔",
    },
    dataUsage: {
        header: "ڈیٹا کیسے استعمال ہوتا ہے",
        title: "ڈیٹا کا ایک مقصد ہے۔",
        description: "Aks ایپ کے اندر معلومات استعمال کرتا ہے تاکہ آپ کا تجربہ زیادہ متعلقہ اور واضح ہو۔",
        sections: [
            {
                title: "Aks ڈیٹا کیوں استعمال کرتا ہے",
                body: "جو معلومات آپ شیئر کرنے کا انتخاب کرتے ہیں، وہ Aks کو آپ کے غور کو ذاتی بنانے، کارآمد موضوعات ڈھونڈنے، اور آپ کے مقاصد کی مدد کرنے میں معاون ہوتی ہیں۔",
            },
            {
                title: "غور اور چیک اِن",
                body: "آپ کے ریکارڈ آپ کے مزاج، توانائی، توجہ اور روزمرہ معمول کی تبدیلیوں کو سیاق دیتے ہیں۔",
            },
            {
                title: "پیٹرن کی نشاندہی",
                body: "Aks آپ کی فراہم کردہ معلومات کا موازنہ کر کے ممکنہ پیٹرن سامنے لا سکتا ہے جنہیں جانچا جا سکتا ہے۔ یہ غور کی دعوتیں ہیں، طبی نتائج نہیں۔",
            },
            {
                title: "یادیں",
                body: "Aks کبھی بار بار آنے والا کارآمد سیاق تھوڑی مقدار میں محفوظ رکھتا ہے۔ یادیں ہمیشہ اُن معلومات سے جڑی ہوتی ہیں جو انہیں تائید دیتی ہیں، اور اصل معلومات حذف کیے بغیر ہٹائی جا سکتی ہیں۔",
            },
            {
                title: "تجربات اور نتائج",
                body: "تجربات کے ریکارڈ آپ کو یہ موازنہ کرنے کا موقع دیتے ہیں کہ آپ نے کیا آزمایا اور کیا نتیجہ نکلا۔",
            },
            {
                title: "AI کی مدد سے سمجھ",
                body: "AI آپ کی فراہم کردہ معلومات کو ترتیب دینے یا خلاصہ کرنے میں مدد کر سکتا ہے۔ اہم بصیرتیں ہمیشہ خود جانچیں اور اپنی صوابدید سے لیں۔",
            },
        ],
        privacyPolicyAction: "مکمل پرائیویسی پالیسی پڑھیں",
    },
    exportData: {
        header: "ڈیٹا برآمد کریں",
        preparingTitle: "آپ کی برآمد تیار ہو رہی ہے",
        preparingBody:
            "آپ کی گفتگوئیں، غور، یادیں، پیٹرن، تجربات اور بصیرتیں جمع کی جا رہی ہیں۔ یہ عام طور پر چند سیکنڈ لیتا ہے۔",
        errorTitle: "اپنا ڈیٹا ساتھ لے جائیں۔",
        errorBody: "درخواست پر ہم آپ کی Aks معلومات کو ڈاؤن لوڈ کے قابل شکل میں تیار کرتے ہیں۔",
        failedTitle: "برآمد نہیں بن سکی۔",
        failedFallback: "برآمد تیار کرتے وقت مسئلہ پیش آیا۔ دوبارہ کوشش کریں۔",
        retryA11y: "برآمد دوبارہ بنانے کی کوشش کریں",
        cancelAction: "منسوخ کریں",
        cancelA11y: "برآمد کی تفصیل پر واپس جائیں",
        readyTitle: "آپ کی برآمد تیار ہے۔",
        readyBody:
            "ابھی آپ کی Aks معلومات کی نقل بنائی گئی ہے۔ یہ وہی حصے ہیں جو درخواست کے وقت دکھائے گئے تھے۔",
        expiresIn: (countdown: string) => `لنک ${countdown} میں ختم ہو جائے گا`,
        expiresSoon: "بہت جلد",
        saveAction: "برآمد محفوظ کریں",
        saveA11y: "برآمد محفوظ کریں",
        requestAnother: "ایک اور برآمد کی درخواست کریں",
        requestAnotherA11y: "ایک اور برآمد کی درخواست کریں",
        idleTitle: "اپنا ڈیٹا ساتھ لے جائیں۔",
        idleBody:
            "درخواست پر ہم آپ کی Aks معلومات کو ڈاؤن لوڈ کے قابل شکل میں تیار کرتے ہیں۔ ہر برآمد ایک فائل ہوتی ہے جو درخواست کے وقت آپ کے اکاؤنٹ کی صورتحال ظاہر کرتی ہے۔",
        includedSection: "کیا شامل ہے",
        included: [
            "پروفائل اور ترجیحات",
            "گفتگوئیں اور پیغامات",
            "غور",
            "چیک اِن",
            "اشارے",
            "یادیں اور شواہد کا ربط",
            "پیٹرن اور شواہد کا ربط",
            "تجربات اور مشاہدات",
            "سبق اور حوالہ جات",
            "بصیرتیں اور حوالہ جات",
        ],
        requestAction: "ڈیٹا برآمد کرنے کی درخواست",
        requestA11y: "برآمد کی درخواست کریں",
    },
    deleteData: {
        header: "ڈیٹا حذف کریں",
        title: "کچھ بھی باقی نہ رہے۔",
        description:
            "اکاؤنٹ حذف کرنے سے Aks میں آپ کا بنایا ہوا ڈیٹا مستقل طور پر مٹ جاتا ہے اور اس ڈیوائس سے لاگ آؤٹ ہو جاتا ہے۔",
        warningTitle: "اسے واپس نہیں لایا جا سکتا۔",
        warningBody:
            "اکاؤنٹ حذف کرنے سے آپ کا Aks ڈیٹا چلا جائے گا اور بحال نہیں ہو سکے گا۔ اگر نقل درکار ہو، تو پہلے ڈیٹا برآمد کرنے پر غور کریں۔",
        removedSection: "کیا حذف ہوگا",
        removed: [
            "گفتگوئیں اور پیغامات",
            "غور",
            "چیک اِن",
            "اخذ کردہ اشارے",
            "یادیں اور شواہد کا ربط",
            "پیٹرن اور شواہد کا ربط",
            "تجربات اور مشاہدات",
            "سبق اور حوالہ جات",
            "بصیرتیں اور حوالہ جات",
        ],
        confirmA11y: "ناقابلِ واپسی عمل کی تصدیق کریں",
        confirmLabel: "مجھے سمجھ آ گیا ہے کہ یہ عمل ناقابلِ واپسی ہے اور میرا سارا Aks ڈیٹا حذف ہو جائے گا۔",
        deleteAction: "اکاؤنٹ اور ڈیٹا حذف کریں",
        deleteActionA11y: "اکاؤنٹ اور ڈیٹا حذف کریں",
        deletingAction: "اکاؤنٹ حذف ہو رہا ہے…",
        deletedTitle: "آپ کا اکاؤنٹ حذف ہو رہا ہے۔",
        deletedBody: "حذف مکمل ہونے پر آپ لاگ آؤٹ ہو جائیں گے۔",
        backToSettings: "سیٹنگز پر واپس",
        backToSettingsA11y: "سیٹنگز پر واپس جائیں",
        keepAccount: "اکاؤنٹ رکھیں",
        keepAccountA11y: "اکاؤنٹ رکھیں",
        keepNote: "اکاؤنٹ حذف کرنے سے اس اکاؤنٹ کے لیے بنائی گئی برآمد فائلیں بھی حذف ہو جاتی ہیں۔",
    },
    helpHome: {
        header: "مدد اور رائے",
        title: "ہم آپ کی بات سننا چاہتے ہیں۔",
        description: "کوئی چیز کام نہیں کر رہی، واضح نہیں، یا آپ چاہتے ہیں کہ Aks کچھ اور کرے؟",
        supportTitle: "مدد چاہیے؟",
        supportBody: "ہماری سپورٹ ٹیم آپ کی مدد کرے گی۔",
        supportAction: "سپورٹ سے رابطہ کریں",
        getHelpSection: "مدد حاصل کریں",
        faqTitle: "عام سوالات",
        faqDescription: "عام سوالات کے جواب جلدی پائیں",
        reportTitle: "مسئلہ رپورٹ کریں",
        reportDescription: "جب کوئی چیز ٹھیک نہ چلے تو بتائیں",
        improveSection: "AKS کو بہتر بنائیں",
        suggestTitle: "تجویز دیں",
        suggestDescription: "بتائیں کہ Aks کیا سیکھے یا کیا کرے",
        shareTitle: "تجربہ شیئر کریں",
        shareDescription: "بتائیں کیا اچھا لگا اور کیا بہتر ہو سکتا ہے",
        contactSection: "رابطہ",
        supportEmail: "support@aks.ai",
        supportResponse: "ہم عام طور پر 1–2 کاروباری دنوں میں جواب دیتے ہیں",
        footerVersion: "1.0.0",
    },
    faq: {
        header: "مدد اور رائے",
        title: "عام سوالات",
        description: "Aks کیسے کام کرتا ہے اور ہم آپ کے ڈیٹا کا خیال کیسے رکھتے ہیں، اس کے جواب جلدی پائیں۔",
        searchPlaceholder: "سوالات تلاش کریں",
        clearSearch: "صاف کریں",
        resultsCount: (count: number) => `${count} نتائج`,
        popularSection: "اکثر پوچھے جانے والے سوالات",
        questionsCount: (count: number) => `${count} سوالات`,
        items: [
            {
                question: "Aks پیٹرن کیسے ڈھونڈتا ہے؟",
                answer: "Aks اُن معلومات اور غور میں کارآمد ربط تلاش کرتا ہے جو آپ شیئر کرنے کا انتخاب کرتے ہیں۔",
            },
            {
                question: "کیا Aks جو ڈیٹا استعمال کرتا ہے، وہ میں خود چن سکتا ہوں؟",
                answer: "جی ہاں۔ «آپ کا ڈیٹا» اور «پرائیویسی» سے آپ اپنی معلومات دیکھ سکتے ہیں اور دستیاب اجازتیں سنبھال سکتے ہیں۔",
            },
            {
                question: "تجربات کیسے کام کرتے ہیں؟",
                answer: "تجربات آپ کو ایک چھوٹی تبدیلی آزمانے اور یہ دیکھنے میں مدد دیتے ہیں کہ اس کا آپ کی توجہ، توانائی، نیند اور روزمرہ معمول پر کیا اثر ہوتا ہے۔",
            },
            {
                question: "کیا اطلاعات کی ترتیبات بدلی جا سکتی ہیں؟",
                answer: "جی ہاں۔ «آپ» صفحے سے «اطلاعات» کھولیں اور چنیں کہ Aks کس وقت رابطہ کرے۔",
            },
            {
                question: "کیا Aks طبی مشورہ ہے؟",
                answer: "نہیں۔ Aks ذاتی غور کی مدد کا ذریعہ ہے، اور کسی معالج یا ڈاکٹر کے مشورے کا متبادل نہیں۔",
            },
        ],
        emptyTitle: "کوئی ملتا جواب نہیں",
        emptyBody: "کوئی اور لفظ آزمائیں یا اوپر کے سوالات دیکھیں۔",
        clearAction: "تلاش صاف کریں",
        helpTitle: "اب بھی مدد چاہیے؟",
        helpBody: "بتائیں کیا ہو رہا ہے، ہم ساتھ مل کر سمجھیں گے۔",
        contactAction: "رابطہ کریں",
    },
    sendFeedback: {
        header: "رائے بھیجیں",
        title: "آئیے Aks کو مل کر بنائیں۔",
        description: "اپنے خیالات، فیچر کی درخواستیں، یا وہ باتیں جو پہلے ہی اچھی لگتی ہیں، شیئر کریں۔",
        optionLabel: "رائے کی قسم",
        optionHint: "ایک چنیں",
        options: ["خیال", "فیچر کی درخواست", "عمومی رائے", "کیا اچھا لگا"],
        initialOption: "عمومی رائے",
        messageLabel: "آپ کی رائے",
        messagePlaceholder: "کون سی بات Aks کو زیادہ کارآمد بنائے گی؟",
        messageHint: "کوئی بھی خیال، تجویز یا تعریف خوش آئند ہے۔",
        emailHint: "اگر جواب چاہیے تو اپنا ای میل شامل کریں۔",
        noteTitle: "آپ کی رائے اہم ہے۔",
        noteBody: "آپ کی شیئر کردہ باتیں Aks کے اگلے قدم کا تعین کرنے میں مدد دیتی ہیں۔",
        submit: "رائے بھیجیں",
        leaveMessage: "کچھ بھیجے بغیر آپ یہ صفحہ چھوڑ سکتے ہیں۔",
    },
    reportProblem: {
        header: "مسئلہ رپورٹ کریں",
        title: "کیا ہوا؟",
        description: "بتائیں کیا ہوا۔ جتنا زیادہ سیاق، اتنی آسانی سے ہم سمجھ اور درست کر سکتے ہیں۔",
        optionLabel: "مسئلے کی قسم",
        optionHint: "ایک چنیں",
        options: [
            "کوئی فیچر کام نہیں کر رہا",
            "ایپ بند ہو گئی",
            "بصیرتیں درست نہیں",
            "ڈیٹا کا مسئلہ",
            "اطلاعات کا مسئلہ",
            "کچھ اور",
        ],
        messageLabel: "کیا ہوا؟",
        messagePlaceholder: "آپ نے کیا توقع کی اور واقعی کیا ہوا، لکھیں…",
        messageHint: "اگر مسئلہ دہرانے کے مراحل ہوں تو شامل کریں۔",
        emailHint: "اگر ہم رابطہ کریں تو اپنا ای میل شامل کریں۔",
        noteTitle: "Aks کو بہتر بنانے میں مدد کا شکریہ۔",
        noteBody: "آپ کی رپورٹ سب کے لیے Aks کو زیادہ قابلِ اعتماد بنانے میں مدد دیتی ہے۔",
        submit: "رپورٹ بھیجیں",
        leaveMessage: "بھیجے بغیر آپ یہ صفحہ چھوڑ سکتے ہیں۔",
    },
    feedbackForm: {
        selectedState: "منتخب",
        contactEmail: "رابطے کا ای میل",
        optionalMark: "(اختیاری)",
        emailPlaceholder: "you@example.com",
        charLimit: 1000,
    },
    profilePreference: {
        saveAction: "ترجیح محفوظ کریں",
        saveA11y: (title: string) => `${title} محفوظ کریں`,
        noteCaption: "پروفائل میں محفوظ",
        noteBody: "آپ کا انتخاب پروفائل میں محفوظ ہوتا ہے۔",
        notices: {
            unableToSave: "ترجیح محفوظ نہیں ہو سکی",
        },
    },
    dataCategory: {
        recentSection: "حالیہ",
        loadingA11y: (title: string) => `${title} لوڈ ہو رہا ہے`,
        loadErrorTitle: "یہ ڈیٹا لوڈ نہیں ہو سکا۔",
        tryAgain: "دوبارہ کوشش",
        loadMore: "مزید لوڈ کریں",
        noteCaption: "AKS کی طرف سے نوٹ",
        noteBody: "آپ کے بنائے ہوئے ریکارڈ یہاں دکھیں گے۔",
    },
    bottomSheet: {
        dismissA11y: "بند کریں",
        defaultConfirm: "ٹھیک ہے",
        cancel: "منسوخ کریں",
    },
    connectedSources: {
        header: "منسلک ذرائع",
        eyebrow: "سیاق و اجازت",
        title: "Aks کیا جانتا ہے، یہ آپ طے کرتے ہیں۔",
        description:
            "کوئی بھی ذریعہ منسلک کیے بغیر بھی Aks استعمال کیا جا سکتا ہے۔ ہر ذریعہ اختیاری اور خودمختار ہے، اور واضح کرتا ہے کہ کیا شیئر کرتا ہے۔ آپ کسی بھی وقت الگ کر سکتے ہیں۔",
        loadingA11y: "ذرائع لوڈ ہو رہے ہیں",
        loadError: "منسلک ذرائع لوڈ نہیں ہو سکے۔",
        status: {
            connected: "منسلک",
            permissionRequired: "اجازت درکار",
            notConnected: "منسلک نہیں",
            notAvailable: "اس ڈیوائس پر دستیاب نہیں",
            revoked: "الگ کیا گیا",
            temporarilyUnavailable: "عارضی طور پر دستیاب نہیں",
            error: "ابھی دستیاب نہیں",
        },
        syncedAgo: (relative: string) => `آخری مطابقت ${relative}`,
        notSynced: "ابھی مطابقت نہیں ہوئی",
        whyHelps: "یہ کیسے مدد کرتا ہے",
        whatReceives: "AKS کیا وصول کرتا ہے",
        whatStored: "کیا محفوظ ہوتا ہے",
        howToStop: "کیسے روکیں",
        goodToKnow: "جاننا اچھا ہے",
        disconnect: "منسلکات الگ کریں",
        deleteData: "درآمد شدہ ڈیٹا حذف کریں",
        allow: "اجازت دیں",
        connect: "منسلک کریں",
        reconnect: "دوبارہ منسلک کریں",
        choiceSection: "آپ کا انتخاب",
        choiceBody: "صرف منسلک ذرائع استعمال ہوتے ہیں۔ آپ کسی بھی وقت ایک ٹیپ سے روک سکتے ہیں۔",
        confirmations: {
            cancelAction: "منسوخ کریں",
        },
        notices: {
            providerNotConfigured: "اس بلڈ میں یہ پرووائیڈر ابھی ترتیب نہیں دیا گیا۔",
            unableToConnect: "ابھی اس ذریعے سے رابطہ نہیں ہو سکا۔",
        },
        groups: {
            productivity: "پیداواریت",
            work: "کام",
            device: "ڈیوائس / رویہ",
        },
    },
    sources: {
        location: {
            name: "مقام",
            purpose:
                "Aks کو یہ سمجھنے میں مدد دیتا ہے کہ آپ کا دن کہاں گزر رہا ہے۔ اس سے مشکل دن اور اُن دنوں میں فرق کرنا آسان ہوتا ہے جو سفر یا غیر متوقع تبدیلیوں سے بگڑ جاتے ہیں۔",
            receives:
                "تقریبی مقام کا سیاق (گھر کے قریب، دفتر کے قریب، سفر میں، غیر مانوس جگہ) اور وقت — مسلسل ٹریکنگ نہیں۔",
            stored: "مشاہدے کی وقتی حدود، جیسے «سفر، تقریباً 18:30 پر 45 منٹ»۔ درست نقاط محفوظ نہیں کیے جاتے۔",
            stop: "مقام آپ کسی بھی وقت الگ کر سکتے ہیں۔ بعد میں جمع کرنا فوراً رک جاتا ہے، اور محفوظ مشاہدات الگ سے حذف کیے جا سکتے ہیں۔",
            batteryNote: "منسلک رہنے کے دوران ہم وقفے وقفے سے مقام دیکھتے ہیں۔ اس سے بیٹری کا استعمال کچھ بڑھ سکتا ہے۔",
        },
        calendar: {
            name: "کیلنڈر",
            purpose:
                "طے شدہ مصروفیات معلوم ہونے پر Aks کے لیے «منصوبہ بدل گیا» اور «حوصلہ کم ہوا» میں فرق کرنا آسان ہو جاتا ہے۔",
            receives:
                "مصروفیات کے اوقات اور تقریبی اقسام۔ عنوانات صرف مصروفیت کی تعریف کے لیے استعمال ہوتے ہیں؛ ہم شرکاء کی فہرست، نوٹس یا میٹنگ لنک نہیں پڑھتے۔",
            stored: "کم سے کم مصروفیت کے ریکارڈ: وقت، دورانیہ، قسم، اور تصدیق شدہ/منسوخ۔",
            stop: "کیلنڈر آپ کسی بھی وقت الگ کر سکتے ہیں۔ بعد میں جمع کرنا فوراً رک جاتا ہے۔",
        },
        reminders: {
            name: "کام اور یاد دہانیاں",
            purpose:
                "وہ کام جو آپ کرنے کا ارادہ رکھتے تھے اور واقعی ہوا — Aks یہ فرض نہیں کرتا کہ آپ نے «نہیں کیا»۔",
            receives: "اُن یاد دہانیوں کی آخری تاریخیں اور تکمیل کی حالت جو آپ نے مطابقت کے لیے چنیں۔",
            stored: "آخری تاریخیں اور تکمیل/غیر ریکارڈ شدہ کی حالت۔",
            stop: "کام اور یاد دہانیاں آپ کسی بھی وقت الگ کر سکتے ہیں۔",
        },
        screenTime: {
            name: "اسکرین ٹائم",
            purpose:
                "ڈیوائس کے استعمال کا مجموعی سیاق توجہ کی تبدیلیوں کی وضاحت کر سکتا ہے — اسے انتشار کے ثبوت کے طور پر نہیں لیا جاتا۔",
            receives: "وقتی حدود کے حساب سے تقریبی اقسام میں مجموعی استعمال کا دورانیہ۔",
            stored: "مجموعی وقتی حدود جیسے «سوشل ایپس، 60 منٹ، 21:00–22:00»۔ ہر ایک تعامل کی سطح کا ڈیٹا نہیں۔",
            stop: "اسکرین ٹائم آپ کسی بھی وقت الگ کر سکتے ہیں۔",
        },
        googleCalendar: {
            name: "Google کیلنڈر",
            purpose:
                "Google کیلنڈر اُن اکاؤنٹس کے لیے وہی منصوبہ بندی کا سیاق دیتا ہے جو آپ واضح طور پر منسلک کرتے ہیں۔",
            receives:
                "منتخب کیلنڈروں کی مصروفیات کے اوقات اور تقریبی اقسام۔ ہم شرکاء کی فہرست، نوٹس یا میٹنگ لنک نہیں پڑھتے۔",
            stored: "کم سے کم مصروفیت کے ریکارڈ: وقت، دورانیہ، قسم، اور تصدیق شدہ/منسوخ۔",
            stop: "Google کیلنڈر آپ کسی بھی وقت الگ کر سکتے ہیں — Google اکاؤنٹ کی سیٹنگز سے رسائی بھی منسوخ کریں۔",
        },
        appleCalendar: {
            name: "Apple کیلنڈر",
            purpose:
                "iPhone اور iPad پر ہمیں Apple کے کیلنڈر اسٹور کے ذریعے وہی ڈیوائس کیلنڈر سیاق ملتا ہے۔",
            receives: "مصروفیات کے اوقات اور تقریبی اقسام۔ ہم شرکاء کی فہرست، نوٹس یا میٹنگ لنک نہیں پڑھتے۔",
            stored: "کم سے کم مصروفیت کے ریکارڈ: وقت، دورانیہ، قسم، اور تصدیق شدہ/منسوخ۔",
            stop: "Apple کیلنڈر آپ کسی بھی وقت الگ کر سکتے ہیں۔",
        },
        googleTasks: {
            name: "Google کام",
            purpose:
                "منسلک Google اکاؤنٹ کے طے شدہ کام Aks کو آپ کے ارادے دکھاتے ہیں — ناکامی کے طور پر نہیں۔",
            receives: "کاموں کی آخری تاریخیں اور تکمیل کی حالت۔",
            stored: "آخری تاریخیں اور تکمیل/غیر ریکارڈ شدہ کی حالت۔",
            stop: "Google کام آپ کسی بھی وقت الگ کر سکتے ہیں — Google اکاؤنٹ کی سیٹنگز سے رسائی بھی منسوخ کریں۔",
        },
        appleReminders: {
            name: "Apple یاد دہانیاں",
            purpose:
                "iPhone اور iPad پر Apple یاد دہانیوں کے طے شدہ کام وہی «منصوبہ اور حقیقت» کا سیاق بن جاتے ہیں۔",
            receives: "یاد دہانیوں کی آخری تاریخیں اور تکمیل کی حالت۔",
            stored: "آخری تاریخیں اور تکمیل/غیر ریکارڈ شدہ کی حالت۔",
            stop: "Apple یاد دہانیاں آپ کسی بھی وقت الگ کر سکتے ہیں۔",
        },
        notion: {
            name: "Notion",
            purpose:
                "وہ صفحات اور ڈیٹا بیس جنہیں آپ واضح طور پر Aks انٹیگریشن کے ساتھ شیئر کرتے ہیں، کام کا سیاق گفتگو میں شامل کر دیتے ہیں۔",
            receives:
                "اُن چیزوں کے عنوانات، اوقات اور تقریبی اقسام جو آپ Aks کے Notion انٹیگریشن کے ساتھ شیئر کرتے ہیں۔ ہم صفحے کا مواد نہیں پڑھتے۔",
            stored: "کم سے کم اشیاء کے ریکارڈ: عنوان کی قسم، وقت، اور حالت۔",
            stop: "Notion آپ کسی بھی وقت الگ کر سکتے ہیں — Notion ورک اسپیس سے Aks انٹیگریشن بھی ہٹائیں۔",
        },
        todoist: {
            name: "Todoist",
            purpose:
                "Todoist جیسی منسلک ٹاسک سروس Aks کو اجازت دیتی ہے کہ وہ Aks سے باہر کا منصوبہ بھی سامنے رکھے۔",
            receives: "کاموں کی آخری تاریخیں اور تکمیل کی حالت۔",
            stored: "آخری تاریخیں اور تکمیل/غیر ریکارڈ شدہ کی حالت۔",
            stop: "Todoist آپ کسی بھی وقت الگ کر سکتے ہیں — پرووائیڈر کے اکاؤنٹ کی سیٹنگز سے رسائی بھی منسوخ کریں۔",
        },
        github: {
            name: "GitHub",
            purpose: "آپ کے اپنے کمٹ اور PR کی سرگرمی بطور معروضی کام کا سیاق — دوسروں کا ڈیٹا نہیں۔",
            receives: "منتخب ریپوزٹریوں میں آپ کے کمٹ اور پل ریکویسٹ کی تعداد اور اوقات۔",
            stored: "مجموعی سرگرمی کی وقتی حدود جیسے «2 کمٹ، 22:00–23:00»۔ کوڈ کا مواد شامل نہیں۔",
            stop: "GitHub آپ کسی بھی وقت الگ کر سکتے ہیں — GitHub سیٹنگز سے Aks کی OAuth ایپ بھی منسوخ کریں۔",
        },
        slack: {
            name: "Slack",
            purpose: "اُس ورک اسپیس سے توجہ کے اوقات اور حالت کے اشارے جو آپ واضح طور پر منسلک کرتے ہیں۔",
            receives: "آپ کی اپنی سرگرمی کے اوقات اور ڈو ناٹ ڈسٹرب (DND) کی حالت۔ ہم پیغامات کا مواد نہیں پڑھتے۔",
            stored: "مجموعی سرگرمی کی وقتی حدود۔ پیغامات، چینلز یا ساتھیوں کا ڈیٹا شامل نہیں۔",
            stop: "Slack آپ کسی بھی وقت الگ کر سکتے ہیں — ورک اسپیس سے Aks ایپ بھی ہٹائیں۔",
        },
        email: {
            name: "ای میل",
            purpose: "منسلک پرووائیڈر (جیسے Gmail) سے ای میل کے بوجھ کا ہلکا سیاق (صرف تعداد)۔",
            receives: "موصول ہونے والے ای میلز کی تعداد اور اوقات۔ ہم عنوانات، متن یا بھیجنے والے نہیں پڑھتے۔",
            stored: "ہر وقتی حد کے لیے مجموعی تعداد۔ نہ مواد اور نہ ایڈریس محفوظ ہوتے ہیں۔",
            stop: "ای میل آپ کسی بھی وقت الگ کر سکتے ہیں — پرووائیڈر کی سیکیورٹی سیٹنگز سے رسائی بھی منسوخ کریں۔",
        },
        voiceSession: {
            name: "مائیک",
            purpose:
                "صوتی گفتگو ایک ایسا عمل ہے جو آپ واضح طور پر شروع کرتے ہیں۔ مائیک صرف صوتی سیشن کے دوران استعمال ہوتا ہے۔",
            receives: "آواز صرف اُس وقت جب صوتی گفتگو چل رہی ہو۔",
            stored: "وہ متن جو آپ رکھتے ہیں۔ آواز محفوظ نہیں کی جاتی۔",
            stop: "صوتی سیشن ختم کرنے سے مائیک بند ہو جاتا ہے۔ Aks پس منظر میں کبھی نہیں سنتا۔",
        },
    },
    transparency: {
        connectedWith: (sources: string) =>
            `چونکہ آپ نے ${sources} منسلک کیا ہے، Aks یہاں شیئر کی گئی باتوں کے ساتھ وہ سیاق بھی دیکھ سکتا ہے۔`,
        names: {
            location: "مقام",
            calendar: "کیلنڈر",
            googleCalendar: "Google کیلنڈر",
            appleCalendar: "Apple کیلنڈر",
            reminders: "کام",
            googleTasks: "Google کام",
            appleReminders: "Apple یاد دہانیاں",
            todoist: "Todoist",
            notion: "Notion",
            github: "GitHub",
            slack: "Slack",
            email: "ای میل",
            screenTime: "اسکرین ٹائم",
            voiceSession: "آواز",
        },
    },
    oauth: {
        googleCalendar: "Google کیلنڈر",
        googleTasks: "Google کام",
        notion: "Notion",
        todoist: "Todoist",
        github: "GitHub",
        slack: "Slack",
        email: "ای میل",
    },
    errors: {
        pagedData: "یہ ڈیٹا لوڈ نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
        pagedDataMore: "مزید ڈیٹا لوڈ نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
        dataSummary: "ڈیٹا کا خلاصہ لوڈ نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
        dataAccess: "منسلک ذرائع لوڈ نہیں ہو سکے۔ دوبارہ کوشش کریں۔",
        memory: "یہ یاد لوڈ نہیں ہو سکی۔",
        pattern: "یہ پیٹرن لوڈ نہیں ہو سکا۔",
        experiment: "یہ تجربہ لوڈ نہیں ہو سکا۔",
        learning: "یہ سبق لوڈ نہیں ہو سکا۔",
        insight: "یہ بصیرت لوڈ نہیں ہو سکی۔",
        conversation: "یہ گفتگو لوڈ نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
        conversationEarlier: "پرانے پیغامات لوڈ نہیں ہو سکے۔ دوبارہ کوشش کریں۔",
        conversationPlain: "یہ گفتگو لوڈ نہیں ہو سکی۔",
        conversationEarlierPlain: "پرانے پیغامات لوڈ نہیں ہو سکے۔",
        messageEmptySave: "محفوظ کرنے سے پہلے کچھ لکھیں۔",
        exportLinkExpired: "برآمد کا لنک ختم ہو گیا۔ دوبارہ درخواست کریں۔",
        renameConversation: "اس گفتگو کا نام تبدیل نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
        exportExpired: "برآمد کا لنک ختم ہو گیا۔ دوبارہ درخواست کریں۔",
        exportCreate: "برآمد نہیں بن سکی۔ دوبارہ کوشش کریں۔",
        exportDownload: "برآمد ڈاؤن لوڈ نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
        deleteAccount: "اکاؤنٹ حذف کرنا ابھی دستیاب نہیں۔ تھوڑی دیر بعد دوبارہ کوشش کریں۔",
        preferences: "آپ کی ترجیحات لوڈ نہیں ہو سکیں۔",
        appSetup: "آپ کے اکاؤنٹ کی ترتیب مکمل نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
        exportSaveTitle: "Aks برآمد محفوظ کریں",
        exportClearDevice: "ہم اکاؤنٹ کا ڈیٹا حذف کر رہے ہیں، لیکن اس ڈیوائس کی صفائی کے لیے ایک اور کوشش درکار ہے۔",
        shareUnavailable: "اس ڈیوائس پر شیئرنگ دستیاب نہیں۔ دوبارہ کوشش کریں۔",
        exportIncomplete: "برآمد کا جواب نامکمل تھا۔ دوبارہ کوشش کریں۔",
        exportInterrupted: "ڈاؤن لوڈ رُک گیا۔ دوبارہ کوشش کریں۔",
        exportGeneric: "کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔",
        connectedSources: "منسلک ذرائع لوڈ نہیں ہو سکے۔",
        sourceUnavailable: "یہ ذریعہ آپ کی ڈیوائس پر دستیاب نہیں۔",
        sourcePermission: "یہ ذریعہ منسلک کرنے کے لیے اجازت درکار ہے۔ بعد میں دوبارہ کوشش کریں۔",
        sourceConnect: "اس ذریعے سے رابطہ نہیں ہو سکا۔",
        sourceDisconnect: "اس ذریعے کو الگ نہیں کیا جا سکا۔",
        sourceDelete: "اس ذریعے کا ڈیٹا حذف نہیں ہو سکا۔",
        oauthRecord: "یہ منسلکہ محفوظ نہیں ہو سکا۔",
        oauthDisconnect: "اس اکاؤنٹ کو الگ نہیں کیا جا سکا۔",
        webPage: "یہ صفحہ لوڈ نہیں ہو سکا۔",
        webPageBody: "اپنا انٹرنیٹ کنکشن دیکھیں اور دوبارہ کوشش کریں۔",
        generic: "کچھ غلط ہو گیا۔ دوبارہ کوشش کریں۔",
        signInUnavailable: "لاگ ان ابھی دستیاب نہیں۔ تھوڑی دیر بعد دوبارہ کوشش کریں۔",
        signInStart: "لاگ ان شروع نہیں ہو سکا۔",
        authRequest: "یہ درخواست مکمل نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
        storeUnreachable: "اسٹور تک رسائی نہیں ہو سکی۔ کنکشن دیکھیں اور دوبارہ کوشش کریں۔",
        plansUnavailable: "ابھی کوئی پلان دستیاب نہیں۔ تھوڑی دیر بعد دوبارہ کوشش کریں۔",
        planUnavailable: "یہ پلان ابھی دستیاب نہیں۔ تھوڑی دیر بعد دوبارہ کوشش کریں۔",
        storeFailed: "اسٹور نے آپ کی درخواست مکمل نہیں کی۔ دوبارہ کوشش کریں۔",
        subscriptionGeneric: "آپ کی سبسکرپشن پر کارروائی میں مسئلہ پیش آیا۔ دوبارہ کوشش کریں۔",
        purchaseCancelled: "خریداری منسوخ ہو گئی۔ کوئی رقم نہیں لی گئی۔",
        purchasePending: "خریداری اسٹور کی تصدیق کے منتظر ہے۔ مکمل ہونے پر یہاں دکھے گی۔",
        alreadySubscribed: "یہ پلان آپ کے پاس پہلے سے فعال ہے۔",
        restoreEmpty: "بحال کرنے کے لیے کوئی سابقہ خریداری نہیں ملی۔",
        checkoutPendingPremium:
            "ادائیگی مکمل ہو گئی ہے، مگر آپ کے اکاؤنٹ میں Premium ابھی فعال نہیں ہوا۔ ایمولیٹر کے Test Store سے خریداری Premium فعال نہیں کرتی — Play اسٹور والی ڈیوائس استعمال کریں۔ ورنہ تھوڑی دیر بعد «خریداریاں بحال کریں» آزمائیں۔",
        emptyMessage: "بھیجنے سے پہلے کچھ لکھیں۔",
        mirror: {
            noReply: "Aks نے ابھی آپ کے آخری پیغام کا جواب نہیں دیا۔",
            unsavedRetry: "آپ کے آخری پیغام کا محفوظ ہونا مکمل نہ ہو سکا ہو۔ دوبارہ کوشش محفوظ ہے۔",
            resolvePending: "اگلا پیغام بھیجنے سے پہلے اپنے پچھلے پیغام کو دوبارہ آزمائیں یا نمٹائیں۔",
            refreshFailed: "Aks یہ جواب تازہ نہیں کر سکا۔ اس سے پہلے کا سب کچھ سلامت ہے۔",
            refreshFailedConversation:
                "Aks نے کئی بار کوشش کی مگر یہ جواب مکمل نہیں کر سکا۔ آپ کا پیغام محفوظ ہے۔",
            refreshFailedUnsafe: "Aks اس جواب کی محفوظ تشریح نہیں کر سکا۔ آپ کا پیغام محفوظ ہے۔",
            refreshFallback: "Aks ابھی اس پر کارروائی نہیں کر سکا۔ آپ کا پیغام محفوظ ہے۔",
            updateMessage: "یہ پیغام اپ ڈیٹ نہیں ہو سکا۔ ہو سکتا ہے Aks کا جواب پہلے سے موجود ہو۔",
            checkInFailed: "آپ کا چیک اِن محفوظ نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
            saveFailed: "آپ کا پیغام محفوظ نہیں ہو سکا۔ کنکشن دیکھیں اور دوبارہ کوشش کریں۔",
            outboxQueued: "اس ڈیوائس پر محفوظ کر لیا گیا۔ آن لائن آنے پر Aks اسے بھیج دے گا۔",
            signInForVoice: "صوتی گفتگو لاگ ان کے بعد دستیاب ہوتی ہے۔",
            voiceStartFailed: "صوتی گفتگو شروع نہیں ہو سکی۔",
        },
        voice: {
            realtimeNotConfigured: "اس بلڈ میں صوتی گفتگو ابھی ترتیب نہیں دی گئی۔",
            sessionUnavailable: "صوتی سیشن شروع نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
            transportUnavailable: "اس منتخبے کے لیے Aks کا ڈیولپمنٹ بلڈ درکار ہے۔",
            audioUnavailable: "لائیو آواز کے لیے Aks کے آڈیو انجن والا ڈیولپمنٹ بلڈ درکار ہے۔",
            micDenied: "صوتی گفتگو کے لیے مائیک کی اجازت درکار ہے۔",
            transcriptionFailed: "Aks آپ کی بات نہیں سن سکا۔ دوبارہ کوشش کریں۔",
            providerError: "Aks ابھی صوتی گفتگو شروع نہیں کر سکتا۔",
            sessionExpired: "صوتی سیشن ختم ہو گیا۔ جاری رکھنے کے لیے دوبارہ جڑیں۔",
            voiceFailed: "صوتی گفتگو ناکام ہو گئی۔",
            saveVoiceMessage: "آپ کا صوتی پیغام محفوظ نہیں ہو سکا۔ یہ صرف اسی سیشن میں رہے گا۔",
            saveVoiceReply: "Aks کا جواب محفوظ نہیں ہو سکا۔ یہ صرف اسی سیشن میں رہے گا۔",
            audioCaptureFailed: "آواز ریکارڈ کرنا ناکام ہو گیا۔",
            audioFailed: "آواز میں مسئلہ پیش آیا۔",
        },
        writes: {
            signInRequired: "جاری رکھنے کے لیے لاگ ان کریں۔",
            experimentInvalid: "تجربے کا جواب درست نہیں تھا۔",
            observation: "یہ مشاہدہ محفوظ نہیں ہو سکا۔",
            reflection: "یہ غور محفوظ نہیں ہو سکا۔",
            message: "یہ پیغام محفوظ نہیں ہو سکا۔",
            checkIn: "یہ چیک اِن محفوظ نہیں ہو سکا۔",
            insightUpdate: "یہ بصیرت اپ ڈیٹ نہیں ہو سکی۔",
            experimentUpdate: "یہ تجربہ اپ ڈیٹ نہیں ہو سکا۔",
            startConversation: "یہ گفتگو شروع نہیں ہو سکی۔",
            sendMessage: "آپ کا پیغام محفوظ نہیں ہو سکا۔",
            confirmMessage: "آپ کا پیغام کنفرم نہیں ہو سکا۔",
            searchConversations: "آپ کی گفتگوئیں تلاش نہیں ہو سکیں۔",
            updateConversation: "یہ گفتگو اپ ڈیٹ نہیں ہو سکی۔",
            updateMessage: "یہ پیغام اپ ڈیٹ نہیں ہو سکا۔",
            confirmUpdatedMessage: "آپ کا اپ ڈیٹ شدہ پیغام کنفرم نہیں ہو سکا۔",
            archiveConversation: "یہ گفتگو آرکائیو نہیں ہو سکی۔",
            archivePattern: "یہ پیٹرن آرکائیو نہیں ہو سکا۔",
            removePattern: "یہ پیٹرن حذف نہیں ہو سکا۔",
            archiveMemory: "یہ یاد آرکائیو نہیں ہو سکی۔",
            removeMemory: "یہ یاد حذف نہیں ہو سکی۔",
            archiveLearning: "یہ سبق آرکائیو نہیں ہو سکا۔",
            removeLearning: "یہ سبق حذف نہیں ہو سکا۔",
        },
    },
    timelineEntries: {
        patternForming: "پیٹرن بن رہا ہے",
        insight: "بصیرت",
        newLearning: "نیا سبق",
        outcomeRecorded: "نتیجہ ریکارڈ ہوا",
        experimentStarted: "تجربہ شروع ہوا",
        experimentActive: "تجربہ جاری",
        reflection: "غور",
        checkIn: "چیک اِن",
        experimentOutcomeTitle: "تجربے کا نتیجہ ریکارڈ ہوا",
        reflectionTitle: "غور ریکارڈ ہوا",
    },
};

export default ur;
