import type { Translation } from "@/constants/copy";
import type { DayPart } from "@/lib/dayPart";

/**
 * Simplified Chinese (简体中文) translation.
 *
 * Every key of the English source of truth is required; the compiler rejects
 * missing or extra keys. Uses 你 (not 您) throughout, the standard warm register
 * for personal consumer apps. Proper nouns keep their official names or stay in
 * Latin script (Aks, Mirror, Google 日历, Apple 提醒事项, Notion, GitHub, Slack,
 * Todoist, Premium). Chinese has no plural inflection, so count strings drop
 * the singular/plural branching the English source needs.
 *
 * Typography: full-width punctuation (，。、？！：) and “ ” quotes; a space
 * separates Chinese text from Latin words and numerals (`版本 1.0.0`,
 * `3 条观察记录`) for readability. Time is written 24-hour (`22:00`).
 * Mirror's deliberately hedged language survives translation — possible
 * patterns are 可能的模式 and observations remain 反思的提示，不是医学结论.
 */
const zh: Translation = {
    common: {
        back: "返回",
        cancel: "取消",
        save: "保存",
        dismiss: "关闭",
        clear: "清除",
        loading: "加载中…",
        tryAgain: "重试",
        loadMore: "加载更多",
        pleaseTryAgain: "请重试。",
        checkConnection: "请检查网络连接后重试。",
        emailPlaceholder: "you@example.com",
        justNow: "刚刚",
        dateUnavailable: "日期不可用",
        version: (value: string) => `版本 ${value}`,
    },
    brand: {
        name: "Aks.ai",
        tagline: "换一种方式了解自己。",
    },
    splash: {
        appName: "Aks.ai",
        subtitle: "换一种方式了解自己。",
    },
    onboarding: {
        skip: "跳过",
        moveForward: "继续",
        getStarted: "开始使用",
        notices: {
            unableToContinue: "无法继续",
        },
        slides: [
            {
                eyebrow: "你的生活留下线索",
                title: "你早已留下\n关于自己的线索。",
                description:
                    "你反复做的事。你回避的时刻。感觉不同的日子。Aks 会把这些信号汇集起来。",
            },
            {
                eyebrow: "不要只是反思",
                title: "别猜。\n去测试。",
                description:
                    "把一个直觉变成小实验。改变一件事，测量会发生什么，找出真正对你有用的做法。",
            },
            {
                eyebrow: "更清晰的你",
                title: "让「自己」\n不再是个谜。",
                description:
                    "随着时间推移，Aks 会持续构建一幅图景：你的模式、你的反应，以及真正带来改变的因素。",
            },
        ],
    },
    legal: {
        termsTitle: "服务条款",
        privacyTitle: "隐私政策",
        acceptance: {
            title: "开始之前。",
            description:
                "Aks 会处理个人信息，帮助你了解自己的模式。继续之前，有些事情你需要知道。",
            cardTitle: "你的数据，由你掌控。",
            cardBody:
                "Aks 使用你选择分享的信息来发现模式，并帮助你进行个人实验。",
            bullets: [
                "由你决定提供哪些信息。",
                "你可以管理自己的数据和权限。",
                "Aks 不能替代专业的医疗或心理健康建议。",
            ],
            agreePrefix: "我同意 Aks.ai 的",
            terms: "服务条款",
            andWord: "和",
            privacy: "隐私政策",
            continue: "继续使用 Aks",
            retryAction: "重试",
            retry: "重试",
            footnote: "你之后可以在「设置」中再次查看这些文件。",
            consentA11y: "同意服务条款和隐私政策",
            notices: {
                unableToSave: "无法保存同意记录",
            },
        },
        links: {
            prefix: "继续即表示你同意 Aks.ai 的",
            terms: "服务条款",
            andWord: "和",
            privacy: "隐私政策",
        },
    },
    login: {
        title: "欢迎回来。",
        description: "登录后，继续发现 Aks 在你身上注意到的事情。",
        emailLabel: "邮箱地址",
        sendLink: "登录",
        sendLinkA11y: "发送登录链接",
        secureLinkNote: "我们会通过邮件发送安全登录链接，无需密码。",
        divider: "或使用以下方式继续",
        google: "Google",
        googleA11y: "使用 Google 继续",
        facebook: "Facebook",
        facebookA11y: "使用 Facebook 继续",
        github: "使用 GitHub 继续",
        githubA11y: "使用 GitHub 继续",
        noAccount: "还没有账号？",
        createOne: "创建一个",
        dismissError: "点击关闭。",
        notices: {
            unableToSendLink: "无法发送登录链接",
            unableToSignIn: "无法登录",
        },
    },
    register: {
        title: "创建你的账号。",
        description: "用 Aks 开始更清晰地了解自己。",
        nameLabel: "姓名",
        namePlaceholder: "你的姓名",
        nameA11y: "姓名",
        emailLabel: "邮箱地址",
        createAccount: "创建账号",
        createAccountA11y: "使用邮箱创建账号",
        secureLinkNote: "我们会通过邮件发送安全登录链接，无需密码。",
        divider: "或使用以下方式注册",
        google: "Google",
        googleA11y: "使用 Google 继续",
        facebook: "Facebook",
        facebookA11y: "使用 Facebook 继续",
        github: "使用 GitHub 继续",
        githubA11y: "使用 GitHub 继续",
        hasAccount: "已经有账号？",
        signIn: "登录",
        dismissError: "点击关闭。",
        notices: {
            unableToCreate: "无法创建账号",
            unableToSignIn: "无法登录",
        },
    },
    emailConfirmation: {
        title: "查看你的邮箱。",
        body: (email: string) =>
            `我们已把安全登录链接发送至 ${email}。请在此设备上打开链接以继续。`,
        resendNote: "如果重新发送，只有最新的链接有效。",
        resend: "重新发送链接",
        resendA11y: "重新发送登录链接",
        editEmail: "修改邮箱",
        editEmailA11y: "修改邮箱地址",
    },
    mirror: {
        eyebrow: "MIRROR",
        greeting: (firstName: string | null, part: DayPart = "morning") => {
            const base =
                part === "afternoon"
                    ? "下午好"
                    : part === "evening"
                        ? "晚上好"
                        : part === "night"
                            ? "晚安"
                            : "早上好";
            return `${base}${firstName ? `，${firstName}` : ""}。`;
        },
        intro: "我是 Aks。我们先从一件小事开始。",
        understandTitle: "你想了解什么？",
        differentHint: "也可以告诉 Aks 完全不同的内容。",
        checkInEyebrow: "快速记录",
        checkInTitle: "今天感觉怎么样？",
        topics: ["专注", "精力", "睡眠", "情绪", "作息", "关系", "效率"],
        topicDraft: (topic: string) => `我想了解自己的${topic}。`,
        checks: ["不错", "还行", "混乱"],
        aksLabel: "AKS",
        errorTitle: "出了点问题。",
        retryResponse: "重试回复",
        listening: "正在聆听…",
        listeningMeta: (duration: string) => `${duration} · 仅保存在本设备`,
        stopRecordingA11y: "停止录音",
        voiceReady: "语音反思已就绪",
        voiceReadyHint: "Aks 会把它转写成一条反思。",
        discardRecordingA11y: "放弃录音",
        sendRecordingA11y: "发送录音",
        composerPlaceholder: "告诉 Aks 你在想什么…",
        sendMessageA11y: "发送消息",
        recordVoiceA11y: "录制语音反思",
        notices: {
            micUnavailable: "麦克风不可用",
            micUnavailableBody:
                "录制语音反思需要麦克风权限。你也可以直接输入文字。",
            cantListen: "无法开始聆听",
            cantListenBody: "请重试，或用文字说出你此刻在想什么。",
            stopRecording: "无法停止录音",
            recordingFailed: "无法保存该录音",
            transcriptionNotConfigured:
                "此版本暂不支持语音反思。你仍然可以输入文字进行反思。",
            audioTooLong: "录音太长了，请试一段短一些的。",
            subscriptionRequired:
                "语音反思需要 Aks Premium，因此这条录音没有被使用。你仍然可以改用文字输入。",
            emptyTranscription:
                "Aks 没能从这条录音中听到任何内容。请确认麦克风工作正常后重试。",
            unsupportedAudio: "不支持该录音格式，请重新录制。",
            transcriptionUnavailable:
                "Aks 目前无法收听这条录音。你可以重试，或改用文字输入。",
            unauthorized: "请先登录后重试。",
            recordingFailedFallback:
                "Aks 刚才无法保存这条录音。你可以重试，或改用文字输入。",
        },
    },
    mirrorBar: {
        newConversation: "新对话",
        composerPlaceholder: "告诉 Aks 你在想什么…",
        sendMessageA11y: "发送消息",
        closeComposerA11y: "关闭输入框",
        openKeyboardA11y: "打开键盘",
        stopVoiceA11y: "结束语音对话",
        startVoiceA11y: "开始语音对话",
        voiceOffA11y: "关闭语音回复",
        voiceOnA11y: "打开语音回复",
        moreOptionsA11y: "更多对话选项",
        hint: "你不需要先整理好思路，直接开口就好。",
    },
    aiConversation: {
        greeting: (firstName: string | null) => (firstName ? `嗨，${firstName} 👋` : "嗨 👋"),
        openingPrompts: [
            "最近有什么事一直萦绕在你心里？",
            "你今天感觉怎么样？",
            "最近有什么一直压在你心上吗？",
            "有什么事情占满了你的脑子？",
            "想聊聊让你烦心的事吗？",
            "有什么想一吐为快的吗？",
            "最近什么让你觉得负担很重？",
            "有什么话是你希望能说出口的？",
        ],
        copyAction: "复制",
        copiedAction: "已复制",
        copyA11y: "复制消息",
        shareAction: "分享",
        shareA11y: "分享消息",
        tryAgainAction: "重试",
        tryAgainA11y: "重新生成这条回复",
        motionReadyA11y: "Aks 已就绪",
        thinking: "思考中…",
        thinkingDefault: "Aks 正在思考…",
        aksTag: "aks",
        youTag: "你",
        listening: "正在聆听…",
        speaking: "正在说话…",
        loadingConversation: "正在加载对话…",
        youPrefix: "你：",
        errorTitle: "出了点问题。",
        retryResponse: "重试回复",
        voicePaused: "语音已暂停。",
        editPlaceholder: "重新修改你的消息…",
        saveAndSend: "保存并发送",
        saveAndSendA11y: "保存并发送修改后的消息",
        cancelEditingA11y: "取消编辑",
        cancel: "取消",
        editMessage: "编辑消息",
        editMessageA11y: "编辑你的消息",
    },
    timeline: {
        header: "时间线",
        headerCaption: "你与 Aks 一路走来的旅程。",
        eyebrow: "你的旅程",
        title: "你的故事，正在展开。",
        description:
            "查看塑造了你与 Aks 这段旅程的时刻、模式、实验和心得。",
        errorTitle: "无法加载你的时间线。",
        errorBody: "你的故事还在。请稍后重试。",
        loadMoreError: "无法加载更多内容。",
        empty: {
            allTitle: "你的故事仍在展开。",
            allBody:
                "随着你与 Aks 交流，有意义的时刻、模式、实验和心得会出现在这里。",
            insightsTitle: "还没有洞察。",
            insightsBody: "当 Aks 随时间看到足够依据时，有意义的洞察会出现在这里。",
            experimentsTitle: "还没有实验。",
            experimentsBody: "你设置的实验会在进行时出现在这里。",
            checkInsTitle: "还没有状态记录。",
            checkInsBody: "你有意义的记录会出现在这里。",
            decisionsTitle: "还没有决定。",
            decisionsBody: "当 Aks 注意到的决定和模式逐渐成形时，会出现在这里。",
            learningsTitle: "还没有心得。",
            learningsBody: "当你的故事变得更清晰时，新的心得会出现在这里。",
        },
    },
    you: {
        title: "你",
        fallbackName: "Aks 用户",
        subtitle: "你的个人空间",
        knowsTitle: "Aks 了解到的",
        knowsEmpty: "还在了解你",
        memoriesCount: (count: number) => `${count} 条记忆`,
        exploringTitle: "你在探索的",
        exploringEmpty: "选择你的关注点",
        unnoticedTitle: "你还没注意到的事",
        insightsCount: (count: number) => `${count} 条值得一看的洞察`,
        insightsEmpty: "还没有定论",
        journeySection: "你的旅程",
        patternsTitle: "模式",
        patternsDescription: "Aks 注意到的事",
        experimentsTitle: "实验",
        experimentsDescription: "你正在测试的内容",
        yourDataTitle: "你的数据",
        yourDataDescription: "查看和管理你的信息",
        preferencesSection: "偏好设置",
        notificationsTitle: "通知",
        notificationsDescription: "Aks 何时联系你",
        appearanceTitle: "外观",
        appearanceDescription: "跟随系统 · 浅色 · 深色",
        privacyTitle: "隐私",
        privacyDescription: "权限与隐私控制",
        supportSection: "支持",
        helpTitle: "帮助与反馈",
    },
    settings: {
        header: "设置",
        eyebrow: "设置",
        title: "你的 Aks，按你的方式来。",
        description: "管理你的账号、方案，以及关于 Aks 的信息。",
        accountSection: "账号",
        profileTitle: "个人资料",
        profileDescription: "管理你的个人信息",
        accountTitle: "账号",
        accountDescription: "退出登录或删除账号",
        subscriptionTitle: "订阅",
        subscriptionDescription: "管理你的 Aks 方案与账单",
        preferencesSection: "偏好设置",
        languageTitle: "语言",
        aboutSection: "关于",
        aboutTitle: "关于 Aks",
        aboutDescription: "进一步了解 Aks",
        termsTitle: "服务条款",
        privacyTitle: "隐私政策",
    },
    profile: {
        header: "个人资料",
        fallbackName: "Aks 用户",
        fallbackEmail: "邮箱不可用",
        editName: "修改姓名",
        editNameA11y: "修改姓名",
        changePhotoA11y: "更改头像",
        photoA11y: "头像",
        photoSheetTitle: "头像",
        chooseImage: "选择图片",
        removePhoto: "移除照片",
        aksSection: "AKS",
        exploringTitle: "你在探索的",
        exploringEmpty: "未设置",
        noticeTitle: "Aks 应关注的内容",
        noticeEmpty: "未设置",
        preferencesSection: "偏好设置",
        timezoneTitle: "时区",
        languageTitle: "语言",
        accountSection: "账号",
        emailTitle: "邮箱",
        emailUnavailable: "不可用",
        memberSince: "加入时间",
        memberSinceUnavailable: "不可用",
        signInMethod: "登录方式",
        signInMethodFallback: "邮箱",
        editNameTitle: "修改你的姓名",
        editNameMessage: "Aks 会用这个名字称呼你。",
        nameA11y: "姓名",
        namePlaceholder: "你的姓名",
        saving: "保存中…",
        saveChanges: "保存更改",
        fullName: "姓名",
        notices: {
            unableToSaveName: "无法保存个人资料",
            unableToUpdatePhoto: "无法更新照片",
            unableToRemovePhoto: "无法移除照片",
            checkConnection: "请检查网络连接后重试。",
            tryAgain: "请重试。",
        },
    },
    exploring: {
        header: "你在探索的",
        eyebrow: "个人",
        title: "选择你的关注点。",
        description: "选择你希望了解得更清楚的方向。",
        options: ["专注", "精力", "睡眠", "情绪", "习惯", "压力"],
    },
    noticeAreas: {
        header: "Aks 应关注的内容",
        eyebrow: "个人",
        title: "引导 Aks 的关注方向。",
        description: "选择 Aks 在整理可能模式时应优先关注的方面。",
        options: ["日常作息", "精力变化", "专注模式", "睡眠质量", "情绪波动", "实验结果"],
    },
    timezone: {
        header: "时区",
        eyebrow: "偏好设置",
        title: "你的本地时间。",
        description: "选择 Aks 用于安排时间的时区。",
    },
    language: {
        header: "语言",
        eyebrow: "偏好设置",
        title: "选择你的语言。",
        description: "选择 Aks 全界面使用的语言。",
        notAvailableYet: (name: string) => `${name} 暂不可用。在它的翻译上线前将使用英文。`,
        comingSoon: "即将推出",
    },
    appearance: {
        header: "外观",
        eyebrow: "你的体验",
        title: "让它更像你自己的。",
        description: "选择 Aks 在应用中的显示方式。",
        themeSection: "主题",
        themes: {
            systemTitle: "跟随系统",
            systemDescription: "跟随你设备的外观设置。",
            lightTitle: "浅色",
            lightDescription: "让 Aks 保持明亮清晰。",
            darkTitle: "深色",
            darkDescription: "在弱光环境下更柔和。",
        },
        noteCaption: "来自 AKS 的提示",
        noteBody: "外观只会改变 Aks 的显示方式。",
        notices: {
            unableToSave: "无法保存外观设置",
        },
    },
    account: {
        header: "账号",
        signedInAs: "当前登录",
        emailUnavailable: "邮箱不可用",
        signOut: "退出登录",
        deleteAccount: "删除账号",
        confirmSignOutTitle: "要退出登录吗？",
        confirmSignOutMessage: "你需要重新登录才能继续使用 Aks。",
        confirmDeleteTitle: "要删除账号吗？",
        confirmDeleteMessage:
            "这会永久删除你的账号及相关数据，且无法撤销。",
        notices: {
            unableToSignOut: "无法退出登录",
            unableToDelete: "无法删除账号",
            deleteUnavailable: "当前不支持删除账号，请稍后再试。",
        },
    },
    about: {
        header: "关于 Aks",
        eyebrow: "关于",
        title: "换一种方式了解自己。",
        description:
            "Aks 帮助你回顾自己的活动、注意可能的模式，并更有意识地做个人实验。",
        productLabel: "产品",
        productValue: "Aks.ai",
        versionLabel: "版本",
        versionValue: "1.0.0",
        note: "Aks 支持个人反思，不能替代专业的医疗或心理健康建议。",
    },
    subscription: {
        header: "订阅",
        eyebrow: "你的方案",
        title: "Aks 方案与账单。",
        description:
            "查看你当前的方案和账单状态。账单功能可用后，可接入订阅管理。",
        checkingPlan: "正在检查你的方案…",
        fallbackError: "我们无法检查你的方案，请重试。",
        currentPlan: "当前方案",
        activeBadge: "生效中",
        planActive: "你的方案已生效。",
        renewsOn: (date: string) => `将于 ${date} 续订`,
        accessUntil: (date: string) => `有效期至 ${date}`,
        autoRenewOff: "自动续订已关闭。",
        billing: "账单",
        manage: "管理订阅",
        restore: "恢复购买",
        choosePlan: "选择你的方案",
        chooseTitle: "与 Aks 相处更久一些。",
        chooseDescription:
            "选择适合你的节奏。你可以随时管理或恢复订阅。",
        expiredWithDate: (date: string) => `你的 Premium 权益已于 ${date} 结束。`,
        expiredFallback: "你的 Premium 权益已结束。",
        plansEmpty: "目前没有列出方案，请稍后再查看。",
        premiumEyebrow: "AKS PREMIUM",
        bestValue: "最超值",
        premiumAccess: "完整使用 Aks Premium",
        continueWith: (title: string) => `使用 ${title} 继续`,
        unavailableTitle: "此设备尚未接入订阅功能。",
        unavailableBody:
            "一旦此设备支持账单功能，方案就会显示在这里，你可以在此页面查看或管理。",
        noteCaption: "来自 AKS 的提示",
        noteBody: "付款由你设备上的应用商店处理。",
    },
    notifications: {
        header: "通知",
        eyebrow: "及时了解",
        title: "只在重要时提醒。",
        description: "选择 Aks 可以联系你的时机。你可以随时更改这些偏好。",
        sectionMain: "通知",
        allowTitle: "允许通知",
        allowDescription: "暂停或恢复所有 Aks 通知。",
        categoriesSection: "AKS 可以发送的内容",
        categories: {
            insightsTitle: "新的洞察",
            insightsDescription: "当 Aks 注意到有意义的模式时。",
            experimentsTitle: "实验更新",
            experimentsDescription: "进行中实验的提醒和结果。",
            checkInsTitle: "记录提醒",
            checkInsDescription: "温和地提醒你回顾今天。",
            weeklyTitle: "每周回顾",
            weeklyDescription: "一周变化的小结。",
        },
        quietSection: "免打扰时段",
        quietTitle: "免打扰时段",
        quietDescription: "22:00 至次日 8:00 之间不发送通知。",
        deviceSection: "设备设置",
        deviceTitle: "管理设备通知",
        deviceDescription: "打开设备设置以管理 Aks 的权限。",
        noteCaption: "来自 AKS 的提示",
        noteBody: "Aks 只在重要的时候才联系你。",
    },
    yourData: {
        header: "你的数据",
        eyebrow: "你的数据",
        title: "Aks 记住的内容。",
        description:
            "查看 Aks 从你的活动中收集到的信息，以及你选择分享的内容。",
        glanceSection: "概览",
        remembersSection: "AKS 记住的内容",
        sourcesSection: "数据来源",
        sourcesTitle: "已连接来源",
        sourcesUnknown: "查看哪些来源已连接。",
        sourcesNone: "暂无已连接来源。在支持时可用。",
        sourcesCount: (count: number) => `已连接 ${count} 个 · 可随时管理或断开。`,
        choiceSection: "你的选择",
        choiceTitle: "由你决定保留什么。",
        choiceBody: "你可以随时查看、导出或删除你的信息。",
        exportAction: "导出数据",
        deleteAction: "删除数据",
        noteCaption: "来自 AKS 的提示",
        noteBody: "你的数据始终清晰易懂，并由你掌控。",
        loadingData: "正在加载数据概览",
        retry: "重试",
    },
    reflections: {
        header: "反思",
        eyebrow: "你的反思",
        title: "你分享过的事。",
        description: "回顾那些为 Aks 提供经历背景的反思。",
        itemTitle: "反思",
        emptyTitle: "还没有反思。",
        emptyBody: "当你开始与 Aks 分享时，你的反思会出现在这里。",
    },
    checkIns: {
        header: "状态记录",
        eyebrow: "你的状态记录",
        title: "记住的小时刻。",
        description: "回顾你用来记录当时感受的状态记录。",
        itemFallback: "状态记录",
        itemTitle: (mood: string) => `${mood}状态记录`,
        energy: (value: number) => `精力 ${value}`,
        focus: (value: number) => `专注 ${value}`,
        stress: (value: number) => `压力 ${value}`,
        noDetails: "没有更多细节",
        emptyTitle: "还没有状态记录。",
        emptyBody: "当你开始记录后，状态记录会出现在这里。",
    },
    conversations: {
        header: "对话",
        eyebrow: "你的对话",
        title: "你与 Aks 的对话。",
        description:
            "回顾你分享过的内容，同时不把它与之后的解读混在一起。搜索会覆盖标题和对话内容。",
        searchA11y: "搜索对话",
        searchPlaceholder: "搜索你的对话",
        clearSearch: "清除",
        loadingA11y: "正在加载对话",
        loadErrorTitle: "无法加载对话。",
        emptyQueryTitle: "没有匹配的对话。",
        emptyQueryBody: "换个词试试 — Aks 搜索的是你说过的内容，而不只是标题。",
        emptyTitle: "还没有对话。",
        emptyBody: "你与 Aks 开始的对话会出现在这里。",
        archiveHint: "长按以归档",
        loadMore: "加载更多",
        archiveTitle: "要归档这个对话吗？",
        archiveMessage: "它会被从活跃对话历史中隐藏。",
        archiveConfirm: "归档",
        notices: {
            unableToArchive: "无法归档",
        },
    },
    conversationDetail: {
        fallbackTitle: "对话",
        renameA11y: "重命名对话",
        loadingA11y: "正在加载对话",
        unavailableTitle: "对话不可用。",
        archivedBody: "它可能已被归档或移除。",
        renameSection: "重命名对话",
        titleA11y: "对话标题",
        titlePlaceholder: "对话标题",
        saveRename: "保存",
        cancelRename: "取消",
        cancelRenameA11y: "取消重命名",
        historySection: "对话历史",
        startedAt: (date: string) => `${date} 开始`,
        continueMirror: "在 Mirror 中继续",
        loadEarlier: "加载更早的消息",
        youLabel: "你",
        aksLabel: "Aks",
        systemLabel: "系统",
        emptyTitle: "还没有消息。",
    },
    memories: {
        header: "Aks 记住的内容",
        eyebrow: "AKS 记住的内容",
        title: "有用的背景，谨慎保存。",
        description:
            "Aks 从你反复分享、有依据支撑的信息中整理出来的内容。",
        observationsCount: (count: number) => `${count} 条观察记录`,
        lastNoticed: (date: string) => `最近注意到：${date}`,
        emptyTitle: "Aks 还在了解你的模式。",
        emptyBody:
            "当有足够依据可以记住时，反复出现且有价值的背景会出现在这里。",
    },
    memoryDetail: {
        header: "记忆",
        loadingA11y: "正在加载记忆",
        unavailableTitle: "记忆不可用。",
        archivedFallback: "它可能已被归档或移除。",
        eyebrow: "AKS 记住的内容",
        reasonTitle: "Aks 为什么记住这个",
        reasonFallback: (count: number) => `它出现在你分享过的 ${count} 条内容中。`,
        lastNoticed: (date: string) => `最近注意到：${date}`,
        evidenceSection: "依据",
        viewConversation: " · 查看对话",
        archiveAction: "归档记忆",
        removeAction: "移除记忆",
        archiveTitle: "要归档这条记忆吗？",
        archiveMessage:
            "Aks 将不再使用这条记忆。你之后分享的内容可能会再次支持它。你原本的对话、反思和状态记录都会保留。",
        archiveConfirm: "归档",
        removeTitle: "要移除这条记忆吗？",
        removeMessage:
            "这只会移除 Aks 保存的记忆，你原本分享的信息不会被删除。",
        removeConfirm: "移除",
        notices: {
            unableToArchive: "无法归档",
            unableToRemove: "无法移除",
        },
    },
    patterns: {
        header: "模式",
        eyebrow: "你的模式",
        title: "值得注意的关联。",
        description: "基于你反复分享的内容，可能存在的关联。",
        observationsCount: (count: number) => `${count} 条观察记录`,
        emptyTitle: "还没有模式。",
        emptyBody: "Aks 需要更多时间和依据，才能发现有用的关联。",
        status: {
            possible: "可能的模式",
            notSupported: "未获支持",
            supported: "已获支持",
            testing: "测试中",
            fallback: "候选",
        },
    },
    patternDetail: {
        header: "模式",
        loadingA11y: "正在加载模式",
        unavailableTitle: "模式不可用。",
        archivedFallback: "它可能已被归档或移除。",
        reasonTitle: "Aks 为什么注意到这个",
        evidenceLine: (supporting: number, contradicting: number) =>
            `这条关联来自 ${supporting} 条支持性观察记录` +
            (contradicting ? `，以及 ${contradicting} 条相反的观察记录` : "") +
            "。",
        confidencePending: "可信度仍在评估中",
        confidenceValue: (percent: number) => `依据可信度 ${percent}%`,
        firstNoticed: (date: string) => `首次注意到：${date}`,
        lastObserved: (date: string) => `最近观察到：${date}`,
        alternativeTitle: "另一种可能",
        evidenceSection: "依据",
        supporting: "支持",
        contradicting: "相反",
        viewConversation: " · 查看对话",
        notReadyA11y: "这个模式还不适合测试",
        testA11y: "测试这个模式",
        notReady: "暂不可测试",
        testAction: "测试这个模式",
        archiveAction: "归档模式",
        removeAction: "移除模式",
        statusLabels: {
            candidate: "候选",
            possible: "可能的模式",
            testing: "测试中",
            supported: "已获支持",
            notSupported: "未获支持",
            archived: "已归档",
        },
        archiveTitle: "要归档这个模式吗？",
        archiveMessage:
            "Aks 将不再显示这个模式。未来的观察可能会支持重新评估。",
        archiveConfirm: "归档",
        removeTitle: "要移除这个模式吗？",
        removeMessage:
            "这只会移除推导出的模式及其依据关联。你的信号和原始信息都会保留。",
        removeConfirm: "移除",
        notices: {
            unableToArchive: "无法归档",
            unableToRemove: "无法移除",
        },
    },
    experiments: {
        header: "实验",
        eyebrow: "你的实验",
        title: "小测试，有用的依据。",
        description: "实验帮助你测试一个可能的模式，而不必把它当成结论。",
        observationsCount: (count: number) => `${count} 条观察记录`,
        emptyTitle: "还没有实验。",
        emptyBody: "当某个模式值得测试时，你可以围绕它做一个小实验。",
        status: {
            active: "进行中",
            completed: "已完成",
            cancelled: "已取消",
            fallback: "草稿",
        },
    },
    experimentSetup: {
        header: "设置实验",
        patternSection: "正在测试的模式",
        titleLabel: "标题",
        titlePlaceholder: "简短的实验标题",
        hypothesisLabel: "假设",
        hypothesisPlaceholder: "一个小小的改变可能会…",
        hypothesisDefault: "一个小小的改变可能会影响你在该模式中观察到的情况。",
        descriptionLabel: "要尝试和观察的内容",
        descriptionPlaceholder: "描述一个小改变，以及你会记录什么。",
        descriptionDefault:
            "选择一个小的、可撤销的改变。每次记录结果感觉是更轻松、和之前一样，还是更困难。",
        durationLabel: "时长",
        durationA11y: (days: number) => `${days} 天时长`,
        durationDays: (days: number) => `${days} 天`,
        defaultTitle: (patternTitle: string) => `测试：${patternTitle}`.slice(0, 120),
        createAction: "创建草稿",
        createA11y: "创建实验草稿",
        createError: "我们无法创建这个实验。请检查填写的内容后重试。",
        patternUnavailable: "该模式不可用。",
    },
    experimentDetail: {
        header: "实验",
        unavailableTitle: "实验不可用。",
        hypothesisTitle: "假设",
        whatToTryTitle: "要尝试的内容",
        startAction: "开始实验",
        startA11y: "开始实验",
        removeAction: "移除实验",
        removeA11y: "移除实验",
        removeTitle: "要移除这个实验吗？",
        removeMessage:
            "这会删除该实验、观察记录，以及仅由此实验支持的心得。原始模式和信号会保留。",
        removeConfirm: "移除",
        recordedFallback: "已记录",
        observationsSection: "观察记录",
        emptyObservations: "还没有记录任何观察。",
        resultSection: "结果",
        analysisPending: "待分析",
        confidenceValue: (percent: number) => `依据可信度 ${percent}%`,
        promptTitle: "这次感觉怎么样？",
        resultEasier: "更轻松",
        resultSame: "和之前一样",
        resultHarder: "更困难",
        recordA11y: (result: string) => `记录${result}`,
        observationPlaceholder: "可选备注",
        observationA11y: "可选观察备注",
        observationsMeta: (count: number) => `已记录 ${count} 条观察`,
        observationsDay: (current: number, total: number | null) =>
            total ? ` · 第 ${current} 天，共 ${total} 天` : "",
        observationsThrough: (date: string) => ` · 截至 ${date}`,
        completeAction: "完成实验",
        completeA11y: "完成实验",
        cancelAction: "取消实验",
        cancelA11y: "取消实验",
        resultPendingBody: "你的观察记录已保存，结果正在整理中。",
        retryAnalysis: "重试解读",
        retryAnalysisA11y: "重试实验分析",
        retryLearning: "重试心得整理",
        retryLearningA11y: "重试心得整理",
        retryInsight: "重试洞察生成",
        retryInsightA11y: "重试洞察生成",
        resultLabels: {
            easier: "更轻松",
            same: "和之前一样",
            harder: "更困难",
        },
        outcomeLabels: {
            supports: "支持该假设",
            mixed: "结果混合",
            doesNotSupport: "未支持该假设",
            insufficientData: "数据不足",
        },
        confirmCompleteTitle: "要完成这个实验吗？",
        confirmCompleteMessage: "Aks 会总结你的观察记录说明了什么。",
        confirmCompleteLabel: "完成",
        confirmCancelTitle: "要取消这个实验吗？",
        confirmCancelMessage: "你已记录的观察会继续保留。",
        confirmCancelLabel: "取消实验",
        keepGoing: "继续",
        notices: {
            unableToUpdate: "无法更新",
            unableToRecord: "无法记录",
            recordRetry: "你上次的尝试可以安全重试。",
        },
    },
    learnings: {
        header: "心得",
        eyebrow: "你的心得",
        title: "依据说明了什么。",
        description:
            "来自你已完成的实验和记录的观察的谨慎结论。",
        statusRevised: "已修订",
        statusActive: "有效",
        observationsCount: (count: number) => `${count} 条观察记录`,
        emptyTitle: "还没有心得。",
        emptyBody:
            "当你测试过一些事情并积累到足够依据后，Aks 可以帮助理清发生了什么变化。",
    },
    learningDetail: {
        header: "心得",
        unavailableTitle: "心得不可用。",
        evidenceTitle: "这是从何而来？",
        evidenceLine: (experiments: number, observations: number) =>
            `基于 ${experiments} 个已完成的实验和 ${observations} 条已记录的观察。`,
        confidenceValue: (percent: number) => `依据可信度 ${percent}%`,
        updatedAt: (date: string) => `${date} 更新`,
        sourceSection: "来源实验",
        openExperimentA11y: (title: string) => `打开实验 ${title}`,
        observationsCount: (count: number) => `${count} 条观察记录`,
        archiveAction: "归档心得",
        archiveA11y: "归档心得",
        removeAction: "移除心得",
        removeA11y: "移除心得",
        resultLabels: {
            supports: "支持该假设",
            mixed: "结果混合",
            doesNotSupport: "未支持该假设",
            insufficientData: "数据不足",
        },
        archiveTitle: "要归档这条心得吗？",
        archiveMessage: "来源实验和观察记录都会保留。",
        archiveConfirm: "归档",
        removeTitle: "要移除这条心得吗？",
        removeMessage:
            "这只会移除推导出的心得。实验、观察记录、模式和信号都会保留。",
        removeConfirm: "移除",
        notices: {
            unableToArchive: "无法归档",
            unableToRemove: "无法移除",
        },
    },
    insights: {
        header: "洞察",
        eyebrow: "洞察",
        title: "值得注意的事。",
        description: "一小部分及时的观察，基于你已测试和已学到的内容。",
        statusNew: "新",
        statusSeen: "已查看",
        emptyTitle: "还没有洞察。",
        emptyBody: "当 Aks 随时间看到足够依据时，有用的事情会逐渐显现。",
    },
    insightDetail: {
        header: "洞察",
        eyebrow: "洞察",
        unavailableTitle: "洞察不可用。",
        reasonTitle: "Aks 为什么注意到这个",
        openExperimentA11y: (title: string) => `打开来源实验 ${title}`,
        openLearningA11y: (title: string) => `打开来源心得 ${title}`,
        observationsCount: (count: number) => `${count} 条已记录的观察 · 查看实验`,
        viewLearning: "查看来源心得",
        confidenceValue: (percent: number) => `依据可信度 ${percent}%`,
        createdAt: (date: string) => `${date} 创建`,
        dismissAction: "忽略洞察",
        dismissA11y: "忽略洞察",
        removeAction: "移除洞察",
        removeA11y: "移除洞察",
        dismissTitle: "要忽略这条洞察吗？",
        dismissMessage: "心得、实验、模式和依据都会保留。",
        dismissConfirm: "忽略",
        removeTitle: "要移除这条洞察吗？",
        removeMessage: "这只会移除该洞察，所有来源信息都会保留。",
        removeConfirm: "移除",
        notices: {
            unableToDismiss: "无法忽略",
            unableToRemove: "无法移除",
        },
    },
    privacyHome: {
        header: "隐私",
        eyebrow: "你的隐私",
        title: "你的生活属于你自己。",
        description:
            "Aks 帮助你了解自己，同时让你始终掌控支撑这份体验的信息。",
        dataSection: "你的数据",
        knowsTitle: "Aks 了解到的",
        knowsDescription: "了解用于构建你体验的信息。",
        accessTitle: "Aks 可以访问的内容",
        accessDescription: "查看你提供或选择连接的内容。",
        controlsSection: "数据控制",
        usageTitle: "你的数据如何被使用",
        usageDescription: "了解信息如何支持洞察和实验。",
        exportTitle: "导出你的数据",
        exportDescription: "申请获取一份你的 Aks 信息。",
        deleteTitle: "删除你的数据",
        deleteDescription: "发起一次谨慎的账号数据删除请求。",
        legalSection: "法律文件",
        privacyPolicyTitle: "隐私政策",
        privacyPolicyDescription: "阅读完整的 Aks 隐私政策。",
    },
    dataAccess: {
        header: "Aks 可以访问的内容",
        title: "设计上清晰透明。",
        description:
            "Aks 只使用你提供的信息，以及你明确选择连接的数据来源。",
        sourcesSection: "已连接来源",
        loadingSources: "正在加载你的已连接来源…",
        loadError: "我们目前无法加载你的已连接来源。",
        emptyTitle: "还没有已连接来源",
        emptyBody:
            "Aks 只在你明确连接之后才会读取外部服务。你可以在账号设置中管理任何连接。",
        connectedNeedsPermission: "已连接 · 需要权限",
        connectedSynced: (relative: string) => `已连接并读取数据 · ${relative}同步`,
        connectedNotSynced: "已连接并读取数据 · 尚未同步",
        holdsSection: "AKS 保存的内容",
        items: [
            {
                title: "你提供的信息",
                body: "你直接在 Aks 中输入的细节，例如个人资料信息和偏好设置。",
            },
            {
                title: "反思与状态记录",
                body: "你创建的、用来描述经历、情绪、专注、精力或作息的内容。",
            },
            {
                title: "实验数据",
                body: "你创建的实验，以及你记录的结果或备注。",
            },
            {
                title: "账号信息",
                body: "用于识别和管理你 Aks 账号所需的基本信息。",
            },
            {
                title: "已连接的数据来源",
                body: "仅包含你明确选择连接的服务中的信息，且以这些连接可用为前提。",
            },
        ],
        controlTitle: "由你掌控",
        controlBody: "Aks 只使用你输入或明确连接的内容。",
    },
    dataUsage: {
        header: "你的数据如何被使用",
        title: "你的数据有它的用途。",
        description:
            "Aks 在产品内使用这些信息，让你的体验更相关、更容易理解。",
        sections: [
            {
                title: "Aks 为什么使用你的数据",
                body: "你选择分享的信息能帮助 Aks 个性化反思、发现有用的主题，并支持你的目标。",
            },
            {
                title: "反思与状态记录",
                body: "你的记录可以为情绪、精力、专注和作息随时间的变化提供背景。",
            },
            {
                title: "模式发现",
                body: "Aks 可以比较你提供的信息，呈现可能的模式供你查看。这些只是反思的提示，不是医学结论。",
            },
            {
                title: "记忆",
                body: "Aks 可能会保留少量反复出现、有用的背景。每条记忆都与支持它的信息相关联，可以单独移除，而不会删除原始来源。",
            },
            {
                title: "实验与结果",
                body: "实验记录可以帮助你比较自己尝试的内容与记录下的结果。",
            },
            {
                title: "AI 辅助理解",
                body: "AI 可能会帮助整理和总结你提供的信息。请自行判断，并审慎看待重要洞察。",
            },
        ],
        privacyPolicyAction: "阅读完整隐私政策",
    },
    exportData: {
        header: "导出你的数据",
        preparingTitle: "正在准备你的导出",
        preparingBody:
            "正在收集你的对话、反思、记忆、模式、实验和洞察。通常只需要几秒钟。",
        errorTitle: "把你的数据带走。",
        errorBody: "可按需生成一份可供下载的 Aks 信息副本。",
        failedTitle: "无法创建你的导出。",
        failedFallback: "准备导出时出了点问题，请重试。",
        retryA11y: "再次尝试创建导出",
        cancelAction: "取消",
        cancelA11y: "返回导出介绍页",
        readyTitle: "你的导出已就绪。",
        readyBody:
            "刚刚生成了一份你的 Aks 信息快照，内容与你申请时列出的部分一致。",
        expiresIn: (countdown: string) => `链接将在 ${countdown} 后过期`,
        expiresSoon: "片刻",
        saveAction: "保存导出",
        saveA11y: "保存导出",
        requestAnother: "再次申请导出",
        requestAnotherA11y: "再次申请导出",
        idleTitle: "把你的数据带走。",
        idleBody:
            "可按需生成一份可供下载的 Aks 信息副本。每次导出都是单个文件，反映你申请当下的账号状态。",
        includedSection: "包含的内容",
        included: [
            "个人资料与偏好设置",
            "对话与消息",
            "反思",
            "状态记录",
            "信号",
            "记忆与依据关联",
            "模式与依据关联",
            "实验与观察记录",
            "心得与来源关联",
            "洞察与来源引用",
        ],
        requestAction: "申请数据导出",
        requestA11y: "申请导出",
    },
    deleteData: {
        header: "删除你的数据",
        title: "不留痕迹。",
        description:
            "删除账号会永久移除你在 Aks 中创建的数据，同时会在本设备上退出登录。",
        warningTitle: "此操作无法撤销。",
        warningBody:
            "账号一旦删除，你的 Aks 数据将无法恢复。如果你希望留存一份副本，请先导出数据。",
        removedSection: "将被移除的内容",
        removed: [
            "对话与消息",
            "反思",
            "状态记录",
            "推导出的信号",
            "记忆与依据关联",
            "模式与依据关联",
            "实验与观察记录",
            "心得与来源关联",
            "洞察与来源引用",
        ],
        confirmA11y: "确认你了解此操作不可撤销",
        confirmLabel: "我明白此操作不可撤销，我的所有 Aks 数据都将被移除。",
        deleteAction: "删除我的账号和数据",
        deleteActionA11y: "删除我的账号和数据",
        deletingAction: "正在删除你的账号…",
        deletedTitle: "你的账号正在被删除。",
        deletedBody: "删除完成后你会被退出登录。",
        backToSettings: "返回设置",
        backToSettingsA11y: "返回设置",
        keepAccount: "保留我的账号",
        keepAccountA11y: "保留我的账号",
        keepNote: "删除账号也会移除为该账号生成的任何导出文件。",
    },
    helpHome: {
        header: "帮助与反馈",
        title: "我们在听。",
        description: "有功能不能用、有地方让人困惑，或你希望 Aks 能做到的事？",
        supportTitle: "需要帮助？",
        supportBody: "我们的支持团队随时为你服务。",
        supportAction: "联系支持",
        getHelpSection: "获取帮助",
        faqTitle: "常见问题",
        faqDescription: "快速找到常见问题的答案",
        reportTitle: "报告问题",
        reportDescription: "告诉我们哪里出了故障",
        improveSection: "让 AKS 更好",
        suggestTitle: "提出想法",
        suggestDescription: "告诉我们你希望 Aks 学会或做到什么",
        shareTitle: "分享你的体验",
        shareDescription: "告诉我们哪些体验很棒，哪些可以更好",
        contactSection: "联系方式",
        supportEmail: "support@aks.ai",
        supportResponse: "通常在 1–2 个工作日内回复",
        footerVersion: "1.0.0",
    },
    faq: {
        header: "帮助与反馈",
        title: "常见问题",
        description: "快速了解 Aks 如何运作，以及你的数据如何处理。",
        searchPlaceholder: "搜索问题",
        clearSearch: "清除",
        resultsCount: (count: number) => `${count} 条结果`,
        popularSection: "热门问题",
        questionsCount: (count: number) => `${count} 个问题`,
        items: [
            {
                question: "Aks 是如何发现模式的？",
                answer: "Aks 会在你选择分享的信息和反思中寻找有用的关联。",
            },
            {
                question: "我可以控制 Aks 使用哪些数据吗？",
                answer: "可以。你可以在「你的数据」和「隐私」中查看信息，并管理可用的权限。",
            },
            {
                question: "实验是怎么运作的？",
                answer: "实验帮助你测试小的改变，并反思它们如何影响你的专注、精力、睡眠和作息。",
            },
            {
                question: "我可以更改通知设置吗？",
                answer: "可以。从「你」页面打开「通知」，选择 Aks 何时可以联系你。",
            },
            {
                question: "Aks 提供的是医疗建议吗？",
                answer: "不是。Aks 支持个人反思，不能替代专业的医疗或心理健康建议。",
            },
        ],
        emptyTitle: "没有匹配结果",
        emptyBody: "换个搜索词，或浏览上面的问题。",
        clearAction: "清除搜索",
        helpTitle: "还需要帮助？",
        helpBody: "告诉我们发生了什么，我们会帮你一起弄清楚。",
        contactAction: "联系我们",
    },
    sendFeedback: {
        header: "发送反馈",
        title: "一起塑造 Aks。",
        description: "分享一个想法、提出功能需求，或告诉我们哪些已经很好用。",
        optionLabel: "反馈类型",
        optionHint: "选择一项",
        options: ["想法", "功能需求", "一般反馈", "我喜欢的地方"],
        initialOption: "一般反馈",
        messageLabel: "你的反馈",
        messagePlaceholder: "什么会让 Aks 对你更有用？",
        messageHint: "想法、建议，或你喜欢的部分都欢迎。",
        emailHint: "只有希望我们回复时才留下邮箱。",
        noteTitle: "你的反馈很重要。",
        noteBody: "你分享的内容会帮助我们决定 Aks 接下来的方向。",
        submit: "发送反馈",
        leaveMessage: "你可以不发送任何内容就离开此页面。",
    },
    reportProblem: {
        header: "报告问题",
        title: "出了什么问题？",
        description:
            "告诉我们发生了什么。你提供的背景越多，我们就越容易理解和修复。",
        optionLabel: "问题类别",
        optionHint: "选择一项",
        options: [
            "某些功能无法使用",
            "应用崩溃",
            "洞察不正确",
            "数据问题",
            "通知问题",
            "其他",
        ],
        messageLabel: "发生了什么？",
        messagePlaceholder: "描述你期待的结果，以及实际发生了什么…",
        messageHint: "请附上导致该问题的操作步骤。",
        emailHint: "只有希望我们跟进时才添加邮箱。",
        noteTitle: "感谢你帮助改进 Aks。",
        noteBody: "你的反馈帮助我们让 Aks 对每个人都更可靠。",
        submit: "提交报告",
        leaveMessage: "你可以不提交就离开此页面。",
    },
    feedbackForm: {
        selectedState: "已选择",
        contactEmail: "联系邮箱",
        optionalMark: "（可选）",
        emailPlaceholder: "you@example.com",
        charLimit: 1000,
    },
    profilePreference: {
        saveAction: "保存偏好",
        saveA11y: (title: string) => `保存${title}`,
        noteCaption: "已保存到你的个人资料",
        noteBody: "你的选择已保存到个人资料。",
        notices: {
            unableToSave: "无法保存偏好设置",
        },
    },
    dataCategory: {
        recentSection: "最近",
        loadingA11y: (title: string) => `正在加载${title}`,
        loadErrorTitle: "无法加载这些数据。",
        tryAgain: "重试",
        loadMore: "加载更多",
        noteCaption: "来自 AKS 的提示",
        noteBody: "你的条目创建后会出现在这里。",
    },
    bottomSheet: {
        dismissA11y: "关闭",
        defaultConfirm: "知道了",
        cancel: "取消",
    },
    connectedSources: {
        header: "已连接来源",
        eyebrow: "背景与权限",
        title: "你决定 Aks 了解什么。",
        description:
            "不连接任何来源，Aks 也能完整使用。每个来源都是可选的、彼此独立的，并会明确说明共享了什么。你可以随时断开任何连接。",
        loadingA11y: "正在加载来源",
        loadError: "我们无法加载你的已连接来源。",
        status: {
            connected: "已连接",
            permissionRequired: "需要权限",
            notConnected: "未连接",
            notAvailable: "此设备不可用",
            revoked: "已断开",
            temporarilyUnavailable: "暂时不可用",
            error: "当前不可用",
        },
        syncedAgo: (relative: string) => `${relative}同步`,
        notSynced: "尚未同步",
        whyHelps: "为什么有帮助",
        whatReceives: "AKS 会收到什么",
        whatStored: "会保存什么",
        howToStop: "如何停止",
        goodToKnow: "值得了解",
        disconnect: "断开连接",
        deleteData: "删除导入的数据",
        allow: "允许",
        connect: "连接",
        reconnect: "重新连接",
        choiceSection: "你的选择",
        choiceBody: "只会使用你连接的来源。随时一键停止。",
        confirmations: {
            cancelAction: "取消",
        },
        notices: {
            providerNotConfigured: "此版本尚未配置该服务商。",
            unableToConnect: "我们目前无法连接该来源。",
        },
        groups: {
            productivity: "生产力",
            work: "工作",
            device: "设备 / 行为",
        },
    },
    sources: {
        location: {
            name: "位置",
            purpose:
                "让 Aks 了解你的一天发生在哪里。这有助于区分艰难的一天，和被出行或意外变化打乱的一天。",
            receives:
                "粗略的地点背景（家附近、工作地附近、出行、陌生地点）和时间段 — 绝不持续追踪。",
            stored: "类似「出行，18:30 前后约 45 分钟」的观察时段。不保存精确坐标。",
            stop: "可随时断开位置。之后的采集会立即停止；已保存的观察可以单独删除。",
            batteryNote:
                "连接期间会偶尔检查位置。开启后可能会略微增加耗电。",
        },
        calendar: {
            name: "日历",
            purpose:
                "计划中的日程帮助 Aks 区分「计划改变了」和「动力下降了」。",
            receives:
                "事件时间和一个宽泛的类别。只有在标题定义了计划时才使用标题；绝不读取参与者名单、备注或会议链接。",
            stored: "最小化的事件记录：时间、时长、类别、已确认/已取消。",
            stop: "可随时断开日历。之后的采集会立即停止。",
        },
        reminders: {
            name: "任务与提醒",
            purpose:
                "计划中的行动与实际发生的情况 — 而 Aks 绝不会因此说你「漏掉」了什么。",
            receives: "你选择同步的提醒的到期时间和完成状态。",
            stored: "到期时间与已完成/未记录状态。",
            stop: "可随时断开任务与提醒。",
        },
        screenTime: {
            name: "屏幕使用时间",
            purpose:
                "聚合的设备使用背景可能解释专注的变化 — 它绝不会被当作分心的证明。",
            receives: "按时间段的宽泛类别聚合的使用时长。",
            stored: "类似「社交应用，60 分钟，21:00–22:00」的聚合时段。没有逐次操作的数据。",
            stop: "可随时断开屏幕使用时间。",
        },
        googleCalendar: {
            name: "Google 日历",
            purpose:
                "你的 Google 事件为 Aks 提供与设备日历相同的计划背景，仅限你明确连接的账号。",
            receives:
                "你所选日历的事件时间和一个宽泛的类别。绝不读取参与者名单、备注或会议链接。",
            stored: "最小化的事件记录：时间、时长、类别、已确认/已取消。",
            stop: "可随时断开 Google 日历 — 并在你的 Google 账号设置中撤销授权。",
        },
        appleCalendar: {
            name: "Apple 日历",
            purpose: "在 iPhone 和 iPad 上，通过 Apple 的日历存储获得相同的设备日历背景。",
            receives: "事件时间和一个宽泛的类别。绝不读取参与者名单、备注或会议链接。",
            stored: "最小化的事件记录：时间、时长、类别、已确认/已取消。",
            stop: "可随时断开 Apple 日历。",
        },
        googleTasks: {
            name: "Google 任务",
            purpose:
                "来自你连接的 Google 账号的计划任务，让 Aks 看到你的意图 — 绝不会断定你失败了。",
            receives: "任务的到期时间和完成状态。",
            stored: "到期时间与已完成/未记录状态。",
            stop: "可随时断开 Google 任务 — 并在你的 Google 账号设置中撤销授权。",
        },
        appleReminders: {
            name: "Apple 提醒事项",
            purpose:
                "在 iPhone 和 iPad 上，Apple 提醒事项中的计划行动会提供同样的「计划 vs 实际」背景。",
            receives: "提醒的到期时间和完成状态。",
            stored: "到期时间与已完成/未记录状态。",
            stop: "可随时断开 Apple 提醒事项。",
        },
        notion: {
            name: "Notion",
            purpose:
                "你明确与 Aks 集成共享的页面和数据库，让工作背景也能帮助对话。",
            receives:
                "你与 Aks Notion 集成共享内容的标题、时间和一个宽泛的类别。绝不读取页面正文。",
            stored: "最小化的条目记录：标题类别、时间、状态。",
            stop: "可随时断开 Notion — 并从你的 Notion 工作区移除 Aks 集成。",
        },
        todoist: {
            name: "Todoist",
            purpose: "连接的任务服务（Todoist 或类似服务），让 Aks 之外的计划也算数。",
            receives: "任务的到期时间和完成状态。",
            stored: "到期时间与已完成/未记录状态。",
            stop: "可随时断开 Todoist — 并在该服务商的账号设置中撤销授权。",
        },
        github: {
            name: "GitHub",
            purpose: "你自己的提交和 PR 活动作为客观的工作背景 — 绝不涉及他人的数据。",
            receives: "你所选仓库中，你的提交和拉取请求的活动次数与时间。",
            stored: "类似「2 次提交，22:00–23:00」的聚合活动时段。不包含代码内容。",
            stop: "可随时断开 GitHub — 并在你的 GitHub 设置中撤销 Aks OAuth 应用。",
        },
        slack: {
            name: "Slack",
            purpose: "来自你明确连接的工作区的专注时段与状态信号。",
            receives: "你自己的活动时段和免打扰状态。绝不读取消息内容。",
            stored: "聚合的活动时段。没有消息、频道，也没有同事的数据。",
            stop: "可随时断开 Slack — 并从你的工作区移除 Aks 应用。",
        },
        email: {
            name: "邮箱",
            purpose: "来自你连接的邮箱服务（Gmail 或其他）的轻量邮件负荷背景（仅计数）。",
            receives: "收到邮件的数量和时序。绝不读取主题、正文或发件人。",
            stored: "按时段聚合的计数。没有内容，也没有地址。",
            stop: "可随时断开邮箱 — 并在该服务的安全设置中撤销授权。",
        },
        voiceSession: {
            name: "麦克风",
            purpose:
                "语音对话是你主动发起的明确操作。麦克风仅在语音会话进行时使用。",
            receives: "仅在语音对话进行时接收音频。",
            stored: "你保留的转写文本；音频不会被保存。",
            stop: "结束语音会话 — 麦克风就会关闭。Aks 绝不会在后台监听。",
        },
    },
    transparency: {
        connectedWith: (sources: string) =>
            `你已连接${sources}，因此 Aks 可以在你在此分享的内容之外，看到这些背景。`,
        names: {
            location: "位置",
            calendar: "日历",
            googleCalendar: "Google 日历",
            appleCalendar: "Apple 日历",
            reminders: "任务",
            googleTasks: "Google 任务",
            appleReminders: "Apple 提醒事项",
            todoist: "Todoist",
            notion: "Notion",
            github: "GitHub",
            slack: "Slack",
            email: "邮箱",
            screenTime: "屏幕使用时间",
            voiceSession: "语音",
        },
    },
    oauth: {
        googleCalendar: "Google 日历",
        googleTasks: "Google 任务",
        notion: "Notion",
        todoist: "Todoist",
        github: "GitHub",
        slack: "Slack",
        email: "邮箱",
    },
    errors: {
        pagedData: "我们无法加载这些数据，请重试。",
        pagedDataMore: "我们无法加载更多数据，请重试。",
        dataSummary: "我们无法加载你的数据概览，请重试。",
        dataAccess: "无法加载你的已连接来源，请重试。",
        memory: "我们无法加载这条记忆。",
        pattern: "我们无法加载这个模式。",
        experiment: "我们无法加载这个实验。",
        learning: "我们无法加载这条心得。",
        insight: "我们无法加载这条洞察。",
        conversation: "我们无法加载这个对话，请重试。",
        conversationEarlier: "我们无法加载更早的消息，请重试。",
        conversationPlain: "我们无法加载这个对话。",
        conversationEarlierPlain: "我们无法加载更早的消息。",
        messageEmptySave: "保存前请先输入内容。",
        exportLinkExpired: "导出链接已过期，请重新申请导出。",
        renameConversation: "我们无法重命名该对话，请重试。",
        exportExpired: "导出链接已过期，请重新申请导出。",
        exportCreate: "无法创建导出，请重试。",
        exportDownload: "无法下载导出文件，请重试。",
        deleteAccount: "当前不支持删除账号，请稍后再试。",
        preferences: "我们无法加载你的偏好设置。",
        appSetup: "我们无法完成你的账号设置，请重试。",
        exportSaveTitle: "保存你的 Aks 导出",
        exportClearDevice: "你的账号数据正在删除，但清理此设备需要再试一次。",
        shareUnavailable: "此设备不支持分享，请重试。",
        exportIncomplete: "导出响应不完整，请重试。",
        exportInterrupted: "下载被中断，请重试。",
        exportGeneric: "出了点问题，请重试。",
        connectedSources: "我们无法加载你的已连接来源。",
        sourceUnavailable: "此来源在你的设备上不可用。",
        sourcePermission: "Aks 需要该权限才能连接此来源。你可以稍后再试。",
        sourceConnect: "我们无法连接该来源。",
        sourceDisconnect: "我们无法断开该来源。",
        sourceDelete: "我们无法删除该来源的数据。",
        oauthRecord: "我们无法记录该连接。",
        oauthDisconnect: "我们无法断开该账号。",
        webPage: "无法加载此页面。",
        webPageBody: "请检查网络连接后重试。",
        generic: "出了点问题，请重试。",
        signInUnavailable: "当前无法登录，请稍后再试。",
        signInStart: "我们无法开始登录。",
        authRequest: "我们无法完成该请求，请重试。",
        storeUnreachable: "我们无法连接应用商店。请检查网络后重试。",
        plansUnavailable: "当前没有可用的方案，请稍后再试。",
        planUnavailable: "该方案当前不可用，请稍后再试。",
        storeFailed: "应用商店无法完成你的请求，请重试。",
        subscriptionGeneric: "处理你的订阅时出了点问题，请重试。",
        purchaseCancelled: "结账已取消，未产生任何费用。",
        purchasePending:
            "你的购买正在等待应用商店确认。完成后会显示在这里。",
        alreadySubscribed: "你已经订阅了该方案。",
        checkoutPendingPremium:
            "结账已完成，但你的账号尚未激活 Premium。模拟器 Test Store 的购买不会激活 Premium — 请使用装有 Play 商店的设备。否则请稍等片刻，然后尝试「恢复购买」。",
        restoreEmpty: "没有找到可以恢复的以往购买。",
        emptyMessage: "发送前请先输入内容。",
        mirror: {
            noReply: "Aks 还没有回复你的最后一条消息。",
            unsavedRetry: "你的上一条消息可能没有保存完成。你可以安全地重试。",
            resolvePending: "请先重试或处理上一条消息，再发送新的消息。",
            refreshFailed: "Aks 无法刷新该回复。之前的内容仍然保留。",
            refreshFailedConversation:
                "Aks 在多次尝试后仍无法完成这条回复。你的消息仍然已保存。",
            refreshFailedUnsafe: "Aks 无法安全地理解该回复。你的消息已保存。",
            refreshFallback: "Aks 目前无法处理该内容。你的消息已保存。",
            updateMessage: "我们无法更新该消息，它可能已经有 Aks 的回复。",
            checkInFailed: "我们无法保存你的状态记录，请重试。",
            saveFailed: "我们无法保存你的消息。请检查网络后重试。",
            outboxQueued: "已保存在本设备。恢复联网后 Aks 会发送它。",
            signInForVoice: "登录后即可使用语音对话。",
            voiceStartFailed: "我们无法开始语音对话。",
        },
        voice: {
            realtimeNotConfigured: "此版本尚未配置语音对话。",
            sessionUnavailable: "我们无法开始语音会话，请重试。",
            transportUnavailable: "此对话选项需要 Aks 的开发版构建。",
            audioUnavailable: "实时语音需要带有 Aks 音频引擎的开发版构建。",
            micDenied: "语音对话需要麦克风权限。",
            transcriptionFailed: "Aks 没能听清你说的话，请重试。",
            providerError: "Aks 目前无法开始语音对话。",
            sessionExpired: "语音会话已过期。重新连接以继续。",
            voiceFailed: "语音对话失败。",
            saveVoiceMessage: "我们无法保存你的语音消息。它只保留在本次会话中。",
            saveVoiceReply: "我们无法保存 Aks 的回复。它只保留在本次会话中。",
            audioCaptureFailed: "音频采集失败。",
            audioFailed: "音频出错。",
        },
        writes: {
            signInRequired: "请先登录再继续。",
            experimentInvalid: "实验响应无效。",
            observation: "我们无法保存该观察记录。",
            reflection: "我们无法保存该反思。",
            message: "我们无法保存该消息。",
            checkIn: "我们无法保存该状态记录。",
            insightUpdate: "我们无法更新这条洞察。",
            experimentUpdate: "我们无法更新这个实验。",
            startConversation: "我们无法开始该对话。",
            sendMessage: "我们无法保存你的消息。",
            confirmMessage: "我们无法确认你已保存的消息。",
            searchConversations: "我们无法搜索你的对话。",
            updateConversation: "我们无法更新该对话。",
            updateMessage: "我们无法更新该消息。",
            confirmUpdatedMessage: "我们无法确认你更新后的消息。",
            archiveConversation: "我们无法归档该对话。",
            archivePattern: "我们无法归档这个模式。",
            removePattern: "我们无法移除这个模式。",
            archiveMemory: "我们无法归档这条记忆。",
            removeMemory: "我们无法移除这条记忆。",
            archiveLearning: "我们无法归档这条心得。",
            removeLearning: "我们无法移除这条心得。",
        },
    },
    timelineEntries: {
        patternForming: "模式正在形成",
        insight: "洞察",
        newLearning: "新的心得",
        outcomeRecorded: "已记录结果",
        experimentStarted: "实验已开始",
        experimentActive: "实验进行中",
        reflection: "反思",
        checkIn: "状态记录",
        experimentOutcomeTitle: "已记录实验结果",
        reflectionTitle: "你记录了一条反思",
    },
};

export default zh;
